86Box/86Box

- src/Makefile.am
- src/Makefile.mingw
- src/Makefile.mingw64
- src/ibm.h
- src/vid_nv_rivatnt.c
- src/vid_nv_rivatnt.h
- src/video.c
Note that the only OSes this works on so far are DOS and Linux if you use the VESA drivers.
> RIVA TNT support

- src/mem.c
This was missing for a long time.
> Adding XT IDE bios to Euro PC

- src/Makefile.am
- src/Makefile.mingw
- src/Makefile.mingw64
- src/ibm.h
- src/vid_nv_riva128.c
- src/vid_nv_riva128.h
- src/video.c
This has a few differences from RIVA TNT emulation so far, and it might work better in some cases, so I'm including it here.
> Add preliminary RIVA 128 emulation

- src/Makefile.am
- src/Makefile.mingw
- src/Makefile.mingw64
- src/vid_nv_riva128.c
> Fix compilation

- src/buslogic.c
Some cleanup.
End the SCSI request if the transfer length is already 0.
Additional fixes to support OS/2 1.3 and DOS buslogic drivers, still not 100% working for those, however, but CD-ROM is recognized.
> Removed excessive logging (R/W functions only for now)

- src/buslogic.c
- src/scsi.c
- src/scsi.h
- src/scsi_cdrom.c
Corrected residual length, fixes Win95's buslogic driver that was not showing the CD drive.
> Added support up to 16 ID/LUN's

- src/vid_nv_riva128.c
> Revert "Add in NV4 context switching"

- src/vid_nv_riva128.c
> Revert "Fix compilation"

- src/SOUND/midi_mt32.c
- src/SOUND/snd_emu8k.c
- src/SOUND/snd_sb.c
- src/VIDEO/vid_ati18800.c
- src/VIDEO/vid_ati28800.c
- src/VIDEO/vid_ati_mach64.c
- src/VIDEO/vid_cl_gd.c
- src/VIDEO/vid_ega.c
- src/VIDEO/vid_et4000.c
- src/VIDEO/vid_et4000w32.c
- src/VIDEO/vid_genius.c
- src/VIDEO/vid_nv_riva128.c
- src/VIDEO/vid_oti067.c
- src/VIDEO/vid_paradise.c
- src/VIDEO/vid_pc1640.c
- src/VIDEO/vid_s3.c
- src/VIDEO/vid_s3_virge.c
- src/VIDEO/vid_tgui9440.c
- src/VIDEO/vid_tvga.c
- src/VIDEO/vid_vga.c
- src/esdi_at.c
- src/hdd_esdi.c
- src/mem.c
- src/mfm_xebec.c
- src/ps1.c
- src/scsi_aha154x.c
- src/tandy_rom.c
- src/xtide.c
I've rearranged the bios files path's to be a bit more sane. I'll send you a zip file with the rearranged bios files on irc too...
> Re-arranged roms' paths to be a bit more sane.

- src/Makefile.local
- src/win/86Box.rc
- src/win/Makefile.mingw
- src/win/resource.h
- src/win/win.c
- src/win/win.h
- src/win/win_d2d.cpp
- src/win/win_d2d.h
- src/win/win_ui.c
Note that taking screenshots is not implemented and silently fails as saving the content of a Direct2D surface to a file is as complicated as it could ever be.
> Added a Direct2D 1.0 renderer

- src/network/net_ne2000.c
- src/network/net_ne2000.h
- src/network/network.c
- src/sound/snd_wss.c
- src/sound/snd_wss.h
- src/sound/sound.c
Added NCR Business Audio MCA card (Windows Sound System compatible) and its copyright information
> NE/2 changed to a NE/2 compatible card (Ethernext/MC).

- src/device.c
- src/isamem.c
Re-worked device handling a bit (from VARCem).
> Added new Paradise ems card and a new 5150 ems card (from VARCem).

- .gitignore
- README.md
Added a section that links to the tutorial/guide so people can hopefully see it.
> Link to totorial/guide

- src/win/win_ui.c
Who know calculating window border sizes can be this hard, it can even be affected by compiler and linker settings...
This fixes https://github.com/86Box/86Box/issues/381 (caused by https://github.com/86Box/86Box/commit/2da25c0a29aa574a2d1ea752c6ef844758de5404).
> win_ui: Proper fix to window border issues

- src/lpt.c
- src/printer/prt_devs.h
- src/printer/prt_ps.c
- src/win/Makefile.mingw
This is pretty much a bare bone text printer that writes the PS code into a file and then uses Ghostscript to convert it to PDF (requires `gsdll32.dll` to be present in path).
> Add generic PostScript printer

- src/lang/language.h
- src/printer/prt_ps.c
- src/win/86Box.rc
* Added Ctrl+D handling
* Added bound checking
* A better message when `gsdll32.dll` is missing
* Code style, refactoring
> Updates to the generic PostScript printer

- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/machine.h
- src/machine/machine_table.c
- src/machine/machine_table_new.c
For https://github.com/86Box/86Box/issues/580
> The Micronics 09-00021 is actually discrete & 386DX based

- src/hwm.c
- src/hwm.h
- src/hwm_w83781d.c
- src/intel_piix.c
- src/machine/m_at_socket8.c
- src/smbus.c
- src/smbus.h
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
Implements the following:
* Frameworks for SMBus and hardware monitor devices
* PIIX4 SMBus controller
* Winbond W83781D family ISA/SMBus hardware monitor (used by the ASUS P2B-LS and other boards) as a reference SMBus device
> SMBus framework + Winbond W83781D hardware monitor

- src/machine/m_ps2_mca.c
- src/mca.c
- src/mca.h
- src/network/net_ne2000.c
- src/network/net_wd8003.c
- src/scsi/scsi_aha154x.c
- src/scsi/scsi_buslogic.c
- src/scsi/scsi_spock.c
- src/sound/snd_ad1848.c
- src/sound/snd_ad1848.h
- src/sound/snd_azt2316a.c
- src/sound/snd_azt2316a.h
- src/sound/snd_mpu401.c
- src/sound/snd_mpu401.h
- src/sound/snd_pas16.c
- src/sound/snd_sb.c
- src/sound/snd_sb.h
- src/sound/snd_sb_dsp.c
- src/sound/snd_sb_dsp.h
- src/sound/snd_wss.c
- src/sound/sound.c
- src/sound/sound.h
- src/video/vid_cl54xx.c
- src/video/vid_et4000.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
Added the reset function of MCA from PCem.
Made the MCA devices use the reset parameter if available.
> Added the Aztech Sound Galaxy 16 cards.

- src/machine/m_at_286_386sx.c
- src/sio.h
- src/sio_f82c710.c
- src/sound/snd_azt2316a.c
Added F82C710 SIO to the super286tr.
> Changed the GPL license of the azt2316a.c source file.

- src/machine/m_at_socket8.c
> Actually move the P2B-LS code to non-dev builds

- src/chipset/chipset.h
- src/chipset/via_apro.c
- src/machine/m_at_socket8.c
- src/machine/machine.h
- src/machine/machine_table.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
Replaced the ECS board with an Apollo PRO based PC Partner board which supports the VIA C3 CPU's.
> Initial VIA Apollo Pro emulation

- src/cpu_common/cpu_table.c
What would preliminary Mendocino emulation be without the remaining speeds?
> Added more speeds to Celeron (Slot 1/Socket 370)

- src/smbus.c
- src/spd.c
* Disable SPD and SMBus logging
* Fix potential underflow situation
* Change Tclk values to 133/100/66 MHz
* Change manufacture week ~~to hopefully convince HWiNFO the module was not made in 2001~~
* Small random code changes
> SPD improvements

- src/include/86box/cs8230.h
- src/include/86box/vid_svga.h
- src/video/vid_mga.c
- src/video/vid_svga.c
> Ported the latest Matrox MGA fixes from PCem.

- src/include/86box/machine.h
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
Replaces the Lucky Star 6ABX3 with the Gigabyte GA-6BXC, a better working machine than the 6ABX3.
> Replace the 6ABX3 with a better working machine

- src/include/86box/smbus_piix4.h
- src/intel_piix.c
- src/smbus_piix4.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
There are other southbridges which use this interface such as the VIA 596B.
> Move the PIIX4 SMBus interface to its own file

- src/cpu_common/cpu.h
- src/disk/hdd_image.c
- src/include/86box/plat.h
- src/include/86box/vid_voodoo_codegen_x86-64.h
- src/include/86box/vid_voodoo_codegen_x86.h
- src/include/86box/win.h
- src/network/net_pcnet.c
- src/printer/prt_ps.c
- src/random.c
- src/scsi/scsi_ncr53c8xx.c
- src/sound/snd_adlibgold.c
- src/sound/snd_audiopci.c
- src/sound/snd_emu8k.c
- src/sound/snd_sb_dsp.c
- src/video/vid_voodoo.c
- src/win/86Box.rc
- src/win/win_discord.c
- src/win/win_joystick.cpp
- src/win/win_joystick_rawinput.c
- src/win/win_joystick_xinput.c
This pull requests contains fixes required to make 86Box compilable using Microsoft Visual C/C++ and the Windows 10 SDK.
It does _not_ contain the project files nor makefiles required for this -- the functionality will be provided via CMake (#529).
> Fix MSVC and Windows SDK compatibility

- src/chipset/via_vpx.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
This commit brings Apollo VPX emulation on 86Box. It includes the Zida Tomato TX100 board. Meant mostly to check issues at Hiflex BIOSes
> Apollo VPX bringup

- src/include/86box/language.h
- src/include/86box/win.h
- src/win/86Box.rc
- src/win/win_stbar.c
- src/win/win_ui.c
This is an alternative way to mount images to the virtual drives, as many people found the current behavior utilizing the status bar icons confusing.
> Add the "Media" menu to the menubar

- src/config.c
> Allow relative path of disk images.

- src/cpu/codegen_timing_p6.c
- src/cpu_new/codegen_timing_p6.c
- Removed the RISC86 references
- Some cleanup
- Balancing fixes, so performance should be more accurate
> Improvements to P6 timings

- src/include/86box/machine.h
- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
- src/video/vid_ati28800.c
- src/video/vid_et4000.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/vid_table.c
and enhancements from greatpsycho.
> Ported the Goldstar 286 machine from PCem alongside video fixes

- src/machine/m_at_socket370.c
> added the missing S370SLM which was causing the Dev branch to fail

- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Fixed the board SPD's, added some basic notes from testing, Added their hardware sensors and few more minor changes.
> Minor changes for the SuperMicro's

- src/include/86box/86box.h
- src/win/86Box.rc
* Add numeric major/minor version constants to 86box.h
* Add copyright year constant to 86box.h
* Update 86Box.rc to use the constants from 86box.h
> Versioning improvements

- src/include/86box/smbus.h
- src/smbus.c
- src/smbus_piix4.c
Fixes a small mistake in the SMBus implementation.
> SMBus: add length to block read operations

- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
More stable than the previous one. Works flawlessly.
> Replaced the 430TX Hiflex board with one 430VX

- src/chipset/intel_4x0.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Short lived but first Intel AGP chipset. Meant to get the S370SLM off dev branch.
> 440LX implementation

- src/chipset/intel_4x0.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
Just a weak 440LX. Works as intended. Has a bit more registers included too.
> Added the 440EX

- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
> Added the SiS Rabbit

- src/include/86box/machine.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
I want to see if I could add the Gateway 2000 OEM-based Zappa ROM.
> Added the Gateway 2000 OEM-based Zappa ROM

- src/cpu_common/cpu.c
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
An i686 Acer BIOS board. Works as intended
> Added the Acer V60N

- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
I want to see if I could add the Gateway 2000 Thor (Socket 7/430FX) and Gateway 2000 Venus (Socket 8/440FX)
> Added two more Gateway 2000 FX machines.

- src/chipset/amd640.c
- src/include/86box/chipset.h
- src/win/Makefile.mingw
A modified kind of VIA VP2 made by AMD for Socket 7. Meant for any future machine implementation we might do.
> Implemented the AMD 640 chipset

- src/chipset/i82335.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/machine_table.c
- src/win/Makefile.mingw
Restored the old Intel 82335 code remnant of the PCem-X era.
> Restored the Intel 82335 chipset

- src/include/86box/vid_svga.h
- src/video/vid_s3.c
- src/video/vid_sc1148x_ramdac.c
- src/win/Makefile.mingw
Made the S3 911 use the SC11483 plus a few minor changes to the S3 code itself.
> Added the Sierra SC11483 and SC11487 ramdac's.

- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
> Added the AmazePC AM-BX133

- src/chipset/opti5x7.c
This implements shadowing of the C0000-DFFFF regions on the OPTi 5x7 chipset. Also brings it a bit more in-line with the other OPTi chipsets.
> Implement C0000-DFFFF shadowing on the OPTi 5x7 chipset

- src/chipset/opti283.c
Corrected many mistakes while also makes use of the RW register for MR Bios.
> Rewrote the OPTi 283 shadowing

- src/chipset/via_vt82c49x.c
- src/chipset/via_vt82c505.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
Just a bringup of the VIA 486 based boards(Award 4.20 ones)
> VIA 486 bringup

- src/config.c
- src/cpu/386_ops.h
- src/include/86box/86box.h
- src/machine/machine_table.c
- src/pc.c
- src/sound/sound.c
- src/win/win.c
- src/win/win_dialog.c
- src/win/win_settings.c
- src/win/win_ui.c
Fixes the fullscreen notification as per #948, and adds confirmation suppression checkboxes to hard reset and exit.
> UI confirmation fixes and enhancements

- .github/workflows/c-cpp.yml
https://github.com/msys2/setup-msys2/blob/master/CHANGELOG.md
> CI: Update to msys2/setup-msys2@v2

- src/chipset/ali1429.c
- src/chipset/ali1489.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
It includes the M1489 which the rewritten M1429. Also a machine for the new 931APM SIO
> Mass ALi work

- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_misc.c
- src/machine/m_at_slot1.c
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
Some machines are repeated variations with minor to no differences. For the sake of clearity they have been removed
> Removed various machines of no use

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
> Added the Micronics Spitfire

- src/codegen_new/codegen_ops_logic.c
Doesn't improve much on Celeron Mendocino 533, but doesn't break anything either...
> Micro-optimizations for the AND and OR opcodes in the new dynarec

- src/cpu/cpu_table.c
Since DimMan88 mentioned about adding back a CPU speed, I'm making this change to the CPU table.
> CPU table changes

- src/include/86box/video.h
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_table.c
Added the Trio64V2/DX and its streams processor and Trio3D/2X cards with their respective VBE 2.0 bioses.
> Re-added the S3 928 card.

- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
Added Gateway 2000 Tigereye ROM
> Added Gateway 2000 Tigereye ROM

- src/chipset/ali1489.c
- src/chipset/intel_82335.c
Implemented basic SMRAM functionality to the M1489 & also the memory remapping capabilities of the Intel 82335.
> Chipset Improvements

- src/chipset/via_apollo.c
- src/chipset/via_pipc.c
- src/device/pci_bridge.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/include/86box/pci.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Needed for excessive 686A/B development
> Apollo ProMedia Implementation

- src/machine/m_at_socket4_5.c
- src/win/Makefile.mingw
> Gave the Dells the regular Intel SIO

- src/network/net_pcnet.c
… the PCnet-FAST III variant.
Summary
=======
Approach
========
_How did you address the problem?_
Checklist
=========
References
==========
> Fix the reported PHY of PCnet-FAST III

- src/win/86Box.manifest
> Add the UAC execution level to the manifest

- src/config.c
> Do not mute CD audio on the first drive by default

- src/chipset/via_apollo.c
- src/codegen_new/codegen.c
- src/machine/machine.c
- src/sio/sio_fdc37c93x.c
> Fix several compilation warnings

- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Fixed busy status on the S3 family of chips using the fifo.

- src/video/vid_voodoo_banshee.c
Summary
=======
Checklist
=========
References
==========
> Ported the latest PCem banshee fixes.

- src/video/vid_voodoo.c
- src/video/vid_voodoo_setup.c
Summary
=======
Checklist
=========
References
==========
> Ported the latest Voodoo 1/2 patches from PCem.

- src/disk/minivhd/minivhd_io.c
Summary
=======
This fixes a bug in multi-sector writes in dynamic VHDs.
> VHD: fix bug in multi-sector writes

- src/include/86box/vid_voodoo_common.h
- src/video/vid_voodoo_banshee.c
- src/video/vid_voodoo_fifo.c
Summary
=======
Checklist
=========
References
==========
> Latest PCem voodoo fifo changes are here.

- src/include/86box/snd_ad1848.h
- src/sound/snd_ad1848.c
Summary
=======
Checklist
=========
References
==========
> Fixed CD Audio scramble in the ad1848 core.

- src/sound/snd_ad1848.c
Summary
=======
Checklist
=========
References
==========
> Fix one off issue about the AD1848. It actually fixes the muted cd audio using the WSS.

- src/cpu/cpu.c
Summary
=======
Injected an AMI MSR used by RC440BX and potentially other Intel AMI boards.
Checklist
=========
* [NO] Closes #xxx
* [NO] I have discussed this with core contributors already
* [NO] This pull request requires changes to the ROM set
* [NO] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/
References
==========
RC440BX BIOS dump
> Injected a new AMI MSR

- src/include/86box/vid_voodoo_codegen_x86-64.h
- src/include/86box/vid_voodoo_codegen_x86.h
- src/video/vid_ati28800.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Checklist
=========
References
==========
> Ported the latest PCem changes (Voodoo and ATI 28800).

- .github/ISSUE_TEMPLATE/bug_report.md
Hopefully this should curb some of the non-helpful "Latest from Jenkins" bits when people go to report bugs :P
> Be a bit more specific in the bug report issue template

- src/video/vid_et4000.c
- src/video/vid_et4000w32.c
- src/video/vid_tvga.c
- src/video/vid_voodoo_banshee_blitter.c
Summary
=======
Checklist
=========
References
==========
> Ported the latest 128K fixes to 86Box.

- src/cpu/386_common.c
- src/video/vid_voodoo_banshee.c
- src/video/vid_voodoo_banshee_blitter.c
Summary
=======
Checklist
=========
References
==========
> Ported the most important patches from PCem.

- src/win/Makefile.mingw
Summary
=======
Removes unused and redundant options and checks from the Makefile.
Checklist
=========
> Some Makefile cleanup

- src/video/vid_table.c
Summary
=======
This PR moves the newly added OGC to a more appropiate section.
Checklist
=========
References
==========
> Moved the OGC in vid_table.c.

- src/win/86Box.rc
- src/win/win_devconf.c
Fixes some labels in the Settings window that were cut off on a 150% scale HiDPI setup.
> Enlarge some labels for HiDPI

- src/chipset/sis_85c50x.c
- src/cpu/386_common.c
- src/disk/hdc_ide_cmd640.c
- src/include/86box/machine.h
- src/include/86box/sio.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/sio/sio_fdc37c66x.c
- src/win/Makefile.mingw
Rewrote the chipset to adopt the new API
Checklist
=========
> Early SiS 50x rework

- src/sound/snd_ad1848.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Checklist
=========
References
==========
> Make cd audio hearable using the CS4248 codec and ported the WinUAE V3 fixes.

- src/machine/machine_table.c
Summary
=======
A small machine table reorganisation.
Checklist
=========
References
==========
> Machine table reorganisation.

- src/chipset/sis_5571.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
The SiS 5571 is a mid range highly integrated chipset by SiS. It is the best performer with a Cyrix 6x86. For now this implementation is enough to have a properly functional machine but still incomplete to get it off dev branch yet.
> SiS 5571 implementation

- src/chipset/ali1489.c
- src/machine/m_at_386dx_486.c
Some changes to improve the M1489 chipset but also have a properly functional IDE.
> Fixes and small rework on the ALi M1489

- src/disk/mo.c
Summary
=======
This is a patch to make disk/mo.c work cross-platform, to help with porting 86Box to Linux.
> Make mo_format use POSIX functions instead of Win32 ones

- src/network/net_pcap.c
- src/network/slirp/ip_input.c
- src/network/slirp/mbuf.c
- src/network/slirp/misc.c
> More POSIX fixes

- src/sound/snd_sb.c
Summary
=======
Checklist
=========
References
==========
> Fixed mixer initialization on the Sound Blaster 2.0.

- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c8xx.c
Summary
=======
Checklist
=========
References
==========
> BIOS BAR now properly working in the NCR 53c8xx PCI adapters.

- src/video/vid_compaq_cga.c
Summary
=======
Checklist
=========
References
==========
> Fixed the Compaq CGA crash upon initialization.

- src/network/net_pcnet.c
Summary
=======
Checklist
=========
References
==========
> Fixed the Racal EtherBlaster nic.

- src/machine/m_ps1.c
- src/machine/m_ps2_isa.c
Summary
=======
Checklist
=========
References
==========
> Fixed configurations of the Serial and LPT in the PS/1 2011 and 2121 models and in the PS/2 model 30 as well.

- src/scsi/scsi_ncr5380.c
Summary
=======
Checklist
=========
References
==========
> Minor fix to the Longshine card, now it formats HDD's as it should.

- src/scsi/scsi_ncr5380.c
Summary
=======
Checklist
=========
References
==========
> Tweaked the NCR 5380 timings a bit, should fix more hanging bugs.

- src/video/vid_ht216.c
Summary
=======
Checklist
=========
References
==========
> Experimental rework of the video 7 code (HT216).

- src/chipset/sis_5571.c
- src/chipset/wd76c10.c
- src/machine/m_at_286_386sx.c
Fairly broken rewrite of the WD76C10
Checklist
=========
References
==========
https://www.datasheetarchive.com/pdf/download.php?id=2157a839ddd36b26f8f32a94267e88c714dc50&type=M&term=WD76C10
> Mass rewrite of the WD76C10

- src/chipset/cs4031.c
- src/chipset/opti283.c
Simplistic but complex shadow implementations, few corrections and clearups
> Sanitize some old chipset code

- src/chipset/ali1429.c
- src/chipset/opti291.c
Few fixes for both the ALi M1429 & OPTi 291
> Sanitize some old chipset code (Part 2)

- src/floppy/fdc.c
- src/floppy/fdc_magitronic.c
- src/floppy/fdc_pii15xb.c
- src/include/86box/fdc.h
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_commodore.c
- src/machine/m_at_socket4_5.c
- src/machine/m_at_t3100e.c
- src/machine/m_ps2_mca.c
- src/machine/m_xt_laserxt.c
- src/machine/m_xt_olivetti.c
- src/machine/m_xt_xi8088.c
The Internal FDC is added when needed for AT machines too.
Some speculative "work" on the main FDC code
> FDC workaround

- src/video/vid_ht216.c
Summary
=======
Checklist
=========
References
==========
> Improved code style and fixed the ht216-32 video memory size.

- src/cpu/cpu.c
- src/cpu/cpu.h
- src/cpu/cpu_table.c
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_ebga368.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
Weak Eden series of machines by VIA
Checklist
=========
References
==========
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi_np_Ymv3uAhWNmBQKHW6pCVQQFjAAegQIAhAD&url=https%3A%2F%2Fwww.industrialtrading.net%2Fdatasheets%2F51yk2qko.pdf&usg=AOvVaw3gtclTxiRwd3rLX0yrBDKa
https://datasheetspdf.com/datasheet/VT8601.html
http://www.acrosser.com/download/200783018326734.pdf
> VIA EBGA368 Bringup

- src/machine/m_xt_t1000.c
Summary
=======
Checklist
=========
References
==========
> Add in weekday stuff to tc8521_time_get.

- src/machine/m_xt_t1000.c
Summary
=======
Checklist
=========
References
==========
> Oops, fix build

- src/machine/m_xt_t1000.c
Summary
=======
Checklist
=========
References
==========
> Actually fix the T1000 RTC

- src/chipset/CMakeLists.txt
- src/chipset/umc_8886.c
- src/chipset/umc_8890.c
- src/chipset/umc_hb4.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
Summary
=======
Some work done on UMC reversing.
https://github.com/86Box/roms/pull/108
Checklist
=========
> Seperated the UMC 8886, Added the UMC 8890

- src/chipset/sis_5571.c
- SMI is now properly provoked
- Removed default methods for registers
- Shadow code is simplified fixing massive slowdowns
- Fixed SMRAM(sort of...)
> Fixes and Improvements on the SiS 5571

- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Fixed "purple pixels" under Win95 using the built-in S3 928 driver.

- src/cpu/cpu.c
Summary
=======
i forgot to add it to the cpu setup on cpu.c
> Fix major issue with the Am486DXL.

- src/config.c
- src/include/86box/plat_dir.h
- src/include/tinyglib.h
- src/win/CMakeLists.txt
- src/win/win_opendir.c
Turns out we had a Windows reimplementation of dirent.h all along.
> Fix build for MSVC

- src/device/hwm_lm78.c
Should fix P3B-F triggering ACPI shutdown early on during the boot process.
> Fix AS99127F GPO defaults

- src/chipset/CMakeLists.txt
- src/chipset/sis_5511.c
- src/chipset/sis_5571.c
- src/chipset/sis_5598.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
- Implemented the SiS 5511
- The SiS 5571 can safely go off Dev Branch now
- Few fixes on the SiS 5598
Checklist
=========
References
==========
https://www.datasheetarchive.com/sis%205511-datasheet.html
> Finalize the SiS Pentiums

- src/video/vid_oak_oti.c
Summary
=======
Checklist
=========
References
==========
> Oak fixes.

- src/disk/hdc.c
- src/disk/hdc_xtide.c
- src/include/86box/hdc.h
> Add a version of XTIDE Universal BIOS for 386

- src/win/win_opengl.c
Summary
=======
This should improve compatibility with older GPUs with drivers that don't support ARB_buffer_storage extension.
Checklist
=========
References
==========
> Alternative buffer method for older GPUs in OpenGL Core

- src/include/86box/machine.h
- src/include/86box/sio.h
- src/machine/m_at_386dx_486.c
- src/machine/m_ps1.c
- src/machine/machine_table.c
- src/sio/CMakeLists.txt
- src/sio/sio_fdc37c651.c
- src/win/Makefile.mingw
Summary
=======
Replaced the unfixable PS/1 2133 with the Siemens D824
Checklist
=========
> Replace the PS/1 2133 with the Siemens D824

- src/chipset/et6000.c
- src/machine/machine_table.c
Summary
=======
Just a few fixes
> Minor fixes for the Olivetti 486

- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/video/CMakeLists.txt
- src/video/vid_att20c49x_ramdac.c
- src/video/vid_ht216.c
- src/video/vid_rtg310x.c
- src/video/vid_s3.c
- src/video/vid_sc1148x_ramdac.c
- src/video/vid_table.c
- src/win/Makefile.mingw
Summary
=======
Checklist
=========
References
==========
> HT209, AT&T 20c49x, Sierra SC1148x fixes and add the Realtek RTG3106 card.

- src/cpu/x87_ops_misc.h
- src/include/86box/vid_svga.h
- src/sound/snd_gus.c
- src/video/vid_cl54xx.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
Fixed 15bpp mode in all cards.
Summary
=======
Checklist
=========
References
==========
> Ported the x87 fix from the other emulator as well as the GUS one.

- src/config.c
> Add config migrations for merged multi-socket machines

- src/video/vid_cl54xx.c
Summary
=======
Checklist
=========
References
==========
> Properly fix the by16 addressing of the Cirrus 542x.

- src/cpu/x87_ops_misc.h
Summary
=======
Checklist
=========
References
==========
> Port over MDK2 fade-in fix from PCem

- src/include/86box/machine.h
- src/machine/m_ps2_mca.c
- src/machine/machine_table.c
- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Made all the non-ViRGE S3 cards disable double word access due annoying acceleration issues in some instances of the software cursor for now.

- src/video/vid_tgui9440.c
Implemented the Graphics Engine linear address from CRTC34-35, required by OS/2.
Implemented 0x21xx acceleration ports.
Implemented Bresenham Line accel command required by OS/2.
Implemented 0xb7fxx linear mapping.
Implemented basic PCI bios rom bar (9440 only).
Revamped Trident TGUI cursor code.
Temporarily removed threading from the code as it caused too many graphical glitches.
Slight improvements to the Recalctimings function.
Un-hardcode the vram mask from the PCI write BAR0 part.
Summary
=======
Checklist
=========
References
==========
> Massive overhaul to the Trident TGUI code:

- src/video/vid_tgui9440.c
implemented MMIO, Linux no longer errors upon initializing the trident module.
Summary
=======
Checklist
=========
References
==========
> Implemented the Scan Line accel command, required by 4Play Win16 game under Win95 using the 4.02 Trident TGUI9440 drivers and

- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> Fix typo on bresenham src x.

- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> Correct src_y/x on the tgui9440 bresenham command once again.

- src/game/gameport.c
- src/include/86box/gameport.h
> Various game port fixes

- src/include/86box/video.h
- src/network/net_ne2000.c
- src/video/vid_table.c
- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> Bring this feature branch up to part with master.

- src/win/win_opengl.c
- src/win/win_opengl_glslp.c
Summary
=======
Add logging via pclog to OpenGL Core renderer:
- Errors on initializing.
- Vendor, renderer and versions.
- Debug messages from driver if supported.
- Errors when building shaders.
Checklist
=========
References
==========
> Add logging to OpenGL Core renderer

- src/win/win_discord.c
> Fix CPU display in Discord Rich Presence

- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> TGUI96x0 banking fixes.

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> Bring the branch up to par with master.

- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Fixed S3 Trio32 PCI ID.

- src/sio/sio_82091aa.c
Summary
=======
Checklist
=========
References
==========
> Fixed 82091AA Serial port disabling.

- src/cpu/386_common.c
Summary
=======
Checklist
=========
References
==========
> Disabled excess CPU logging.

- src/include/86box/scsi_ncr5380.h
- src/scsi/scsi.c
- src/scsi/scsi_ncr5380.c
Summary
=======
Initial implementation of the Trantor T128 XT SCSI (V20+) card along with its BIOS.
Checklist
=========
References
==========
> Added the Trantor 128

- src/scsi/scsi_ncr5380.c
Summary
=======
Hard disk boot fixes for DOS.
Checklist
=========
References
==========
> Bug fixes to the T128 Pseudo-DMA read routine.

- src/disk/hdc_ide_sff8038i.c
Summary
=======
Checklist
=========
References
==========
> Fixed the IDE BusMaster IRQ fix.

- src/include/86box/lpt.h
Summary
=======
Checklist
=========
References
==========
> Fixes to lpt.h.

- src/unix/unix_sdl.c
Summary
=======
Ports commit https://github.com/86Box/86Box/commit/448aec5d405d70c19ab69ef4656e4cc758130715 to unix_sdl.c.
> Port close fix to unix_sdl.c

- src/video/CMakeLists.txt
- src/video/vid_tvp3026_ramdac.c
- src/win/Makefile.mingw
Initial implementation of the tvp3026 ramdac, (clock still missing, will be added later).
Summary
=======
Checklist
=========
References
==========
> S3 & TVP3026: Part 1.

- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Minor pix trans fixes to the S3 code (R/W).

- src/unix/unix.c
Summary
=======
This PR fixes major monitor bug.
Checklist
=========
References
==========
None.
> unix.c: Fix character count in fullscreen string

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Checklist
=========
References
==========
> Added the 3dfx Velocity 100 per request, alongside its BIOS.

- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Fix the dword mode fix in the S3 code.

- src/unix/unix.c
Summary
=======
This PR fixes monitor argument count.
Checklist
=========
References
==========
None.
> Fix monitor argument count

- src/video/vid_voodoo_banshee.c
Summary
=======
Checklist
=========
References
==========
> Corrected SUBSYS information of the Velocity 100, now it displays fine.

- src/win/win_opengl.c
Summary
=======
OpenGL 3.3 renderer can define row length (like sdl renderer) so there's no need to memcpy every line.
Checklist
=========
References
==========
> Make OpenGL 3.3 renderer use only one memcpy

- .github/workflows/cmake.yml
Summary
=======
This PR adds macOS and Linux targets to the GitHub Actions CI.
Checklist
=========
References
==========
None.
> Add macOS and Linux targets to GitHub Actions

- .github/workflows/cmake.yml
Summary
=======
This PR unbreaks GitHub Actions.
Checklist
=========
References
==========
None.
> Unbreak GitHub Actions

- .github/workflows/cmake.yml
Summary
=======
This PR fixes an oversight I made in GitHub Actions.
Checklist
=========
References
==========
None.
> Actually use GCC 11

- src/video/vid_s3.c
Added dword addressing to pix trans reads.
Added VRAM masking to the hardware cursor.
Properly fixed the FIFO slots.
Width set to 1024 by default in the 911 and 924 chips.
Summary
=======
Checklist
=========
References
==========
> S3 changes part 7:

- README.md
Summary
=======
Winbox for 86Box is in pretty good condition now, time to add it as a recommended manager in readme.
Checklist
=========
References
==========
> Add Winbox to recommended managers in readme

- src/config.c
- src/device/serial.c
- src/include/86box/config.h
- src/include/86box/serial.h
- src/machine/m_pcjr.c
- src/machine/m_xt_zenith.c
Summary
=======
just some bits which deal with 4 ports on machines which dont support more than 1/2 ports and some code cleanup
Checklist
=========
> Trivial fixes and cleanups for serial & parallel

- src/win/languages/hr-HR.rc
Summary
=======
This PR commits a few missing translations in the Croatian translation.
Checklist
=========
References
==========
(can be supplied, if necessary)
> Fixes some missing Croatian translations

- src/win/languages/de-DE.rc
Summary
=======
Updates the last remaining vestiges of English text in the translation while also updating some wording.
Checklist
=========
References
==========
(can be added later)
> Fixing some small remaining errors in the German translation

- src/win/languages/zh-CN.rc
Summary
=======
Add Simplified Chinese translation
Checklist
=========
References
==========
> Add Simplified Chinese (zh-CN) translation

- src/86box.c
Summary
=======
This PR fixes macOS ROM directory.
Checklist
=========
References
==========
None.
> Fix macOS rom directory

- src/video/vid_ati28800.c
Reverted one major change of the ATI 28800 cards that caused glitches.
Summary
=======
Checklist
=========
References
==========
> Changes list 3:

- src/video/vid_s3_virge.c
Summary
=======
Fixed Diamond Stealth 3D 4000's hangs using its specific drivers on Win9x.
Checklist
=========
References
==========
> Changes list 4:

- src/CMakeLists.txt
Summary
=======
This PR fixes macOS building.
Checklist
=========
References
==========
> Fix macOS linking

- src/win/languages/de-DE.rc
- src/win/languages/hr-HR.rc
Summary
=======
This PR improves the German and Croatian translation even further to make some phrases less awkward sounding.
Checklist
=========
References
==========
(can be supplied if needed)
> Further improvements to the German and Croatian translation

- src/win/languages/fi-FI.rc
Summary
=======
Clarify the two different settings.
Shorten few strings.
Checklist
=========
References
==========
> Improve some of fi-FI translation

- src/win/languages/zh-CN.rc
Summary
=======
Update Chinese (zh-CN) translation. "Preferences" translated into Chinese. 
Checklist
=========
References
==========
> Update Chinese (zh-CN) translation

- src/video/vid_sigma.c
Summary
=======
Checklist
=========
References
==========
> Fixed text mode of the Sigma video card.

- src/video/vid_tgui9440.c
Summary
=======
Checklist
=========
References
==========
> Removed excess logs of the tgui9440/96x0.

- src/win/languages/ru-RU.rc
Summary
=======
Fixed some grammar issues. Fixed some long text labels in dialogs that don't fit.
Overall translation text changed to be more natural for native speakers.
Checklist
=========
References
==========
> Updated Russian translation ru-RU.rc

- src/win/languages/fr-FR.rc
Properly translated the Help menu tab to Aide instead of ?.
> Fixed a translating error.

- src/win/languages/zh-CN.rc
Correct a few typos, adjust individual sentences
Summary
=======
Checklist
=========
References
==========
> Update simplified Chinese text

- src/win/languages/zh-CN.rc
Summary
=======
Update Simplified Chinese translation.
Checklist
=========
References
==========
> Update Simplified Chinese translation

- src/CMakeLists.txt
- src/fifo8.c
- src/include/86box/fifo8.h
- src/include/86box/scsi_pcscsi.h
- src/scsi/scsi.c
- src/scsi/scsi_pcscsi.c
- src/win/Makefile.mingw
Added the NCR 53c90 SCSI MCA card and reworked the AMD PCscsi/Tekram DC390 code to use a better port.
Summary
=======
Checklist
=========
References
==========
> Added QEMU's fifo8 code.

- src/game/gameport.c
- src/game/joystick_standard.c
- src/game/joystick_sw_pad.c
- src/include/86box/gameport.h
- src/include/86box/joystick_standard.h
Summary
=======
Add support for generic 3 axis, 2 button and 3 axis, 4 button joysticks as windows 9x supports them
also add support for a game port at 0x208-0x20f
Checklist
=========
References
==========
> More Joysticks

- src/win/languages/ru-RU.rc
Summary
=======
Checklist
=========
References
==========
> Парочка изменений // A couple of changes

- src/mac/CMakeLists.txt
- src/win/languages/de-DE.rc
Summary
=======
Fixes some smaller awkward translations and translates the previously untranslated strings.
Checklist
=========
References
==========
(can be supplied later)
> Updates to the current German translation

- src/sound/snd_mpu401.c
Summary
=======
Checklist
=========
References
==========
> Pass sysex messages in mpu-401 uart mode

- src/win/languages/de-DE.rc
- src/win/languages/hr-HR.rc
Summary
=======
- fixes some smaller translations in German
- translates the new renderer strings to Croatian
- other minor fixes
Checklist
=========
References
==========
_(can be supplied by request)_
> Various translation fixes

- src/config.c
- src/include/86box/plat.h
- src/unix/unix.c
- src/win/win_ui.c
In preparation for toolbar implementation in both win32 and qt
Summary
=======
Checklist
=========
References
==========
> Add hide_tool_bar config file setting

- src/sound/snd_adlibgold.c
Summary
=======
See above.
Checklist
=========
References
==========
> Added MIDI In/Out to the AdLib Gold as well as a fix to wave out.

- src/win/languages/pl-PL.rc
Summary
=======
Polish translation
Checklist
=========
References
==========
N/A
> Polish translation

- src/win/languages/ru-RU.rc
> Update the Russian translation

- CMakeLists.txt
- src/device/CMakeLists.txt
- src/device/isamem.c
- src/win/Makefile.mingw
Summary
=======
Add prelimanary support for the Boca Research BocaRAM/AT
Checklist
=========
References
==========
https://stason.org/TULARC/pc/memory-cards/BOCA-RESEARCH-INC-Memory-card-BOCARAM-AT.html
> Initial Boca Research BocaRAM/AT support

- src/win/languages/ru-RU.rc
Summary
=======
_[Better Russian translation](https://github.com/86Box/86Box/blob/master/src/win/languages/ru-RU.rc)_
> Better translation

- src/cpu/CMakeLists.txt
This fixes build with dynarec that i broke. (and still builds with dynarec disabled)
> fix build with dynarec

- src/include/86box/vid_cga.h
- src/include/86box/vid_cga_comp.h
- src/include/86box/vid_hercules.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_vga.h
- src/video/vid_hercules.c
- src/video/vid_vga.c
Summary
=======
Cleanups to some video stuff, should make it easier to implement dual video cards in future, but does make things more consistent.
Checklist
=========
References
==========
> Some video related cleanups

- .github/workflows/cmake.yml
- CMakePresets.json
Summary
=======
More consistency for Github Actions builds
Checklist
=========
References
==========
> More Consistency for github actions builds

- src/win/languages/uk_UA.rc
Add Ukrainian Translation.
Original Translator: Олександр (Олександр#9368)
Summary
=======
Ukrainian Translation.
Checklist
=========
[ V ] Translation to Ukrainian
References
==========
Олександр (Олександр#9368) | Original Translator.
> Add Ukrainian Translation.

- src/win/languages/pl-PL.rc
Summary
=======
Fix missing strings in polish
Checklist
=========
References
==========
> Fix missing strings

- src/sound/snd_speaker.c
- src/sound/sound.c
Summary
=======
This PR fixes brief extreme noise on hard resets.
Checklist
=========
References
==========
None.
> Fix brief extreme noise on hard resets

- src/config.c
Summary
=======
Preliminary config stuff for selectable uart type, commented out for now, just so I don't forget.
Checklist
=========
References
==========
> Preliminary config stuff for selectable uart type

- src/sound/snd_sb_dsp.c
Summary
=======
Additional comments for (missing) DSP commands
Checklist
=========
References
==========
> Additional comments in sb_dsp.c

- src/chipset/scamp.c
Summary
=======
Checklist
=========
References
==========
> Added EMS emulation to the SCAMP chipset from the PCem emulator.

- src/disk/hdc_ide.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fixed IDE storage class identification.

- src/qt/qt_ui.cpp
Summary
=======
Fixes status bar messages (ISA debugger, POST card)
Checklist
=========
References
==========
> fix statusbar message

- src/chipset/scamp.c
Summary
=======
See above
Checklist
=========
References
==========
> Ported the latest fixes of the SCAMP EMS implementation from PCem.

- src/qt/languages/de-DE.po
- src/qt/languages/hr-HR.po
- src/win/languages/de-DE.rc
- src/win/languages/hr-HR.rc
Summary
=======
Updating the German and Croatian translations with the missing strings and doing smaller fixes.
Checklist
=========
References
==========
_(can be supplied later)_
> Translation updates for Win32 and Qt (German and Croatian)

- .github/workflows/cmake.yml
- CMakeLists.txt
Summary
=======
This PR makes Qt UI the default for non-Windows systems.
Checklist
=========
References
==========
None.
> Qt is now on by default for non-Windows

- src/qt/qt_deviceconfig.cpp
- src/qt/qt_deviceconfig.hpp
- src/qt/qt_settings.cpp
- src/qt/qt_settings.hpp
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsinput.cpp
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsotherperipherals.cpp
- src/qt/qt_settingssound.cpp
- src/qt/qt_settingsstoragecontrollers.cpp
- src/qt/qt_styleoverride.cpp
- src/qt/qt_styleoverride.hpp
Summary
=======
* Fix fixed size window sizing
* Fix device config windows not appearing centered and modal under Wayland
Checklist
=========
References
==========
None.
> Qt: More bug fixes

- src/qt/qt_machinestatus.cpp
- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Scale statusbar icons based on DPI
Checklist
=========
References
==========
None.
> qt: Scale statusbar icons based on DPI

- src/qt/qt_filefield.cpp
- src/qt/qt_filefield.ui
- src/qt/qt_styleoverride.cpp
Summary
=======
* qt: Combo boxes are no longer cramped
* qt: File fields are no longer cramped
Checklist
=========
References
==========
None.
> qt: Dialog improvements

- src/qt/qt_mainwindow.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_progsettings.cpp
Summary
=======
* qt: Replace plat_path_abs with the ones from the Unix and Win32 backends
* qt: Fix compilation on Qt 6
Checklist
=========
References
==========
None.
> qt: Platform code fixes

- src/qt/qt_hardwarerenderer.cpp
- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_softwarerenderer.cpp
Summary
=======
* Patch to build with Qt 5.11 and later by @jriwanek 
* Attempt to fix viewport on hardware renderers
* qt: Properly set saved window size for real
Checklist
=========
* [X} Closes #2100
References
==========
None.
> qt: Compatibility improvements

- src/disk/hdc_ide.c
Summary
=======
See above.
Checklist
=========
References
==========
> Ported the SCAMP IDE fix from PCem.

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
Summary
=======
* qt: Group with the manager on taskbar on settings mode
* qt: Fix toolbar text when paused
Checklist
=========
References
==========
None.
> qt: Windows fixes

- .github/workflows/cmake.yml
- src/device/ibm_5161.c
- src/include/86box/sound.h
- src/sound/snd_gus.c
- src/sound/snd_pssj.c
- src/sound/snd_sb.c
- src/sound/snd_sn76489.c
- src/sound/sound.c
- src/win/languages/de-DE.rc
- src/win/languages/dialogs.rc
Summary
=======
More Win32 UI and Soundblaster Improvements
Adds the TNDY sound card using the SN76496 courtesy of @Ompronce 
Checklist
=========
References
==========
> More Win32 UI, TNDY, and Soundblaster Improvements

- CMakeLists.txt
- src/chipset/intel_piix.c
- src/device/isamem.c
- src/include_make/86box/version.h
- src/printer/prt_cpmap.c
- src/printer/prt_escp.c
- src/qt/languages/pl-PL.po
- src/qt/qt_sdl.c
- src/win/win_sdl.c
Summary
=======
* Update the default copyright year
* The U+FFFD REPLACEMENT CHARACTER in certain code comments is replaced with the intended letter
* Change the internal name for the PIIX3 variation for boards with I/O APIC to disambiguate it for the regular PIIX3
* ISAMEM changes: fix a compilation warning, use proper #ifdefs for the dev-branching
* Port the Polish translation changes from #2070 to the Qt UI 
Checklist
=========
> Miscellaneous fixes

- src/qt/qt_progsettings.hpp
> Remove the last remaining trace of the defunct VRAM dumping function

- src/qt/qt_settingsmachine.cpp
Summary
========
The "Machine type" combobox in the Qt UI now hides machine types for which no machines have their ROMs available.
Checklist
=========
> qt: hide machine types with no available machines

- src/cdrom/CMakeLists.txt
- src/cdrom/cdrom.c
- src/cdrom/cdrom_mitsumi.c
- src/include/86box/cdrom.h
- src/include/86box/cdrom_mitsumi.h
Summary
=======
See above
Checklist
=========
References
==========
> Added preliminary emulation of the Mitsumi CD-ROM interface

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Adds the  Z-NIX PC-1600 a budget friendly 8088 PC
Checklist
=========
References
==========
Bios is from Don Maslin's Archive
> Add the Z-NIX PC-1600

- src/CMakeLists.txt
- src/include/86box/device.h
- src/video/vid_et4000.c
- src/video/vid_oak_oti.c
- src/video/vid_svga.c
- src/win/Makefile.mingw
Summary
=======
More consistency changes to bring better in line with M&K
Checklist
=========
References
==========
> A few consistency changes form M&K branch

- src/acpi.c
- src/include/86box/acpi.h
- src/include/86box/chipset.h
Summary
=======
Removes leftover SIS ACPI stuff
Checklist
=========
References
==========
> Removes leftover SIS ACPI stuff

- src/qt/qt_main.cpp
- src/qt/qt_unixmanagerfilter.cpp
Summary
=======
qt: Actually make client-side Unix manager integration functional
Checklist
=========
References
==========
None.
> qt: Actually make client-side Unix manager integration functional

- src/qt/qt_openglrenderer.hpp
Summary
=======
qt: Fix building with Qt 6
Checklist
=========
References
==========
None.
> qt: Fix building with Qt 6

- src/include/86box/scsi_ncr5380.h
- src/scsi/scsi.c
- src/scsi/scsi_ncr5380.c
Summary
=======
See above.
Checklist
=========
References
==========
> Added the Corel LS2000 53c400-based card.

- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
Summary
=======
This should fix the arm32 linux builds on jenkins.
Checklist
=========
References
==========
> qt: fix linux arm32 build error

- src/qt/qt_opengloptions.cpp
- src/qt/qt_opengloptionsdialog.cpp
- src/qt/qt_openglrenderer.cpp
Summary
=======
Fixing the last error revealed more errors; try to fix them with this.
Checklist
=========
References
==========
> More fixes to linux arm32 build

- src/include/86box/vid_svga_render_remap.h
Summary
=======
See above.
Checklist
=========
References
==========
> Fix compile.

- src/86box.c
- src/config.c
- src/disk/hdd_image.c
- src/include/86box/plat.h
- src/qt/qt_platform.cpp
- src/unix/unix.c
- src/win/win.c
Summary
=======
qt: Fix HDD path relativization on Windows
Checklist
=========
References
==========
None.
> qt: Fix HDD path relativization on Windows

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Add support for the Vendex HeadStart Turbo 888-XT
https://discord.com/channels/262614059009048590/873940177716924416/949378524073050122
Checklist
=========
> Add support for the Vendex HeadStart Turbo 888-XT

- src/qt/qt_winrawinputfilter.cpp
- src/qt/qt_winrawinputfilter.hpp
Summary
=======
Checklist
=========
References
==========
> qt: fix Qt6 windows build

- src/game/gameport.c
- src/include/86box/gameport.h
Summary
=======
Support for ThrustMaster ACM, it's not plumbed in yet as that would require UI changes.
Checklist
=========
References
==========
> Thrustmaster ACM

- src/include/86box/machine.h
- src/machine/m_at_compaq.c
- src/machine/machine_table.c
- src/video/vid_ati_mach64.c
Summary
=======
And re-added threading fifo of the mach64 series.
Checklist
=========
References
==========
> Added deskpro386 and fixed 24bpp mode issues of the Mach64GX/VT2.

- src/win/win.c
Summary
=======
win: Fix AppData directory creation for ROMs.
Checklist
=========
References
==========
None.
> win: Fix AppData directory creation

- src/win/Makefile.mingw
Summary
=======
Just a quick reorganise of defines in makefile.mingw to bring it more in-line with the CMake scripts
Checklist
=========
References
==========
> Reorganise stuff in makefile.mingw

- src/qt/qt_deviceconfig.cpp
- src/win/Makefile.mingw
Summary
=======
Fixes for remaining issues compiling M&K
Checklist
=========
References
==========
> Fixes for remaining issues compiling M&K

- src/unix/assets/86Box.spec
Summary
=======
- Add a release date variable, and use that to update the release date in the metainfo file
- Update release to 3.4.1
> Update RPM spec file

- src/qt/qt_vulkanrenderer.cpp
- src/qt/qt_vulkanwindowrenderer.cpp
Summary
=======
vulkan: Add HiDPI support
vulkan: Don't select sRGB formats for swapchain
Checklist
=========
References
==========
None.
> vulkan: HiDPI and brightness fixes

- src/86box.c
- src/discord.c
- src/sound/midi_rtmidi.cpp
Summary
=======
Fix some more LLVM/Clang warnings
Checklist
=========
References
==========
> Fix some clang/LLVM warnings

- src/device.c
- src/machine/machine.c
- src/win/win_devconf.c
Summary
=======
Fix segfault and some compiler warns
Checklist
=========
References
==========
> Fix segfault and some compiler warns

- src/device.c
- src/include/86box/machine.h
- src/machine/m_amstrad.c
- src/machine/m_at_compaq.c
- src/machine/m_pcjr.c
- src/machine/m_tandy.c
- src/machine/machine_table.c
Summary
=======
As discussed, (hopefully) the last of the machine_t struct changes we'll need.
Checklist
=========
References
==========
> First bunch of refactors.

- src/qt/qt_platform.cpp
Summary
=======
qt: attempt fixing freezes on power off of emulated machine
Checklist
=========
References
==========
None.
> qt: attempt fixing freezes on power off of emulated machine

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/machine/machine.c
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.ui
- src/video/CMakeLists.txt
- src/video/vid_8514a.c
- src/video/vid_svga.c
- src/win/Makefile.mingw
Summary
=======
Currently the GUI option is on the QT frontend.
Checklist
=========
References
==========
[_ATI Mach32/IBM 8514/A._](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
Mainly the IBM 8514/A side.
> Initial emulation of the IBM 8514/A coprocessor for both the MCA and ISA buses.

- src/network/net_dp8390.c
Summary
=======
Fix broken debug traces
> Buildable with ENABLE_DP8390_LOG

- bumpversion.sh
- src/unix/assets/86Box.spec
> Bump rom version

- src/config.c
- src/include/86box/86box.h
- src/qt/qt_mainwindow.cpp
- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.hpp
- src/qt/qt_progsettings.ui
- src/qt/qt_rendererstack.cpp
- src/qt/wl_mouse.cpp
- src/unix/unix_sdl.c
- src/win/win_mouse.c
Summary
=======
qt: Add mouse sensitivity setting.
Workaround for #2374.
Checklist
=========
References
==========
None.
> qt: Add mouse sensitivity setting

- src/video/vid_8514a.c
- src/video/vid_svga.c
8514/A: More fixes to the accelerated engine, mainly in paintbrush (blackness brush).
SVGA: Preparation of the next batch.
Summary
=======
Checklist
=========
References
==========
> 8514/A: Pitch no longer hardcoded to 1024, fixes 640x480x256 resolutions

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_xga.h
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.ui
- src/video/CMakeLists.txt
- src/video/vid_svga.c
- src/video/vid_xga.c
- src/win/Makefile.mingw
Summary
=======
For both MCA and ISA buses.
Checklist
=========
References
==========
> Added initial (and a bit buggy on OS/2, so use 8514/A on it instead) emulation of XGA

- src/include/86box/video.h
- src/machine/machine.c
Summary
=======
Checklist
=========
References
==========
> Forgot one more thing about XGA. Fixes initialization of the card.

- src/qt/CMakeLists.txt
- src/qt/qt.c
- src/qt/qt_d3d9renderer.cpp
- src/qt/qt_d3d9renderer.hpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.ui
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
This PR adds the Direct3D 9 renderer that was previously removed.
Checklist
=========
References
==========
None.
> qt: add Direct3D 9 renderer

- src/video/vid_ega_render.c
Summary
=======
Checklist
=========
References
==========
> EGA fixes to its renderer.

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
modes.
Summary
=======
Checklist
=========
References
==========
> Slight fixes to the 8514/A blitter in line draw, rectangle and outline

- src/scsi/scsi_ncr5380.c
Summary
=======
Checklist
=========
References
==========
> Fixed the Rancho RT1000A/B aspi manager loading (rtaspi10.sys).

- src/scsi/scsi_ncr5380.c
Summary
=======
Checklist
=========
References
==========
> Make the dedicated Longshine SCSI ASPI driver work under DOS.

- src/video/vid_8514a.c
Summary
=======
Checklist
=========
References
==========
> Fixed the overscan setting when using the 8514/A native drivers.

- src/win/Makefile.mingw
Summary
=======
Actually build PAS16 on win32ui dev builds
Checklist
=========
References
==========
> Actually build PAS16 on win32ui dev builds

- src/disk/hdc_ide.c
- src/disk/hdd.c
- src/include/86box/hdc_ide.h
- src/include/86box/hdd.h
Summary
=======
- realistic seeking and read/write speed
- read-ahead cache
- write cache
- preset system for performance characteristics (default preset chosen according to HDD size)
Only integrated with IDE currently.
> Add realistic HDD timing simulation

- src/disk/hdd_image.c
- src/port_6x.c
- src/qt/sdl_joystick.cpp
Summary
=======
Various small performance optimisations (no functional change)
Checklist
=========
References
==========
> Various small performance optimisations

- src/gdbstub.c
Summary
=======
gdbstub: Implement 'qsThreadInfo/qfThreadInfo' query
Checklist
=========
References
==========
None.
> gdbstub: Implement 'qsThreadInfo/qfThreadInfo' query

- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/machine_table.c
Summary
=======
Added Soltek SL-56A5
Socket 7, 430TX
Checklist
=========
References
==========
none
> Added  Soltek SL-56A5

- src/chipset/ali1489.c
- src/chipset/via_pipc.c
- src/machine/m_amstrad.c
- src/sound/snd_audiopci.c
- src/video/vid_sigma.c
Summary
=======
Checklist
=========
References
==========
> Revert to the old NMI way in the AudioPCI code.

- src/config.c
- src/disk/hdc_ide.c
- src/disk/hdd.c
- src/include/86box/hdd.h
- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddiskdialog.hpp
- src/qt/qt_harddiskdialog.ui
- src/qt/qt_harddrive_common.cpp
- src/qt/qt_harddrive_common.hpp
- src/qt/qt_settingsharddisks.cpp
- src/qt/qt_settingsharddisks.hpp
- src/qt/qt_settingsharddisks.ui
Summary
=======
Add Qt UI and configuration for selecting HDD speed
Checklist
=========
References
==========
> hdd: make speed preset configurable

- src/dma.c
Summary
=======
Checklist
=========
References
==========
> Revert the DMA auto-init hack on PS/2.

- src/cpu/cpu.c
- src/include/86box/keyboard.h
- src/include/86box/machine.h
- src/machine/m_amstrad.c
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_compaq.c
- src/machine/m_at_slot1.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket4.c
- src/machine/m_at_socket7.c
- src/machine/m_at_socket7_3v.c
- src/machine/m_pcjr.c
- src/machine/m_ps2_isa.c
- src/machine/m_ps2_mca.c
- src/machine/m_tandy.c
- src/machine/m_xt_olivetti.c
- src/machine/m_xt_t1000.c
- src/machine/m_xt_xi8088.c
- src/machine/m_xt_zenith.c
- src/machine/machine_table.c
- src/mem/spd.c
Summary
=======
Named initializers in machine table
Checklist
=========
References
==========
None
> Named initializers in machine table

- src/machine/machine_table.c
Summary
=======
Re-add ICH2 machines, they got lost
Checklist
=========
References
==========
None
> Re-add ICH2 machines, they got lost

- src/acpi.c
- src/config.c
- src/cpu/cpu.c
- src/include/86box/machine.h
- src/include/86box/nvr_ps2.h
- src/include/86box/vid_ega_render_remap.h
- src/pic.c
- src/sound/midi_rtmidi.cpp
Summary
=======
Cleanups to various bits of code
Checklist
=========
References
==========
None
> Cleanups to various bits of code

- src/include/86box/device.h
Summary
=======
Fix compile
Checklist
=========
References
==========
None
> Fix compile

- src/device/pci_bridge.c
- src/device/smbus_piix4.c
- src/include/86box/machine.h
- src/include/86box/smbus.h
- src/machine/machine_table.c
Summary
=======
Missing ports from M&K
Checklist
=========
References
==========
> Missing ports from M&K

- src/network/net_pcnet.c
- src/scsi/scsi_pcscsi.c
- src/scsi/scsi_spock.c
Summary
=======
Storage: Implemented initial DMA DRQ's in the 53c90 MCA SCSI card. Properly fixed the multiple drives on the IBM PS/2 SCSI card (Spock).
Checklist
=========
References
==========
> Networking: moved the pcnetPollTimer calls to a timer.

- src/include/86box/video.h
- src/video/vid_cl54xx.c
- src/video/vid_table.c
Summary
=======
Adds the Boca Research 4610
Checklist
=========
References
==========
> Boca Reseach 4610

- src/86box.c
- src/config.c
- src/device/serial.c
- src/include/86box/86box.h
- src/include/86box/config.h
- src/include/86box/serial.h
- src/qt/qt_settingsports.cpp
- src/win/win_settings.c
Summary
=======
More serial cleanups in preperation for serial device support.
Checklist
=========
References
==========
None
> More serial cleanups

- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
- src/unix/unix.c
Summary
=======
qt: Fix black screen when switching between renderers
Checklist
=========
References
==========
None,
> qt: Fix black screen when switching between renderers

- src/config.c
- src/disk/hdc_esdi_at.c
- src/qt/qt_harddrive_common.cpp
Summary
=======
ESDI: implement HDD timings and fix status icon updating
Checklist
=========
References
==========
> ESDI: implement HDD timings and fix status icon updating

- src/disk/hdc_esdi_mca.c
Summary
=======
ESDI MCA: implement HDD timings and fix status icon updating
Checklist
=========
References
==========
> ESDI MCA: implement HDD timings and fix status icon updating

- src/machine/machine_table.c
Summary
=======
Re-add other machines which went missing from the machine table
Checklist
=========
References
==========
None
> Re-add other machines which went missing from the machine table

- src/video/vid_cl54xx.c
Summary
=======
Checklist
=========
References
==========
> Fixed the rom loading of the boca cirrus 5428 bios.

- src/device.c
- src/include/86box/device.h
- src/sound/snd_pas16.c
Summary
=======
Remove unnecessary DEVICE_NOT_WORKING flag
Checklist
=========
References
==========
None
> Remove unnecessary DEVICE_NOT_WORKING

- bumpversion.sh
- src/unix/assets/86Box.spec
Summary
=======
- Remove rom version, since it is now in sync with the main release
- add openal to the build requirements
> update RPM spec

- src/sound/midi_fluidsynth.c
Summary
=======
fluidsynth: Add channel pressure handling
Checklist
=========
References
==========
https://www.fluidsynth.org/api/group__midi__messages.html#ga3fda0f875e943e3ec100e4990fddaaf8
> fluidsynth: Add channel pressure handling

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_at_slot1.c
- src/machine/m_xt_t1000.c
- src/machine/machine_table.c
Summary
=======
Machine table changes and function cleanups
Checklist
=========
References
==========
None
> Machine table changes and function cleanups

- src/nvr.c
Summary
=======
NVR: Don't fatal on failure to read NVR properly
Checklist
=========
References
==========
None.
> NVR: Don't fatal on failure to read NVR properly

- src/qt/qt_rendererstack.cpp
Summary
=======
qt: Restore Xinput2 for Qt5 builds
Disabled by default but still available for Qt6 builds.
Checklist
=========
References
==========
None.
> qt: Restore Xinput2 for Qt5 builds

- src/86box.c
- src/config.c
- src/include/86box/net_dp8390.h
- src/include/86box/net_event.h
- src/include/86box/network.h
- src/network/CMakeLists.txt
- src/network/net_3c503.c
- src/network/net_dp8390.c
- src/network/net_event.c
- src/network/net_ne2000.c
- src/network/net_pcap.c
- src/network/net_pcnet.c
- src/network/net_plip.c
- src/network/net_slirp.c
- src/network/net_wd8003.c
- src/network/network.c
- src/qt/qt_machinestatus.cpp
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsnetwork.hpp
- src/qt/qt_settingsnetwork.ui
- src/win/Makefile.mingw
- src/win/win_settings.c
- src/win/win_stbar.c
Summary
=======
- Add support for multiple NICs
- Switch from polling to an event loop for the host networking to improve latency and locking issues
Checklist
=========
References
==========
> Network overhaul: support for multiple NICs, performance improvement

- src/include/86box/midi.h
- src/sound/midi.c
- src/sound/midi_mt32.c
Summary
=======
Adds MT-32 (New) and CM-32LN
Checklist
=========
References
==========
None
> Add MT-32 (New) and CM-32LN

- src/chipset/intel_4x0.c
- src/chipset/via_apollo.c
- src/include/86box/agpgart.h
- src/include/86box/video.h
- src/video/agpgart.c
Summary
=======
Simplifies code in the long term
Checklist
=========
References
==========
None
> Expose agpgart_t

- src/qt/qt_hardwarerenderer.cpp
Summary
=======
qt_hardwarerenderer: Fix compilation with Qt 5.12
Checklist
=========
References
==========
None.
> qt_hardwarerenderer: Fix compilation with Qt 5.12

- src/CMakeLists.txt
- src/config.c
- src/device.c
- src/include/86box/config.h
- src/include/86box/ini.h
- src/ini.c
- src/network/net_slirp.c
- src/qt/qt_deviceconfig.cpp
- src/sound/midi_rtmidi.cpp
- src/win/Makefile.mingw
- src/win/win_devconf.c
Summary
=======
This moves the INI parsing business into a separate module that `config.c` and friends call.
Checklist
=========
> config: Refactor the INI parser out

- src/include/86box/machine.h
- src/machine/m_at_socket7_3v.c
- src/machine/machine_table.c
Summary
=======
machine: Add MSI MS-5124
Checklist
=========
References
==========
None.
> machine: Add MSI MS-5124

- .clang-format
- src/device/isapnp.c
Summary
=======
A few minor improvements:
no longer try to format include order
a missing ni change in isapnp
Checklist
=========
References
==========
None
> Improvements

- CMakeLists.txt
- src/cpu/386.c
- src/include/86box/sound.h
- src/ini.c
- src/sound/CMakeLists.txt
- src/sound/snd_pssj.c
- src/sound/snd_sn76489.c
- src/sound/sound.c
- src/video/vid_xga.c
- src/video/video.c
- src/win/Makefile.mingw
Summary
=======
Fix bug in PSSJ ISA Clone
Add alternate address options to PSSJ ISA clone
Add alternate address options to TNDY
Fix several compile warns
PSSJ ISA and TNDY no longer dev branched (The noise issue occurs on real hardware too)
Checklist
=========
References
==========
Utility to silence PSSJ/TNDY: https://github.com/matze79/sndoff
> Enable TNDY & PSSJ ISA clone

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_tvga.c
Summary
=======
Add NEC SV9000 (Trident TVGA9000B)
Checklist
=========
References
==========
None.
> Add NEC SV9000 (Trident TVGA9000B)

- src/video/vid_table.c
> vid_table: Fix build with logging enabled

- src/video/video.c
Summary
=======
This fixes a copy & paste error.
Checklist
=========
> Fix build with ENABLE_VIDEO_LOG

- src/qt/qt_ui.cpp
Summary
=======
qt: Always resize
Checklist
=========
References
==========
None.
> qt: Always resize

- src/machine/m_amstrad.c
- src/machine/m_xt_olivetti.c
> Fix Amstrad/Olivetti internal mice not working by explicitly defining the number of buttons

- src/machine/m_xt_olivetti.c
Summary
=======
Fix Linux build
Checklist
=========
References
==========
None.
> Fix Linux build

- src/disk/hdc.c
Summary
=======
Remove unnecessary functions
Checklist
=========
References
==========
None
> Remove unnecessary functions

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
a V20-XT only bios, doesn't work with  a 8088 cpu
Checklist
=========
> Added V20-XT

- src/device/mouse_ps2.c
- src/unix/unix.c
- src/win/win_mouse.c
Summary
=======
Add option for 5-button PS/2 mouse.
Checklist
=========
References
==========
None.
> Add option for 5-button PS/2 mouse

- src/machine/machine_table.c
Summary
=======
Checklist
=========
References
==========
> Sorted 8088 & 8086 entries alphabetically

- src/device/mouse_ps2.c
Summary
=======
mouse_ps2: Unify movement packet reporting mechanisms
Checklist
=========
References
==========
None.
> mouse_ps2: Unify movement packet reporting mechanisms

- src/device/mouse_ps2.c
Summary
=======
Fix warning.
Checklist
=========
References
==========
None.
> Fix warning

- src/machine/m_xt_olivetti.c
- src/machine/machine_table.c
Summary
=======
Emulation of National Semiconductor MM58274 RTC for Olivetti M240.
> Olivetti M240 - Support MM58274 RTC

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: make background of main window black
Checklist
=========
References
==========
None.
> qt: make background of main window black

- src/qt/qt_mainwindow.hpp
Summary
=======
qt: try another fix for the issue
Checklist
=========
References
==========
None.
> qt: try another fix for the issue

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Adding the Packard Bell PB8810
Checklist
=========
* [ x ] This pull request requires changes to the ROM set
* [ x ] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/
References
==========
http://pbplanet.info/wiki/images/archive/0/0e/20130113013546%21PB8810.JPG
> Added the Packard Bell PB8810

- src/qt/qt_hardwarerenderer.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_rendererstack.cpp
Summary
=======
qt: fix white screen for real
Checklist
=========
References
==========
None.
> qt: fix white screen for real

- src/qt/qt_openglrenderer.cpp
Summary
=======
qt: fix macOS build
Checklist
=========
References
==========
None.
> qt: fix macOS build

- src/86box.c
- src/config.c
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/en-GB.po
- src/qt/languages/en-US.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sl-SI.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/zh-CN.po
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
Summary
=======
2× really doesn't cut it for many lower resolutions on my 4K monitor. I know people also with 8K monitors, so let's go even higher than that to somewhat future-proof the emulator here.
Checklist
=========
> Higher scaling factors

- src/qt/qt_mainwindow.cpp
- src/qt/qt_vulkanwindowrenderer.cpp
Summary
=======
qt: disable Vulkan early if not available
Checklist
=========
References
==========
None.
> qt: disable Vulkan early if not available

- src/video/vid_voodoo_banshee.c
Summary
=======
Improve Banshee error reporting
Stubbed Banshee AGP registers
Checklist
=========
References
==========
None.
> Improve Banshee error reporting

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Adding Micoms XL7-Turbo (8088 board, PC/XT compatible)
Checklist
=========
References
==========
https://www.sandacite.com/forum/index.php?topic=13546.0
https://www.vogons.org/viewtopic.php?t=65088
https://www.phantom.sannata.org/viewtopic.php?t=13443&start=77
> Micoms XL7-Turbo

- src/cdrom/CMakeLists.txt
- src/cdrom/cdrom.c
- src/cdrom/cdrom_mitsumi.c
- src/include/86box/cdrom.h
- src/include/86box/cdrom_mitsumi.h
- src/win/Makefile.mingw
Summary
=======
Port the remaining Mitsumi cdrom stuff from M&K
Checklist
=========
References
==========
None
> Port Mitsumi cdrom stuff from M&K

- src/video/CMakeLists.txt
- src/video/vid_et3000.c
- src/video/vid_table.c
- src/win/Makefile.mingw
Summary
=======
Port Tseng Labs ET3000AX (ISA) from M&K
ROM PR not yet done as I don't have the ROM.
Checklist
=========
References
==========
None
> Port Tseng Labs ET3000AX (ISA) from M&K

- src/include/86box/vid_voodoo_common.h
- src/video/vid_voodoo_banshee.c
- src/video/vid_voodoo_fifo.c
Summary
=======
voodoo: Partial implementation of cmdStatus0 register
Checklist
=========
References
==========
None.
> voodoo: Partial implementation of cmdStatus0 register

- src/86box.c
- src/cdrom/cdrom_image_viso.c
- src/config.c
- src/include/86box/ini.h
- src/include/86box/network.h
- src/ini.c
- src/network/net_slirp.c
- src/network/network.c
- src/video/vid_xga.c
Summary
=======
More compile warning fixes
Checklist
=========
References
==========
None
> More compile warning fixes

- src/video/vid_et4000.c
- src/video/vid_svga.c
- src/video/vid_voodoo_banshee_blitter.c
Summary
=======
Merge harmless bits from M&K and also fix compile fail
Checklist
=========
References
==========
None
> Merge harmless bits from M&K and also fix compile fail

- src/io.c
- src/machine/m_at_socket7.c
Summary
=======
More cleanups of obsolete code
Checklist
=========
References
==========
None
> More cleanups of obsolete code

- src/video/vid_ati_mach64.c
- src/video/vid_mga.c
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
Summary
=======
video: Make the rest of the FIFO variables atomic
Checklist
=========
References
==========
None.
> video: Make the rest of the FIFO variables atomic

- src/win/languages/de-DE.rc
Summary
=======
Update de-DE.rc according to @dob205
Checklist
=========
References
==========
> Update de-DE.rc according to @dob205

- src/include/86box/win.h
- src/win/win_ui.c
Summary
=======
Fix silly mistake
Checklist
=========
References
==========
None
> Fix silly mistake

- src/86box.c
- src/config.c
- src/disk/hdd.c
- src/include/86box/language.h
- src/printer/prt_escp.c
- src/printer/prt_ps.c
- src/qt/qt_main.cpp
- src/qt/qt_platform.cpp
- src/sound/midi_fluidsynth.c
- src/video/vid_svga.c
- src/win/win.c
- src/win/win_about.c
- src/win/win_devconf.c
- src/win/win_dialog.c
- src/win/win_media_menu.c
- src/win/win_new_floppy.c
- src/win/win_opengl.c
- src/win/win_settings.c
- src/win/win_stbar.c
- src/win/win_toolbar.c
- src/win/win_ui.c
Summary
=======
Fix language string offsetting in win32 ui
Checklist
=========
References
==========
None
> Fix language string offsetting in win32 ui

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Adds Voodoo 3 3500, 3500 SE, 3500 SI, 3500 (Compaq OEM), Voodoo 3 1000, and Velocity 200 AGP
Also cleans up the code a little bit
Checklist
=========
References
==========
https://3dfxbios.cl-rahden.de/index.php?title=Voodoo3
http://3dfxbios.stantoworld.co.uk/files/3dfx_source_code.rar
http://3dfxbios.stantoworld.co.uk/html/bios.html
> Voodoo3 updates

- src/include/86box/hdd.h
- src/qt/qt_harddiskdialog.cpp
- src/win/win_settings.c
Summary
=======
Fix up some more magic numbers relating to hdd image creation
Checklist
=========
References
==========
None.
> Fix up some more magic numbers relating to hdd image creation

- src/video/vid_tgui9440.c
Summary
=======
Fixed Bresenham infinite loop when error term is > 0 alongside CX being 0.
Checklist
=========
References
==========
> Fixed LFB access on the VLB front of the TGUI9440AGi.

- src/sound/snd_azt2316a.c
Summary
=======
Add proper AcerMagic S20 emulation
Checklist
=========
References
==========
None.
> Add proper AcerMagic S20 emulation

- src/sound/snd_azt2316a.c
Summary
=======
Fix AcerMagic S20 detection in a third-party driver
Checklist
=========
References
==========
None.
> Fix AcerMagic S20 detection in a third-party driver

- CMakeLists.txt
- debian/changelog
- src/include_make/86box/version.h
- src/unix/assets/86Box.spec
- src/unix/assets/net.86box.86Box.metainfo.xml
- vcpkg.json
Summary
=======
Update version to 3.11 in preparation for release
Checklist
=========
References
==========
None
> Update version to 3.11 in preparation for release

- src/include/86box/rom.h
- src/include/86box/snd_opl.h
- src/include/86box/sound.h
- src/mem/rom.c
- src/sound/snd_opl.c
- src/sound/snd_opl_ymfm.cpp
- src/sound/snd_optimc.c
- src/sound/sound.c
- src/sound/ymfm/ymfm_pcm.h
Summary
=======
Add OPL4 and miroSOUND PCM10 emulation
Checklist
=========
References
==========
None.
> Add OPL4 and miroSOUND PCM10 emulation

- src/sound/snd_ad1848.c
- src/sound/snd_optimc.c
Summary
=======
OPTiMC: Fix CD audio mixer and gameport type
Checklist
=========
References
==========
None.
> OPTiMC: Fix CD audio mixer and gameport type

- src/include/86box/net_3c501.h
- src/network/CMakeLists.txt
- src/network/net_3c501.c
- src/network/net_pcnet.c
- src/network/network.c
- src/win/Makefile.mingw
Summary
=======
Added IRQ's 10 and 11 to the AMD PCnet ISA/VLB nics.
Checklist
=========
References
==========
> Ported the 3c500/3c501 nic from VirtualBox.

- src/minitrace/minitrace.c
- src/win/Makefile.mingw
Summary
=======
Minitrace fixes so it compiles again
Checklist
=========
References
==========
None
> Minitrace fixes so it compiles again

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
Summary
=======
Fix Github win32 QT Builds
Checklist
=========
References
==========
None
> Fix Github win32 QT Builds

- src/qt/qt_mainwindow.cpp
Summary
=======
Reset size of screen on 4:3 option toggling
Checklist
=========
References
==========
None.
> Reset size of screen on 4:3 option toggling

- src/include/86box/unix_sdl.h
- src/unix/macOSXGlue.h
- src/unix/unix.c
- src/unix/unix_sdl.c
Summary
=======
Fix some issues on non QT unix builds
Checklist
=========
References
==========
None
> Fix some issues on non QT unix builds

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
- cmake/llvm-win32-arm.cmake
Summary
=======
Fix many inconsistencies in GHA scripts
Checklist
=========
References
==========
None
> Fix many inconsistencies in GHA scripts

- src/device/isartc.c
- src/machine/m_xt.c
Summary
=======
Add Vendex HeadStart Turbo 888-XT RTC
Checklist
=========
References
==========
None.
> Add Vendex HeadStart Turbo 888-XT RTC

- src/disk/hdc.c
- src/disk/hdc_st506_xt.c
- src/include/86box/hdc.h
Summary
=======
Add Western Digital WDXT-GEN
Checklist
=========
References
==========
[WDXT-GEN Users Guide](https://minuszerodegrees.net/manuals/Western%20Digital/WDXT-GEN%20-%20Users%20Guide.pdf)
Ownership of the physical hardware.
> Add Western Digital WDXT-GEN

- src/sound/snd_audiopci.c
Summary
=======
Backport commit e1e3475bd482e3350a2ec442a0a9fda8ba5cff06 from PCem
Checklist
=========
References
==========
None.
> Backport commit e1e3475bd482e3350a2ec442a0a9fda8ba5cff06 from PCem

- src/floppy/fdc.c
- src/floppy/fdc_monster.c
- src/include/86box/fdc_ext.h
Summary
=======
Correct mistakes in monster-fdc
Checklist
=========
References
==========
> Correct mistakes in monster-fdc

- src/cpu/cpu_table.c
Summary
=======
Initial P2 Covington support
Checklist
=========
References
==========
None
> Initial P2 Covington support

- .github/workflows/codeql.yml
Summary
=======
Add CodeQL checking github action
Checklist
=========
References
==========
None
> Add CodeQL checking

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
- src/discord.c
Summary
=======
Use pacboy in mingw makefile builds too 
Preparations for alternate UI builds in GHA 
Use pkgconf, not pkg-config, fixes a warning 
release: false should speed up the msys2 builds a little 
Fix another warning
Checklist
=========
References
==========
> (GHA) Buildsystem updates

- .github/workflows/cmake.yml
- src/include/86box/device.h
Summary
=======
Add some missed bits
Checklist
=========
References
==========
None
> Missed bits

- src/cdrom/cdrom_mitsumi.c
- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_spock.c
Summary
=======
Fix some bits which got lost in the last merge
Checklist
=========
References
==========
None
> Fix some bits which got lost in the last merge

- src/include/86box/vid_svga.h
- src/include/86box/vid_voodoo_common.h
- src/qt/qt_settingsdisplay.cpp
- src/video/vid_cl54xx.c
- src/video/vid_s3.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/vid_table.c
- src/video/vid_voodoo_banshee.c
- src/video/vid_voodoo_display.c
Summary
=======
Add SVGA multi-monitor support
Cirrus Logic CL-GD5436/CL-GD5446 works as secondary video adapters
Checklist
=========
References
==========
None.
> Add SVGA multi-monitor support

- src/include/discord_game_sdk.h
Summary
=======
Fix compile on OpenBSD
Checklist
=========
References
==========
None
> Fix compile on OpenBSD

- src/floppy/fdc.c
- src/floppy/fdc_monster.c
- src/include/86box/fdc.h
Summary
=======
Add tertiary and quaternary FDC options + improvements to monster FDC
Checklist
=========
References
==========
None
>  Add tertiary and quaternary FDC options + improvements to monster FDC

- src/include/86box/version.h.in
- src/win/Makefile.mingw
Summary
=======
More makefile simplification and formatting in version.h.in
Checklist
=========
References
==========
None
> More makefile simplification and formatting in version.h.in

- src/include/86box/flash.h
- src/mem/sst_flash.c
Summary
=======
Add many more flash ROM options
Checklist
=========
References
==========
Winbond and SST Datasheets
> Add many more flash rom options

- src/include/86box/plat_dir.h
- src/unix/unix.c
Summary
=======
Fix non QT builds & Add support for Termux
Checklist
=========
References
==========
None
> Fix non QT builds & Add support for Termux

- src/device/serial.c
- src/include/86box/serial.h
Summary
=======
serial: Fix compilation with Qt
Checklist
=========
References
==========
None.
> serial: Fix compilation with Qt

- src/video/vid_mga.c
Summary
=======
vid_mga: Pattern drawing now works correctly on OS/2
Checklist
=========
References
==========
None.
> vid_mga: Pattern drawing now works correctly on OS/2

- src/video/vid_voodoo_banshee.c
- src/video/vid_voodoo_display.c
Source: https://github.com/sarah-walker-pcem/pcem/pull/199 and https://github.com/86Box/86Box/pull/3035
Summary
=======
Checklist
=========
References
==========
> Port PR#199 from pcem to 86Box.

- CMakeLists.txt
- debian/changelog
- src/include_make/86box/version.h
- src/unix/assets/86Box.spec
- src/unix/assets/net.86box.86Box.metainfo.xml
- vcpkg.json
Summary
=======
Bump version to 4.0
Checklist
=========
References
==========
None
> Bump version to 4.0

- src/device.c
- src/include/86box/device.h
- src/include/86box/machine.h
Summary
=======
device: Add extended parameters infrastructure
Checklist
=========
References
==========
None.
> device: Add extended parameters infrastructure

- src/86box.c
- src/include/86box/language.h
- src/qt/qt_platform.cpp
- src/win/languages/cs-CZ.rc
- src/win/languages/de-DE.rc
- src/win/languages/en-GB.rc
- src/win/languages/en-US.rc
- src/win/languages/es-ES.rc
- src/win/languages/fi-FI.rc
- src/win/languages/fr-FR.rc
- src/win/languages/hr-HR.rc
- src/win/languages/hu-HU.rc
- src/win/languages/it-IT.rc
- src/win/languages/ja-JP.rc
- src/win/languages/ko-KR.rc
- src/win/languages/pl-PL.rc
- src/win/languages/pt-BR.rc
- src/win/languages/pt-PT.rc
- src/win/languages/ru-RU.rc
- src/win/languages/sl-SI.rc
- src/win/languages/tr-TR.rc
- src/win/languages/uk-UA.rc
- src/win/languages/zh-CN.rc
- src/win/languages/zh-TW.rc
Summary
=======
Language strings for missing video 2 rom, and capitalize dynarec
Checklist
=========
References
==========
> Language strings for missing video 2 rom, and capitalize dynarec

- src/chipset/ali1429.c
- src/win/languages/cs-CZ.rc
- src/win/languages/de-DE.rc
- src/win/languages/en-GB.rc
- src/win/languages/en-US.rc
- src/win/languages/es-ES.rc
- src/win/languages/fi-FI.rc
- src/win/languages/fr-FR.rc
- src/win/languages/hr-HR.rc
- src/win/languages/hu-HU.rc
- src/win/languages/it-IT.rc
- src/win/languages/ja-JP.rc
- src/win/languages/ko-KR.rc
- src/win/languages/pl-PL.rc
- src/win/languages/pt-BR.rc
- src/win/languages/pt-PT.rc
- src/win/languages/ru-RU.rc
- src/win/languages/sl-SI.rc
- src/win/languages/tr-TR.rc
- src/win/languages/uk-UA.rc
- src/win/languages/zh-CN.rc
- src/win/languages/zh-TW.rc
Summary
=======
Converts tabs to spaces in the win32 ui language files, next commit will make them less messy.
Checklist
=========
References
==========
> Tabs to spaces in win32 lang files (1/2)

- src/win/win_settings.c
Summary
=======
Some cleanups in win_settings.c
Checklist
=========
References
==========
None
> Some cleanups in win_settings.c

- src/device/mouse_wacom_tablet.c
Summary
=======
wacom: Fix settings reporting
Checklist
=========
References
==========
None.
> wacom: Fix settings reporting

- src/game/gameport.c
Summary
=======
Fix mistake in Thrustmaster ACM code caused by a copy paste fail
Checklist
=========
References
==========
None
> Fix mistake in Thrustmaster ACM code

- src/qt/qt_d3d9renderer.cpp
Summary
=======
qt_d3d9renderer: HiDPI and stability fixes
Checklist
=========
References
==========
None.
> qt_d3d9renderer: HiDPI and stability fixes

- src/usb.c
Summary
=======
OHCI: Replace magic numbers with named enums
Checklist
=========
References
==========
None.
> OHCI: Replace magic numbers with named enums
