86Box/86Box

- src/Makefile.mingw
- src/Makefile.mingw64
- src/model.c
- src/mouse_amstrad.c
- src/mouse_amstrad.h
- src/ps1.c
- src/vid_ati28800.c
Added Amstrad mouse emulation:
Made the Amstrad models prior to the MegaPC use the new Amstrad mouse implementation.
IBM PS/1 ROM DOS Shell now optional.
Interlace support added to the ATI 28800, should allow 800x600x8bpp in the XL24.
> Patchset 1

- src/sound_cms.c
This patch make more accurate CMS emulation like actual GameBlaster.
Original works of this patch from https://www.vogons.org/viewtopic.php?f=41&t=38350 for DOSBox, thanks to them.
> CMS/Game Blaster pitch correction

- src/Makefile.mingw
- src/Makefile.mingw64
- src/win-crashdump.c
- src/win-crashdump.h
- src/win.c
With this PR, just before a crash/segfault happens, and maybe some other times too(?), a crash dump will be made in the same directory as 86Box.exe containing exception details and a register dump.
> Add crash dump functionality

- src/sound/snd_mpu401.c
- src/video/vid_s3.c
Fix for the MPU-401 that was preventing certain SB16 drivers for Windows 3.1 and NT 3.1 to work properly.
> Clock of NT 3.1 now renders correctly with its S3 2.3 drivers.

- src/win/Makefile.mingw
This removes the useless W5580 if condition (-march=native already detects the CPU and sets appropriate flags, no need to do its job manually), and fixes the nonexistent -O6 to be -O3 (the compiler would treat -O6 like -O3 anyway).
> Fix oddities in makefile

- src/86box.h
- src/config.c
- src/machine/m_europc.c
- src/machine/m_xt_t1000.c
- src/nvr.c
- src/nvr.h
- src/nvr_at.c
- src/pc.c
- src/win/86Box.rc
- src/win/resource.h
- src/win/win_settings.c
Some operating systems are not much fond of the RTC running in local time. This patch introduces a UTC mode for timesync, which is fully configurable from the Settings dialog:
This patch also replaces the numeric `enable_sync` config value with the textual `time_sync` with three possible values: `disabled`, `local` and `utc`. This shouldn't break existing configs. Existing `enable_sync` setings are automatically replaced with an appropriate `time_sync` value. In case `enable_sync` and `time_sync` settings are both present in a configuration file (shouldn't happen without manually editing the config), `time_sync` takes precedence.
> Add support for synchronizing guest clock to UTC

- src/sound/snd_sb.c
The CD sound volume is too quiet with Sound Blaster cards.
The mixing tables give headroom to avoid integer overflow, and the rest of the SB emulation code is written to reflect this. But the headroom needs to be accounted for when setting the CD volume, so as to span the full range of the global CD sound volume. The Ensoniq AudioPCI code has code to compensate of this, but the Sound Blaster code doesn't.
Because two factors (master and CD volumes) are multiplied, this error multiplies up from 50% too quiet, to 25% too quiet. A factor increase of 4 was added to fix this.
> Fix CD volume issue present on SB cards.

- src/win/Makefile.mingw
This patch fixes the incompatibility with the latest msys2 toolchain from http://www.msys2.org/ (which uses GCC-9.2).
> Fix incompatibility with latest mingw toolchain

- src/86box.h
- src/config.c
- src/pc.c
- src/win/86Box.rc
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
- src/win/discord_game_sdk.h
- src/win/resource.h
- src/win/win_discord.c
- src/win/win_discord.h
- src/win/win_ui.c
This PR adds an implementation of DIscord rich presence functionality.
~~This is currently locked down behind the `DISCORD` makefile option - run `make` with the `DISCORD=y` argument to enable it.~~
Requires `discord_game_sdk.dll`, which can be found in the [Discord Game SDK](https://dl-game-sdk.discordapp.net/latest/discord_game_sdk.zip) (`lib/x86/discord_game_sdk.dll`).
To do:
> Add Discord integration

- src/win/win_d2d.c
- src/win/win_d2d.cpp
- src/win/win_d2d.h
After some time, I got into the mood to make some minor adjustments to the Direct2D renderer code.
* Code path for rendering was unified for both windowed and full screen modes.
* The blitter now also copies the contents of `render_buffer` directly into the renderer buffer without doing half the job on its own with secondary buffers and what not.
* The D2D buffer is now lazily initialized in the blitter when it's first used.
* Ported the renderer to C.
Sorry, still Direct2D 1.0. ~~Also, there seems to be some strange crash on optimized builds.~~
> Direct2D refinements

- src/machine/m_at_socket4_5.c
- src/machine/machine.h
- src/machine/machine_table_new.c
The IBM Ambra DP60 and DP90 use the standard Intel OEM boards but with their own special BIOS. These machines weren't that famous but they can be a good and special implementation for 86Box.
> Adding the IBM Ambra's on 86Box

- src/machine/m_at.c
- src/machine/m_at_286_386sx.c
- src/machine/machine.h
- src/machine/machine_table.c
- src/machine/machine_table_new.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
Added a few 286 boards:
- Unknown Phoenix Headland
- Unknown Quadtel Headland
- Headland IQS(Phoenix A286)
- The AMI, Quadtel and Phoenix variants of IBM AT
- Samsung Deskmaster 286
- A Dev branched Micronics 386 Board
Please consider checking a little bit for any mistakes. All machines are working as intended. The Micronics 386 has troubles with the memory probably caused from the NEAT emulation.
> Fix the Ambra's not appearing for the old dynarec. Added few 286 boards

- src/config.c
- src/game/gameport.c
- src/game/gameport.h
- src/game/joystick_standard.c
- src/game/joystick_standard.h
- src/machine/m_amstrad.c
- src/machine/m_at.c
- src/machine/m_europc.c
- src/machine/m_olivetti_m24.c
- src/machine/m_ps1.c
- src/machine/m_tandy.c
- src/machine/m_xt.c
- src/machine/m_xt_compaq.c
- src/machine/m_xt_laserxt.c
- src/machine/m_xt_xi8088.c
- src/pc.c
- src/win/win_joystick.cpp
- src/win/win_joystick_xinput.cpp
- src/win/win_jsconf.c
- src/win/win_settings.c
Implemented use of DirectInput sliders.  They were previously lumped in with axis and then not read or used at all.
Lots of use of joystick_type == 7 or joystick_type != 7 to detect if the joystick_type was none.  Changed this to a define so it's easier to add more joystick types.
The text to enumerate the types of joysticks was contained in a numbered LPARAM sheet.  Switched to using the name listed in the joystick struct so it's easier to add more joystick types.
Joysticks with more than 32 buttons would overflow the plat_joystick_state button array.  Added overflow checks.
Added a 4 axis 4 button joystick type that Win98se can pick up as a generic 4 axis 4 button controller.  Probably other systems too, but I never tried.
> Assorted Joystick fixes

- src/machine/machine_table.c
- src/machine/machine_table_new.c
- src/video/vid_s3.c
- Removed VLB from all PCI boards as none that are emulated have VLB slots
- Changed max ram of the PB410A and LS486E to 36 MB and 128 MB respectively.
- ISA/VLB boards now identified in board name
- 3.3V only Socket 7 boards now grouped together
- Some spacing fixes
> Machine table fixes

- src/machine/m_at_socket8.c
- src/machine/machine.h
- src/machine/machine_table.c
Slot 1 440BX board. coreboot supports this board but we're far from supporting coreboot itself.
* BIOS: [1014ls.003](https://ideafix.name/old/mb/asus/slot1/440bx/p2b-ls/1014ls003.zip) - beta BIOS from 2002
* Super IO: Winbond W83977EF (compatible with -TF)
* Flash: SST of some description
* Hardware monitor: Winbond W83781D on SMBus (not implemented, BIOS will complain, set all monitor entries to Ignore to fix it)
* Slot configuration decoded from coreboot [DSDT](https://github.com/coreboot/coreboot/blob/3b618bb/src/mainboard/asus/p2b-ls/dsdt.asl#L134) and [device tree](https://github.com/coreboot/coreboot/blob/2270a15/src/mainboard/asus/p2b-ls/devicetree.cb)
> ASUS P2B-LS board

- src/machine/m_at_socket8.c
More CPUs use a 2.0V vcore so make Klamath's 2.8V the exception rather than the rule.
> Change hardware monitor VCORE around on the P2B-LS

- src/postcard.c
Fixes tpatx and possibly other boards taking forever to boot with the POST card enabled due to constant refreshing with the same value.
> Only update POST card if the POST code has actually changed

- src/printer/prt_escp.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
- src/win/win.c
- src/win/win.h
- src/win/win_joystick.cpp
- src/win/win_joystick_rawinput.c
- src/win/win_joystick_xinput.c
- src/win/win_keyboard.c
- src/win/win_mouse.c
- src/win/win_settings.c
- src/win/win_ui.c
RawInput joystick:
- Supports 32 buttons, 6 axis and 4 POVs per joystick (in theory)
- Supports 8 Joysticks (also in theory)
- Tested with Xbox 360 controller, and two more generic HID compatible controllers
- DirectInput is used by default, RawInput enabled when `DINPUT=n` is specified in makefile.
Fixes:
- Add proper declaration and lib of SetCurrentProcessExplicitAppUserModelID.
- Fix the progress bar in new disk image dialog
- Now all RawInput data (keyboard, mouse, joystick) are processed at once.
> Rawinput Joystick, and some other minor fixes

- src/machine/m_at_socket8.c
- src/spd.c
- src/spd.h
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
SPD is a small I2C EEPROM on every SDRAM module, connected to SMBus on addresses 0x50 onwards, containing information about the module's RAM. This PR implements the SPD device, as well as logic to distribute RAM according to the emulated machine's slot configuration.
> Implement SPD (Serial Presence Detect)

- src/machine/machine.h
Fixes a compile error on non-dev builds.
> Export P2B-LS to non-dev builds

- src/machine/m_at_socket7_s7.c
- src/machine/m_at_socket8.c
- src/machine/machine.h
- src/machine/machine_table.c
- src/video/vid_s3.c
- Fixes maximum RAM amounts on some motherboards
- Adds finalized 430TX roster
- Removes VLB from all PCI boards as none of our emulated PCI boards have VLB
- Move the Soltek Socket 370 board out of Dev-branch as it works with the VIA C3 other than identifying it as a Celeron
> Machine table revisions

- src/machine/m_at_socket7_s7.c
- src/machine/machine.h
- src/machine/machine_table.c
The PC Partner MB520N is a Socket 7 430VX board with AMI WinBIOS, using SMC 669 Super I/O and SST 29EE010 flash.
> Added PC Partner MB520N

- src/hwm.c
- src/hwm.h
- src/hwm_w83781d.c
- src/machine/m_at_socket8.c
* Switch the P2B-LS to the W83781D, because it actually has the AS97127F which is just a rebadge of the W83781D (so much for not reading the manual)
* Add AS99127F proprietary registers (the BIOS on boards with that chip won't boot without those registers in place) with values dumped from a real Rev. 2 chip on a P4B board
> W83781D hardware monitoring improvements

- src/win/Makefile_ndr.mingw
there was no space between the 596B & objects as referenced by mooch
> Fix compile breaking issue

- src/cpu_common/386_common.h
- src/cpu_new/codegen.h
The main compile failures are due to MuNT and undefined references now :P
> Some compile fixes for clang. Still doesn't compile, but still :P

- src/cpu_common/x87_ops.h
- src/cpu_new/codegen_allocator.c
- src/cpu_new/codegen_allocator.h
- src/cpu_new/codegen_backend.h
- src/cpu_new/codegen_backend_arm.c
- src/cpu_new/codegen_backend_arm_ops.c
- src/cpu_new/codegen_backend_arm_uops.c
- src/cpu_new/codegen_backend_x86.c
- src/cpu_new/codegen_backend_x86_ops.c
- src/cpu_new/codegen_backend_x86_ops_fpu.c
- src/cpu_new/codegen_backend_x86_ops_sse.c
- src/cpu_new/codegen_backend_x86_uops.c
- src/win/Makefile_ndr.mingw
Enable new dynarec to build for Windows ARM with Clang/LLVM/MinGW.
Still buggy and crashy when run, but this is a beginning.
> Enable New Dynarec on Windows ARM

- src/cpu_common/cpu.c
- src/cpu_common/cpu.h
Some dynarec backends (x86-64, arm64) expect the offset between cpu_state and CR0 to within a certain limit, otherwise they crashes (e.g: "host_x86_MOV64_REG_ABS - out of range").
Move CR0 to the end of cpu_state, make sure the offset is within limit.
Helps NT4 and Win95 with dynarec on.
> Dynarec: Move CR0 into cpu_state

- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Socket 370 motherboard with SMSC SLC90E66 southbridge and native VIA C3 support.
> A-Trend ATC7020BXII

- src/win/Makefile_ndr.mingw
It's only enabled on old dynarec for some reason.
> Re-enable VNC on dev builds with new dynarec

- src/include/86box/machine.h
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
Socket 8 Phoenix board. Works flawlessly.
> Added the Micronics M6MI

- src/cpu_common/cpu.h
- src/cpu_common/cpu_table.c
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
Adds the ECS P6KFX-A as well as appropriate CPU tables for an early Slot 1 motherboard without Deschutes or 100 MHz FSB support. Also fixes a minor bug with 266 MHz Pentium IIs and ISA clock frequencies.
> Add the ECS P6KFX-A, a 440FX Slot 1 machine.

- src/hwm_w83781d.c
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Twin 440BX boards (the P3B-F is Slot 1 and the CUBX is Socket 370) with Award 6.0 (Phoenix style setup) BIOS. Also includes a fix to the AS99127F hardware monitor required for these boards to boot, and machine table formatting fixes.
These boards currently have an IDE enumeration delay issue on the Boot tab of the setup. The CUBX notably identifies the Cyrix III correctly, but the P3B-F does not.
> ASUS P3B-F and CUBX motherboards

- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
Make the 430HX & 430VX Phoenix boards available while removed the 596B AMI machine
> 430VX rework

- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
Intel AMI based board. To cover up the needs for an AMI BIOS on 430VX
> Added the Packard Bell PB680

- src/win/win_about.c
Now when click the close button, the about dialog won't close.
We should handle the 'IDCANCEL' command, which is associated with the close button.
> Fix the close button of about dialog not working.

- src/cpu/codegen_timing_p6.c
- src/cpu_new/codegen_timing_p6.c
This implements a basic timing model for Intel P6 CPUs, in our case that means the Pentium Pro, the Pentium II and the Celeron Mendocino.
> Implement a proper P6 timing model

- src/machine/m_at_slot1.c
- src/machine/m_at_socket7_s7.c
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
This board returns D4 POST with no output. Needs further examination. Meant for the future PC87307 implementation.
Also all boards that miss their SIO chips got Dev Branched just in case 2.10 gets released while some miss their SIO.
> Dev branch all machines with missing SIO chips + added the VS440FX

- src/include/86box/spd.h
- src/spd.c
* Add EDO SPD (not fully accurate as it's so rare)
* Change manufacture week/year values; most software expects decimal instead of BCD
* Remove version header
* Minor change: don't execute the splitting process if all slots are full from the get go
> SPD improvements

- src/cpu_common/cpu.h
- src/cpu_common/cpu_table.c
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
This PR adds the WinBios boards by SuperMicro + brings Slot 2 to the surface. It'll help debugging why AMI hates i686's and also on the future 440LX + 440GX implementation
> SuperMicro WinBios 440LX & 440BX + Slot 2 440GX bringup

- src/cpu_common/cpu.c
Windows Vista will write to this MSR on presumably any CPU with a GenuineIntel vendor ID string. This should (and does on a real one) cause a GPF on Intel Pentium/Pentium MMX CPUs. IDT WinChip, AMD K6, VIA Cyrix III, and Intel P6 family CPUs are not affected.
> Make writing to MSR 0x8B cause a GPF on Intel Pentium/Pentium MMX

- src/hwm.c
- src/hwm_lm75.c
- src/hwm_lm78.c
- src/include/86box/hwm.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
- src/smbus.c
- src/spd.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
* Separate LM75 temperature sensor from LM78 emulation
* Add LM75 CPU temperature sensor to the Supermicro P5MMS98 (fixes CPU temperature reading)
* Fix JTPWR readout on AS99127F machines (somehow)
* Fix SMBus logging, enabling logging should no longer return bad values
> Hardware monitor refactoring, part 2

- src/include/86box/machine.h
- src/machine/m_at_socket7_s7.c
- src/machine/machine_table.c
The NuPRO-592 is a i430TX machine which uses the W83977EF Super I/O, W83781D hardware monitoring chip, Intel flash, and has full ACPI support.
> Replace the P55XB2 with the NuPRO-592, as it also has ACPI.

- src/hwm_lm78.c
- src/include/86box/machine.h
- src/include/86box/pci.h
- src/include/86box/sound.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
- src/pci.c
- src/sound/snd_audiopci.c
- src/sound/sound.c
* Add onboard sound device support, similar to onboard video; the "Internal" option (visible only on machines with onboard sound) adds the onboard sound device to a PCI_CARD_SOUND slot
* Add onboard ES1371 device
* Add missing PCI slot and fix configuration of the onboard sound slot on the Tyan Tsunami ATX
* Add onboard ES1371 to the Tyan Tsunami ATX
* Small outstanding fixes to the hardware monitor
> Onboard sound support + onboard ES1371 for Tsunami ATX

- src/hwm_lm75.c
- src/hwm_lm78.c
Reads from the mirrored area were subtracting instead of ANDing the register index.
> Fix hardware monitor mistake preventing P3B-F/CUBX from booting

- src/machine/m_amstrad.c
- src/machine/m_at.c
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_commodore.c
- src/machine/m_at_compaq.c
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket4_5.c
- src/machine/m_at_socket7_s7.c
- src/machine/m_at_socket8.c
- src/machine/m_at_super7_ss7.c
- src/machine/m_europc.c
- src/machine/m_ps1.c
- src/machine/m_ps2_isa.c
- src/machine/m_ps2_mca.c
- src/machine/m_tandy.c
- src/machine/m_xt.c
- src/machine/m_xt_compaq.c
- src/machine/m_xt_laserxt.c
- src/machine/m_xt_t1000.c
- src/machine/m_xt_xi8088.c
- src/machine/m_xt_zenith.c
- src/machine/machine_table.c
The machine roms have been reorganized according to class(8086 - 286), CPU model (286 - 486) & Socket(Socket 4 - PGA370). Few exceptions are some manufacturer ROMs
> Machine path reorganisation

- src/hwm_lm75.c
- src/machine/m_at_slot1.c
* Fix secondary temperature readouts on AS99127F machines
* Work around the P3B-F's expected VCORE for Cyrix III
> Hardware monitor fixes

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
KN97 is a popular Slot 1 FX board included also in the PCem-X days. Thanks to the recent additions it can be reintroduced back.
> Replace the P6KFX with the KN97

- src/cpu_common/cpu.h
- src/cpu_common/cpu_table.c
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
* Fix KN97 southbridge location (fixes IDE)
* Work around the KN97's hardware monitor misreporting fan speeds
* Switch the 2.8V Pentium II table for a 66MHz Pentium II table to accomodate both Slot 1 440FX machines
* Fix maximum RAM amounts for 440FX boards (MB-8500ttc still pending, couldn't find a picture)
* Add Cyrix III CPUs to the Soltek SL-63A1 (they were just never added)
> Machine table (and KN97) fixes

- src/cpu_common/cpu.c
Improves emulation of the EBL_CR_POWERON MSR on Intel P6 and VIA C3 CPUs. Also makes a fix to a logging bug.
> Improved EBL_CR_POWERON MSR

- src/chipset/opti5x7.c
- src/cpu_common/cpu.c
- src/cpu_common/cpu.h
- src/cpu_common/cpu_table.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/pit.c
- src/video/vid_et4000w32.c
- src/win/Makefile.mingw
- src/win/Makefile_ndr.mingw
Also adds emulation of the OPTi 5x7 chipset, and introduces a clock divider for VLB on 64-bit bus systems.
> Add the AMI Excalibur, a VLB OPTi 596/597 machine.

- src/cpu_common/cpu_table.c
- src/machine/machine_table.c
This is an update to the Slot 1/Socket 370, since the 440EX has support for Celeron processors up to 333 MHz.
> Slot 1/Socket 370 Updates

- src/chipset/intel_4x0.c
- src/cpu_common/cpu_table.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/machine_table.c
A Slot 1 440LX board. The 440GX is now implemented with a now off dev branch Slot 2 board following it.
> Added the Abit LX6 + rework on the 440GX

- src/machine/machine_table.c
- Fixes the maximum RAM amount on the Acer V60N
- Adds the MACHINE_PS2 flag on the HP Vectra VL 5 Series 4
> Fixed some inconsistencies in the machine table

- src/machine/m_at_386dx_486.c
Changed the 2CH IDE controller to the ISA variation as the A1G doesn't have any VLB capabilities at all.
> The A1G doesn't have VLB capabilities

- src/include/86box/machine.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
Some 430LX board using Award 4.50 non G BIOS.
> Readded the ASUS P5MP3

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
Restored this old machine from the PCem-X era. Seems to be ok with the restored Intel 82335 chipset.
> Restored the Phoenix 386SX clone

- src/chipset/opti5x7.c
- src/include/86box/sio.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/pit.c
- src/sio/sio_fdc37c661.c
- src/win/Makefile.mingw
- Add emulation of the FDC37C661 Super I/O
- Fix Pentium VLB timing (was running VLB at 2x bus speed instead of 1/2 bus speed)
- Fix the cache register on the OPTi 5x7 chipset
- The actual minimum RAM amount according to the datasheet is 2 MB, not 1 MB.
- Fix chipset naming consistency
> Improvements to the OPTi 597 machine

- src/chipset/intel_420ex.c
- src/chipset/intel_4x0.c
- src/chipset/via_apollo.c
- src/chipset/via_vpx.c
- src/include/86box/spd.h
- src/machine/m_at_socket7_s7.c
- src/machine/m_at_sockets7.c
- src/machine/machine_table.c
- src/mem/spd.c
* Single implementation for all chipsets
* Added DRB locking to VIA VPX and Apollo
* Fixed maximum RAM amount on VIA boards (after research into DRAM bank configurations)
* Fixed SPD
> DRB locking fixes

- src/include/86box/machine.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
The OptiPlex 560L works as intended.
The Dimension XPS P60 is dev branched due to the SMC 665QFP being slightly different than the regular 665.
> Added various Dell machines

- src/cpu/386_ops.h
- src/cpu/cpu.c
- src/cpu/x86_ops.h
Implement the MSRs supported by the IBM 386SLC/486SLC/486BL, as documented in [in this list](http://www.lpjjl.net/pgm/fichiers/docasm/opcodes.lst).
> Implement IBM 486 MSRs

- src/cpu/cpu.c
Also give the IBM 386SLC 'isibm486' as it is believed to identify as a 486 to software.
> Fix MSRs on the IBM 386/486 CPUs

- src/chipset/opti291.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
Adds the DTK PPM-3333P, an OPTi 291-based 386SX machine using an Award v4.20 BIOS.
> Add an OPTi 291-based Award v4.20 machine

- src/cpu/cpu.c
- src/cpu/cpu.h
- src/win/Makefile.mingw
Fix some issues with the Cyrix DX2 & DX4 CPUs and restore the Cyrix 6x86 for dev-branch builds.
> Fix issues with Cyrix DX2/DX4 CPUs and restore Cyrix 6x86 for dev-branch builds

- src/chipset/stpc.c
- src/machine/m_at_386dx_486.c
* Fixed PCI IDs
* Fixed IDE device for non-Atlas models (only Atlas has it on a discrete device ID)
* Added the Atlas USB OHCI device
* Refactored `sb` -> `isab`
> STPC IDE improvements and USB device

- src/chipset/stpc.c
Implement PCI IRQ steering, leave blank space for interrupt edge/level control registers.
> STPC PCI IRQ steering

- src/disk/hdc_ide_cmd640.c
- src/disk/hdc_ide_sff8038i.c
- src/include/86box/language.h
- src/include/86box/mo.h
- src/include/86box/resource.h
- src/include/86box/win.h
- src/pc.c
- src/win/86Box.rc
- src/win/Makefile.mingw
- src/win/win_settings.c
- src/win/win_stbar.c
Moved CD-ROM to a sperate page, and reserve "Other removable devices" to MO and ZIP.
This change is for UI only, structure of the config file is left intact.
> Add MO settings UI

- src/win/win_sdl.c
SDL scaling was using the original (unscaled) width and height. This simple change makes 4:3 scaling work correctly.
> Fix fullscreen SDL scaling.

- src/cpu/x87_ops_arith.h
- src/cpu/x87_ops_loadstore.h
- src/cpu/x87_ops_misc.h
This is done by making it so that if the FPU is not at least a 487SX, the clock cycles are multiplied by the CPU multiplier.
> Implement clock-dividing for FPUs on clock-multiplied 386s

- src/chipset/intel_4x0.c
- src/config.c
- src/cpu/386_ops.h
- src/include/86box/86box.h
- src/machine/m_at_slot1.c
- src/mem/spd.c
Add more VPCEXT opcodes, change the 440BX special behavior, and fix the longstanding crash when an out-of-bounds CPU type is selected.
> Virtual PC machine improvements

- src/printer/prt_ps.c
The message box and documentation say .ps files are saved if GhostScript is absent, but the current code only leaves the temporary .tmp files behind. Fix that.
> PostScript printer: actually save .ps files if GhostScript is absent

- src/include/tinyglib.h
- src/win/Makefile.mingw
De-inline the tinyglib functions, fixes the optimization-related issues reported in #960.
> Fix build for SLiRP

- src/device/hwm_lm75.c
- src/device/smbus.c
- src/machine/m_at_slot2.c
- src/machine/machine_table.c
Change flash type to SST (real board has Winbond of some description), limit RAM to 2032 MB (BIOS overflow bug with the full 2048 MB), fix a SMBus-related reset crash that I've reproduced with this board.
> Freeway FW-6400GX fixes

- src/device/postcard.c
PS/1 and ISA PS/2 machines actually use 190h, and ISA Compaq machines use 84h.
> Fix POST card I/O ports

- src/chipset/intel_4x0.c
- src/chipset/via_apollo.c
- src/device/pci_bridge.c
- src/include/86box/language.h
- src/include/86box/pci.h
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket7_s7.c
- src/machine/m_at_sockets7.c
- src/pci.c
- src/win/86Box.rc
- src/win/Makefile.mingw
This adds:
* Support for multiple PCI bus numbers in `pci.c`
* Emulation of the DEC/Intel 21150 PCI bridge (9 bus masters, so 9 children)
* Automatic insertion of a 21150 PCI bridge upon reaching the last NORMAL slot (never run out of slots)
* Proper emulation of AGP bridges on Intel and VIA chipsets
* A few IRQ steering fixes on AGP machines
Notes:
* The meaning of the `pci_add_card` return value has changed to accomodate for multiple bus numbers. The data type and usage haven't changed.
* Having a PCI device on the AGP bridge is legal at least on Intel platforms. See the Intel C440GX+ motherboard which uses a 21150 bridge attached to the AGP bus providing 66 MHz PCI slots.
* On the other hand, VIA AGP bridges accept PCI devices but not PCI bridges ("not enough resources..."), so the PCI …
> PCI bridge support

- src/cpu/cpu_table.c
There are no emulated chipsets which officially support 133 MHz FSB.
> Undo anabate's VIA C3 changes entirely

- src/device/smbus_piix4.c
- src/printer/prt_ps.c
The PostScript printer code was ending the document upon reaching 64k of PostScript data, instead of just flushing to the temporary file.
> Fix PostScript printer

- src/chipset/via_pipc.c
- src/network/net_plip.c
- src/network/net_slirp.c
- src/network/network.c
* SLiRP forward protocol should be compared using regular strcmp
* Unpause network RX queue on PLIP timeout
* Improve thread safety and add safeguards to the network packet dumping code
* (unrelated) Fix VIA ISA bridge subsystem ID write
> Small non-critical changes to networking

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
Better BIOS (ACPI actually works) but has flash corruption issues to be investigated.
> Replace FIC KA-6100 with KA-6130

- src/cpu/cpu_table.c
Since CRTRevivalDreamer requested that he wants to emulate a Socket 5 CPU with a 133MHz Pentium processor, I'm opening this PR.
> Added support for the 133MHz Pentium processor for Socket 5 CPUs

- src/acpi.c
- src/chipset/via_pipc.c
- src/device/hwm.c
- src/device/hwm_gl518sm.c
- src/device/hwm_lm75.c
- src/device/hwm_lm78.c
- src/device/hwm_vt82c686.c
- src/device/postcard.c
- src/floppy/fdc.c
- src/include/86box/fdc.h
- src/include/86box/hwm.h
- src/machine/m_at_386dx_486.c
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket7.c
- src/machine/m_at_socket8.c
- src/machine/m_at_sockets7.c
- src/pci.c
- src/sio/sio_vt82c686.c
* Change the hardware monitor values API: each individual monitoring chip now provides its own default values, which can be overridden in a per-machine basis, massively cleaning up machine initialization code
* Added the Winbond W83782D hardware monitor required by the Gigabyte GA-6GXU
* Fixed hardware monitoring entries in some machines
* Small fixes to VIA southbridges that I forgot to PR earlier
> Hardware monitoring overhaul

- src/video/vid_cl54xx.c
Summary
=======
This is a fix for the on-board Acumos AVGA2 graphics card, used by the Commodore SL386SX machine.
Approach
========
The superfluous `video/` was removed from the path to the card's BIOS, matching the current ROM set.
Checklist
=========
> Correct the onboard AVGA2 BIOS path

- src/win/Makefile.mingw
Summary
=======
The Makefile silences the command output in some cases by redirecting it to NUL, which, when run under `bash` in an MSYS2 environment results in the output being redirected to a regular file called `NUL`, which then can't be deleted by standard Windows methods due to NUL being a reserved name.
Approach
========
Since the Makefile is obviously not intended to be run under `cmd.exe`, the input is now redirected to `dev/null` instead. Additionally, an unused leftover variable has been removed as well.
Checklist
=========
> Small Makefile fixes

- src/scsi/scsi_aha154x.c
- src/scsi/scsi_buslogic.c
Summary
=======
This changes the default IRQ for Adaptec AHA-145x and BusLogicBT-54x/44x SCSI controllers from 9 (this configuration which is known to cause problems and is discouraged in the official documentation) to 11.
Checklist
=========
> Change the default IRQ for some ISA SCSI controllers

- src/device/hwm_gl518sm.c
- src/device/hwm_lm78.c
- src/device/hwm_vt82c686.c
- src/include/86box/hwm.h
- src/machine/m_at_sockets7.c
These were somehow forgotten during the hardware monitor overhaul. Also includes tweaks to the LM78 code.
> Fix VT82C686 and GL518SM hardware monitors

- src/win/win.c
Summary
=======
The debug logging console window does not appear even when the `--debug` command line argument is specified. This pull request fixes that.
Approach
========
The relevant variable is now checked after, and not before, the arguments are processed.
Checklist
=========
> Fix the debug console window not appearing.

- src/network/net_pcap.c
This allows 86Box to use pcap properly under WINE under Linux as most
interfaces on Linux leave the description as a NULL.
Signed-off-by: Michael Casadevall <michael@casadevall.pro>
Summary
=======
Fixes PCAP list being null when under Linux/WINE
Approach
========
Failback to use the interface name if the list is otherwise empty.
Checklist
=========
> Failback for PCAP to use name as description if the later is blank

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
Summary
=======
I am submitting the Fujitsu ErgoPro x365 (a new machine).
Approach
========
The first board I considered was the HP Brio 83xx (an i440EX system), but since it required the SM(S)C FDC37C675.
I chose the ErgoPro x365, after tiseno100 opened pull request #1053. 
Checklist
=========
References
==========
x365 Quick Reference Guide: http://pub.agrarix.net/HW/Fujitsu/ErgoPro%20x365_bestanden/X365qrg.pdf
> Added the Fujitsu ErgoPro x365

- src/acpi.c
Summary
=======
This makes 86Box close normally on ACPI soft power off instead of abruptly terminating without saving the configuration or the emulated machine's NVRAM.
Checklist
=========
> Properly close the emulator on ACPI soft power off

- src/win/win_sdl.c
Summary
=======
This fixes an issue where after leaving the fullscreen mode, the host mouse cursor remains locked to the dimensions of the emulated screen.
Checklist
=========
> Fix the mouse cursor being locked after leaving fullscreen mode

- src/include/86box/win.h
- src/win/win_sdl.c
- src/win/win_ui.c
Summary
=======
This PR is a rework of #1074, which attempted to fix an issue with the host mouse cursor being locked after leaving the fullscreen mode, except done in a more proper way that resolves the issue even on optimized builds.
Checklist
=========
> Fix the mouse getting locked after leaving fullscreen, take 2

- src/include/86box/language.h
- src/win/86Box.rc
- src/win/Makefile.mingw
- src/win/win_settings.c
Small tweaks and fixes to the Settings dialog (and the UI in general):
* Changed the save settings dialog to better conform to Windows user interface guidelines (turned the Cancel button to a regular button and changed the wording for when the dialog is invoked by clicking the close button)
* Changed button text to sentence case
* Video card selection now loads instantly
* Made list views in the settings prettier by using the Explorer theme (required adding a link to uxtheme.dll)
> Tweaks to the Settings dialog

- src/win/win_settings.c
> Add new hard disk dialog: fix broken CHS when changing back from diff image format

- src/mem/mem.c
Summary
=======
I looked through the 386 Programmer's Reference Manual to see what bits CR0 had, and it does NOT have the WP (Write-Protect) bit in CR0 on the 386. Once removed, IBM AIX 1.3 no longer page faults immediately upon inserting the installation diskette.
Checklist
=========
References
==========
https://css.csail.mit.edu/6.858/2014/readings/i386.pdf
> i386 CPUs don't have the WP bit in CR0. Fixes IBM AIX 1.3

- src/chipset/via_pipc.c
- src/device/clock_ics9xxx.c
- src/device/i2c_gpio.c
- src/device/smbus_piix4.c
- src/include/86box/clock.h
- src/include/86box/language.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
- src/win/86Box.rc
* Improvements and fixes to ICS9xxx clock generators, including a detection tool
* Fix socket 370 machines accidentally shipped with test configurations
* Change SMSC machines to the VictoryBX-66 marketing name
* Decrease minimum voltage for boards that should have Coppermine support
* Change settings save confirmation text to follow the established "emulated machine" convention
* Fix VIA 596A revision ID, should be up to 0x0F according to Linux pata_via
> Fixes to the previous big PR and other changes

- src/machine/machine_table.c
- src/mem/spd.c
- src/win/win_settings.c
Summary
=======
This PR converts the `ram_granularity`, `min_ram` and `max_ram` fields in the machine table to always be in kilobytes.
Checklist
=========
References
==========
> Unify RAM size units in the machine table

- src/config.c
- src/game/gameport.c
- src/include/86box/gameport.h
- src/machine/m_amstrad.c
- src/machine/m_at.c
- src/machine/m_europc.c
- src/machine/m_ps1.c
- src/machine/m_tandy.c
- src/machine/m_xt.c
- src/machine/m_xt_compaq.c
- src/machine/m_xt_laserxt.c
- src/machine/m_xt_olivetti.c
- src/machine/m_xt_xi8088.c
- src/pc.c
- src/win/win_joystick.cpp
- src/win/win_joystick_xinput.c
Summary
=======
The joystick type configuration option is now stored in the .cfg file as a string referencing the type instead of a direct integer index; backwards compatibility with old configs is provided. Additionally, the "None" option was moved to the top of the list for consistency with other dropdown lists.
Checklist
=========
> Joystick type option improvements

- src/include/tinyglib.h
- src/network/net_slirp.c
> Correct tinyglib data type size macros

- src/chipset/via_apollo.c
- src/device/clock_ics9xxx.c
- src/device/hwm_lm78.c
- src/include/86box/clock.h
- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
- src/sio/sio_vt82c686.c
VIA 693A machine, not previously added due to a misunderstanding about 693A emulation status.
> Add ASUS P3V133

- src/win/win.c
- src/win/win_ui.c
Summary
=======
Removed unnecessary calls to video_wait_for_blit(), which in
addition to not doing much were also in a race with the
video_blit_memtoscreen() thread to wait for and reset the
blit_data.blit_complete event signalled by blit_thread(),
causing several deadlocks.
> Fix blit thread related deadlocks

- src/device/keyboard_at.c
- src/include/86box/keyboard.h
- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_xt_zenith.c
- src/machine/machine_table.c
Summary
=======
Added the following new machines:
- NCR PC8/810/710/3390/3392
- NCR 3302
- Olivetti M290
Checklist
=========
References
==========
NCR PC-8/810/710/3390/3392
Note: several 286-class PCs were produced by NCR with different model names, depending on the case form-factor and on the mainboard layout (passive backplane with ISA CPU card or active mainboard). However, the chipset being used in all those models is the same, and BIOS chips appear to be interchangeable.
- Press releases: http://www.thecorememory.com/html/ncr_servers___pcs.html
- Manual: http://www.thecorememory.com/NCR_286_TRM.pdf
NCR 3302
Note: Chips & Technologies NEAT chipset (82C206, 82C211, 82C212, 82C215), PVGA1A VGA card on-board, IDE controller onboard
- Info on NCR 3000 Series PCs: …
> Added NCR and Olivetti AT-class machines:

- src/include/86box/plat.h
- src/include/86box/vid_voodoo_common.h
- src/video/vid_voodoo.c
- src/video/vid_voodoo_display.c
- src/win/win_thread.c
Certain applications using the Voodoo adapter stop blitting
when there's no activity (e.g mouse movement, animation).
This results in a black screen when events like window/full screen
transitions take place. Usually this can be fixed by
moving the mouse or with keyboard inout. This change forces
a blit to refresh the screen.
In addition, added critical sections since they are lighter
than mutexes.
Summary
=======
Checklist
=========
References
==========
> Force Voodoo blit

- src/include/86box/machine.h
- src/include/86box/sio.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
- src/sio/CMakeLists.txt
- src/sio/sio_prime3b.c
- src/win/Makefile.mingw
This includes also the Goldstar Prime3B Super I/O
Summary
=======
Quite bad and cheap AMI board using the ALi M1489 chipset.
Checklist
=========
References
==========
https://www.datasheetarchive.com/pdf/download.php?id=4211c2d5813655ce0b9566343f609a82f78bba&type=O&term=goldstar%2520gm16c450
> Added an AMI ALi M1489 board

- src/include/86box/plat.h
- src/include/86box/vid_voodoo_common.h
- src/video/vid_voodoo.c
- src/video/vid_voodoo_display.c
- src/win/win_thread.c
Removing all win32 mutexes and turning them into critical
sections, since mutexes in win32 are meant generally for
inter process communication, tend to be slower, and aren't
really needed for current purposes. Critical sections
are roughly equivalent to std::mutex in the c++ stl.
> Turn all mutexes into critical sections

- src/floppy/CMakeLists.txt
- src/floppy/fdc.c
- src/floppy/fdc_magitronic.c
- src/floppy/fdc_pii15xb.c
- src/include/86box/fdc.h
- src/include/86box/fdc_ext.h
- src/win/Makefile.mingw
Rewrote few parts so the DTK FDC is more adaptive on 86Box standards.
Update: This PR also adds the Magitronic B215 FDC controller. The ROM is at the PR below.
https://github.com/86Box/roms/pull/100
> Adapt the DTK FDC to 86Box

- src/chipset/intel_4x0.c
- src/cpu/cpu.c
- src/video/vid_ati28800.c
- src/video/vid_cl54xx.c
- src/video/vid_voodoo_reg.c
Summary
=======
This fixes a few issues that a tool called Sonarcloud found in our code. Most of the issues were false positives relating to fallthroughs in switch statements, but some were indeed legitimate, and so have been fixed :P
> Fixes to legitimate issues Sonarcloud caught in our code

- src/chipset/ali1543.c
- src/chipset/ali6117.c
- src/chipset/intel_4x0.c
- src/chipset/intel_piix.c
- src/chipset/via_apollo.c
- src/chipset/via_pipc.c
- src/cpu/cpu.c
- src/cpu/cpu.h
- src/device/clock_ics9xxx.c
- src/device/pci_bridge.c
- src/include/86box/pci.h
- src/include/86box/pit.h
- src/include/86box/video.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket7.c
- src/pci.c
- src/pit.c
- src/video/vid_table.c
- src/video/vid_voodoo_banshee.c
- src/video/video.c
- src/win/win_settings.c
* Add basic AGP support to PCI and video frameworks
* Add ISA/PCI/AGP bus clock control API for chipsets and clock generators
* Add bus clock control on Intel 4x0 and VIA chipsets, M6117 SoC, and ICS9xxx clock generator
* Add Voodoo 3 AGP cards
* Fix Voodoo Banshee/3 video timings
* Fix Voodoo Banshee/3 DDC on Windows 98
* Improve ALi M1543 PCI device assignment
* Hide machine types with no available machines
> AGP and clock control

- src/video/vid_ddc.c
Fixes ~~Voodoo 3~~ DDC detection behavior on Windows 98.
> Make EDID frequency limits sane

- src/video/vid_voodoo_banshee.c
The AGP flag was set when it shouldn't be.
> Fix PCI Voodoo Banshee

- src/device/CMakeLists.txt
- src/device/isapnp.c
- src/include/86box/isapnp.h
- src/include/86box/snd_emu8k.h
- src/include/86box/sound.h
- src/machine/machine_table.c
- src/network/net_ne2000.c
- src/sound/snd_emu8k.c
- src/sound/snd_sb.c
- src/sound/sound.c
- src/win/Makefile.mingw
* Add ISAPnP framework based on the old RTL8019AS PnP code
* Switch RTL8019AS to the ISAPnP framework
* Add ISAPnP variants of the Sound Blaster 16 and AWE32, with PnP ROMs reconstructed from pnpdump outputs posted on forums
> ISAPnP support

- src/include/86box/sound.h
- src/network/net_ne2000.c
- src/sound/snd_sb.c
- src/sound/sound.c
The existing AWE32 PnP ROM goes to the Sound Blaster 32, and an actual AWE32 PnP ROM takes its previous place.
> Add Sound Blaster 32 PnP

- src/device/isapnp.c
- src/disk/hdc_ide.c
The additional IDE controllers now have an IRQ option labeled "Plug and Play", which turns them into ISAPnP devices with a dynamic IRQ and fixed I/O ports.
> Add PnP tertiary/quaternary IDE controllers

- src/include/86box/vid_svga.h
- src/video/vid_et4000w32.c
- src/video/vid_s3.c
- src/video/vid_sdac_ramdac.c
Fixed (at least in a more correct way) software cursor under OS/2 Warp with the s3 trio/vision drivers.
Implemented 128x128 sprite/hwcursor on the et4000w32 cards per manual.
Summary
=======
Checklist
=========
References
==========
> Added Tseng specific variants of the GenDAC ramdac (ICS 53x1).

- src/chipset/umc_8886.c
Comply the UMC with the recent clock divider implementation.
> Add the PCI & ISA Clock registers of the UMC 8886F

- src/video/vid_et4000w32.c
Fixed freezes, once and for all, on win2000 (W32p).
Fixed some graphical glitches under win3.x that were caused by the FIFO (W32p).
Fixed vlb flag, now it loads the VLB rom properly (W32i).
Anything using the ICS ramdacs now has a svga->clock /= 2 in recalctimings (W32p rev c and W32/W32i).
Summary
=======
Checklist
=========
References
==========
> Tseng ET4000w32x changes:

- src/chipset/CMakeLists.txt
- src/chipset/intel_i450kx.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
450GX & 450KX are the first chipsets intended for the i686 era of processors. Mostly they were used on workstations and servers but also a few general boards. This is an early implementation, not complete due to 86Box limitations in terms of memory handling.
ROM PR below
https://github.com/86Box/roms/pull/109
Checklist
=========
References
==========
http://66.113.161.23/~mR_Slug/pub/datasheets/chipsets/Intel/82450/82450%20(1996).pdf
> Early implementation of the Intel 450KX

- src/device/isapnp.c
* Don't reset read data port on reset command (follows spec and fixes UM8669F AMI machines)
* Add proper support for I/O range check, decoupling the device's I/O handlers away when range check is enabled
> ISAPnP fixes

- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
I am submitting a change that renames the PC 330 type 6571 to the type 6573.
Checklist
=========
> Renamed the 6571 to the 6573

- src/win/win_ui.c
Summary
=======
Returning from full screen has not worked properly after changing `WM_MOVE` and `WM_SIZE` to `WM_WINDOWPOSCHANGED`.
There is a check for `SWP_NOSIZE` flag, but returning from full screen doesn't disable it and thus the rendering window remains the size of full screen window and offset. Mouse capture area is likewise misaligned.
Adding an additional check for variable `user_resize` alongside the existing check for `SWP_NOSIZE` allows the rendering window resize be triggered when exiting full screen.
Checklist
=========
References
==========
The originating window resize event changes: 220fffc4a211c688f3aeaf77038a447a8eb5e295
> Full screen resize fix

- src/device/keyboard_at.c
- src/include/86box/machine.h
- src/machine/m_at_socket4_5.c
- src/machine/machine_table.c
Summary
=======
Adds the TMC PAT54PV, an ISA/VLB only Socket 5 machine. Also makes KBC command A0 return 0x28 then 0 so that the BIOS can function.
Checklist
=========
> Add the TMC PAT54PV machine

- src/machine/machine_table.c
According to stason, the minimum FSB of this board is 50 MHz, not 60 MHz.
> Fix minimum FSB on TMC PAT54PV

- src/win/win_media_menu.c
- src/win/win_stbar.c
Summary
=======
This fixes a bug where HDDs connected to a machine's onboard SCSI controller would not show an icon in the status bar.
Additionally, CD-ROM drives and other removable devices connected to an onboard SCSI controller now show up in the Media menu.
Checklist
=========
> Improvements to onboard SCSI controller handling

- src/86box.c
- src/chipset/via_pipc.c
- src/include/86box/language.h
- src/include/86box/vid_svga.h
- src/video/vid_ati_mach64.c
- src/video/vid_cl54xx.c
- src/video/vid_ddc.c
- src/video/vid_mga.c
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_svga.c
- src/video/vid_voodoo_banshee.c
- src/win/86Box.rc
- src/win/win_stbar.c
* Add frameworks for SVGA DPMS (monitor sleep) and sticky status bar messages (higher priority than POST card and ISABugger)
* Add DPMS to Voodoo Banshee/3, S3, Cirrus Logic, Mach64 and Mystique cards (Windows XP doesn't enable DPMS for Mach64)
* Add screen blanking and a sticky status bar message when DPMS is active
* Move hard reset handling to the pc thread for improved thread safety (and hopefully no more UI hard reset crashes)
* Work around P3V133 POST issues (ACPI I/O space collision)
> SVGA DPMS implementation + hard reset fix + P3V133 fix

- src/win/Makefile.mingw
Summary
=======
Defining DEV_BRANCH affects only source files when building with make. In CMake it affects both source files and resource files.
#1382 didn't build as expected while this was missing; the experimental menu option is missing.
> Make DEV_BRANCH available in .rc files when building with make

- src/win/CMakeLists.txt
- src/win/win_opendir.c
- src/win/win_settings.c
Summary
=======
- Fix missing opendir symbol after recent changes. Defining UNICODE makes it always produce symbols opendirw.
- Fix resouce compiling by adding -n switch to append null to resource strings.
- Fix uninitialized variable causing settings listview missing content randomly.
Checklist
=========
References
==========
> Fixes to CMake/msvc/clang builds and debug builds

- src/win/win_stbar.c
Summary
=======
There is a deadlock situation when changing renderer while e.g. booting or other disk activity that updates status bar.
The dead lock occurs when 
- worker thread has locked a mutex with startblit() and tries to SendMessage
- main thread is processing a message event that tries to lock same mutex with startblit()
Changing SendMessage to PostMessage solves the situation, as worker thread can continue to unlock the mutex and allow main thread (and message pump) to continue.
Checklist
=========
References
==========
Here is stack traces of the two threads in dead lock:
```
Worker Thread	86Box.exe!thread_start<void (__cdecl*)(void *),0>	win32u.dll!_NtUserMessageCall@28
[External Code]
86Box.exe!ui_sb_update_icon(int tag, int active) Line 152
86Box.exe!fdc_callback(void * priv) …
```
> Fix a deadlock with changing renderer and status bar activity

- src/chipset/CMakeLists.txt
- src/chipset/et6000.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
- src/win/Makefile.mingw
> Removed the IBM PS/2 Model 70. Replaced with the Olivetti 486

- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/video/vid_ht216.c
- src/video/vid_rtg310x.c
- src/video/vid_s3.c
- src/video/vid_sc1148x_ramdac.c
- src/video/vid_table.c
Fixed 16 color mode in the Realtek 3106 card.
Reworked the Sierra 1148x for the second time.
Registers that only exist on 928/80x and up are not used by the 911/924 anymore.
Summary
=======
Checklist
=========
References
==========
> Reworked the HTVGA/Video7 clocks. Fixes the HT209 2401 error on MCA.

- src/config.c
- src/disk/hdc.c
- src/printer/prt_escp.c
- src/printer/prt_ps.c
- src/printer/prt_text.c
- src/win/win_media_menu.c
- src/win/win_stbar.c
Summary
=======
This includes the following fixes and improvements:
* Fix the generic text printer saving output files into the current working directory, instead of the "printer" sub-directory as intended
* Fix the generic ESC/P printer looking for font files in the wrong directory
* Fix the generic PostScript printer saving output PDFs with a double ".ps.pdf" extension
* Change the internal config name for the VLB IDE controllers to fix an issue where drives attached to these controllers would not appear in the status bar
* Make the "Media" menu recognize drives attached to external IDE controllers
* Remove an extra unneeded #include in win_stbar.c
Checklist
=========
> Various small fixes

- src/video/vid_oak_oti.c
- src/video/vid_s3.c
Summary
=======
Checklist
=========
References
==========
> Fixed 256 color modes in the Oak OTI, made the New MMIO-capable S3 cards behave like the ViRGE and fixed some modes in the 868/968 in recalctimings

- src/win/win_ui.c
Summary
=======
Pressing Alt+F4 in full screen mode closes SDL renderer window resulting in black screen while emulator continues (debug will throw warning in a while). This is because of default handlers in message pump and can be fixed by ignoring the key messages.
Checklist
=========
References
==========
> Fix Alt-F4 closing SDL renderer window.

- src/game/gameport.c
Summary
=======
Fixes the standalone ISAPnP game port working as plain ISA.
Checklist
=========
> Fix the PnP gameport

- src/win/win_media_menu.c
- src/win/win_stbar.c
Summary
=======
Fixes paths to loaded MO images displayed in the status bar and ZIP images in the media menu being displayed as a string of random characters due to the intended UTF-8 to UTF-16 conversion not being performed.
Checklist
=========
> Fix UTF-8 to UTF-16 conversion of displayed paths to MO/ZIP images

- src/CMakeLists.txt
- src/video/CMakeLists.txt
- src/win/Makefile.mingw
Summary
=======
This suppresses a series of false positive "writing 1 byte into a region of size 0" warnings issued by GCC at vid_voodoo_codegen_x86.h line 49 (or vid_voodoo_codegen_x86_64.h line 51), that result in rest of the header file (about 3000 lines) to be printed to the output several times, causing excessive log sizes.
Checklist
=========
> Suppress GCC false positive warnings in vid_voodoo_codegen_x86[-64].h

- src/win/win.c
- src/win/win_opengl.c
Summary
=======
There is some indication that improperly initializing COM library could cause hangs or crashes with common file dialogs.
COM library isn't explicitly initialized but SDL does it implicitly. By initializing the library in main and opengl thread, both which create windows and have message pump, there is better control on the initialization.
Related issue #1485
Checklist
=========
References
==========
https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex
https://jackiichan.wordpress.com/2007/09/19/getopenfilename-and-some-deep-crashes/
> Explicitly initialize COM library in main and opengl threads

- src/video/vid_s3_virge.c
Summary
=======
This patch implements fog support for S3 ViRGE. The image below shows the change using the dolphin sample from DirectX 7.0a SDK (left before the change, right after the change):
https://i.imgur.com/ftzSRTl.jpg
References
==========
http://www.bitsavers.org/components/s3/DB019-B_ViRGE_Integrated_3D_Accelerator_Aug1996.pdf (see "15.4.8.4  Fogging" and "Fog Color Register (FOG_CLR) (MMB0F4, MMB4F4)" in "19.4 3D Registers")
> S3 ViRGE fog implementation.

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_tgui9440.c
Added the TGUI9680 card and its corresponding 32bit mode and clipping.
Patterns on bitblt are more properly emulated.
Summary
=======
Checklist
=========
References
==========
> Properly fixed the Bresenham line draw command on TGUI9440.

- src/video/vid_tgui9440.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fixed the difference in handling the bresenham command between the 9440 and 96xx.

- src/chipset/via_pipc.c
- src/device/CMakeLists.txt
- src/device/hasp.c
- src/device/smbus_piix4.c
- src/include/86box/chipset.h
- src/include/86box/lpt.h
- src/include/86box/smbus_piix4.h
- src/lpt.c
- src/machine/m_at_slot1.c
- src/network/net_plip.c
- src/printer/prt_escp.c
- src/printer/prt_ps.c
- src/printer/prt_text.c
- src/win/Makefile.mingw
* Port MAME's emulation of the protection dongle for Savage Quest, an arcade cabinet which falls into our emulated hardware (440BX board, P2 450, Trio64V2, Voodoo 2, AWE64)
* Remove device names from the LPT device table
* VIA southbridge fixes and changes, including SMBus clock register
> Savage Quest LPT dongle + some fixes

- src/include/86box/snd_sb.h
- src/include/86box/sound.h
- src/sound/snd_sb.c
- src/sound/snd_sb_dsp.c
- src/sound/sound.c
Summary
=======
Adds the Sound Blaster AWE64 Gold sound card, as a variation of the AWE32 PnP with 4 MB of Onboard RAM and reported DSP version 4.16.
Checklist
=========
References
==========
https://sourceforge.net/p/alsa/mailman/message/9654275/ - contains ISAPnP dump of a real AWE64 Gold.
> Add the Sound Blaster AWE64 Gold

- src/sound/snd_sb.c
Summary
=======
_I have implemented a change to the RAM selection for the Sound Blaster AWE64 Gold and Sound Blaster 32 PnP cards, which allows for the correct and actual RAM combinations on the real cards._
Checklist
=========
References
==========
_https://www.vogons.org/viewtopic.php?p=988235#p988235_
> Corrected RAM selections and combinations on Sound Blaster AWE64 Gold and Sound Blaster 32 PnP

- src/include/86box/resource.h
- src/include/86box/snd_cms.h
- src/include/86box/snd_sb.h
- src/sound/snd_cms.c
- src/sound/snd_sb.c
- src/win/86Box.rc
- src/win/win_settings.c
Summary
=======
This pull request adds some improvements regarding the Creative Music System and early Sound Blaster emulation:
- C/MS chips as part of the Sound Blaster 1.0, 1.5 and 2.0 are now emulated; always enabled on 1.0, optional (disabled by default) on 1.5 and 2.0;
- Adds an option to select the standalone C/MS / Game Blaster's base I/O address (since the real card had a jumper block to select one) in the range from 210h to 260h.
It also implements several changes concerning the CT1335 mixer chip of the Sound Blaster 2.0 CD Interface card:
- The mixer is now disabled by default;
- The mixer no longer erroneously uses the SB's base address instead of the one selected in the device configuration;
- 0x250 is added as an option for its base address.
Related: …
> Creative Music System and early Sound Blaster improvements

- src/include/86box/plat.h
Summary
=======
Extends the changes defined for FreeBSD considering fopen64, fseeko64, ftello64 and off64_t towards macOS. This should ensure a clean compile on macOS and make the pull request https://github.com/86Box/86Box/pull/1626 compatible not just with Linux but also with macOS, so that 86Box can start running on the most used UNIX-based operating systems.
Checklist
=========
References
==========
Implementation of the suggestion by dhrdlicka https://github.com/86Box/86Box/pull/1626#issuecomment-903285900.
> Update plat.h to ensure 86Box compatibility under macOS

- src/sound/snd_audiopci.c
Summary
=======
I have removed unused references to snd_mpu401.h and corrected a minor typographical error in the AudioPCI code.
Checklist
=========
> Removed unused references to snd_mpu401.h and corrected minor typo

- src/86box.c
- src/include/86box/86box.h
- src/win/win_discord.c
- A global variable added as `vm_name` in `86box.h`
- This variable can be filled with the `--vmname "Name"` or `-V "Name"` parameter, or if there are no such a parameter definied this variable will filled up with the VM's directory name.
- The Discord module displays this global variable, as VM name.
- Various 86Box managers can use this feature to display internal fancy VM names, instead of the GUID folder names.
- This variable can be easily used later for adding cool things, like the VM name in title bar, etc.
Summary
=======
With this features the GUID-based managers for 86Box, can display the VM's internal display names in the Discord module. This PR also helps future changes in UI, such as adding VM name in the title bar, etc..
This feature can be integrated to WinBox-for-86Box, …
> Add support for overridable VM name

- src/scsi/scsi_ncr5380.c
Summary
=======
Checklist
=========
References
==========
> Fix T128 timer initialization on reads for faster cpu's.

- CMakePresets.json
Summary
=======
This PR makes the presets default to "build" for binaryDir.
Checklist
=========
References
==========
> Default to "build" binary directory for presets

- src/unix/unix.c
Summary
=======
This PR adds missing Windows key mappings to Unix backend.
Checklist
=========
References
==========
None.
> Add Windows key mappings to Unix backend

- src/unix/linux_midi_alsa.c
Summary
=======
This PR fixes NULL access crashes on ALSA MIDI close
Checklist
=========
References
==========
None.
> Fix NULL access crashes on ALSA MIDI close

- src/include/86box/plat.h
Summary
=======
This PR redirects fopen64 to fopen for all non-Linux Unix systems instead of just macOS.
Checklist
=========
References
==========
None.
> Redirect fopen64 functions to fopen for non-Linux Unix systems

- src/device/serial.c
- src/include/86box/machine.h
- src/include/86box/nvr.h
- src/include/86box/serial.h
- src/include/86box/sio.h
- src/include/86box/video.h
- src/machine/CMakeLists.txt
- src/machine/m_v86p.c
- src/machine/machine_table.c
- src/nvr_at.c
- src/sio/sio_f82c710.c
- src/video/CMakeLists.txt
- src/video/vid_f82c425.c
- src/win/Makefile.mingw
Summary
=======
This adds emulation of Victor V86P portable computer along with related changes involving SuperIO and display controller emulation.
Details in commit messages for individual patches.
Checklist
=========
* I have not, because they may contain copyrighted code I might not be allowed to distribute. Some images are available at  https://github.com/86Box/86Box/issues/966#issuecomment-812881749 and https://github.com/86Box/86Box/issues/966#issuecomment-672187713 and perhaps a search for "Victor V86P" in Internet Archive may yield something.
References
==========
Chips and Technologies, Inc., 82C605/82C606 CHIPSpak/CHIPSport MULTIFUNCTION CONTROLLERS,
PRELIMINARY Data Sheet, Revision 1, May 1987.
<https://archive.org/download/82C606/82C606.pdf>
Chips and Technologies, Inc., …
> Victor V86P Emulation

- src/unix/unix.c
Summary
=======
This PR adds the help command to monitor interface and also adds missing PrintScreen key mapping.
Checklist
=========
References
==========
None.
> unix.c: Add help command to monitor

- src/unix/unix_sdl.c
Summary
=======
This PR adds resizable window support to Unix backend.
Checklist
=========
References
==========
None.
> unix_sdl.c: Add resizable window support

- src/unix/unix.c
Summary
=======
This PR makes unix.c include SDL.h before anything else. This also cleans up the unnecessary source-level defines.
Checklist
=========
References
==========
None.
> Include SDL.h before anything else

- src/video/vid_s3.c
Reintroduced dword mode for chips before Trio64V+.
The Trio64V+ and Trio64V2 chips now have svga->fb_only (which is strongly required by the mapping and the modes) and packed_chain4 set, just like the ViRGE.
Summary
=======
Checklist
=========
References
==========
> S3 changes part 6:

- src/sound/snd_audiopci.c
Summary
=======
I have corrected a minor typo in the Ensoniq AudioPCI emulation.
Checklist
=========
References
==========
ES1371 datasheet - https://datasheetspdf.com/pdf-file/555592/ETC/ES1371/1
> Corrected typo in Ensoniq AudioPCI emulation

- src/video/vid_att20c49x_ramdac.c
- src/video/vid_ht216.c
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_sc1148x_ramdac.c
Properly fixed text/graphics mode of the S3 pre-ViRGE cards.
PIX TRANS cleanups.
Added a sanity check to banking, per bit 0 of CRTC31.
Initial implementation of Enhanced 4-bit mode.
911/924 chips use CRTC43 bit 3 for enabling 15/16bpp mode.
fb_only variable used correctly as of now (depending if on 4bit or 8bit+ modes).
S3 ViRGE changes part 2:
Made the Trio3D/2X AGP use the PCI_ADD_AGP part accordingly
RAMDAC changes:
Sierra 11483 and 11487 don't have an RS2 signal so the four times reading scheme of 0x3c6 is used instead, per documentation.
Fixed AT&T 49x bpp selection.
Other changes:
Fixed remaining rendering issues with the Radius SVGA HT209 card.
Summary
=======
Checklist
=========
References
==========
_Provide links to datasheets or other …
> S3 changes part 8:

- README.md
Summary
=======
In WinBox for 86Box I wrote the B in the Box word with uppercase in the program everywhere, so I want to apply the same casing in README.md, as in the project itself, and at the project page.
Checklist
=========
References
==========
N/A
> Fix character casing in the managers list

- src/sound/snd_audiopci.c
- src/sound/snd_opl.c
Fixed MIDI UART OUT of the ES1371 using NT 4.0's drivers and keeping compatibility with Win9x/2000.
Fixed OPL3 timer status for some games and programs.
Summary
=======
Checklist
=========
References
==========
> MIDI changes:

- src/video/vid_et4000w32.c
- src/video/vid_paradise.c
Bit 1 is of 0x3DA (read only) is apparently required to make the OS/2 Tseng ET4000W32/i drivers work fine, fixes hangs upon reaching the GUI with said drivers.
Avoid division by zero in the blitter of the ET4000W32/i under OS/2.
Video changes (PVGA):
Fixes mode changes of the PVGA1a, including the built-in video card of the Amstrad 2086/3086.
Summary
=======
Checklist
=========
References
==========
> Video changes (ET4000W32/i):

- src/unix/unix_thread.c
Summary
=======
This change removes `timespec_get()` from Unix systems inside `unix_threads.c` and makes it also possible to cross-compile binaries on macOS Big Sur (v11) or macOS Monterrey (v12) that target macOS Mojave (v10.14) at minimum since Mojave lacks support for `timespec_get()` as long as the required libraries are working on that OS.
Checklist
=========
References
==========
https://stackoverflow.com/a/5167506 (for proving that `clock_gettime()` is also available on macOS Sierra and higher)
> Removes timespec_get() from Unix systems

- src/machine/machine_table.c
Summary
=======
Several other systems had PS/2 mouse support, this PR enables that support
Checklist
=========
References
==========
(Will add later)
> More systems which have PS/2 mouse

- src/floppy/fdd.c
Summary
=======
This PR fixes startup crash on macOS when loading floppy images.
Checklist
=========
References
==========
None.
> Fix startup crash on macOS when loading floppy images

- src/video/vid_ega.c
Summary
=======
EGA also supported 32K RAM setting, which is apparently required for the IBM PC model 5150.
Lines 194-205 appear to cover the memory window setting so this looks to be a pretty simple one.
Checklist
=========
References
==========
> EGA 32k support

- src/chipset/CMakeLists.txt
- src/unix/unix.c
- src/win/languages/pt-BR.rc
- src/win/win_lang.c
Summary
=======
Add ims8848.c to CMakeLists, and add the new missing plat_ prototypes to unix.c, with some new platform-specific global variables.
Edit: also added a quick fix to pt-BR because the meaning IDS_7168 is changed during the development.
Checklist
=========
References
==========
N/A
> Fix some compile breaking stuff under Linux/Mac

- src/win/win.c
Summary
=======
The resource strings are limited to 512 characters on read and with the new translations, that limit is hit on atleast the file dialogs. Increased it to 1024 to add some head room. There is also an issue with different builds using different rc-compilers that can end up without terminating null character; this is fixed here by using calloc that initializes the memory with 0.
Checklist
=========
References
==========
> Fix resource string over bounds issues

- src/86box.c
- src/include/86box/win.h
- src/win/win.c
- src/win/win_ui.c
Summary
=======
This fix is intented for fixing two problems:
- The menu states are lost when switching lanugages
- The OpenGL menu disappears when switching languages
By saving the reloaded HMENU to the `menuMain` variable and calling `ResetAllMenus` in `set_language`, the first part was solved. As for the OpenGL menu, I had to pull out the two static variables from `win_ui.c/show_render_options_menu()`, and set them to their initial value in `ResetAllMenus`. In this way the OpenGL menu is also recreated correctly.
Checklist
=========
References
==========
N/A
> Menu reloading fixes for Multilanguage UI

- src/unix/unix.c
Help says that fullscreen TOGGLES fullscreen. Fix this.
Signed-off-by: Andreas J. Reichel <andreas@reichel.bayern>
Summary
=======
Checklist
=========
References
==========
> Unix: Make fullscreen command really toggle

- src/scsi/scsi_ncr5380.c
Fixed errors of the Trantor T128 SCSI adapter using the CD-ROM on low speed 386/486 processors.
Summary
=======
Checklist
=========
References
==========
> Changes list 1:

- src/86box.c
- src/CMakeLists.txt
Summary
=======
This commit adds the `macOSXglue.m` and `macOSXglue.h` into the project to enable macOS application bundles to store the ROM files independently from the application bundle and it's storage location, such as having the bundle in a separate directory or inside the `Applications` folder on macOS.
Checklist
=========
References
==========
(can be added later if needed)
> Adding proper support for storing the 86Box ROMs on macOS inside app bundles

- src/win/win_icon.c
- src/win/win_progsett.c
Summary
=======
This fix solves the problem, that none of the iconsets are discovered or loadable, when there are non-english characters in the path. By using different conversion functions the problem was solved.
The problem was encoding-related, and made that all related W-version of Windows functions returned error, with GetLastError 0x03 (ERROR_PATH_NOT_FOUND).
Checklist
=========
References
==========
N/A
> Fix encoding issues in win_progsett.c and win_icon.c

- src/config.c
- src/include/86box/snd_sb_dsp.h
- src/sound/snd_sb_dsp.c
Summary
=======
Setting the default memory to 64k when 86box is started without options (This is the most the v1 IBM 5150 supports onboard)
Adding emulation of the SB16's DSP 8051 RAM, ported from PCBox
Checklist
=========
References
==========
> default RAM and SB16 8051 RAM emulation

- src/win/win_ui.c
Summary
=======
Put the OpenGL 3.3 renderer's options menu back to it's original place; under the renderer selection.
Checklist
=========
References
==========
> Adjust the OpenGL 3.3 submenu position

- src/device/keyboard_xt.c
Summary
=======
While I was debugging the M240 option ROM issue #1861 (which was resolved by OBattler before I committed my modifications), I found out that Olivetti M19 was set to 40x25 CGA text mode instead of 80x25 M24/AT&T text mode. Turned out to be an issue in the way jumper settings are read by the keyboard controller, so I corrected it.
As this bug was identified and corrected by myself, I haven't created an issue. If needed for tracking purposes, I can create one though.
Checklist
=========
> Fixed Olivetti M19 display bug

- src/win/languages/fr-FR.rc
Fixed a typo under the Vue menu section. The typo is Echelle facteurr while the correct spelling is Echelle facteur.
> Fixed a typo.

- src/win/languages/fr-FR.rc
Fixed a typo under the cassette menu. The typo is Image Exsistane while the correct spelling is Image Existante.
> Fixed a typo under cassette menu.

- src/win/win_opengl_glslp.c
Summary
=======
This fixes using shaders that define the exact language version. The version is searched for, commented out and then prefixed to the program instead of the default one.
Checklist
=========
References
==========
> opengl: fix for shaders with version directive

- src/include/86box/ui.h
- src/unix/unix.c
- src/win/win_preferences.c
- src/win/win_stbar.c
Fix that POST card's message is disappearing when language/iconset change occurs
Summary
=======
Calling ui_sb_set_ready(0) is needed before ui_sb_update_panes() to update the lanugage-specific hints/icons in both cases. Originally  ui_sb_set_ready(0) clears the POST card's text, now a new value is accepted  ui_sb_set_ready(-1), which does the same as value 0, but does not clears the text. Also ui_sb_update_text() call was needed to update the text when the status bar is updated - this call has changed from static to extern.
Checklist
=========
References
==========
N/A
> Fix that POST card's message is disappearing when language/iconset change occurs

- src/win/win_opengl_glslp.c
Summary
=======
The fix in #1913 didn't work in 32bit release builds, most likely due to missing null terminating character. Changed the way the string is copied for less error prone method.
Checklist
=========
References
==========
> Fix null termination issue in opengl shader version replacement

- src/rtmidi_midi.cpp
Summary
=======
This PR fixes wrong copyright information in rtmidi_midi.cpp file.
Checklist
=========
References
==========
None.
> Fix wrong copyright information

- src/include/86box/language.h
- src/win/languages/cs-CZ.rc
- src/win/languages/de-DE.rc
- src/win/languages/en-GB.rc
- src/win/languages/en-US.rc
- src/win/languages/es-ES.rc
- src/win/languages/fi-FI.rc
- src/win/languages/fr-FR.rc
- src/win/languages/hr-HR.rc
- src/win/languages/hu-HU.rc
- src/win/languages/it-IT.rc
- src/win/languages/ja-JP.rc
- src/win/languages/ko-KR.rc
- src/win/languages/pt-BR.rc
- src/win/languages/pt-PT.rc
- src/win/languages/ru-RU.rc
- src/win/languages/sl-SI.rc
- src/win/languages/tr-TR.rc
- src/win/languages/zh-CN.rc
- src/win/win_opengl.c
Summary
=======
General failure notice message box to OpenGL 3.0 renderer initialization failure.
Fail if reported OpenGL version is less than 3.0 or errors are generated after context is created. This should fix some crashes on unsupported hardware or faulty drivers.
Enable debug output only when logfile is defined as debug mode can include a performance hit.
Checklist
=========
References
==========
> Error handling updates on OpenGL 3.0 renderer

- src/win/languages/fr-FR.rc
The words Sauver have been replaced by the word Sauvegarder for a more accurate french translation.
> Made the translation more accurate

- src/game/gameport.c
- src/include/86box/gameport.h
Summary
=======
Adds support for a gameport at 0x209, like the Thrustmaster ACM has
Checklist
=========
References
==========
https://www.flyfoxy.com/images/disable3.jpg
> Add support for a joystick port at 0x209

- src/config.c
- src/game/gameport.c
Summary
=======
* Handle the internal name change for the S3 ViRGE/GX card (formerly known as ViRGE/DX VBE 2.0)
* Fix a typo in CH Flightstick Pro's internal name
* Fix joystick type migration not working properly; also map legacy integer-based joystick type options to their string counterparts directly instead of relying on the array index
Checklist
=========
> Fixes to config file backwards compatibility

- src/include/86box/mo.h
Summary
=======
Makes sure the string doesn't overflow its field into other fields.
Checklist
=========
References
==========
None.
> Change MO vendor length to 9

- src/include/86box/midi.h
- src/include/86box/snd_mpu401.h
- src/include/86box/snd_sb_dsp.h
- src/sound/midi.c
- src/sound/midi_rtmidi.cpp
- src/sound/snd_gus.c
- src/sound/snd_mpu401.c
- src/sound/snd_sb_dsp.c
Summary
=======
Fix buffer overflow on midi input messages by passing length of the message.
Detect sysex messages by the first byte instead of length.
Checklist
=========
References
==========
> Fixes for midi input

- src/sound/snd_mpu401.c
Summary
=======
`mpu->intelligent` is still true even when mpu-401 has reveived command to switch to UART-mode. Fix the check to only compare `mpu->mode`.
Checklist
=========
References
==========
> Fix UART-mode detection on input sysex messages

- src/win/win_opengl.c
Summary
=======
Makes OpenGL 3.0 renderer empty the message queue in one go and only translate and dispatch unhandled messages.
This should fix the full screen mouse lag problem which has been introduced by unknown reason; probably a change in SDL library or Nvidia drivers.
Checklist
=========
References
==========
> Fix opengl core renderer message pump

- src/win/win_opengl.c
- src/win/win_ui.c
If the user leaves full screen window by alt-tab or similar method (unintended way), 86Box goes into an unstable state; mouse cursor can be hidden or clipped to an arbitrary area and the rendering can be distorted. 
Fixing this "properly" would mean refactoring the way windows and renderers are created and going through the process in which window and video resizing works to ensure proper operation.
In this PR is a simpler solution that makes 86Box leave full screen if the user leaves the program.
Summary
=======
Checklist
=========
References
==========
> Exit full screen mode if changing window (with alt-tab)

- src/sound/snd_adlibgold.c
Summary
=======
I have added the gameport at port 201h to the AdLib Gold sound card.
Checklist
=========
References
==========
Yamaha YMZ263B-F datasheet: https://pdf1.alldatasheet.com/datasheet-pdf/view/87670/YAMAHA/YMZ263B-F.html
AdLib Gold drivers, software and documents: https://archive.org/details/adlib-gold-bundle/
> Added gameport at port 201h to AdLib Gold sound card

- src/sound/snd_adlibgold.c
Summary
=======
I have fixed the incorrect control chip ID of the AdLib Gold, as well as added the auxillary registers (used for line in and CD audio to the AdLib Gold mixer. I have also added a CD audio filter as well based on the work of TC1995.
Checklist
=========
References
==========
Gold Sound Standard - Software Development Toolkit: http://www.symphoniae.com/soundcard/Ad_Lib/GOLD/DOCS/GOLD_SDTK.zip
> Fixed incorrect control chip ID of AdLib Gold and added auxillary registers to mixer

- src/sound/snd_adlibgold.c
- src/win/86Box.rc
- src/win/languages/pl-PL.rc
Properly implemented MIDI Out/In.
Changed the ID from 0x50/0x70 to 0x51/0x71 to identify as AdLib Gold 1000.
Added CD Audio volume and filter (Courtsey of Ompronce!)
Summary
=======
See above.
Checklist
=========
References
==========
> AdLib Gold changes:

- src/86box.c
- src/cpu/CMakeLists.txt
- src/cpu/x86seg.c
- src/dma.c
Summary
=======
cyrix_load_seg_descriptor() touches codegen_flat_ds and codegen_flat_ss even if dynarec is disabled.
386_dynarec_ops.c is built even if dynarec is disabled, references many things, and is not needed in that configuration.
dma_page_write() calls update_tsc(), and while this isn't called if dynarec is disabled in software, the call is still built in if built with dynarec disabled.
pc_hard_reset_init() sets cycles_main, which only exists if build with dynarec.
these prevent the codebase from building if built with -DDYNAREC=Off.
this pull request fixes all of these.
Checklist
=========
References
==========
> Fix several build issues if built with -DDYNAREC=Off

- src/sound/snd_adlibgold.c
Summary
=======
Adlib gold default EEPROM data
Checklist
=========
References
==========
Created using setup /r to restore factory EEPROM contents
> Adlib Gold EEPROM data fix

- src/config.c
- src/game/joystick_ch_flightstick_pro.c
Summary
=======
Re-submitting PR #1968 after its changes were accidentally overwritten in a conflict resolution:
* Handle the internal name change for the S3 ViRGE/GX card (formerly known as ViRGE/DX VBE 2.0)
* Fix a typo in CH Flightstick Pro's internal name
* Fix joystick type migration not working properly; also map legacy integer-based joystick type options to their string counterparts directly instead of relying on the array index
Checklist
=========
> Fixes to config file backwards compatibility, take 2

- src/win/languages/dialogs.rc
Summary
=======
Fixes all the win32 UI layout issues reported to me, atleast all the ones I remember.
Checklist
=========
References
==========
> More win32 UI changes

- src/qt/qt_mainwindow.cpp
- src/qt/qt_ui.cpp
Summary
=======
Text update behaviour now identical to Win32 in Qt.
Checklist
=========
References
==========
win_stbar.c.
> qt: Text update behaviour now identical to Win32

- src/qt/qt_mainwindow.ui
Summary
=======
Preferences on macOS now brings up program settings instead.
Checklist
=========
References
==========
None.
> qt: Preferences on macOS now brings up program settings instead

- src/video/vid_ati_mach64.c
- src/video/vid_s3_virge.c
Removed the threaded FIFO on the ViRGE cards due to bugs, instead, relying on a non-threaded FIFO again.
Fixed some 8MB parts of the blitter for the ViRGE/VX-based STB Velocity 3D card so that 8MB RAM detection doesn't glitch everything else, including the blitter.
Summary
=======
See above.
Checklist
=========
References
==========
> Fixed the ISA bus detection of the Mach64GX.

- src/qt/qt_mainwindow.ui
Summary
=======
qt: Fix untranslated hide toolbar string
Checklist
=========
References
==========
None.
> Fix untranslated hide toolbar string

- src/qt/qt_styleoverride.cpp
Summary
=======
This PR fixes theming bugs under KDE, such as background having the wrong color, glitched scrollbars, buttons having no hovering effect, etc.
Checklist
=========
References
==========
None.
> qt: Fix theming bugs under KDE

- src/sound/midi_mt32.c
Summary
=======
This PR disables LCD messages on Roland CM-32L emulation.
Checklist
=========
References
==========
None.
> Disable LCD messages on Roland CM-32L emulation

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Scale toolbar icons based on screen DPI
Checklist
=========
References
==========
None.
> qt: Scale icons based on screen DPI

- src/qt/qt_machinestatus.cpp
Summary
=======
* Fix inverted logic for network icon
* Scale the status bar pixmaps only on Windows
Checklist
=========
References
==========
None.
> qt: Status bar fixes

- src/qt/qt_machinestatus.cpp
- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
Summary
=======
* Fix remember window option
* Status bar pixmaps are now scaled when building with Qt 5
* Force HiDPI scaling on UI for all platforms with Qt 5
Checklist
=========
References
==========
https://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum
> qt: Status bar and window fixes

- src/qt/qt_main.cpp
Summary
=======
qt: Set Application attributes before construction
Enables HiDPI scaling for real.
Checklist
=========
References
==========
None.
> qt: Set Application attributes before construction

- src/network/CMakeLists.txt
Summary
=======
Use external libslirp on Unix systems except macOS
It should hopefully fix networking with SLiRP mode on Linux.
Checklist
=========
References
==========
None.
> Use external libslirp on Unix systems except macOS

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_util.cpp
- src/qt/qt_util.hpp
Summary
=======
qt: Use non-integer HiDPI scaling on Qt 5
Checklist
=========
References
==========
None.
> qt: Use non-integer HiDPI scaling on Qt 5

- src/video/vid_ati_mach64.c
Added 4x2 and 8x1 color patterns in the OpRect side, fixes OS/2 8-bit color.
Unthreaded the cards as well.
ISA versions can access the dword/long mapping too, fixes more graphical bugs in various operating systems such as Windows 95.
Summary
=======
See above.
Checklist
=========
References
==========
> Mach64 changes/improvements:

- src/sound/snd_sb.c
Summary
=======
Add missing I/O, DMA and IRQ Ranges to the Sound Blaster series of soundcards
Checklist
=========
References
==========
> Add missing I/O, DMA and IRQ Ranges

- src/qt/qt_main.cpp
Summary
=======
qt: Set font immediately after QApplication initialization
Fixes Settings mode on Windows.
Checklist
=========
References
==========
None.
> qt: Set font immediately after QApplication initialization

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_winmanagerfilter.cpp
- src/qt/qt_winmanagerfilter.hpp
Summary
=======
Fixes and unifies shutdown behavior when initiated by 86BoxManager.
Add implementation for -N command line switch.
Save NVR on close.
Fix taskbar grouping with 86BoxManager.
Checklist
=========
References
==========
> Qt fixes for 86BoxManager

- .github/workflows/cmake.yml
Summary
=======
Disable stable building on github actions, it doesn't provide any benefit and people should be using the ci builds, not actions builds anyway, they just slow down actions building. Left them in incase they're needed in future though.
Fix silly derp and restore linux actions building again.
Checklist
=========
References
==========
> Disable excessive GH Actions builds

- src/qt/qt_newfloppydialog.cpp
Summary
=======
qt: Port Win32 86F creation code to Qt
Fixes the new floppy dialog creating malformed/corrupted images on Qt.
Checklist
=========
References
==========
None.
> qt: Port Win32 86F creation code to Qt

- src/qt/CMakeLists.txt
- src/qt/qt_main.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_unixmanagerfilter.cpp
- src/qt/qt_unixmanagerfilter.hpp
Summary
=======
qt: Add Unix manager support (client-side interface)
This should bring Qt closer to feature parity with Windows.
Checklist
=========
References
==========
None.
> qt: Add Unix manager support (client-side interface)

- src/qt/qt_mainwindow.cpp
- src/qt/qt_opengloptions.cpp
- src/qt/qt_opengloptions.hpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
Summary
=======
This PR adds support for OpenGL ES 3.0 in the OpenGL 3.0 renderer.
Checklist
=========
References
==========
None.
> qt: OpenGL ES 3.0 support

- src/qt/qt_mainwindow.ui
- src/qt/qt_opengloptions.cpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_settingsmachine.ui
Summary
=======
* qt: Fix loading of shaders using GL_ARB_shading_language_420pack extension
* qt: Make central widget expanding, fixes shrunk emulator screen on certain circumstances
Checklist
=========
References
==========
None.
> qt: More assortment of fixes

- src/qt/qt_opengloptions.cpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
- src/qt/qt_rendererstack.cpp
Summary
=======
- Improve error handling and add more checks to initialization.
- Request 3.2 core profile context instead of 3.0; this doesn't mean raising the requirement as Qt will still provide the closest matching version, but requesting lower that 3.2 will not give core profile even if it was supported by the system.
Checklist
=========
References
==========
> qt: More error handling and tweaking to OpenGL 3 renderer

- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddrive_common.cpp
- src/qt/qt_platform.cpp
- src/sound/xaudio2.c
- src/unix/unix.c
Summary
=======
* [qt: XT IDE should be XTA](https://github.com/86Box/86Box/commit/40a75379b7db93f2d595ebf4780a10ba243da9c5)
* [qt: Default to 0:0 if bus is full](https://github.com/86Box/86Box/commit/5e4cb50da0d5533cc171d604fbe42571f6f944c0)
Checklist
=========
References
==========
None.
> qt: XT IDE should be XTA

- src/qt/qt_main.cpp
Summary
=======
This should fix the pipe/socket based manager feature
Checklist
=========
References
==========
> qt: Fix a typo connecting to resetVM signal on unix manager socket

- src/qt/qt_opengloptions.cpp
- src/qt/qt_opengloptions.hpp
- src/qt/qt_opengloptionsdialog.cpp
- src/qt/qt_opengloptionsdialog.hpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
Summary
=======
MacOS will use OpenGL 2.1 unless specifically requested for OpenGL 4.1.
Shader language version is now set to what is reported by the driver for best compatibility.
Checklist
=========
References
==========
> Fix OpenGL Core renderer on macOS

- src/qt/qt_ui.cpp
Summary
=======
Make the same check as in Win32 UI; if keyboard doesn't require capture and VM has no mouse selected, then don't capture mouse on click.
Checklist
=========
References
==========
> qt: fix mouse getting captured even if VM has no mouse

- src/qt/qt_machinestatus.cpp
- src/qt/qt_newfloppydialog.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_settings_bus_tracking.cpp
- src/qt/qt_settingsinput.cpp
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
Fix some of the compiler warnings (mainly gcc/mingw) from Qt code.
Checklist
=========
References
==========
> qt: fix multiple compiler warnings

- src/qt/languages/fi-FI.po
- src/win/languages/fi-FI.rc
This is an improvement for the 86Box Finnish translation (both Win32 and Qt). I tried to synchronize the changes between the two, although I might've missed some.
Something I noticed is that there are more Win32 strings than Qt ones. For example, the Win32 version has separate strings for tape drives, cartridges, floppies etc. but there's only one set of strings for Qt. For the latter, the first matches had been picked, which meant that the Qt translation used the tape drive strings for all media. That sounded odd, because floppy drive "eject" translated to "remove from cassette tray". I tried to change the Qt translation to be fairly media-agnostic.
> improve Finnish translation

- src/qt/qt_mainwindow.cpp
- src/qt/qt_winrawinputfilter.cpp
Summary
=======
Prevents Alt-F4 from quitting 86Box by stopping the message handling on windows raw input filter.
Checklist
=========
References
==========
> qt: Disable processing of alt-f4 in windows.

- src/qt/qt_harddiskdialog.cpp
Summary
=======
Adds the available formats and corresponding extensions to file dialog filter when creating a hard disk. The format combo box is set to the same selection. This also fixes the error when not adding the extension on the file dialog and automatically adds the extension if necessary. 
Checklist
=========
References
==========
> qt: Improve hard disk create file selection

- src/qt/qt_opengloptions.cpp
Summary
=======
This fixes shader crashing with Intel HD4000 on Windows with latest drivers. Probably also fixes the errors with HD4400.
Checklist
=========
References
==========
> qt: Fix shaders on HD4000/4400

- src/lpt.c
Summary
=======
Fix yet another null dereference in lpt.c
Checklist
=========
References
==========
> Fix yet another null dereference in lpt.c

- src/qt/qt_joystickconfiguration.cpp
- src/qt/qt_joystickconfiguration.ui
Summary
=======
The joystick dialog was set to fixed size while it's widgets are added dynamically per device selection.
Set fixed size as a constraint to allow the dialog conform to selections instead of staying the initial minimum size.
Also set the dialog title "Dialog" -> "Joystick configuration".
Checklist
=========
References
==========
> Fix Qt joystick dialog

- src/qt/qt_platform.cpp
- src/unix/unix.c
> Add handling for several missing strings to plat_get_string on Qt and legacy Unix UIs

- src/qt/qt_joystickconfiguration.cpp
Summary
=======
The dynamically added widgets in joystick dialog weren't removed properly.
Checklist
=========
References
==========
> qt: Another joystick dialog fix

- src/qt/qt_mainwindow.cpp
Summary
=======
Uncapture mouse when application is deactivated or window is blocked (dialog shown). Re-capture after full screen dialog.
Checklist
=========
References
==========
> qt: mouse capture fixes

- src/qt/wl_mouse.cpp
Summary
=======
wl_mouse: Don't uncapture mouse if is already uncaptured
Checklist
=========
References
==========
None.
> wl_mouse: Don't uncapture mouse if is already uncaptured

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Keyboard input now works properly when mouse is uncaptured.
Checklist
=========
References
==========
None.
> qt: Keyboard input now works properly when mouse is uncaptured

- src/sound/midi_fluidsynth.c
Summary
=======
fluidsynth: Fallback to system soundfont if one isn't specified.
Checklist
=========
References
==========
None.
> fluidsynth: Fallback to system soundfont if one isn't specified

- vcpkg.json
Summary
=======
86box i as 3.3, not 3.1
Checklist
=========
References
==========
> Correct version in vcpkg.json

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Get rid of resize rounding
Checklist
=========
References
==========
None.
> qt: Get rid of resize rounding

- src/CMakeLists.txt
Summary
=======
cmake: Enable 64-bit file support on 32-bit Linux
This is to allow proper support for large files on 32-bit Linux.
Checklist
=========
References
==========
None.
> cmake: Enable 64-bit file support on 32-bit Linux

- src/qt/qt_rendererstack.cpp
Summary
=======
qt: Avoid reading absolute mouse input from cross-platform Qt code on Windows
This ensures only RAWINPUT sends mouse input to the emulated machine on Windows.
Checklist
=========
References
==========
None.
> qt: Avoid reading absolute mouse input from cross-platform Qt code on Windows

- src/qt/CMakeLists.txt
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
Summary
=======
Fix some build system issues with Qt 6 on macOS and work around a modifier key input handling bug on the same configuration. See the commit messages for the gory details.
I've tested these changes on macOS 12.3 (on Apple Silicon, but using an x86-64 build of 86Box).
A possible alternative to consider would be to switch input handling to something like [qkeycode](https://github.com/nyanpasu64/qkeycode), which abstracts away the platform differences using code based on Qt WebEngine and would obviate the need for platform-specific input handling and tables.  Since it would involve dealing with adding another potentially-vendored dependency and qkeycode isn't currently as effective as this manual handling (it doesn't distinguish left and right modifiers on macOS and I'd need …
> Fix Qt 6 build and modifier key handling on macOS

- src/unix/unix.c
Summary
=======
unix: Fix missing include needed for ROM paths code.
Checklist
=========
References
==========
None.
> unix: Fix missing include

- src/qt/qt_mediamenu.cpp
Summary
=======
qt: Fix crashes on failed loads of media images
Checklist
=========
References
==========
None.
> qt: Fix crashes on failed loads of media images

- src/gdbstub.c
- src/include/86box/gdbstub.h
Summary
=======
Makes gdbstub works on mac with clang
- Fix the switch scoping preventing declaration
- Adding stdint.h as inclusion to make uint*_t works
- Fix WSAGetLastError to `errno` on unices.
> Fix: GdbStub Code to make it compiled with Clang

- src/network/network.c
Summary
=======
Log statements broke somewhere in development.
Checklist
=========
References
==========
> network.c: fix log statement

- src/network/net_pcap.c
Summary
=======
This change fixes a difference between pcap on windows and pcap on linux where pcap_next blocks until a new packet arrives.
It may also improve mac OS although this patch uses `ifdef __linux__` because I cannot test on Mac OS.
Checklist
=========
References
==========
PCAP linux manual page, specifically the section about "packet buffer timeout"
[This github issue goes into more detail](https://github.com/the-tcpdump-group/libpcap/issues/572)
> linux pcap fix

- src/86box.c
Summary
=======
Don't accept a directory as config file parameter.
Fixes startup freeze if the config file specified on the command line turns out to be a directory.
Checklist
=========
References
==========
None.
> Don't accept a directory as config file parameter

- src/qt/qt_rendererstack.cpp
Summary
=======
qt: Disable Xi2 mouse input backend.
evdev will be used for now until click-and-drags are working again.
Checklist
=========
References
==========
None.
> qt: Disable Xi2 mouse input backend

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Attempt fixing Windows/Super key input
Checklist
=========
References
==========
None.
> qt: Attempt fixing Windows/Super key input

- src/qt/qt_rendererstack.cpp
- src/qt/qt_settings.cpp
- src/qt/qt_settings.ui
Summary
=======
qt: Fix dangling pointers on Vulkan init failure
Checklist
=========
References
==========
None.
> qt: Fix dangling pointers on Vulkan init failure

- src/machine/m_xt.c
Summary
=======
Prevents the vendex adding the FDC twice. (Doesn't fix the HDD at drive E bug, that's elsewhere and harder to resolve)
Checklist
=========
References
==========
> Dont add the fdc twice to the vendex

- src/machine/m_xt_olivetti.c
https://forum.vcfed.org/index.php?threads/olivetti-m21-m24-with-bios-version-1-44.72815/
Summary
=======
change BIOS rom from 1.43 to 1.44
Checklist
=========
* [ X] This pull request requires changes to the ROM set
* [ X] I have opened a roms pull request - https://github.com/86Box/roms/pull/165
References
==========
https://forum.vcfed.org/index.php?threads/olivetti-m21-m24-with-bios-version-1-44.72815/
> change m24 BIOS rom to newer 1.44 version

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
Summary
=======
Reduced the number of variables that depend on the main SVGA handler.
Re-implemented accel command 5 (Polygon Boundary Line) right.
Implemented Polygon fill type A and B (latter not tested yet) on accel command 2 per manual.
Fixed crashes when starting Win2.1x using the built-in 8514/A driver.
Some wip cleanups.
Checklist
=========
References
==========
> 8514/A changes:

- src/unix/unix.c
Summary
=======
Fix typo in unix.c preventing build on macOS with Qt disabled
Checklist
=========
> Fix building on macOS without Qt

- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingssound.cpp
> Fix 8514/A and GUS checkboxes not being grayed out with 8-bit ISA-only machines as intended

- src/include/86box/mca.h
- src/mca.c
- src/qt/CMakeLists.txt
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
- src/qt/qt_mcadevicelist.cpp
- src/qt/qt_mcadevicelist.hpp
- src/qt/qt_mcadevicelist.ui
Summary
=======
This PR adds a dialog that lists all MCA devices that currently exist in the emulated machine, with the MCA IDs of said devices. The dialog can be accessed from the Tools menu.
Note that this doesn't include the friendly name of the devices.
Checklist
=========
References
==========
None.
> qt: Add MCA device list to Tools

- src/include/86box/vid_ega.h
- src/include/86box/vid_ega_render_remap.h
- src/video/vid_ega.c
- src/video/vid_ega_render.c
Summary
=======
The remapping functions of SVGA have been backported to EGA as they work better in some areas like FantasyLand.
Checklist
=========
References
==========
> EGA fixes to FantasyLand for said card.

- src/qt/qt_d3d9renderer.cpp
- src/qt/qt_machinestatus.cpp
- src/qt/qt_mediamenu.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
qt: Fix crashes and freezes when switching to/from Direct3D 9
Checklist
=========
References
==========
None.
> qt: Fix crashes and freezes when switching to/from Direct3D 9

- src/qt/qt_d3d9renderer.cpp
Summary
=======
qt_d3d9renderer: Account for HiDPI scaling.
Checklist
=========
References
==========
None.
> qt_d3d9renderer: Account for HiDPI scaling

- src/cpu/x86.c
- src/include/86box/vid_xga.h
- src/video/vid_xga.c
Summary
=======
Cursor and mapping on Windows 2.x' 286/808x XGA driver.
Pattern and DMA bus master fixes to OS/2 2.x/Warp's XGA driver.
Software reset no longer causes glitches to the screen using XGA (x86.c)
Checklist
=========
References
==========
> And finally, more fixes to the XGA implementation including:

- bumpversion.sh
- src/unix/assets/86Box.spec
Summary
=======
Fix the regex bug I introduced with the last commit, it caused an invalid update to the RPM spec file which is also fixed.
I also added support for an optional second argument to `bumpversion.sh` to allow the ROM release version to be manually specified. This way if you know you will be releasing a new ROM version just after the new 86Box release, you can already update it to the next ROM release version, instead of the current version.
Lastly, I ran ShellCheck against the script and cleaned up some minor warnings.
> Fix regex bug

- src/disk/hdc_esdi_mca.c
- src/include/86box/scsi_ncr5380.h
- src/include/86box/vid_8514a.h
- src/scsi/scsi.c
- src/scsi/scsi_ncr5380.c
- src/video/vid_8514a.c
- src/video/vid_xga.c
Summary
=======
ESDI MCA: Increased esdi_time from 200 to 512, should fix the timeout that caused the bad attention 03 fatal.
Rancho: Added the Rancho RT1000B-MC MCA SCSI controller, it uses the 8.20R BIOS.
8514/A: Reworked the Outline command to satisfy the manual and the win2.10 (286/386) driver.
XGA: Initial rom len is set to 0x8000 (which, after being configured, is set back to 0x2000) just to not make it hang with POST code 40 25 on most MCA configurations.
Checklist
=========
References
==========
> IBM ESDI MCA, 8514/A, XGA and Rancho changes:

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_ui.cpp
Summary
=======
qt: Make fatal messageboxes have the correct icons
Fatals now exit the emulator properly
Checklist
=========
References
==========
None.
> qt: Make fatal messageboxes have the correct icons

- src/video/vid_pgc.c
Summary
=======
PGC: Properly draw 40x25 CGA text mode
Checklist
=========
References
==========
https://www.seasip.info/VintagePC/pgc.html
> PGC: Properly draw 40x25 CGA text mode

- src/win/languages/dialogs.rc
Summary
=======
Fix incorrect position of CD speed combobox
Checklist
=========
References
==========
> Fix incorrect position of CD speed

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Fix Hard Reset dialog button order
Checklist
=========
References
==========
None.
> Fix Hard Reset dialog button order

- src/qt/qt_mainwindow.cpp
Summary
=======
Restore code to properly restore coordinates
Checklist
=========
References
==========
None.
> Restore code to properly restore coordinates

- src/include/86box/video.h
- src/video/video.c
Summary
=======
Make screenshots thread-safe.
Checklist
=========
References
==========
None.
> Make screenshots thread-safe

- src/qt/qt_d3d9renderer.cpp
Summary
=======
qt_d3d9renderer: Make screenshots work.
Checklist
=========
References
==========
None.
> qt_d3d9renderer: Make screenshots work

- .github/workflows/cmake.yml
Summary
=======
Fix accidental removal of rtmidi on msys2 builds
Checklist
=========
References
==========
> Fix accidental removal of rtmidi on msys2 builds

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: restore fixed window size properly 
Checklist
=========
References
==========
None.
> qt: restore fixed window size properly

- src/qt/evdev_mouse.cpp
Summary
=======
qt: Fix double free when multi-monitor is enabled and evdev is used
Checklist
=========
References
==========
None.
> qt: Fix double free when multi-monitor is enabled and evdev is used

- src/qt/qt_rendererstack.cpp
Summary
=======
Fixes closing 86box *entirely* when second display window is closed
KNOWN BUG (Cosmetic only): Inverts the setting on the menu if you close the window manually
Checklist
=========
References
==========
> Don't shut down when second display is closed

- src/disk/hdc_esdi_mca.c
Summary
=======
operating systems such as NT.
Remove horrible status hack.
Checklist
=========
References
==========
> Revert to the IBM ESDI MCA roms to prevent a hang into booting some

- src/include/86box/vid_ega_render_remap.h
- src/video/vid_8514a.c
- src/video/vid_xga.c
Summary
=======
Revert initial XGA rom length back to 0x2000 to prevent error 114 in the MCA bioses.
Note: if you encounter a 40 25 hang again with the XGA-2 roms, just close and re-open the emulator, this typically affects hard resets.
Checklist
=========
References
==========
> Fix warnings on the XGA, 8514/A and EGA Render map files.

- src/acpi.c
- src/include/86box/acpi.h
- src/include/86box/pit.h
- src/pit.c
Summary
=======
The 3.579545 MHz ACPI timer has a high performance cost. Now we only tick as needed.
My testing shows around a 10% improvement in overall emulation speed.
Checklist
=========
References
==========
> ACPI: replace 3.58MHz timer with an overflow timer

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_rendererstack.cpp
Summary
=======
[qt: Make renderer widget resizable only once](https://github.com/86Box/86Box/commit/548e8b360abe43bee3169fc21c35b4c2377034b3)
[qt: Fix mouse polling](https://github.com/86Box/86Box/commit/7beec38ed3624c4bf0a00caa8b7bc22b00efa5f1)
Checklist
=========
References
==========
None.
> qt: Make renderer widget resizable only once

- src/qt/qt_rendererstack.cpp
Summary
=======
qt: don't enable blitting too early on software renderer fallbacks.
Checklist
=========
References
==========
None.
> qt: don't enable blitting too early

- src/include/86box/machine.h
- src/include/86box/nvr_ps2.h
- src/machine/m_ps2_isa.c
- src/machine/m_ps2_mca.c
- src/machine/machine_table.c
- src/nvr_ps2.c
Summary
=======
MCA PS/2: Added Model 60 (8-slot version of 50 with the same bios) and Model 65sx (essentially the same as 55sx but with a new bios and a secondary nvram a la 70-80 but limited to 2KB of size instead of 8KB).
MCA PS/2: Made the i486 cpu selection on only on Type 3 MCA models (70-80) and not Type 2 anymore, therefore the latter is limited to 386DX cpu's only.
Checklist
=========
References
==========
> ISA PS/2: Clean-ups and converted into a typedef struct.

- src/unix/assets/net.86box.86Box.desktop
It should be there according to the desktop file specification.
> Add missing semicolon to desktop file

- src/dma.c
- src/video/vid_xga.c
Summary
=======
Apparently MCA Audio cards always want auto-init enabled.
Checklist
=========
References
==========
> Made reg 0x53 (read only) default temp val to 0x70 to satisfy xgaaidos.sys' detection.

- src/machine/machine_table.c
Summary
=======
Re-add the Soltek SL-56A5, it got lost
Checklist
=========
References
==========
None
> Re-add the Soltek SL-56A5, it got lost

- src/win/Makefile.mingw
Summary
=======
Add GDBStub to win32 makefile, it was missing
Checklist
=========
References
==========
None
> Add GDBStub to win32 makefile

- src/video/vid_tgui9440.c
Summary
=======
Fix crash in TGUI 9440CXI
Checklist
=========
References
==========
null pointer frees are always a bad idea.
> Fix crash in TGUI 9440CXI

- src/86box.c
- src/CMakeLists.txt
- src/config.c
- src/device/keyboard_xt.c
- src/include/86box/86box.h
- src/include/86box/pit.h
- src/include/86box/pit_fast.h
- src/machine/m_amstrad.c
- src/machine/m_at.c
- src/machine/m_europc.c
- src/machine/m_pcjr.c
- src/machine/m_ps1.c
- src/machine/m_ps2_isa.c
- src/machine/m_ps2_mca.c
- src/machine/m_xt.c
- src/machine/m_xt_compaq.c
- src/machine/m_xt_laserxt.c
- src/machine/m_xt_olivetti.c
- src/machine/m_xt_philips.c
- src/machine/m_xt_t1000.c
- src/machine/m_xt_zenith.c
- src/machine/machine.c
- src/pic.c
- src/pit.c
- src/pit_fast.c
- src/port_6x.c
- src/win/Makefile.mingw
Summary
=======
This is enabled by default on 486+ CPUs and can be forced disabled/enabled with pit_mode=0/1
Around 10% improvement on emulation speed.
Checklist
=========
References
==========
> PIT: add alternative faster PIT

- src/qt/qt_platform.cpp
Summary
=======
Fixes a typo that made the dialog box shown upon failing to load the Ghostscript library display the wrong message.
Checklist
=========
> Fix a typo in qt_platform.cpp

- src/sound/snd_sb.c
Summary
=======
Adds an option to control MIDI input that was missing from the Sound Blaster Pro MCV despite having been added to other Sound Blasters.
Checklist
=========
> Add an option to control SBMIDI input receiving on SB Pro MCV

- src/sound/snd_sb.c
Summary
=======
Fixes a segfault at startup when the Sound Blaster Pro v2 or Pro MCV are selected. Additionally, seems to fix OPL playback on Sound Blaster Pro v1 outputting only on the left channel.
Checklist
=========
> Fix a crash with Sound Blaster Pro v2

- src/sound/midi_mt32.c
Summary
=======
Makes the last MT-32 LCD message in the status bar disappear upon a hard reset instead of persisting until the emulator is closed, to avoid interfering with the POST card. 
Checklist
=========
> Clear the MT-32 LCD message on reset

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Fix fullscreen at start with Direct3D 9 renderer
Checklist
=========
References
==========
None.
> qt: Fix fullscreen at start with Direct3D 9 renderer

- src/sound/snd_mpu401.c
Summary
=======
Add IRQ selection for MPU-IMC.
This existed in later revisions of the card in real hardware.
Checklist
=========
References
==========
https://www.ardent-tool.com/sound/Roland_MPU-IMC.html
> On the newer MPU IMC cards, there is a line of double pins and a small square blue shorting block that can be moved. The area is labeled "IRQ".  There are about six numbered pairs including 9 and 7.
> Add IRQ selection for MPU-IMC

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Fix separators not showing up on macOS
Checklist
=========
References
==========
https://bugreports.qt.io/browse/QTBUG-94802?gerritIssueType=IssueOnly
> qt: Fix separators not showing up on macOS

- src/include/86box/video.h
- src/video/vid_cl54xx.c
- src/video/vid_table.c
Summary
=======
Add orchid variants of the GD5430 and 5434
Checklist
=========
References
==========
None
> Add orchid variants of the GD5430 and 5434

- src/config.c
- src/qt/qt_mainwindow.cpp
- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
[qt: Fix hide toggles on resizable main window](https://github.com/86Box/86Box/commit/94c84b299d6b9c58b01bfd07b2d9f6a2be4f04d6)
[qt: Properly display tertiary/quarternary IDE toggle in Settings](https://github.com/86Box/86Box/commit/313b2ab8523beabea87229505ec1abab61c04dbe)
[config: Save and load cassette toggle properly](https://github.com/86Box/86Box/commit/e6cfdf4f6991d4d36d3d2e29ae4cdbb9173cc7d6)
Checklist
=========
References
==========
None.
> qt: Important bug fixes

- src/video/vid_voodoo_fifo.c
Summary
=======
fixes a lot of graphical corruption on the menu of NFS2SE when render threads = 4, seems to fix all corruption in game too, according to @Dizzy611 it also improves performance.
Checklist
=========
References
==========
None
> Voodoo fix for NFS2SE

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/qt/qt_mediamenu.cpp
- src/qt/qt_mediamenu.hpp
- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.ui
Summary
=======
On macOS, after launching 86Box from finder the image file selection directory defaults to `/`. On Windows and Linux, qt defaults to what is essentially the `$CWD` of the application. There are a few reasons for the macOS difference, mostly just the way application bundles are structured and the way they are launched.
This PR adds an option to try and mimic the Windows / Linux behavior on macOS . When this option is selected any media selection dialog will default to the `usr_path` directory.
The option appears to have no effect on Windows or Linux because open dialogs are in `$CWD` by default. Additionally, current behavior can be maintained by not selecting the option.
Tested on: macOS, linux, windows 10
**Note:** A side effect of this PR is making the preferences dialog …
> qt: Global option in preferences to use usr_path as the file image open directory

- src/unix/assets/86Box.spec
Summary
=======
The symlink hack is no longer needed, since the roms can reside in other places.
> Remove obsolete symlink hack

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: fix hard freeze on hidden second windows
Checklist
=========
References
==========
None.
> qt: fix hard freeze on hidden second windows

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
- src/qt/qt_platform.cpp
Summary
=======
qt: Fix compile on ARM64 with GLES2 headers
Checklist
=========
References
==========
None.
> qt: Fix compile on ARM64 with GLES2 headers

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_rendererstack.cpp
Summary
=======
qt: properly update "Show non-primary monitors" settings when they are closed
Checklist
=========
References
==========
None.
> qt: properly update "Show non-primary monitors" settings when they are closed

- src/qt/qt_newfloppydialog.cpp
Summary
=======
qt: Fix unresponsive progress bar when creating floppy images
Checklist
=========
References
==========
None.
> qt: Fix unresponsive progress bar when creating floppy images

- src/pit_fast.c
Summary
=======
pit_fast: fix off by one error with mode 2 counter
Checklist
=========
References
==========
> pit_fast: fix off by one error with mode 2 counter

- src/qt/qt_mediamenu.cpp
- src/qt/qt_mediamenu.hpp
Summary
=======
The CD-ROM menu was a bit inconsistent with the floppy media menu. For example, to eject an image it's listed as `Eject` in floppy but `Empty` in cd. To load an image you click `Image`, but in a different location than that of the floppy menu.
In addition, the `Reload previous image` had no effect while an image was loaded.
This PR tries to clean that up a little:
* `Empty` is now called `Eject` like the floppy and moved to the bottom. 
* `Reload previous image` is only visible when the conditions are met: 1) no image mounted and 2) a previous image was used.
* To load an image, you now select `Image...` in a similar location to the floppy menu
This also adds the currently mounted image name to the floppy and CD-ROM menu while an image is mounted. See pictures below. …
> qt: Media menu updates

- src/cdrom/cdrom.c
- src/disk/mo.c
- src/disk/zip.c
- src/include/86box/hdc_ide.h
- src/include/86box/scsi.h
- src/include/86box/scsi_device.h
- src/scsi/scsi_cdrom.c
- src/scsi/scsi_disk.c
- src/win/win_settings.c
Summary
=======
Use defines instead of hardcodes for drive limits
This only updates the win32 ui, and core code at the moment, I have limited time today, but QT-UI should remain how it was before functionally. (Infact, everything should in reality)
Checklist
=========
References
==========
None
> Use defines instead of hardcodes for drive limits

- src/qt/qt.c
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
- src/vnc.c
Summary
=======
qt: Enable and make VNC renderer work properly
Checklist
=========
References
==========
None.
> qt: Enable and make VNC work properly

- src/sound/snd_mpu401.c
Summary
=======
mpu401: Add MPU-401AT I/O address ranges
Checklist
=========
References
==========
https://wiki.preterhuman.net/Roland_MPU-401AT
> mpu401: Add MPU-401AT I/O address ranges

- src/qt/qt_settingsmachine.ui
Summary
=======
This updates the machine settings layout in order to make mac and linux consistent with the windows version. Even though they use the same code, it appears that qt on windows makes some assumptions on the layout that the others do not.
The widget that is the container for the other widgets was set to a form layout (`QFormLayout`). I had to change the form layout to a grid layout (`QGridLayout`) in order for the combo boxes to fully honor their `sizePolicy` of `Preferred`(`QSizePolicy::Policy`). With `Preferred` it would normally expand to fill up the space, but qt seems to require a grid to make that happen.
This fixes the issue on mac and linux but has no effect on windows. Windows apparently automatically converts to a grid layout so making it explicit has no effect. See …
> qt: Update machine settings layout for consistency

- src/vnc.c
Summary
=======
vnc: Pause always when switching to VNC renderer.
Checklist
=========
References
==========
None.
> vnc: Pause always when switching to VNC renderer

- src/cpu/386.c
- src/cpu/386_dynarec.c
- src/cpu/x86_ops_mov_ctrl.h
Summary
=======
x86: mov r, DR6 now always writes bits 4-11 and bits 16-31 as 1
Checklist
=========
References
==========
None.
> x86: mov r, DR6 now always writes bits 4-11 and bits 16-31 as 1

- src/qt/evdev_mouse.cpp
Summary
=======
Replace busy looping which was using 100% cpu with poll()
Checklist
=========
References
==========
> qt: fix busy looping with evdev mouse

- bumpversion.sh
- src/unix/assets/86Box.spec
Summary
=======
With both the main and roms package having the exact same source package filenames, one clobbers the other and the build fails. Prevent this by using the zip package instead for the ROMs.
> use zip for roms to prevent clobbering

- src/qt/qt_openglrenderer.cpp
Summary
=======
Fix fullscreen rendering on mac.
glViewport needs to be called inside onBlit on mac or the viewport transformation will be reset at some point.
Also correct the x/y offset scaling for retina displays.
Checklist
=========
References
==========
> qt_openglrenderer: fix fullscreen rendering on mac

- src/86box.c
- src/CMakeLists.txt
- src/include/86box/86box.h
- src/qt/qt_main.cpp
Summary
=======
Not built by default, this allows printing the emulation speed on stdout and exiting after a certain emulation time.
Useful for automated performance profiling.
Checklist
=========
References
==========
> Add an instrumentation option for performance profiling

- src/video/vid_svga_render.c
Summary
=======
SVGA rendering optimizations
References
==========
CPU time
_Before_:
_After_:
> SVGA rendering optimizations

- src/include/86box/timer.h
- src/timer.c
Summary
=======
Around 25% faster timer processing
References
==========
CPU time
_Before_:
_After_:
> Optimize timer processing

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
Summary
=======
qt: Add ability to open screenshots folder
Checklist
=========
References
==========
None.
> qt: Add ability to open screenshots folder

- src/86box.c
- src/config.c
- src/include/86box/video.h
- src/qt/qt_d3d9renderer.cpp
- src/qt/qt_hardwarerenderer.cpp
- src/qt/qt_hardwarerenderer.hpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_renderercommon.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
- src/qt/qt_softwarerenderer.cpp
- src/qt/qt_vulkanwindowrenderer.cpp
Summary
=======
qt: Add option to apply fullscreen stretching modes when maximized
Checklist
=========
References
==========
None.
> qt: Add option to apply fullscreen stretching modes when maximized

- src/include/86box/vid_xga.h
- src/video/vid_svga.c
- src/video/vid_xga.c
Mono blits no longer cause transparency issues in some programs (e.g.: Creative utilities such as MIDI and CD on Win3.1x).
Summary
=======
Checklist
=========
References
==========
> XGA: Cursor no longer gets black parts when returning from Mystify screensaver to GUI and, at the same time, keeping the Win95 cursor intact.

- src/disk/hdc_esdi_mca.c
Summary
=======
Checklist
=========
References
==========
> ESDI MCA: No longer fatal on default reads, fixes Win3.0 MME installation to hard disk using ESDI MCA.

- src/qt/qt_d3d9renderer.cpp
Summary
=======
qt_d3d9renderer: Clear screen backbuffer at each render
Checklist
=========
References
==========
None.
> qt_d3d9renderer: Clear screen backbuffer at each render

- src/cdrom/cdrom_image.c
- src/qt/qt_platform.cpp
Summary
=======
[cdrom: Properly empty the path of image if it can't be loaded](https://github.com/86Box/86Box/commit/740108c37c84f22ae2cca1c8145d85a12b2de2b0)
[qt: Fix usage of unconverted path in plat_fopen64](https://github.com/86Box/86Box/commit/97242168ded8a5f1fbd289512056961952784d15)
Checklist
=========
References
==========
None.
> qt: cdrom loading fixes on Windows

- src/qt/qt_rendererstack.cpp
- src/qt/xinput2_mouse.cpp
Summary
=======
qt: Raise minimum Xi2 version requirement to 2.1
This is needed for click-and-drag to work with both Qt5 and Qt6, especially the latter which was previously broken, without any hacks.
Checklist
=========
References
==========
None.
> qt: Raise minimum Xi2 version requirement to 2.1

- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddiskdialog.hpp
Summary
=======
qt: large sizes when entered no longer decrement by 1MB
Checklist
=========
References
==========
None.
> qt: large sizes when entered no longer decrement by 1MB

- src/sound/snd_sb.c
Summary
=======
Fix SB 2.0 OPL crash
Thanks to TC1995 for reporting.
Checklist
=========
References
==========
> Fix SB 2.0 OPL crash

- src/cpu/cpu.c
Summary
=======
When writing the results of the CPUID instruction into EAX/EBX/ECX/EDX registers, on AMD K6-2/III/2+/III+ CPUs unfilled registers in most cases aren't cleared to 0, like on any other CPU, including the original K6, which leads to bogus extended CPU feature flags and L3 cache size of 32 MiB (!) being read.
Checklist
=========
> Clear unfilled registers when returning CPUID results on K6-2/III/+ CPUs

- src/qt/qt_openglrenderer.cpp
- src/qt/qt_openglrenderer.hpp
Summary
=======
Fixes the following warnings:
```
In file included from C:/Jenkins/agent/workspace/86Box@9/src/qt/qt_openglrenderer.cpp:27:
C:/Jenkins/agent/workspace/86Box@9/src/qt/qt_openglrenderer.hpp: In constructor 'OpenGLRenderer::OpenGLRenderer(QWidget*)':
C:/Jenkins/agent/workspace/86Box@9/src/qt/qt_openglrenderer.hpp:81:20: warning: 'OpenGLRenderer::renderTimer' will be initialized after [-Wreorder]
81 |     QTimer        *renderTimer;
|                    ^~~~~~~~~~~
C:/Jenkins/agent/workspace/86Box@9/src/qt/qt_openglrenderer.hpp:80:20: warning:   'OpenGLOptions* OpenGLRenderer::options' [-Wreorder]
80 |     OpenGLOptions *options;
|                    ^~~~~~~
C:/Jenkins/agent/workspace/86Box@9/src/qt/qt_openglrenderer.cpp:37:1: warning:   when initialized here [-Wreorder]
37 | …
```
> Fix two warnings in Qt code

- src/machine/machine_table.c
Summary
=======
The Gigabyte GA-586IP motherboard has no PS/2 mouse header, yet 86Box allows to select the PS/2 mouse.
Checklist
=========
References
==========
https://www.ultimateretro.net/en/motherboards/2741
> Remove the PS/2 mouse flag from the Gigabyte GA-586IP

- src/config.c
- src/include/86box/video.h
- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
qt: Remember maximized state of monitor windows if enabled
This is rolled into the same "Remember size and position" toggle.
Checklist
=========
References
==========
None,
> qt: Remember maximized state of monitor windows if enabled

- src/network/CMakeLists.txt
Summary
=======
network: always link to ws2_32 on win32
Checklist
=========
References
==========
> network: always link to ws2_32 on win32

- src/include/86box/network.h
- src/network/net_pcap.c
- src/network/network.c
Summary
=======
This fixes a crash when the host has a lot of network interfaces
Checklist
=========
References
==========
> pcap: do bounds checking in net_pcap_prepare

- src/machine/machine_table.c
Summary
=======
Correct the BCM GT694VA, it's a Slot 1 board, not a Socket 370 board, and according to the manual (and testing the BIOS), supports a minimum of 8MB, installed, as opposed to 16MB.
Checklist
=========
References
==========
None
> Correct BCM GT694VA

- src/qt/qt_settingsnetwork.cpp
Summary
=======
qt: fix duplicate entries in network settings
Checklist
=========
References
==========
> qt: fix duplicate entries in network settings

- src/include/86box/network.h
- src/network/net_slirp.c
- src/network/network.c
Summary
=======
slirp: fix port forwarding and handle configuration with multiple nics
The forwarding configuration should now be set under the category [SLiRP Port Forwarding #1] for the first nic, etc..
Checklist
=========
References
==========
> slirp: fix port forwarding and handle configuration with multiple nics

- src/include/86box/vid_voodoo_codegen_x86-64.h
- src/include/86box/vid_voodoo_codegen_x86.h
Summary
=======
voodoo_codegen_x86*: Remove bounds checking for block_pos
Block sizes are sufficiently large enough to ensure no buffer overrun as block_pos is initialized to 0 every time a block is generated. It should cause a good Voodoo performance increase on x86 and x86-64 when the recompiler of it is enabled.
Checklist
=========
References
==========
None.
> voodoo_codegen_x86*: Remove bounds checking for block_pos

- src/printer/prt_escp.c
- src/qt/CMakeLists.txt
Summary
=======
Dynamic loading of bundled libraries appears to have been broken for a while. This affects anything that is loaded through `dynld_module()` (ultimately handled by `QLibrary` on this version). 
The libraries were bundled appropriately, however the executable didn't know where to look for them. This is normally handled with `RPATH` but that was being stripped off by cmake during the install section.
This PR adds an additional step during the install process to add `@executable_path/../Frameworks/` as an `RPATH` to the final binary.
This also fixes the freetype library name to `libfreetype.6.dylib` on macOS as well. It was trying to load the wrong name, but without this fix it still would not have worked even with the correct name.
This should also fix the discord integration …
> macOS: Fix dynamic loading of bundled libraries

- src/config.c
- src/include/86box/86box.h
- src/include/86box/cdrom.h
- src/qt/CMakeLists.txt
- src/qt/qt_mediahistorymanager.cpp
- src/qt/qt_mediahistorymanager.hpp
- src/qt/qt_mediamenu.cpp
- src/qt/qt_mediamenu.hpp
- src/qt/qt_platform.cpp
Summary
=======
This PR implements a new media history manager on the UI side and associated storage on the emu side for persistence. Up to 4 recent images are stored in this list.
I created a new class for this because I wanted to make it generic / robust enough to apply to any of the supported media types in 86Box. While it may look a bit complicated, I discovered there are a lot of sharp edges and corner cases when it comes to implementing something as seemingly simple as media history. This is further complicated by the different types of media, multiple devices, etc. that are supported in 86Box. I found it was easier to put all of this into a class rather than hard-coding a mess into the existing media menu structure.
Right now, however, only optical is currently implemented. The …
> Implement media history manager and recently used images

- CMakeLists.txt
- src/CMakeLists.txt
- src/qt/CMakeLists.txt
Summary
=======
This PR adds the ability to enable Vulkan support on macOS via MoltenVK.
* MoltenVK headers and library. Can be installed with `brew install molten-vk`. Cmake will automatically search the necessary homebrew paths for headers and standard library path for the library. If the headers are in a different location it can be specified with `-DMOLTENVK_INCLUDE_DIR`.
* Vulkan-enabled QT. If you wish to use this, you must first build QT with vulkan support (via MoltenVK) and have it available locally. You'll also need to adjust `Qt5_DIR` and other associated variables to point to that specific QT.
To enable, build with `-DMOLTENVK`. The default is off.
The installation process was also updated to create a symlink (`libVulkan.dylib` -> `libMoltenVK.dylib`) in the installation …
> macOS: Add Vulkan support via MoltenVK

- src/qt/qt_mediahistorymanager.cpp
Summary
=======
Needed to make one line a little more explicit to make vcpkg builds happy.
Checklist
=========
N/A
References
==========
N/A
> Media history: small adjustment for vcpkg builds

- src/qt/qt_hardwarerenderer.cpp
- src/qt/qt_hardwarerenderer.hpp
Summary
=======
qt_hardwarerenderer: Don't update the entire texture on blits
Improves performance by a lot (especially in the intro of Jazz Jackrabbit 1).
Checklist
=========
References
==========
None.
> qt_hardwarerenderer: Don't update the entire texture on blits

- src/qt/qt_hardwarerenderer.cpp
Summary
=======
qt_hardwarerenderer: Don't blit black, hidden portions of images
Checklist
=========
References
==========
None.
> qt_hardwarerenderer: Don't blit black, hidden portions of images

- src/include/86box/win.h
- src/network/net_slirp.c
- src/qt/win_joystick_rawinput.c
- src/win/win_joystick_rawinput.c
Summary
=======
Clang 14 does not like defining new variables in a switch label, which errors with:
```
D:\msys64\clang64\bin\cc.exe -DCMAKE -DUSE_DYNAREC -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS -ID:/msys64/clang64/include/freetype2 -ID:/msys64/clang64/include/SDL2 -ID:/86Box/build/src/include -ID:/86Box/src/include -ID:/86Box/src/cpu -ID:/86Box/src/codegen -std=gnu11 -MD -MT src/network/CMakeFiles/net.dir/net_slirp.c.obj -MF src\network\CMakeFiles\net.dir\net_slirp.c.obj.d -o src/network/CMakeFiles/net.dir/net_slirp.c.obj -c D:/86Box/src/network/net_slirp.c
D:/86Box/src/network/net_slirp.c:333:21: error: expected expression
int packets = network_tx_popv(slirp->card, slirp->pkt_tx_v, …
```
> Build fixes on Clang

- src/qt/qt_main.cpp
Summary
=======
The discord timer in `qt_main` seems to be running at full speed (timeout of zero) when the library is loaded, eating up the main qt thread. This PR changes it to an appropriate interval of one second.
The performance penalty happens even if discord is disabled. The whole section should probably be cleaned up, but this at should at least address the immediate performance problem. All qt platforms that have the discord library loaded are likely affected by this.
Checklist
=========
References
==========
N/A
> qt: Fix discord update timer to run at one second interval

- src/qt/qt_hardwarerenderer.cpp
Summary
=======
qt_hardwarerenderer: Use setData on Qt 5.14 and later
Checklist
=========
References
==========
None.
> qt_hardwarerenderer: Use setData on Qt 5.14 and later

- src/qt/qt_mediahistorymanager.cpp
Summary
=======
There is a potential null pointer access if the image history doesn't yet exist, as in the first run of a new system. The main pointer (already checked) is valid but the first pointer in the array will not be. This adds a check.
Checklist
=========
References
==========
N/A
> qt: Fix potential null pointer access in media history

- src/qt/qt_progsettings.cpp
Summary
=======
The existing code essentially hardcodes the icons path to `exe_path/roms`. Therefore the icon packs will only display in settings *if* the roms dir is in the same dir as the executable. With any other configuration (such as roms installed to global dir) the icon packs won't display.
This PR changes it to walk `rom_paths` and search each directory for `icons/` to find packs. Tested on mac, windows, linux and makes the icons appear for me in preferences.
Checklist
=========
References
==========
N/A
> qt: Fix searching for icon packs in roms dir

- src/video/vid_xga.c
Summary
=======
This fixes intermittent hangs on the XGA-2 end (MCA only, ISA version is intact).
Also includes indenting fixes.
Checklist
=========
References
==========
> XGA: Revert to the rom_init routine to load the XGA-1/XGA-2 bios

- src/config.c
Summary
=======
Fixes a missed spot when refactoring out the INI parser that can cause segfaults when saving the monitor config sections that store window dimensions and coordinates.
Checklist
=========
> Fix a crash when saving window dimensions and coordinates

- src/config.c
- src/floppy/fdd.c
- src/include/86box/fdd.h
- src/qt/qt_mediahistorymanager.cpp
- src/qt/qt_mediahistorymanager.hpp
- src/qt/qt_mediamenu.cpp
- src/qt/qt_mediamenu.hpp
- src/qt/qt_platform.cpp
Summary
=======
This is a continuation of #2656. In the first PR only CD-ROM support was initially added to media history. This one adds the same support for floppy images.
Just about everything applies from the original PR, except floppy instead of CD. Some variable names differ due to the different subsystem of floppy vs. cd, but the same form of serialization / deserialization, persistence in the config file, etc. all apply here. A lot of the groundwork for supporting other media types was already put in with the previous PR.
In the original PR I had to update in `plat_fopen64()` in `qt_platform.cpp` in order to have mac and linux properly support relative paths. More specifically: paths relative to `usr_path`. 
In this PR I had to do the same but for `plat_fopen()` instead. The exact …
> qt: Media history part II: Floppy

- src/qt/qt_platform.cpp
Summary
=======
In #2703 I had to update `plat_fopen()` to allow relative paths for mac and linux. It doesn't, however, account for blank / null paths. 
Apparently floppy and cassette drives blindly load image paths, including null ones (because they aren't set in the config). This wasn't a problem before, but the new logic was still appending the `usr_path` to the blanks paths because apparently blank / null paths evaluate to relative paths. Ultimately it was causing it to try and load a directory.
The blind loading of null images should probably also be fixed in a separate PR, but this one will at least account for blank / null paths using the new `plat_fopen()` logic and fix the immediate issue. I also updated the `plat_fopen64()` as well.
Thanks to @telanus for helping me locate the …
> qt: Account for empty path in plat_fopen

- src/disk/hdd.c
- src/include/86box/hdd.h
Summary
=======
Cast from `char*` to `QVariant` was removed in Qt 6.4 and caused builds to fail. Fix by using `const char*` instead.
Checklist
=========
References
==========
> Fix Qt 6.4 builds

- src/qt/qt_mainwindow.cpp
Summary
=======
The main toolbar pause button always displays the pause icon, even when the system is paused. When paused, the button goes into the checked state (but remains a pause icon).
This PR changes it to:
* Switch back and forth between play and pause icon depending on pause / run state
* Update the tooltip based on the current state
* Make the pause action button uncheckable so it will never appear checked or recessed (previous behavior, not necessary with the icon change)
Checklist
=========
References
==========
N/A
> qt: Fix play / pause icon to reflect current state

- src/cpu/codegen_timing_p6.c
Summary
=======
Hopefully fix Windows Protection Errors in Windows 95 and 98 First Edition on faster-clocked Intel P6-architecture CPUs.
Checklist
=========
References
==========
[https://archive.org/details/bitsavers_intelpentimIIIntelArchitecureOptimization1999_1886592](url)
> Fix 95/98FE protection errors on emulated P6

- src/cdrom/cdrom_image_backend.c
- src/include/86box/plat_dir.h
Summary
=======
The code was relying on `fopen()` to return null when a directory is opened in order to take the correct path for viso support. But since opening a directory is undefined (unless requesting write perms), it succeeds on mac / linux. This updates `bin_init()` to `stat()` the requested file / dir and follow the appropriate path for viso to work.
There were also some issues with the POSIX re-implementation of various `dir.h` structures that are used on windows. I updated `plat_dir.h` to use `sys/dir.h` on mac and linux because the structures returned by those platforms did not line up with the existing re-implementations. 
As far as I can tell, with this fix VISO works now on all platforms. Tested on windows (msys2), mac, linux. 
cc @richardg867 for review
Edit: Note that the …
> VISO fixes for mac / linux

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Adding Pravetz-16 (IMKO-4), an IBM PC/XT compatible made in Bulgaria in the 80s that featured Intel 8088 at 4.77 MHz.
Checklist
=========
References
==========
https://www.old-computers.com/museum/computer.asp?st=2&c=615
https://www.sandacite.com/forum/index.php?topic=10864.0
https://paskov.vmsoft-bg.com/tag/pravetz-16/
https://sandacite.com/biblio/files/original/8/132/_%D0%BA%D0%BE%D0%BC%D0%BF%D1%8E%D1%82%D1%8A%D1%80_%D0%9F%D1%80%D0%B0%D0%B2%D0%B5%D1%86-16,_%D0%BF%D0%B0%D1%81%D0%BF%D0%BE%D1%80%D1%82,_%D0%98%D0%A2%D0%9A%D0%A0_%D0%91%D0%90%D0%9D,_1982_[2].pdf
> Pravetz-16 / IMKO-4

- src/86box.c
Summary
=======
Global "AT" is not there since commit bc90f993503f ('Finally got rid of the AT and PCI global variables.').
Checklist
=========
> Fix build with -DENABLE_PC_LOG=1

- src/disk/hdc.c
- src/disk/hdc_st506_xt.c
- src/include/86box/hdc.h
Summary
=======
This emulates a JVC-branded controller/drive pair, using RLL encoding, connected via a small connector electrically compatible with ST-506.
The controller is ST-506 compatible with an extra command for self-power-off. The option ROM is made by SMS. Commented disassembly is available for study [1].
The disk is a 3.5" 20MiB "made by Victor", labeled JD3824T100 on the outer protective casing, JD3824T00-1 on the actual drive. It's 615/2/34 physically, pretends to be a 614/4/17 so that it's type 3 compatible.
Checklist
=========
References
==========
[1] https://archive.org/details/v86p-hd
> Add a Victor V86P disk driver

- src/include/86box/machine.h
- src/include/86box/nvr.h
- src/machine/CMakeLists.txt
- src/machine/m_elt.c
- src/machine/machine_table.c
- src/nvr_at.c
- src/win/Makefile.mingw
Summary
=======
This is a portable computer based around NEC V30 processor and what
seems to be a proprietary Epson chip set.
The chip set provides a XT-class keyboard controller/PPI, controller for
two DD floppy drives, CGA-compatible video, one serial and one parallel
port. There's no datasheet for the chip set.
The machine has a 640x200 monochromatic LCD display, optionally backlit
and an external CRT connector. There can be up to two floppy drives,
one of them optionally connected to an external connector (shared with
the parallel port). There are physical switches to enable the external
CRT and floppy connectors.
There's a battery-backed RTC/NVRAM that holds configuration, including
backlight timeout, UART configuration and floppy types.
The machine has two expansion slots, half the …
> Add the Epson Equity LT Machine

- src/qt/qt_mediamenu.cpp
Summary
=======
This adds icons to the media history menu to help distinguish image files from VISO directories. 
The disc icon from the currently selected icon set is used. Because there is no folder icon, the qt stock icon is used in that case (`QStyle::SP_DirIcon`) which should match the style of the OS in use. When / if a dedicated folder icon is added to the project, it could be easily swapped in to replace the stock icon.
The same applies to mute where stock is also used (`QStyle::SP_MediaVolumeMuted`). There is a volume icon in the existing set, but not one for mute.
Checklist
=========
References
==========
N/A
> qt: Add icons to the optical media menu

- src/qt/qt_mediamenu.cpp
Summary
=======
Fixes a deprecated overload in qt 6.4.
Checklist
=========
References
==========
N/A
> qt: Fix qt6 compile

- src/qt/qt_ui.cpp
Summary
=======
This reverts commit 6ac2faf2f87544e42043c8536a52b14b94909780.
Breaks fullscreen scaling.
Checklist
=========
References
==========
None.
> Revert "qt: Always resize"

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Shortcut fixes
* Make Pause key pause/resume the emulator when both Alts are held, passthrough to emulated machine otherwise.
* Make screenshot taking and C+A+D shortcuts work on fullscreen
Checklist
=========
References
==========
None.
> qt: Shortcut fixes

- src/floppy/fdc.c
- src/include/86box/fdc.h
Summary
=======
Adds secondary XT and AT fdc types, along with fdc_none for future use
Checklist
=========
References
==========
None
>  Add secondary XT and AT fdc types, also a none type

- src/machine/m_at_286_386sx.c
Summary
=======
Simplify and reuse code in m_at_286_386sx.c, makes the code flow a little bit easier to follow
Checklist
=========
References
==========
None
> Simplify and reuse code in m_at_286_386sx.c

- src/qt/qt_settingsfloppycdrom.cpp
- src/qt/qt_settingsfloppycdrom.hpp
- src/qt/qt_settingsfloppycdrom.ui
Summary
=======
qt: Add earlier drive checkbox in CD-ROM settings
Checklist
=========
References
==========
None.
> qt: Add earlier drive checkbox in CD-ROM settings

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_platform.cpp
Summary
=======
This moves the ui pause button updates into `plat_pause`. A new function had to be added in `qt_mainwindow.cpp` to actually place the logic and updates due to `MainWindow:ui` being private.
This allows it to catch all `plat_pause` calls instead of just ones triggered from ui actions.
Checklist
=========
References
==========
N/A
> qt: Update ui pause state in plat_pause

- src/machine/machine_table.c
Summary
=======
Set an NVR of 16 bytes. Fixes save date/time on Olivetti M24 restart.
> Fix NVR size for Olivetti M24

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_platform.cpp
Summary
=======
Hopefully this is the last one on the pause icon.
In #2758 I moved pause icon updates into `plat_pause`. However, `plat_pause` can be called from non-UI threads. Because of that I moved the update function to a slot, to be called from `plat_pause`. This is because in general UIs shouldn't be updated from a non-UI thread.
Checklist
=========
References
==========
#2758
> qt: Rework ui pause update into a slot

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Add missing Windows/Menu key X11-to-Set1 mappings
Checklist
=========
References
==========
None.
> qt: Add missing Windows/Menu key X11-to-Set1 mappings

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: force the screen output widget to be resizable
Checklist
=========
References
==========
None.
> qt: force the screen output widget to be resizable

- src/cpu/x86_ops_flag.h
- src/mem/mem.c
Summary
=======
Fixes CPU-Z detection on IBM 486 by restoring 486 behavior to EFLAGS without breaking NT 3.1
Checklist
=========
References
==========
CPU-Z Vintage Edition CPU detection.
> Fix CPU-Z on IBM 486

- src/disk/hdc_st506_xt.c
Summary
=======
Adds BIOSless version of the WD1002-WX1 primarily for use with the Olivetti M24
Also fixes a few related mistakes and cleans up even more magic number usage
Checklist
=========
References
==========
None
> Adds BIOSless version of the WD1002A-WX1 primarily for use with the Olivetti M24

- src/qt/qt_hardwarerenderer.hpp
Summary
=======
qt: force update to happen after hardware renderer is created
Checklist
=========
References
==========
None.
> qt: force update to happen after hardware renderer is created

- src/qt/qt_hardwarerenderer.cpp
Summary
=======
qt: display at initialization time (update() call doesn't work there)
Checklist
=========
References
==========
None.
> qt: display at initialization time (update() call doesn't work there)

- src/video/vid_voodoo_banshee.c
Summary
=======
voodoo: Fix misleading pixel format error message
Checklist
=========
References
==========
None.
> voodoo: Fix misleading pixel format error message

- .github/workflows/c-cpp.yml
Summary
=======
Modernize MSYS2 Makefile build so it uses similar names to the cmake build and actually produces artifacts too.
Checklist
=========
References
==========
None
> Modernize MSYS2 Makefile build

- src/machine/m_xt.c
- src/video/vid_cga.c
Summary
=======
Change of Pravetz-16 BIOS filenames to include the addresses. 
Renamed the CGA BIOS file as well to include VDC-2 info.
Checklist
=========
References
==========
The naming matches the starting memory address as depicted here:
https://www.sandacite.com/forum/index.php?action=dlattach;topic=2702.0;attach=133236;image
> Pravetz-16 proper naming of BIOS files

- src/include/86box/vid_voodoo_common.h
Summary
=======
vid_voodoo_common: All volatile variables are now atomic
AArch32 and AArch64 has far lesser atomicity guarantees for simple load-store accesses unlike x86/x64. This should take care of the majority, if not all, of Voodoo crashes on Apple Silicon systems.
Checklist
=========
References
==========
None.
> vid_voodoo_common: All volatile variables are now atomic

- src/qt/qt_mediamenu.cpp
Summary
=======
The media history menu is updated on certain events such as mount and unmount. During that time, files or directories that no longer exist will be removed from the menu. 
However, if a directory or file is removed prior to that event, they will still be temporarily displayed in the menu. This PR will remove (hide) them from the menu until they can be properly processed in the next event.
Checklist
=========
N/A
References
==========
N/A
> qt: Do not display removed viso directories in media history

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.ui
Summary
=======
qt: Match toolbar background with Win32 backend
Checklist
=========
References
==========
None.
> qt: Match toolbar background with Win32 backend

- src/video/vid_voodoo_fifo.c
Summary
=======
voodoo: CMDFIFO type 2 is available starting with Voodoo 2
Checklist
=========
References
==========
http://vgamuseum.info/images/doc/3dfx/voodoo2.pdf
> voodoo: CMDFIFO type 2 is available starting with Voodoo 2

- src/disk/hdd_image.c
Summary
=======
hdd_image: Try to reopen existing disk image next time
Checklist
=========
References
==========
None.
> hdd_image: Try to reopen existing disk image next time

- src/video/vid_voodoo_fifo.c
Summary
=======
voodoo: Account for padding words in CMDFIFO3
Checklist
=========
References
==========
None.
> voodoo: Account for padding words in CMDFIFO3

- src/config.c
- src/qt/qt_harddiskdialog.cpp
Summary
=======
When creating a new hdd image in qt, there were a few issues:
* If the image to be created was greater than a certain size, bit 32 and above would get lopped off resulting in the wrong size created.
* Once an image with > 16 heads was written to config, the image config would be changed and head count clamped to 16.
* If you type in an image file (as opposed to using the file picker) in the new HD image dialog, the resulting file would get placed in `$CWD` instead of `usr_path`. The image file would be created, but in the wrong location. As soon as the settings were confirmed the image file would then be created in `usr_path` resulting in two image files.
To fix:
* The image size logic was happening as a 32-bit unsigned int due to `toUInt()` grabbing the calculated number. …
> qt: Fix multiple issues with hdd image creation

- src/config.c
Summary
=======
config: Cap memory size to maximum allowed by machine
Checklist
=========
References
==========
None.
> config: Cap memory size to maximum allowed by machine

- src/qt/qt_harddiskdialog.cpp
Summary
=======
This is a follow-up to #2859. The fix did work, but the updated (full path) filename also needs to be manually updated in the ui field. Without it, there would be an error after saving the settings (though it would work fine after the error). This fix updates the ui field.
Checklist
=========
References
==========
#2859
> qt: New hdd image creation path

- src/video/vid_s3.c
- src/video/vid_tgui9440.c
Summary
=======
S3 (all): Fixes to the commonly used accel commands (0, 1, 2, 6, 7) to make the OS/2 software cursor to not bug on the left edge of the screen.
TGUI: Reworked the non-bitblt commands as well as the accel pitch and bpp modes.
Checklist
=========
References
==========
> S3 80x: added 0xe2e8/0xe2e9 ports in MMIO mode, fixes garbled fonts when using MMIO in those chips.

- src/video/vid_voodoo_banshee.c
Summary
=======
banshee: Implement cmdBaseSize0 readback
Checklist
=========
References
==========
None.
> banshee: Implement cmdBaseSize0 readback

- src/sound/snd_opl_ymfm.cpp
- src/sound/snd_optimc.c
Summary
=======
Fixes the following warnings:
```
src/sound/snd_optimc.c:134:1: warning: 'optimc_reload_opl' defined but not used [-Wunused-function]
134 | optimc_reload_opl(optimc_t *optimc)
| ^~~~~~~~~~~~~~~~~
```
```
src/sound/snd_opl_ymfm.cpp: In instantiation of 'YMFMChip<ChipType>::YMFMChip(uint32_t, fm_type, uint32_t) [with ChipType = ymfm::ym3812; uint32_t = unsigned int]':
src/sound/snd_opl_ymfm.cpp:288:87:   required from here
src/sound/snd_opl_ymfm.cpp:243:13: warning: 'YMFMChip<ymfm::ym3812>::m_samplecnt' will be initialized after [-Wreorder]
243 |     int32_t m_samplecnt;
|             ^~~~~~~~~~~
src/sound/snd_opl_ymfm.cpp:236:36: warning:   'uint32_t YMFMChip<ymfm::ym3812>::m_samplerate' [-Wreorder]
236 |     uint32_t                       m_samplerate;
| …
```
> snd_optimc, snd_opl_ymfm: Fix warnings

- src/include/86box/snd_ad1848.h
- src/include/86box/snd_sb.h
- src/sound/snd_ad1848.c
- src/sound/snd_optimc.c
- src/sound/snd_sb.c
Summary
=======
OPTiMC: Fix OPL volume mixing
Windows driver operates the chip in WSS mode so AUX2 volume filtering for OPL playback is required
Checklist
=========
References
==========
None.
> OPTiMC: Fix OPL volume mixing

- src/sound/snd_optimc.c
Summary
=======
OPTiMC: Don't factor in the SB mixer OPL volumes
Checklist
=========
References
==========
None.
> OPTiMC: Don't factor in the SB mixer OPL volumes

- src/sound/snd_optimc.c
Summary
=======
OPTiMC: MC6 register is readable, despite what the datasheet says
Checklist
=========
References
==========
None.
> OPTiMC: MC6 register is readable, despite what the datasheet says

- src/sound/snd_ad1848.c
Summary
=======
AD1848: Writes to register 27 are rejected on Crystal codecs
Checklist
=========
References
==========
None.
> AD1848: Writes to register 27 are rejected on Crystal

- src/sound/snd_optimc.c
Summary
=======
OPTiMC: Gameport remains enabled at startup
Checklist
=========
References
==========
None.
> OPTiMC: Gameport remains enabled at startup

- src/cpu/cpu.c
Summary
=======
Do not set a member that doesn't exist on platforms without dynarec support. Currently it fails to build with
````
/builddir/build/BUILD/86Box-3.11/src/cpu/cpu.c: In function 'cpu_set':
/builddir/build/BUILD/86Box-3.11/src/cpu/cpu.c:1173:17: error: 'x86_dynarec_opcodes_3DNOW' undeclared (first use in this function); did you mean 'x86_opcodes_3DNOW'?
1173 |                 x86_dynarec_opcodes_3DNOW = dynarec_ops_3DNOWE;
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~
|                 x86_opcodes_3DNOW
/builddir/build/BUILD/86Box-3.11/src/cpu/cpu.c:1173:17: note: each undeclared identifier is reported only once for each function it appears in
builddir/build/BUILD/86Box-3.11/src/cpu/cpu.c:1173:45: error: 'dynarec_ops_3DNOWE' undeclared (first use in this function)
1173 | …
```
> fix build for non-dynarec platforms

- src/disk/hdc_ide.c
Summary
=======
Fixes Solaris 2.6 CD installation on ide/atapi.
Checklist
=========
References
==========
> IDE/ATAPI: Don't overwrite data in packet writes during Phase Data In.

- src/cpu/cpu.c
- src/cpu/cpu.h
- src/cpu/x86_ops_mov_ctrl.h
Summary
=======
Title.
Should fix certain operating systems expecting it to be present and refusing to boot.
Code ported from PCBox.
Checklist
=========
> Add the CR4 Page Global Enable bit support to Pentium Pro and Pentium II CPUs

- src/qt/qt_newfloppydialog.cpp
Summary
=======
On macOS the new file dialog was forcing the use of the `.mdi` suffix on files for MO disks (and likely all removable types). This PR updates the filter to allow one to specify `.img` files for the suffix on all of the removable drive types where supported (currently: floppy, zip, mo).
There was another issue where the newly-created image would appear in the incorrect place when manually typing in the filename to be used (similar to #2859 and #2868 it would just dump into `$CWD`). This PR also applies the same fix for the removable image types.
Checklist
=========
References
==========
#2859 and #2868
> qt: Fixes for removable image files

- src/machine/m_ps2_mca.c
Summary
=======
Looks like the model 50 bios expects the 50 POS id and given the 60 shares its stuff with 50 (being a larger 8-slot version of the 50), I believe the id is identical then until a I find a proper 60-specific bios.
Checklist
=========
References
==========
> Corrected (more or less) the IBM PS/2 model 60 POS ID

- src/cdrom/cdrom.c
- src/include/86box/cdrom.h
- src/scsi/scsi_cdrom.c
Summary
=======
SCSI/CD-ROM fixes: Properly implemented the Toshiba specific SCSI commands including the Audio side per the Toshiba CD-ROM SCSI-2 manual from 1990 (they were previously implemented with some hacks). These were required for proper Audio handling in OS/2 and other stuff.
Checklist
=========
References
==========
[_Provide links to datasheets or other documentation that helped you implement this pull request._](http://bitsavers.informatik.uni-stuttgart.de/pdf/toshiba/cdrom/Toshiba_CD-ROM_SCSI-2_Interface_Specifications_Version_5.0_Sep90.pdf)
> SCSI/CD-ROM fixes: Properly implemented the Toshiba specific SCSI commands

- src/video/vid_s3.c
Summary
=======
S3: Don't allow 16-bit I/O pixtrans blitting on the first port of the 8-bit I/O handling (e2e8 write), fixes fonts on Unix flavors where affected.
Checklist
=========
References
==========
> S3: Don't allow 16-bit I/O pixtrans blitting on the first 8-bit I/O write port of pixtrans (non-MMIO).

- src/qt/qt_machinestatus.cpp
- src/qt/qt_machinestatus.hpp
- src/qt/qt_mainwindow.cpp
Summary
=======
Disabling status bar icons activity was left unimplemented on qt. Prevent refreshing the icons and clear their activity status on setting change.
Checklist
=========
References
==========
> qt: Fix status bar icons ignoring update activity setting

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/m_at_socket370.c
- src/nvr_at.c
Summary
=======
Restores a removed case in nvr_at.c, the absence of which made the BCM GT694VA and ASUS CUV4X-LS hang at POST C1 C0.
Also moves the GT694VA code to the proper file.
Checklist
=========
> nvr_at: Re-add a forgotten check for VIA NVR

- src/sound/snd_optimc.c
Summary
=======
Solves the issue of the power-on IRQ being 7 instead of 5, and removes the unused NVR reference (these cards don't have an EEPROM on board), as well as using the correct WSS IRQ ranges, amongst other things.
Checklist
=========
References
==========
https://www.philscomputerlab.com/82c929a.html
https://www.philscomputerlab.com/uploads/3/7/2/3/37231621/optcs00036-1.pdf
https://www.philscomputerlab.com/uploads/3/7/2/3/37231621/82c929_mad16_pro.pdf
> Minor changes to OPTi 82C929A emulation

- src/device/isartc.c
Summary
=======
Time sync now works correctly with Vendex RTC.
Checklist
=========
References
==========
None.
> Time sync now works correctly with Vendex RTC

- src/floppy/CMakeLists.txt
- src/floppy/fdc.c
- src/floppy/fdc_monster.c
- src/win/Makefile.mingw
Summary
=======
Initial Monster FDC support
* No flash memory yet
* Secondary FDC not yet enabled
Checklist
=========
References
==========
> Initial Monster FDC support

- src/disk/hdc.c
- src/disk/hdc_xtide.c
- src/include/86box/hdc.h
Summary
=======
Adds a new "XT+" version of the XTIDE Universal BIOS for V20/V30/186/188 compatible CPUs.
Note that booting from hard drives will fail due to #2939. Other functions work fine.
Checklist
=========
> Add a version of the XTIDE Universal BIOS for V20/V30 CPUs

- src/video/vid_cl54xx.c
Summary
=======
cl54xx: clear only FLAG_EXT_WRITE and FLAG_ADDR_BY16
Checklist
=========
References
==========
None.
> cl54xx: clear only FLAG_EXT_WRITE and FLAG_ADDR_BY16

- src/qt/qt_mcadevicelist.cpp
Summary
=======
qt_mcadevicelist: device IDs are always 4 hex digits long
Checklist
=========
References
==========
None.
> qt_mcadevicelist: device IDs are always 4 hex digits long

- CMakeLists.txt
Summary
=======
RTMidi support is now available on Haiku
Checklist
=========
References
==========
None.
> RTMidi support is now available on Haiku

- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.hpp
Summary
=======
qt_settingsdisplay: Changes are not lost on machine switch anymore
Checklist
=========
References
==========
None.
> qt_settingsdisplay: Changes are not lost on machine switch anymore

- bumpversion.sh
Summary
=======
Submitting a simple two liner patch to bumpversion.sh to make it update the version and date on the debian changelog.
Checklist
=========
References
==========
N/A
> Bumpversion.sh updated to support Debian changelog

- src/qt/qt_mainwindow.cpp
Summary
=======
qt: Display architecture information in About box
Checklist
=========
References
==========
None.
> qt: Display architecture information in About box

- src/cpu/cpu.c
Summary
=======
Add Slot1 to Socket 8 slotket
One such example is the ASUS C-P6S1
Checklist
=========
References
==========
https://www.cpushack.com/2020/09/09/finding-the-limits-of-the-socket-8/
https://arstechnica.com/civis/threads/looking-for-a-socket-8-to-slot-1-converter-riser-card-asus-c-p6s1.1118291/
> Add Slot1 to Socket 8 slotket

- src/sound/snd_optimc.c
Summary
=======
snd_optimc: IRQs of 12, 14 and 15 are actually used
Checklist
=========
References
==========
None.
> snd_optimc: IRQs of 12, 14 and 15 are actually used

- src/machine/machine_table.c
Summary
=======
Fixed the QDI EXCELLENT II (Slot 1, i440EX) to have an AGP slot, as the actual board itself also has one [as can be seen in it's user manual](https://www.manualslib.com/manual/2297520/Qdi-P6i440ex-Matx-Excellent-Ii.html?page=23).
Checklist
=========
References
==========
https://www.manualslib.com/manual/2297520/Qdi-P6i440ex-Matx-Excellent-Ii.html?page=23
https://www.osta.ee/en/legend-qdi-p61440exmatx-excellent-ii-celeron-300a-143346542.html
> Fix QDI EXCELLENT II to have an AGP slot as it's supposed to.

- src/video/vid_mga.c
Summary
=======
vid_mga: Fix Matrox Mystique MGA modes
Clock selection now works properly
Checklist
=========
References
==========
None.
> vid_mga: Fix Matrox Mystique MGA modes

- src/include/86box/language.h
- src/qt/qt_mainwindow.cpp
- src/win/languages/cs-CZ.rc
- src/win/languages/de-DE.rc
- src/win/languages/en-GB.rc
- src/win/languages/en-US.rc
- src/win/languages/es-ES.rc
- src/win/languages/fi-FI.rc
- src/win/languages/fr-FR.rc
- src/win/languages/hr-HR.rc
- src/win/languages/hu-HU.rc
- src/win/languages/it-IT.rc
- src/win/languages/ja-JP.rc
- src/win/languages/ko-KR.rc
- src/win/languages/pl-PL.rc
- src/win/languages/pt-BR.rc
- src/win/languages/pt-PT.rc
- src/win/languages/ru-RU.rc
- src/win/languages/sl-SI.rc
- src/win/languages/tr-TR.rc
- src/win/languages/uk-UA.rc
- src/win/languages/zh-CN.rc
- src/win/languages/zh-TW.rc
- src/win/win_about.c
Summary
=======
Adds information on what dynarec 86Box was compiled with (old, new or none) in the About box.
Done for both Qt and Win32 UIs; for the latter, architecture info was added as well.
Checklist
=========
> Display dynarec information in the About box

- src/machine/machine_table.c
Summary
=======
Added PS/2 mouse support for TriGem 486G (which I forgot to add) and bumped Gigabyte GA-586IP's RAM limit to 256MB (tested, works perfectly, although the user manual states a 768MB RAM limit)
Checklist
=========
References
==========
[TriGem 486G page on The Retro Web](https://theretroweb.com/motherboards/s/trigem-486gm)
[Gigabyte GA-586IP User Manual](https://theretroweb.com/motherboard/manual/5ip-9412-5f93528866e94941858988.pdf)
> Add PS/2 mouse support for TriGem 486G and bump Gigabyte GA-586IP's RAM limit to 256MB

- src/qt/qt_deviceconfig.cpp
Summary
=======
qt: Display device name separately in device configuration
Checklist
=========
References
==========
None.
> qt: Display device name separately in device configuration

- src/include/86box/machine.h
- src/machine/m_at_socket5.c
- src/machine/m_at_socket7_3v.c
- src/machine/machine_table.c
Summary
=======
Moved DataExpert EXP8551 and PC Partner MB500N (both previously listed as Socket 5) to Socket 7 (Single Voltage) in the machine list.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/dataexpert-exp8551
https://theretroweb.com/motherboards/s/pcpartner-mb500n-35-8212-32
> Move DataExpert EXP8551 and PC Partner MB500N from Socket 5 to Socket 7 (Single Voltage)

- src/include/86box/machine.h
- src/machine/m_at_socket5.c
- src/machine/machine_table.c
Summary
=======
Added Gemlight GMB-P54SPS (SiS 501, Socket 5)
NOTE: The Winbond W83769F IDE controller is not emulated yet, although a datasheet is available [here](https://pdf.datasheetcatalog.com/datasheet_pdf/winbond-electronics/W83769F.pdf).
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/gemlight-gmb-p54sps
> Add Gemlight GMB-P54SPS (SiS 501, Socket 5)

- src/qt/qt_settingssound.cpp
Summary
=======
QT: Fix crash in the first sound card selection.
Checklist
=========
References
==========
> QT: Fix crash in the first sound card selection.

- src/86box.c
- src/acpi.c
- src/include/86box/acpi.h
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
Summary
=======
qt: Reenable and make functional ACPI shutdown button
Checklist
=========
References
==========
None.
> qt: Reenable and make functional ACPI shutdown button

- src/qt/qt_filefield.cpp
- src/qt/qt_filefield.hpp
- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddiskdialog.hpp
Summary
=======
In settings -> hdd selection -> existing disk, when you type a filename *then* select specify, you'll get an error about the file not existing. Sometimes the dialog will still appear for selection, but this seems to vary a little by OS.
The message is mainly because once the file entry loses focus (`editingFinished` signal) it's connected to `fileSelected` which then connects to `onExistingFileSelected`. The file *does* need to be checked once selected and I believe that was the intent. However, the way the signals are wired up you can actually wind up with the check happening twice: once before selection and once after selection.
I tried to go for a minimal fix without too much impact to the existing logic (which could use some updating, really). I did this by allowing …
> qt: Fixes to the process for selecting an existing hdd image

- src/qt/qt_settingsfloppycdrom.ui
- src/qt/qt_settingsharddisks.ui
- src/qt/qt_settingsotherremovable.ui
Summary
=======
When viewing the hard drive listing in the settings view, you can double click some of the fields and edit them. This disables the editable aspect of those fields (they shouldn't be editable).
Edit: Added the same fix for floppy, cd-rom, and other devices after @lemondrops brought it to my attention.
Checklist
=========
References
==========
N/A
> qt: Various fields should not be editable in settings view

- CMakePresets.json
Summary
=======
Make CMakePresets.json better by sharing base configurations, lower versioning to minimum, and change some settings so VS Code puts output in a neater location.
Checklist
=========
References
==========
None.
> Make CMakePresets.json better

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
Summary
=======
Ability to build with CLANG and Regular builds
This is ofcourse disabled by default, and primarily to make my life easier on branches
Checklist
=========
References
==========
None.
> Ability to build with CLANG and Regular builds

- src/machine/machine_table.c
Summary
=======
Add APM flags to 386 & later, ACPI flag to Pentium and later
This isn't a perfect solution, but it'll be less false positives than elsewise.
Checklist
=========
References
==========
None
> Add APM flags to 386 & later, ACPI flag to Pentium and later

- src/device/mouse_ps2.c
Summary
=======
This commits adds support for the command 0xea - set stream for PS2 mice. I was messing with OpenServer, and PS2 mice is not detected before this patch.
Checklist
=========
References
==========
https://wiki.osdev.org/PS/2_Mouse
> add command 0xea - set stream mode

- src/qt/qt_deviceconfig.cpp
- src/win/win_serial_passthrough.c
Summary
=======
[qt: Fix serial ports enumeration on Windows](https://github.com/86Box/86Box/commit/ed6f7a6f8e3529b956992056d4d36f01682b0258)
[win_serial_passthrough: Don't error on 0-byte writes](https://github.com/86Box/86Box/commit/e6156022cfcabbe82d6b12c1c735633edcd249fa)
References
==========
None.
> Serial passthrough fixes on Windows

- src/config.c
- src/device/serial_passthrough.c
- src/include/86box/serial_passthrough.h
- src/qt/qt_deviceconfig.cpp
- src/win/win_devconf.c
- src/win/win_serial_passthrough.c
Summary
=======
serial_passthrough: Allow configuration of named pipe parameter
Windows-only.
Checklist
=========
References
==========
None.
> serial_passthrough: Allow configuration of named pipe parameter

- src/video/vid_tvp3026_ramdac.c
Summary
=======
vid_tvp3026_ramdac: Don't ignore CCR2 and CCR3 bits for Cursor RAM reads/writes.
Fixes hardware cursor under Windows 95 (and potentially others).
Checklist
=========
References
==========
None.
> vid_tvp3026_ramdac: Don't ignore CCR2 and CCR3 bits for Cursor RAM reads/writes.

- src/video/vid_mga.c
Summary
=======
vid_mga: Fix opaque pattern blits
Checklist
=========
References
==========
None.
> vid_mga: Fix opaque pattern blits

- src/machine/m_pcjr.c
Summary
=======
The PCjr Technical Reference says that all joystick inputs go through 0x201, and at least Imagic's Demon Attack seems to expect this. I've tested this and it does let the game work fine.
Checklist
=========
References
==========
[PCjr Technical Reference, p.2-119](http://bitsavers.org/pdf/ibm/pc/pc_jr/PCjr_Technical_Reference_Nov83.pdf#page=145)
> Make joysticks work with the PCjr

- src/qt/qt_settings.ui
- src/qt/qt_settingsdisplay.ui
- src/qt/qt_settingsnetwork.ui
Summary
=======
Network settings could get really wide with pcap and the host network interfaces having them all at a same row. Now they are aligned vertically and each network card have their own tab.
Display settings also had long strings in the combobox and putting it under the label gives it more room.
Checklist
=========
References
==========
Screenshots of the changes
==================
> Network & display settings layout tweaking

- src/machine/machine_table.c
Summary
=======
Fix accidental reversion from Socket 7 to socket 5 in two machines
Checklist
=========
References
==========
None
> Fix accidental reversion from Socket 7 to socket 5 in two machines

- src/qt/qt_winrawinputfilter.cpp
Summary
=======
qt: Poll for 4th and 5th mouse buttons on Windows
Checklist
=========
References
==========
None.
> qt: Poll for 4th and 5th mouse buttons on Windows

- src/include/86box/keyboard.h
- src/machine/m_xt_laserxt.c
Summary
=======
Fix a bug in the VTech Laser Turbo XT - we don't need to load it's and the XT's BIOS
Checklist
=========
References
==========
None
> Fix a bug in the VTech Laser Turbo XT

- src/include/86box/sound.h
- src/sound/midi_fluidsynth.c
- src/sound/midi_mt32.c
- src/sound/openal.c
- src/sound/snd_ac97_via.c
- src/sound/snd_audiopci.c
- src/sound/snd_emu8k.c
- src/sound/snd_opl_nuked.c
- src/sound/snd_opl_ymfm.cpp
- src/sound/snd_resid.cc
- src/sound/snd_sb.c
- src/sound/snd_sb_dsp.c
- src/sound/snd_sn76489.c
- src/sound/sound.c
- src/sound/xaudio2.c
Summary
=======
Magic numbers for sound freq changed to defines, initial work for frequency customization
Checklist
=========
References
==========
None
> Magic numbers for sound freq changed to defines

- src/device/mouse_wacom_tablet.c
Summary
=======
mouse_wacom_tablet: Resets now set the mode properly
Checklist
=========
References
==========
None.
> mouse_wacom_tablet: Resets now set the mode properly

- src/device/mouse_wacom_tablet.c
Summary
=======
mouse_wacom_tablet: Point mode is disabled when suppressed mode is enabled
Checklist
=========
References
==========
None.
> mouse_wacom_tablet: Point mode is disabled when suppressed mode is enabled

- src/vnc.c
Summary
=======
vnc: report absolute mouse coordinates
Checklist
=========
References
==========
None.
> vnc: report absolute mouse coordinates

- src/qt/qt_winrawinputfilter.cpp
- src/qt/qt_winrawinputfilter.hpp
Summary
=======
Raw input was processed only when main window is active. Now we have 2nd monitor window that can also be active. If the main window isn't active, non-primary monitor windows are checked for activity too and raw input processed for them also.
Checklist
=========
References
==========
> Accept raw input from non-primary monitor windows on Qt

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
Summary
=======
[Fix crashes when exiting emulator in multimonitor modes](https://github.com/86Box/86Box/commit/e650ec75052132bb811fdf164538d6182e8e8630)
[Absolute mouse input now works on secondary monitors](https://github.com/86Box/86Box/commit/7de41b383c2f0d4925b433fb7250aa8d7aebae80)
Checklist
=========
References
==========
None.
> qt: Multimonitor and absolute mouse input fixes

- src/video/vid_mga.c
- src/video/vid_table.c
- src/video/vid_tvp3026_ramdac.c
Summary
=======
vid_mga: Make Matrox Millennium multi-monitor compatible.
Tested working under Windows XP with AGP Voodoo 3 AmigaSport v3.0 drivers and built-in Matrox Millennium drivers. The latter is to be selected as primary in BIOS settings if feasible for Windows XP's multi-monitor to work properly.
Checklist
=========
References
==========
None.
> vid_mga: Make Matrox Millennium multi-monitor compatible

- src/include/86box/snd_mpu401.h
Summary
=======
mpu401: Extend MPU401_QUEUE to 1024 bytes.
Allows SysEx messages larger than 64 bytes to be received correctly.
Checklist
=========
References
==========
None.
> mpu401: Extend MPU401_QUEUE to 1024 bytes

- src/video/vid_voodoo_banshee.c
Summary
=======
vid_voodoo_banshee: Extend screen filter buffers to 2048 * 3 bytes.
Fixes crashes when screen filtering is enabled and AmigaSport V3.0 drivers for Windows XP are used.
Checklist
=========
References
==========
None.
> vid_voodoo_banshee: Extend screen filter buffers to 2048 * 3 bytes

- src/win/languages/cs-CZ.rc
- src/win/languages/de-DE.rc
- src/win/languages/en-GB.rc
- src/win/languages/en-US.rc
- src/win/languages/es-ES.rc
- src/win/languages/fi-FI.rc
- src/win/languages/fr-FR.rc
- src/win/languages/hr-HR.rc
- src/win/languages/hu-HU.rc
- src/win/languages/it-IT.rc
- src/win/languages/ja-JP.rc
- src/win/languages/ko-KR.rc
- src/win/languages/pl-PL.rc
- src/win/languages/pt-BR.rc
- src/win/languages/pt-PT.rc
- src/win/languages/ru-RU.rc
- src/win/languages/sl-SI.rc
- src/win/languages/tr-TR.rc
- src/win/languages/uk-UA.rc
- src/win/languages/zh-CN.rc
- src/win/languages/zh-TW.rc
- src/win/win_settings.c
Summary
=======
[Whitespace in win32 lang files (2/2)](https://github.com/86Box/86Box/commit/93a1f2d2f980b769bf1ced76307839e380b90387)
[Fix a compile warn in win_settings.c](https://github.com/86Box/86Box/commit/bfcc11c5126ce25f1ca65307eceb22a5890a23ba)
Checklist
=========
References
==========
None
>  Whitespace in win32 lang files (2/2)

- src/cpu/cpu.c
- src/cpu/cpu.h
Summary
=======
cpu_busspeed is now a double
Checklist
=========
References
==========
None.
> cpu_busspeed is now a double

- src/video/vid_et4000w32.c
Summary
=======
Mouse cursor shape is now alright by being forced to be 128x128 and if the cursor regs (0xe2 and 0xe6) have a non-0 value in the non-i chip (or if on 15/16bpp, forcing it to 128x128 anyway).
Also fixed are the blitter patterns in 8/15/16bpp modes by re-ordering (if it's the right term) the pixels of the Y pattern coordinates (code lines are from 1165 to 1183). And properly implemented X/Y Count control routing blitters, fixes anything that uses software Bresenham and/or polygon stuff.
Checklist
=========
References
==========
> ET4000w32/i (and non-i): More fixes, see below.

- src/include/86box/vid_ega.h
- src/video/vid_ega.c
- src/video/vid_ega_render.c
Summary
=======
This merges the 4 graphics renderers together (2bpp vs 4bpp x lowres vs highres) and the 2 text renderers together (40 wide vs 80 wide). This makes it easier to implement correct behaviour without having to do it in up to 6 different places.
This also contains a few bugfixes. These are:
- The CGA compatibility 2-bit-chunky rendering now actually factors in the upper 2 planes.
- The CRTC memory address is now wrapped correctly in 2-bit-chunky modes and text modes. (Had to fix this in 2 places already; now this fixes it in the remaining 4 places, partly by merging them all together.)
- Graphics modes now support blinking, as required by the 640x350 2bpp monochrome mode from the BIOS. (How I forgot this was a thing when I was working on getting the 64KB 640x350x2bpp modes …
> vid_ega: Merge renderers and fix a few extra bugs

- src/video/vid_ega.c
Summary
=======
This makes the read-write CRTC registers readable.
For completeness, this also provides a stub for anyone wanting to implement the read-only light pen address registers, but until someone fills it out, the behaviour should remain unchanged.
This fixes a lockup that happens when returning from QBASIC under many screen modes, including SCREEN 0. It probably fixes other things too.
Checklist
=========
References
==========
IBM EGA reference.
> vid_ega: Make the read-write CRTC registers readable

- src/qt/qt_mediamenu.cpp
Summary
=======
qt: Fix mute icon in CD-ROM menus
Checklist
=========
References
==========
None.
> qt: Fix mute icon in CD-ROM menus

- bumpversion.sh
- src/unix/assets/86Box.spec
Summary
=======
- Handle changed source filenames, which now include a 'v' at the beginning
- Add libxkbcommon-x11-devel to the build requirements
Checklist
=========
References
==========
My local builds started failing due to a missing xkbcommon-x11 header file. e.g.
```
[23/45] Building CXX object src/qt/CMakeFiles/ui.dir/xkbcommon_keyboard.cpp.o
FAILED: src/qt/CMakeFiles/ui.dir/xkbcommon_keyboard.cpp.o 
/usr/lib64/ccache/c++ -DCMAKE -DDISCORD -DEVDEV_INPUT -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DRELEASE_BUILD -DUSE_DYNAREC -DUSE_NEW_DYNAREC -DUSE_RTMIDI -DWAYLAND -DXKBCOMMON -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -D_LARGEFILE_SOURCE=1 -I/home/rderooy/src/github/86Box/build/src/qt -I/home/rderooy/src/github/86Box/src/qt …
```
> Fix RPM spec file

- src/unix/unix.c
Summary
=======
Add missing semicolon for Apple build
Checklist
=========
References
==========
> Update unix.c to add a missing semicolon for Apple build

- src/cdrom/cdrom_image_backend.c
Summary
=======
tldr: `bin_init` (`cdrom_image_backend.c`) calls `plat_fopen64` and doesn't close the handle when it detects a directory.
Some more details:
```c
tf->file = plat_fopen64(tf->fn, "rb");
```
`tf->fn` is the directory name for the viso mount. This open succeeds even though it is a directory (Opening a directory is a valid operation). 
However, the next part includes a check to see if it is a directory. If so, it sets `error` to 1. The problem here is that `error` is 1 because of the dir check (this is normal operation and causes viso to kick in following this function). But the error action taken in the `else` assumes a more serious error. It wipes out `tf` and just returns.
This leaves the directory open that was opened in `plat_fopen64` above - at least until 86box closes. …
> viso: Make sure to close file descriptors 

- src/cpu/386_common.c
- src/cpu/386_common.h
- src/cpu/cpu.h
- src/cpu/x86_ops_io.h
- src/cpu/x86_ops_rep.h
- src/cpu/x86_ops_rep_dyn.h
- src/cpu/x86_ops_string.h
Summary
=======
(based on qemu)
Checklist
=========
References
==========
> 386_common: Optimize I/O permission checking for word and dword operations

- src/cpu/386_common.c
- src/include/86box/86box.h
Summary
=======
The qemu code always checks task segment limits for and reads a word, which creates a corner case if an I/O port is in the last IOPB byte allowed by the segment limit. This new code is based on v86 and should behave more like the old byte-by-byte check.
The behavior of a real CPU remains unknown.
Checklist
=========
References
==========
https://github.com/copy/v86/blob/38a103c56b0ef83cca4e1723bd723b3ffe471dbe/src/rust/cpu/cpu.rs#L2762
> 386_common: Handle IOPB segment limit corner case more like the old code

- src/qt/qt_d3d9renderer.cpp
Summary
=======
qt: Destroy existing Direct3D 9 devices if it exists
Checklist
=========
References
==========
None.
> qt: Destroy existing Direct3D 9 devices if it exists

- README.md
Summary
=======
Update README.md to add info about MacBox - for 86Box users who use MacOS.
> Add macbox to README.md

- src/chipset/sis_85c50x.c
Summary
=======
Checklist
=========
References
==========
> Fix build by adding pic.h include in sis_85c50x.c

- src/include/86box/usb.h
- src/usb.c
Summary
=======
OHCI: HcHCCA's lower 8 bits are always zero
Start of work on USB endpoint device infrastructure
Checklist
=========
References
==========
None.
> OHCI: HcHCCA's lower 8 bits are always zero

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Port reset logic is now on a timer
Checklist
=========
References
==========
None.
> usb: Port reset logic is now on a timer

- src/include/86box/machine.h
- src/machine/m_ps2_mca.c
- src/machine/machine_table.c
Summary
=======
Re-added the IBM PS/2 model 70 type 4 (Softfloat is always used in this machine).
Checklist
=========
References
==========
> Re-added the IBM PS/2 model 70 type 4 (Softfloat is always used in this machine).

- src/cpu/808x.c
- src/floppy/fdd_86f.c
- src/sound/snd_adlibgold.c
- src/sound/snd_audiopci.c
- src/sound/snd_gus.c
- src/sound/snd_sb_dsp.c
- src/video/vid_ht216.c
Summary
=======
Several loops compared narrow with wide types, this is usually a bad idea.
Checklist
=========
References
==========
None
> Fix some variant type comparisons

- .github/codeql/codeql-config.yml
- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
Summary
=======
Expands codeql checks to security-extended
Also checks win32 and macos builds
checks dev instead of regular builds for more complete coverage
Checklist
=========
References
==========
None
> Make codeql check more of the code

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Add infrastructure for interrupt descriptor polling
Checklist
=========
References
==========
None.
> usb: Add infrastructure for interrupt descriptor polling

- src/chipset/sis_5571.c
- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: start hooking up USB interrupts to chipsets.
Currently SiS 5571 only.
Checklist
=========
References
==========
None.
> usb: start hooking up USB interrupts to chipsets

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
XGA: Fix crash when (S)VGA cards not selected as the primary display (e.g.: EGA, CGA. etc). Better handling of the VGA on/off passthrough (vga_on variable). MCA side: to avoid lfb issues, bit 0 of POS4 will be always enabled regardless of the ram size (most software uses the >16MB memory method). Better handling of the BIOS ROM mapping and Memory Mapped I/O during the MCA PS/2 POST and resets, fixes 40 25 hang (once and for all). Re-organized the ROM loading in ISA mode.
Edit: See the second commit for part 2.
Checklist
=========
References
==========
> Accelerator fixes: XGA and 8514/A, see below.

- src/chipset/ali1543.c
- src/chipset/intel_piix.c
- src/chipset/stpc.c
- src/include/86box/usb.h
Summary
=======
usb: Hook up USB interrupts to rest of the chipsets
Checklist
=========
References
==========
None.
> usb: Hook up USB interrupts to rest of the chipsets

- src/chipset/ali1543.c
- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: More work on frame timing and events
I should be getting close to implementing HCCA read/write and transfer/endpoint descriptor parsing.
Checklist
=========
References
==========
None.
> usb: More work on frame timing and events

- .gitignore
- CMakePresets.json
- src/config.c
- src/include/86box/network.h
- src/network/CMakeLists.txt
- src/network/net_vde.c
- src/network/network.c
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsnetwork.ui
Summary
========
Adds VDE (https://github.com/virtualsquare/vde-2) support to 86Box.
- Adds the possibiity of defining new networking types apart from PCAP and SLIRP.
- Adds new networking type for VDE
- Modifies networking configuration dialog to provide the VDE socket directory name
- Adds CMake Presets to build and debug under MacOS
Checklist
=========
References
==========
https://github.com/virtualsquare/vde-2
> VDE networking support

- src/qt/qt_mediamenu.cpp
- src/qt/qt_settingsnetwork.cpp
Summary
=======
Fix: Show the interface list in the network settings dialog when PCAP is not selected at VM startup.
Fix: Show "VDE" when hovering over the status icon for a VDE connected NIC
The vde implementation was bugged. It did not load the interface combo unless NIC was selected at startup. This has been fixed. Also, a cosmetic bug which showed "none" in the status icon when VDE was selected has been addeessed.
Checklist
=========
References
==========
> Fix: Load the interface list even if PCAP is not selected

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Transfer and endpoint descriptor structure
Checklist
=========
References
==========
None.
> usb: Transfer and endpoint descriptor structure

- src/include/86box/network.h
- src/network/network.c
Summary
=======
`network_devmap` wasn't being properly initialized to zero. `network_devmap_t` also seems like it was initially supposed to be a bit field but is assigned ints in the code. 
Checklist
=========
References
==========
N/A
> vde: Properly initialize a variable and fix sizing

- src/network/net_vde.c
Summary
=======
Network drivers shouldn't `fatal` during init. Instead, they are supposed to return `NULL` and let the caller take appropriate action.
Once #3326 is merged a vde init failure will automatically fall back to null driver.
Checklist
=========
References
==========
N/A
> vde: Don't fatal() in network driver

- src/machine/machine_table.c
Summary
=======
Changes memory step on the pcjr from 128k to 64k.
Checklist
=========
References
==========
None
> Fix PCjr memory steps

- src/include/86box/resource.h
- src/win/languages/dialogs.rc
Summary
=======
Allow HDD Speed to be set in win32 ui, this is the initial part to add the visible UI elements
Checklist
=========
References
==========
None
> Allow HDD Speed to be set in win32 ui (1/2)

- src/include/86box/net_dp8390.h
- src/network/net_dp8390.c
Summary
=======
Novell Netware 3.12 would always appear to send out packets to the network but could never actually establish any form of communication. Digging deeper into the issue I found that the packets would either be all zeroes or random data from memory.
Turns out the the netware drivers seem to rely on a memory wraparound functionality that wasn't fully implemented (at least, not for tx).
This PR implements the wraparound for all dp8390 devices based on the configured memory size. I've tested it with netware 3.12 and vde for networking but I suspect it will fix all versions of netware that had this problem. The tests were performed with pure IPX, no TCP. 
The issues reported in #2389 should be fixed with this PR as well.
Checklist
=========
References
==========
* [ne2k at …
> network: ne2k / dp8390 fixes for netware

- .ci/AppImageBuilder.yml
- .ci/build.sh
- .ci/dependencies_macports.txt
Summary
=======
This adds VDE dependencies to the build process for both macOS and linux.
There's an additional minor update to `build.sh` where `-D NEW_DYNAREC=ON` gets added automatically to all arm64 builds.
Checklist
=========
References
==========
N/A
> Build / CI: Add dependencies for VDE

- src/include/86box/mem.h
Summary
=======
mem: Force 'page_in_evict_list' to be always inlined
Checklist
=========
References
==========
None.
> Force 'page_in_evict_list' to be always inlined

- src/include/86box/plat_dir.h
- src/unix/unix_serial_passthrough.c
Tested on FreeBSD 13.2 only.  FreeBSD is more similar to Mac OS X in system-level library support than it is to Linux.
So far as I know, need to use `CFLAGS=-I/usr/local/include/freetype2 cmake ...` to get cmake to include the proper FreeType 2 headers. If there's a cmake expert that could fix it, that'd be great.
> Add some defines to build succesfully on FreeBSD

- src/video/vid_ega.c
Closes: #3386
Summary
=======
Fixes the EGA split screen restart address being incorrect.
Note that this does NOT implement the hardware bug which makes the first line of the lower split render twice - that can be fixed later once there's a good test case for it.
Checklist
=========
References
==========
C&T 82C434 datasheet; IBM EGA docs; Michael Abrash's Graphics Programming Black Book.
> (mostly) Fix EGA split screen - fix done by @cons-cinnabar

- src/qt/qt_deviceconfig.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_settingsnetwork.cpp
Summary
=======
Cleans up a few qt warnings. There should not be any others (in qt) once this is merged.
Checklist
=========
References
==========
N/A
> Clean up some qt warnings

- src/qt/qt_mediahistorymanager.cpp
Summary
=======
QT6 changed container sizes from `int` to `qsizetype` (aka `long long`). To maintain qt5 compatibility we cast qt5's `int` to `long long`.
Checklist
=========
References
==========
https://wiki.qt.io/New_Features_in_Qt_6.0 mentions "Container classes now use `qsizetype` as an underlying type for size and indexing"
> Fix minor qt6 warning

- src/config.c
Summary
=======
When VDE support was added some parts of `config.c` had to be reworked to allow `net_XX_host_device` to be used for the VDE socket. A missing `else` clause caused the pcap network device to not get loaded properly.
Checklist
=========
References
==========
N/A
> Fix loading of PCAP network device

- src/include/86box/plat_dir.h
Summary
=======
Always include dirent.h on non-Windows
Checklist
=========
References
==========
None.
> Always include dirent.h on non-Windows

- src/qt/qt_platform.cpp
- src/win/win.c
Summary
=======
Improvements to `plat_tempfile()`-generated file names:
- Fix milliseconds being appended twice (e.g. "Monitor_1_20230701-172615-**71**071") in the Qt UI's implementation;
- Change the Win32 UI's implementation to use local time instead of UTC - makes more sense for screenshots or printer output, shouldn't affect any other uses.
Checklist
=========
> Improvements to `plat_tempfile()`-generated file names

- src/config.c
- src/include/86box/machine.h
- src/machine/machine_table.c
- src/qt/qt_settingsstoragecontrollers.cpp
- src/win/win_settings.c
Summary
=======
Introduce a new machine feature flag for machines with a cassette port (IBM PC 1981 and 1982, and PCjr) and disables the cassette option (including graying out the checkbox in Qt and Win32 UIs) on machines without the flag. Cassette is now added to the default IBM PC (1981) configuration that is loaded when starting without a .cfg file.
Checklist
=========
> Add a machine flag for machines with a cassette port

- src/qt/qt_settingsotherperipherals.cpp
- src/win/win_settings.c
Summary
=======
Fix an oversight in Qt and Win32 UIs when the ISABugger device would not be removed after switching to a machine without ISA slots.
Checklist
=========
> Fix ISABugger not being actually disabled on machines without ISA

- src/qt/qt_settingsmachine.cpp
Summary
=======
Hide the dynamic recompiler checkbox in the settings dialog of the Qt UI when 86Box is built without a dynarec.
Checklist
=========
> qt: Hide the dynarec checkbox if built without a dynarec

- src/unix/unix.c
Summary
=======
For completeness and the benefit of the few people who still build 86Box with the legacy SDL-based Unix frontend, add a `version` monitor command to it that prints the version information, credits, and license, like the About dialog in the GUI frontends.
Checklist
=========
> unix: add a monitor command to display version and license info

- src/config.c
- src/include/86box/machine.h
- src/machine/machine_table.c
- src/qt/qt_settingsmachine.cpp
- src/win/win_settings.c
Summary
=======
* Introduce a new machine feature flag for machines that require softfloat FPU emulation to work, and replace existing hacks for the IBM PS/2 Model 70 type 4 with checks for this flag;
* Disable the softfloat checkbox in the Qt and Win32 UIs when a machine with this flag is selected;
* Remove the existing restrictions on having softfloat and dynarec enabled simultaneously.
Checklist
=========
> Add a machine flag for machines requiring softfloat FPU and improve the related UI behavior

- src/qt/qt_filefield.cpp
- src/qt/qt_filefield.hpp
- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddiskdialog.hpp
Summary
=======
This PR changes the default disk image type to dynamic vhd. All of the other options still remain.
There are some other small fixes in here. `qt_filefield` had some unfinished functionality which caused some things in `qt_harddiskdialog` to not work at all. Such as
* Not selecting the proper file filter in the open dialog based on the selected type
* Not properly enabling the OK button once a filename is entered
* No setter for `selectedFilter`
All things considered, `qt_filefield` should probably be rewritten but that is for another day.
Checklist
=========
References
==========
N/A
> qt: Change default disk image type to dynamic vhd

- src/qt/cocoa_keyboard.hpp
- src/qt/qt_mainwindow.cpp
Summary
=======
macOS doesn't really have a concept of the insert key, but guests do. On modern macOS keyboards (at least en-us) what would be close to the insert key is now the `Fn` or "Globe" key. However, that key is owned by macOS and will not pass through to guests.
This adds a special case for `Command + Delete` which will send `Insert` to the guest. 
**Note:** The delete key being referred to here is "forward delete" on a mac keyboard, not the delete key where the backspace key would be on some keyboards.
**Note 2:** An external keyboard that has a regular insert key still works fine.
Checklist
=========
References
==========
N/A
> macos: Add special mapping for insert key

- src/sound/midi_fluidsynth.c
Summary
=======
* Cleanup of stuff left over after the removal of FluidSynth dynloading: remove #defines that were never used and #includes that are no longer needed, use actual types for pointers to FluidSynth-specific structs instead of `void *`
* Use the new reverb/chorus control API functions added in FluidSynth v2.2.0 if linking to v2.2.0 or later, and keep using the older now-deprecated functions otherwise 
* Bring default configuration values and their limits in line with the latest FluidSynth version
Thing to note: due to 86Box device configuration system only supporting integer numbers for options, reverb width on the config side is now multiplied by 10 to accommodate the new default value of 0.5 (5).
Checklist
=========
> FluidSynth code improvements

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
Summary
=======
Fixes CI builds failing due to missing FluidSynth (and for Makefile actions, libslirp).
Checklist
=========
> Fix GitHub Actions failing

- src/video/vid_et4000w32.c
Summary
=======
Tseng ET4000W32/i: corrected (in the best possible way) the mouse cursor shape (under NT) when it's at the top edges while not affecting the proper shape in other operating systems.
Checklist
=========
References
==========
> Tseng ET4000W32/i: hardware cursor fixes (see below).

- src/scsi/scsi_cdrom.c
- src/scsi/scsi_pcscsi.c
Summary
=======
SCSI CD-ROM: some vendor specific commands for Toshiba and others now have more correct speed.
PCSCSI PCI: re-implemented SCSI bus reset.
Checklist
=========
References
==========
> SCSI card and CD-ROM fixes (below).

- src/cpu/x86_ops_i686.h
- src/cpu/x87.c
- src/cpu/x87.h
Summary
=======
CPU with softfloat: Added softfloat versions of the i686 FX opcodes while preserving the existing non-softfloat ones.
Checklist
=========
References
==========
> CPU with softfloat features (below).

- src/device/kbc_at.c
- src/include/86box/keyboard.h
- src/include/86box/machine.h
- src/machine/m_at_compaq.c
- src/machine/machine_table.c
Summary
=======
Revamped and refactored the Compaq AT clone code, including a more correct Plasma emulation and undev branch the Deskpro 386 while adding the September 1986 and January 1988 bioses. Added Compaq AT KBC strictly for the Deskpro 386 with the right settings, including the FPU bit. The generic AMI/Quadtel/Phoenix IBM AT's don't issue the speed problems of the pure IBM AT beyond 8Mhz, so don't limit them to 8Mhz.
Checklist
=========
References
==========
> Machine features and fixes:

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_eeprom.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_xga.h
- src/include/86box/vid_xga_device.h
- src/include/86box/video.h
- src/qt/qt_settingsdisplay.cpp
- src/video/CMakeLists.txt
- src/video/vid_8514a.c
- src/video/vid_ati_eeprom.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_table.c
- src/video/vid_xga.c
- src/win/Makefile.mingw
Summary
=======
Added the Mach8 and Mach32 ISA/VLB/PCI cards (initial implementation and MCA coming soon for the Mach32) and their corresponding EEPROM's. Added INMOS XGA ISA card and updated the SVGA core to reflect its mapping as well as the Mach8/32 mapping when in 8514 monitor mode. Mark the XGA button as already checked and locked when a standalone XGA BIOS card is present like the INMOS one. (QT only) Same concept as above, but applies to the Mach8 and 32 for the 8514 option as well. (QT only)
Checklist
=========
References
==========
> Video features and fixes:

- src/video/vid_s3.c
Summary
=======
Cosmetic cleanups and fixed the 512KB and 1MB settings of the 864/964+ chips, thus no longer thinking they were 2MB.
Checklist
=========
References
==========
> S3 Pre-ViRGE changes:

- src/cpu/386_ops.h
- src/cpu/x86_ops_misc.h
- src/floppy/fdd_img.c
- src/scsi/scsi_buslogic.c
- src/sio/sio_82091aa.c
- src/sound/snd_ad1848.c
- src/sound/snd_sb.c
- src/video/vid_ati_mach64.c
- src/video/vid_et4000w32.c
- src/video/vid_xga.c
Summary
=======
Fix several instances of uninitialized variables.
Solves about 24 of the codeql reports
Checklist
=========
References
==========
[codeql](https://github.com/86Box/86Box/security/code-scanning)
> Fix several instances of uninitialized variables.

- src/device/isartc.c
Summary
=======
`isartc_close()` tries to `free` a pointer that isn't allocated (`nvr.fn`). The `char *` is actually pointed to an existing string in `isartc_init()`. This causes a crash when the rtc device is closed.
This PR removes the unneeded `free`.
Checklist
=========
References
==========
N/A
> rtc: Fix crash when closing device

- src/include/86box/vid_xga.h
- src/video/vid_xga.c
Summary
=======
XGA: 16bpp mode in accelerated mode no longer shows inverted colors in various parts of some stuff (e.g.: Win3.1x, OS/2).
Checklist
=========
References
==========
> XGA 16bpp fixes (see below).

- src/video/vid_ati_mach64.c
Summary
=======
Mach64 GX/VT2: apparently I was wrong about the reserved aperture bit values...
Always enable the aperture when the linear base is > 0 and valid.
Checklist
=========
References
==========
> Mach64GX/VT2 aperture fix for win98fe (see below).

- src/include/86box/net_tulip.h
- src/network/CMakeLists.txt
- src/network/net_l80225.c
- src/network/net_tulip.c
- src/network/network.c
Summary
=======
Add DECchip 24110 NIC emulation.
Checklist
=========
References
==========
None.
> Add DECchip 24110 NIC emulation

- src/pci_dummy.c
Summary
=======
Fix missed bits from pci rewrite in pci_dummy.c
Checklist
=========
References
==========
None
> Fix missed bits from pci rewrite in pci_dummy.c
