86Box/86Box

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Set up infrastructure for system interrupts from OHCI
Checklist
=========
References
==========
None.
> usb: Set up infrastructure for system interrupts from OHCI

- src/device/mouse_wacom_tablet.c
Summary
=======
mouse_wacom_tablet.c: fix warnings
Checklist
=========
References
==========
None.
> mouse_wacom_tablet.c: fix warnings

- src/include/86box/usb.h
Summary
=======
usb: More USB endpoint device infrastructure work
Checklist
=========
References
==========
None.
> usb: More USB endpoint device infrastructure work

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Increment HcFmNumber in EOF function
Checklist
=========
References
==========
None.
> usb: Increment HcFmNumber in EOF function

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Implement HCCA reads and writes
Checklist
=========
References
==========
None.
> usb: Implement HCCA reads and writes

- src/include/86box/usb.h
- src/usb.c
Summary
=======
usb: Start implementing Endpoint/Transfer descriptor parsing
Checklist
=========
References
==========
None.
> usb: Start implementing Endpoint/Transfer descriptor parsing

- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
- sonar-project.properties
Summary
=======
Adds all the relevant changes for Sonarcloud support (currently disabled)
Disables LLVM builds on windows till we can actually fix it
Some GHA script consistency improvements
Checklist
=========
References
==========
None
> Sonarcloud support and GHA fixes

- src/cdrom/cdrom.c
- src/cdrom/cdrom_image.c
- src/cdrom/cdrom_image_backend.c
- src/cdrom/cdrom_image_viso.c
- src/floppy/fdc.c
- src/floppy/fdd.c
- src/floppy/fdd_86f.c
- src/floppy/fdd_common.c
- src/floppy/fdd_fdi.c
- src/floppy/fdd_imd.c
- src/floppy/fdd_img.c
- src/floppy/fdd_json.c
- src/floppy/fdd_mfm.c
- src/floppy/fdd_td0.c
- src/floppy/fdi2raw.c
- src/mem/i2c_eeprom.c
- src/mem/intel_flash.c
- src/mem/rom.c
- src/mem/smram.c
- src/mem/spd.c
- src/mem/sst_flash.c
- src/printer/png.c
- src/printer/prt_escp.c
- src/printer/prt_ps.c
- src/printer/prt_text.c
Summary
=======
More fixes for sonarcloud findings
Checklist
=========
References
==========
> More fixes for sonarcloud findings

- src/include/86box/86box.h
Summary
=======
Introduce compiler checks for pclog/fatal calls
Checklist
=========
References
==========
None.
> Introduce compiler checks for pclog/fatal calls

- src/unix/unix.c
Summary
=======
Checklist
=========
> unix: Add a missing #include

- src/sound/snd_adlibgold.c
Summary
=======
AdLib Gold: corrected (more or less) the timer period to allow the sound card to behave more normally instead of locking up the emulator in certain instances (e.g.: jukebox of the card's DOS utilities).
Checklist
=========
References
==========
> AdLib Gold: timer period fixes (see below).

- src/video/vid_ati_mach64.c
Summary
=======
ATI Mach64GX/VT2: Corrected the 24bpp accelerated mode in terms of colors and bitblt so that it could be glitchless.
Corrected 8bpp mode under Win2000 as well so that it no longer glitches.
VT2 is PCI only, so use its PCI timings only.
Small cosmetic fixes in the if's of the linear apertures of said card.
24bpp mode will be unthreaded while the rest of the bpp's is left intact, this is due to desyncing in 24bpp mode in NT 3.1's 24bpp drivers.
Checklist
=========
References
==========
> ATI Mach64GX/VT2 fixes (see below).

- src/video/vid_s3_virge.c
Summary
=======
Attempt at fixing a small but breaking bug reported by a Discord user.
Checklist
=========
References
==========
> S3 ViRGE change:

- src/cpu/x86_ops_mmx.h
- src/cpu/x86_ops_mmx_arith.h
- src/cpu/x86_ops_mmx_cmp.h
- src/cpu/x86_ops_mmx_logic.h
- src/cpu/x86_ops_mmx_mov.h
- src/cpu/x86_ops_mmx_pack.h
- src/cpu/x86_ops_mmx_shift.h
Summary
=======
Added softfloat versions of the MMX instructions while preserving the non-softfloat ones.
Checklist
=========
References
==========
> SoftFloat MMX:

- src/include/86box/plat.h
- src/include/86box/plat_fallthrough.h
Summary
=======
Fixes my clang fix
Checklist
=========
References
==========
None
> Fix my clang fix

- src/include/86box/net_eeprom_nmc93cxx.h
- src/include/86box/net_tulip.h
- src/network/CMakeLists.txt
- src/network/net_eeprom_nmc93cxx.c
- src/network/net_tulip.c
- src/network/network.c
Summary
=======
This PR ports QEMU's DECchip 21143 "Tulip" NIC emulation.
As of this writing QEMU doesn't have a iPXE ROM for it yet so this PR also doesn't require ROMs.
Checklist
=========
References
==========
None.
> Port DECchip 21143 "Tulip" NIC emulation from QEMU

- src/network/net_tulip.c
Summary
=======
net_tulip.c: Copyright header
> net_tulip.c: Copyright header

- src/include/86box/vid_8514a.h
- src/include/86box/vid_cga.h
- src/include/86box/vid_cga_comp.h
- src/include/86box/vid_ega_render_remap.h
- src/include/86box/vid_mda.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_vga.h
- src/include/86box/vid_xga.h
- src/video/vid_8514a.c
- src/video/vid_ati18800.c
- src/video/vid_ati28800.c
- src/video/vid_ati_eeprom.c
- src/video/vid_ati_mach64.c
- src/video/vid_ati_mach8.c
- src/video/vid_cga.c
- src/video/vid_cga_comp.c
- src/video/vid_ega.c
- src/video/vid_ega_render.c
- src/video/vid_mda.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/vid_table.c
- src/video/vid_vga.c
- src/video/vid_xga.c
Summary
=======
More Sonarlint work in src/video
Checklist
=========
References
==========
None
> More Sonarlint work in src/video

- src/network/net_eeprom_nmc93cxx.c
Summary
=======
net_eeprom_nmc93cxx.c: Proper logging
Checklist
=========
References
==========
None.
> net_eeprom_nmc93cxx.c: Proper logging

- src/include/86box/net_rtl8139.h
- src/network/CMakeLists.txt
- src/network/net_rtl8139.c
- src/network/network.c
Summary
=======
Port Realtek RTL8139C+ emulation from QEMU.
Checklist
=========
References
==========
None.
> Port Realtek RTL8139C+ emulation from QEMU

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_svga_render.h
- src/include/86box/vid_xga.h
- src/video/CMakeLists.txt
- src/video/vid_8514a.c
- src/video/vid_ati68875_ramdac.c
- src/video/vid_ati_mach8.c
- src/video/vid_ics2494.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/vid_table.c
- src/win/Makefile.mingw
Summary
=======
Update mach32mca to current code
Checklist
=========
References
==========
None
> Update mach32mca to current code

- src/video/vid_cga.c
Summary
=======
Reduces the CGA output resolution from 400 to 200. See https://github.com/86Box/86Box/discussions/3323#discussioncomment-5866733 .
Checklist
=========
References
==========
[6845.pdf](https://github.com/86Box/86Box/files/11480773/6845.pdf)
[OA - IBM Color Graphics Monitor Adapter (CGA).pdf](https://github.com/86Box/86Box/files/11480781/OA.-.IBM.Color.Graphics.Monitor.Adapter.CGA.pdf)
[IBM_VGA_XGA_Technical_Reference_Manual_May92.pdf](https://github.com/86Box/86Box/files/11480782/IBM_VGA_XGA_Technical_Reference_Manual_May92.pdf)
> Reduce CGA vertical res from 400 to 200.

- .ci/build.sh
- src/acpi.c
- src/device/mouse.c
- src/device/mouse_bus.c
- src/device/mouse_ps2.c
- src/device/mouse_serial.c
- src/include/86box/86box.h
- src/include/86box/machine.h
- src/include/86box/mouse.h
- src/include/86box/plat.h
- src/machine/m_at_socket5.c
- src/machine/machine_table.c
- src/pic.c
- src/qt/qt_mainwindow.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_renderercommon.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
- src/sound/snd_opl_ymfm.cpp
- src/sound/ymfm/ymfm.h
- src/sound/ymfm/ymfm_fm.ipp
- src/sound/ymfm/ymfm_opl.cpp
- src/sound/ymfm/ymfm_opm.cpp
- src/sound/ymfm/ymfm_opn.cpp
- src/sound/ymfm/ymfm_opq.cpp
- src/sound/ymfm/ymfm_opz.cpp
- src/video/vid_herculesplus.c
- src/video/vid_incolor.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Add the Dell OEM variant of Intel Premiere PCI/II Socket 5 i430NX board 
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/dell-dimension-xps-p___-mdt-p___-minitower
> Add Dell Dimension XPS Pxxx (OEM version of Intel Premiere PCI/II)

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_svga_render.h
- src/include/86box/video.h
- src/machine/m_at_socket4.c
- src/machine/machine_table.c
- src/qt/qt_settingsdisplay.cpp
- src/video/CMakeLists.txt
- src/video/vid_8514a.c
- src/video/vid_ati68860_ramdac.c
- src/video/vid_ati68875_ramdac.c
- src/video/vid_ati_mach64.c
- src/video/vid_ati_mach8.c
- src/video/vid_et4000w32.c
- src/video/vid_ics2494.c
- src/video/vid_oak_oti.c
- src/video/vid_svga.c
- src/video/vid_table.c
- src/video/vid_tgui9440.c
- src/win/Makefile.mingw
Summary
=======
1. The passthrough from VGA to 8514/A and/or 8514/A to VGA no longer relies on hackish places where to switch from/to, instead, relying on port 0x3c3 of VGA doing so (though the Mach8/32 still needs some places where to manually switch from/to, mainly the MCA one when configuring the EEPROM).
2. Implemented the MCA behalf of the Mach32 and its corresponding reset function as well as its ROM.
3. Properly implemented (more or less) true color, including 24-bit BGR rendering
4. Other fixes such as color patterns and mono patterns being more correct than before in various operating systems and in 24-bit true color.
5. Implemented the onboard Mach32 video of the IBM PS/ValuePoint P60 machine.
6. Made the onboard internal video detect when it's 8514/A compatible or not …
> Video changes: (see below)

- src/video/vid_ati_mach8.c
Summary
=======
And changed the ATI Mach32 ISA bios to a working one (phew).
Checklist
=========
References
==========
> Compile fix (3).

- src/video/vid_ati_mach8.c
Summary
=======
Please...
Checklist
=========
References
==========
> Compile fix (4).

- src/config.c
- src/game/gameport.c
- src/include/86box/gameport.h
- src/qt/qt_settingsinput.cpp
- src/qt/win_joystick_rawinput.c
- src/win/win_joystick_rawinput.c
- src/win/win_settings.c
Summary
=======
Joystick code improvements
Checklist
=========
References
==========
None
> Joystick code improvements

- src/video/vid_ati_mach8.c
Summary
=======
Fix minor bug in the pitch when it was not being issued correctly in the Mach8/32.
Checklist
=========
References
==========
> Pitch fix for Mach8/32.

- README.md
Summary
=======
Add license, latest stable release and download count to readme
Checklist
=========
References
==========
None
> Add license, latest stable release and download count to readme

- .github/workflows/cmake.yml
- src/include/86box/plat.h
- src/include/86box/plat_fallthrough.h
- vcpkg.json
Summary
=======
Fix LLVM GHA builds as best I can for now and some small fixes for MSVC
Checklist
=========
References
==========
None
> Fix LLVM GHA builds as best I can for now and some small fixes for MSVC

- src/qt/languages/ja-JP.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
Summary
=======
Update language modules
Checklist
=========
References
==========
> Update language modules

- src/video/vid_tgui9440.c
Summary
=======
Fixed the Win98 Trident PCI (and 9440 VLB) card accelerator pitch while maintaining compatibility with other OSes, despite being undocumented (this is at least an attempt to fix it properly based on the logs).
Checklist
=========
References
==========
> Assorted TGUI9440/96x0 fixes:

- src/include/86box/vid_xga.h
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
These make XGAKIT report 1MB of VRAM (from DOS).
Checklist
=========
References
==========
> More XGA fixes:

- src/sound/snd_gus.c
Summary
=======
* Revert the GUS to use edge-triggered IRQs, fixes MIDI not working, among other things;
* *Dev branch only: Fix the GUS type selector not doing anything; GUS Classic now behaves like it does in non-Dev builds instead of being identical to MAX.*
Checklist
=========
References
==========
N/A
> Gravis UltraSound fixes

- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/win/languages/zh-CN.rc
- src/win/languages/zh-TW.rc
Summary
=======
Update language module
Checklist
=========
References
==========
> Update language module

- .github/workflows/c-cpp.yml
- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
Summary
=======
Update github actions/checkout to v4
Checklist
=========
References
==========
None
> Update actions/checkout to v4

- src/video/vid_xga.c
Summary
=======
Forgot a draw_pixel variable.
Checklist
=========
References
==========
> Fix compilation.

- src/cdrom/cdrom.c
- src/cpu/808x.c
- src/pic.c
- src/video/vid_xga.c
Summary
=======
Remove several unused variables
Checklist
=========
References
==========
None
> Remove several unused variables

- src/qt/languages/ja-JP.po
- src/win/languages/ja-JP.rc
Summary
=======
Make fixes to Japanese translation.
> Fix Japanese translation (Win32 and Qt)

- src/machine/m_at_socket4.c
> Revert a testing change that shouldn't have been there

- src/86box.c
- src/config.c
- src/cpu/386.c
- src/cpu/386_dynarec.c
- src/cpu/808x.c
- src/cpu/cpu.c
- src/cpu/cpu.h
- src/gdbstub.c
- src/include/86box/ini.h
- src/include/86box/mem.h
- src/include/86box/pit.h
- src/ini.c
- src/machine/m_xt_olivetti.c
- src/nvr_at.c
- src/pit.c
- src/qt/qt_renderercommon.cpp
Summary
=======
Future support for higher clocked CPU's
A little more linting
Checklist
=========
References
==========
None
> Future support for higher clocked CPU's + A little more lint

- src/include/86box/video.h
- src/machine/m_at_compaq.c
- src/video/video.c
Summary
=======
Fixed the blinking/test cursor of said built-in video on Portable III/386.
Checklist
=========
References
==========
> Compaq Plasma fixes:

- .github/workflows/cmake.yml
- .github/workflows/codeql.yml
- CMakeLists.txt
- src/unix/unix.c
- src/unix/unix_sdl.c
Summary
=======
Fixes and GHA for SDL UI
Correct copyright year
Checklist
=========
References
==========
None
> Fixes and GHA for SDL UI

- src/sound/snd_adlibgold.c
- src/video/vid_ati_mach64.c
Summary
=======
Fixes wrong colors in patterns on various operating systems and possibly other stuff too.
Checklist
=========
References
==========
> Mach64 (both GX and VT2) 24bpp mono pattern fix placed in.

- src/video/vid_tgui9440.c
Summary
=======
1. Its execution is exactly (actually 99%) the same as the S3 Bresenham procedure, so I thought of making the Bresenham command of the TGUI9440/96x0 behave like the S3 one but adapted to use Trident's ports and meanings and now OS/2 and Windows lines in certain programs work fine.
Checklist
=========
References
==========
> Trident TGUI9440/96x0 Bresenham update:

- src/video/vid_s3.c
Summary
=======
X/Y coordinates are corrected for real even while wrapping. Fixes Trio64V+/Trio64V2 Win9x desktop icons as well as OS/2 software cursor madness.
Checklist
=========
References
==========
> S3 accel command fixes:

- CMakeLists.txt
- debian/changelog
- src/unix/assets/86Box.spec
- src/unix/assets/net.86box.86Box.metainfo.xml
Summary
=======
misc 4.1 updates to bring 4.1 entirely in line with master
Checklist
=========
References
==========
None
> Misc 4.1 updates

- src/video/vid_svga_render.c
Summary
=======
This implements the 4bpp blink mode properly for real this time.
It turns out that if the plane 3 output is enabled in the graphics controller, then when it's 1, blink is enabled on that bit plane, and when it's 0, that bit plane's output is forced to... 1. Apparently someone thought this made sense.
Exactly what triggers it is something that will remain a mystery until I or someone willing to run tests actually gets access to a real VGA, but until then, this is the most logical explanation I can think of.
Checklist
=========
References
==========
Lotus 1-2-3 release 2.3 and QBASIC SCREEN 10. I'm not sure if any references explicitly document how graphics blink actually works, because from what I've read and remembered so far, IBM didn't. (The original implementation is …
> Implement 4bpp graphics mode blink properly on VGA

- src/video/vid_svga_render.c
Summary
=======
This reworks the renderer to be internally chunky rather than planar. In doing so, the only lookup tables I needed boiled down to something that only needs to be in a single 32-bit integer and shifted around.
I focused entirely on the "turn 32 bits of VRAM data into 4 or 8 pixels" part. There shouldn't be any regression in functionality.
I isolated this implementation and the implementation it replaces so I could run multiple iterations of a 320x200 output as fast as possible. My results from running this under the prestigious compatibility standard known as My Machine™ indicates that this implementation is almost twice as fast as what it replaces, except in the case of high-resolution 8bpp where for some reason it renders at about 7x the speed...?! [EDIT: This was using …
> Rework and optimise the (S)VGA pixel renderer

- .github/workflows/cmake.yml
Summary
=======
Update Github Actions to macos 12
Checklist
=========
References
==========
None
> Update Github Actions to macos 12

- .github/workflows/codeql.yml
Summary
=======
Fix codeql runs
Checklist
=========
References
==========
None
> Fix codeql runs

- src/chipset/neat.c
- src/device/mouse_serial.c
- src/disk/hdc_st506_xt.c
Summary
=======
Several fixes to compile with logging enabled
Checklist
=========
References
==========
None
> Several fixes to compile with logging enabled

- src/disk/hdc_ide.c
- src/video/vid_compaq_cga.c
Summary
=======
More compile fixes with logging turned on
Checklist
=========
References
==========
None
> More compile fixes with logging turned on

- src/include/86box/vid_svga_render.h
- src/include/86box/video.h
- src/video/CMakeLists.txt
- src/video/vid_mga.c
- src/video/vid_svga_render.c
- src/video/vid_table.c
Summary
=======
See the title.
Checklist
=========
References
==========
> Undev branch the Matrox Millennium since it is now mostly usable.

- src/video/vid_mga.c
Summary
=======
See title.
Checklist
=========
References
==========
> Fixed warning in vid_mga.c.

- src/video/vid_mga.c
Summary
=======
1. LFB access is now done properly through the right svga_read/write linear calls.
2. Lowres 8bpp mode and Packed/Extended 8bpp+ mode don't mix together, fixes Debian Woody matroxfb module when testing the modes while keeping other compatibility intact (basically enable packed stuff only when gdcreg5 bits 5-6 are 0 when extended mode is set).
3. Small cleanup in the line accel stuff.
Checklist
=========
References
==========
> MGA Fixes:

- src/chipset/ali1543.c
- src/config.c
- src/include/86box/86box.h
- src/network/net_rtl8139.c
- src/qt/qt_renderercommon.cpp
- src/unix/unix.c
Summary
=======
Fixes most of the warnings I've seen in the codebase (Only 3 left!)
Checklist
=========
References
==========
None
> Warning fixes

- src/video/vid_s3.c
Summary
=======
Just a quick fix for Commander Keen 4 EGA's flickering.
Checklist
=========
References
==========
> S3 wraparound fix.

- src/include/86box/vid_ega.h
- src/include/86box/video.h
- src/video/vid_ati18800.c
- src/video/vid_ega.c
- src/video/vid_table.c
Summary
=======
1. Proper cleanup of the code.
2. Migrate the card in question to the VGA class list as it's actually a rebadged VGA Edge (thus 18800).
3. Some VGA only features are not supported on this card and are documented in the recalctimings.
Checklist
=========
References
==========
> ATI EGA Wonder 800+ and 18800 refactoring:

- src/video/vid_mga.c
Summary
=======
Matrox Mystique: Attempt fixing 3D busmastered drawing
NT 4.0's OpenGL screensavers only display one frame before freezing the system.
Checklist
=========
References
==========
None.
> Matrox Mystique: Attempt fixing 3D busmastered drawing

- src/video/vid_mga.c
Summary
=======
Mystique: SOFTRAP register writes correctly reset the primary DMA channel
Step 1 at fixing 3D busmastering operations. Not fully fixed yet due to a strange race condition bug that still freezes the system.
Checklist
=========
References
==========
None.
> Mystique: SOFTRAP register writes correctly reset the primary DMA channel

- src/video/vid_mga.c
Summary
=======
Fix M3D programs
Checklist
=========
References
==========
None.
> Fix M3D programs

- src/video/vid_ega.c
Summary
=======
Implement PEL panning per hardware features.
Checklist
=========
References
==========
> EGA PEL fix.

- src/video/vid_mga.c
Summary
=======
It's time to end the flickers once and for all by making the start address correctly emulated in vblank_start when in power graphics mode.
Checklist
=========
References
==========
> MGA flicker fixes.

- CMakeLists.txt
- src/include/86box/video.h
- src/video/CMakeLists.txt
- src/video/vid_mga.c
- src/video/vid_table.c
- src/win/Makefile.mingw
Summary
=======
Un-dev matrox mystique cards
Checklist
=========
References
==========
None
> Un-dev matrox mystique

- src/include/86box/vid_svga.h
- src/video/vid_mga.c
- src/video/vid_svga_render.c
Summary
=======
MGA: Gamma-correct hardware cursor
Checklist
=========
References
==========
None.
> MGA: Gamma-correct hardware cursor

- src/video/vid_mga.c
Summary
=======
Mystique: Fix flickering display on Direct3D
Checklist
=========
References
==========
None.
> Mystique: Fix flickering display on Direct3D

- src/video/vid_mga.c
Summary
=======
Mystique: Don't do busmastering until SOFTRAP status is read
MSICUBE sample for Windows 9x no longer freezes the entire VM after a while
Checklist
=========
References
==========
None.
> Mystique: Don't do busmastering until SOFTRAP status is read

- src/video/vid_svga.c
Summary
=======
See above.
Checklist
=========
References
==========
> Restore correct CGA compatible mode behavior in (S)VGA.

- src/video/vid_ati_mach8.c
Summary
=======
1. Apparently some stuff uses read-only port 0x86ee and expects it to return 0 while port 0xf6ee is an alias to 0x82e8, this should fix hangs in Majong 8514 using ATI's DOS drivers.
2. 8514 data available bits are reset properly when new parameters for a new command are installed (port 0xCEEE), fixes remaining hangs with some stuff.
Checklist
=========
References
==========
> More ATI accel fixes and undocumented stuff.

- debian/control
- debian/copyright
- debian/rules
- debian/source/format
Summary
=======
Fix creation of Debian .deb packages
Checklist
=========
References
==========
None
> Fix debian package build

- src/video/vid_mga.c
Summary
=======
Fix a dumb copy-paste mistake.
Checklist
=========
References
==========
None.
> Fix a dumb copy-paste mistake

- src/video/vid_mga.c
Summary
=======
Fix yet another dumb copy-paste mistake
Checklist
=========
References
==========
None.
> Fix yet another dumb copy-paste mistake

- src/include/86box/video.h
- src/video/vid_mga.c
- src/video/vid_table.c
Summary
=======
Add Matrox Productiva G100 video adapter
Checklist
=========
References
==========
None.
> Add Matrox Productiva G100 video adapter

- src/video/vid_mga.c
Summary
=======
MGA G100: Fix fog acceleration
Minor variable cleanups
Checklist
=========
References
==========
None.
> MGA G100: Fix fog acceleration

- src/video/vid_s3.c
Summary
=======
1. Moved the wraparound fix to the respective recalctimings, makes Commander Keen still playable without flickering and, at the same time, making Solaris work right in 640x480x8bpp+ mode (including 1024x768x8bpp).
2. The multifunction index 0x0e bit that can be toggled in 32bpp mode is now initialized properly, should fix the pinkness on Solaris' 32bpp mode.
Checklist
=========
References
==========
> S3 changes again:

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Add GLaBIOS XT clone machine.
Checklist
=========
References
==========
> Add GLaBIOS machine.

- src/video/vid_cl54xx.c
Summary
=======
vid_cl54xx: Revert changes made to special blanking mode
Checklist
=========
References
==========
None.
> vid_cl54xx: Revert changes made to special blanking mode

- src/video/vid_s3.c
Summary
=======
See above
Checklist
=========
References
==========
> Corrected S3 864 horizontal display.

- src/cpu/386.c
- src/cpu/386_dynarec.c
- src/cpu/x86seg.c
Summary
=======
Implement TSS debug trap bit.
Checklist
=========
References
==========
None.
> Implement TSS debug trap bit

- src/machine/m_elt.c
Summary
=======
Use Toshiba T1200's HDC in Epson Equity LT
Checklist
=========
References
==========
None.
> Use Toshiba T1200's HDC in Epson Equity LT

- src/video/vid_tgui9440.c
Summary
=======
If the chips are PCI-based, assume linear addressing is always enabled when the linear base is on valid value (e.g.: not 0). Should fix a regression when linear addressing is used by almost everything in the PCI world (e.g.: Win95's drivers).
Checklist
=========
References
==========
> TGUI9440AGi/96xx changes:

- src/include/86box/video.h
- src/video/vid_rtg310x.c
- src/video/vid_table.c
Summary
=======
See above.
Checklist
=========
References
==========
> Added the RTG3105 video card and fixed some wrong stuff in the RTG3106 as well

- src/video/vid_xga.c
Summary
=======
Cleanup the area fill side.
Checklist
=========
References
==========
> XGA changes:

- src/video/vid_s3.c
Summary
=======
Reset bit 4 of the Misc Index register (from port 0xbee8) on mode changes.
Checklist
=========
References
==========
> S3 true color update.

- src/video/vid_tgui9440.c
Summary
=======
See above.
Checklist
=========
References
==========
> Added a proper VLB variant to the TGUI9440AGi

- src/include/86box/net_tulip.h
- src/network/net_eeprom_nmc93cxx.c
- src/network/net_tulip.c
- src/network/network.c
Summary
=======
DEC DE-435 EtherWorks Turbo (DECchip 21040) emulation
Checklist
=========
References
==========
None.
> DEC DE-435 EtherWorks Turbo (DECchip 21040) emulation

- src/video/vid_xga.c
Summary
=======
1. Remove some useless parentheses and correct some identation.
2. The reversed linear mapping activation and a5 vram test are reset properly now.
3. More correct Area Fill emulation, especially in 640x480 mode, (800x600 and 1024x768 too).
Checklist
=========
References
==========
[XGA-2 manual](http://bitsavers.trailing-edge.com/pdf/ibm/pc/cards/IBM_VGA_XGA_Technical_Reference_Manual_May92.pdf)
> XGA update/slight fixes:

- CMakeLists.txt
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
The machine seems to be broken, so it's being moved into dev branch here.
Checklist
=========
References
==========
> Move MSI MS-4144 into dev branch

- src/qt/languages/zh-TW.po
- src/win/languages/zh-TW.rc
Summary
=======
Update Trad-Chinese translation (29.01.2024)
Checklist
=========
References
==========
> Trad-Chinese translation

- src/scsi/scsi_ncr5380.c
Summary
=======
More timer related fixes regarding the speed combinations, looking at you, Rancho (8.10R and 8.20R), but at least it should solve most problems with boots.
Checklist
=========
References
==========
> More fixes to the 5380-based core.

- src/video/vid_svga.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fix SVGA code warnings.

- CMakeLists.txt
- src/sound/CMakeLists.txt
- src/sound/midi.c
Summary
=======
Devbranch OPL4-ML daughterboard emulation
Checklist
=========
References
==========
None.
> Devbranch OPL4-ML daughterboard emulation

- src/dma.c
- src/include/86box/dma.h
- src/include/86box/machine.h
- src/include/86box/pic.h
- src/include/86box/pit.h
- src/include/86box/pit_fast.h
- src/include/86box/vid_pc98x1_disp.h
- src/include/86box/vid_upd7220.h
- src/io.c
- src/machine/machine.c
- src/pic.c
- src/pit.c
- src/pit_fast.c
- src/video/vid_pc98x1_disp.c
- src/video/vid_upd7220.c
1.Fixed I/O step when using interleaving I/O.
2. Add more and fixes of the existing incomplete PC-98x1 core.
Summary
=======
Checklist
=========
References
==========
> More updates regarding the PC-98x1:

- src/video/vid_chips_69000.c
Summary
=======
C&T: Implement clock select and LCD/CRT panning properly
Fixes 1600x1200 resolution under Windows 2000 and slow refresh rate.
Checklist
=========
References
==========
None.
> C&T: Implement clock select and LCD/CRT panning properly

- CMakeLists.txt
- src/video/CMakeLists.txt
- src/video/vid_mga.c
- src/win/Makefile.mingw
Summary
=======
Fix unused variable warnings and remove the leftovers of the dev-branching.
Checklist
=========
> MGA cleanup

- src/video/vid_tvp3026_ramdac.c
Summary
=======
See above.
Checklist
=========
References
==========
> TVP3026: remove excess logs.

- src/video/vid_chips_69000.c
Summary
=======
C&T 69000: Fix black cursor on Red Hat Linux 8
Checklist
=========
References
==========
None.
> C&T 69000: Fix black cursor on Red Hat Linux 8

- src/video/vid_chips_69000.c
- src/video/vid_svga.c
- src/video/video.c
Summary
=======
C&T 69000: DPMS
Also draw black overscan when monitor is turned off via DPMS.
Checklist
=========
References
==========
None.
> C&T 69000: DPMS

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE: a bit of cleanup
Checklist
=========
References
==========
None.
> S3 ViRGE: a bit of cleanup

- README.md
Summary
=======
Updates to README.md adding links to other managers
Checklist
=========
References
==========
None
> Updates to README.md adding links to other managers

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE/GX2: Fix frozen display when stream processors are enabled.
Video playback on Windows XP is still broken, but the display no longer remains in an unfixable state.
Checklist
=========
References
==========
None.
> S3 ViRGE/GX2: Fix frozen display when stream processors are enabled

- src/video/vid_mga.c
Summary
=======
MGA: Move BPLAN handling to the right place
Checklist
=========
References
==========
None.
> MGA: Move BPLAN handling to the right place

- src/video/vid_mga.c
Summary
=======
MGA: Implement X11 hardware cursor
Checklist
=========
References
==========
None.
> MGA: Implement X11 hardware cursor

- src/sound/openal.c
Summary
=======
Fix OPL audio not playing
Checklist
=========
References
==========
None.
> Fix OPL audio not playing

- src/disk/hdc_esdi_at.c
- src/disk/hdc_st506_at.c
Summary
=======
Make sure they IRQ activations are more IDE-like and correct.
Checklist
=========
References
==========
> ESDI/MFM AT changes:

- src/disk/hdc_esdi_mca.c
Summary
=======
This should also fix the timing/fatal's on ramdisk speeds using said controller on NT and OS/2 on MCA.
Checklist
=========
References
==========
> Solved the IRQ mess of ESDI MCA.

- src/86box.c
- src/device/serial.c
- src/include/86box/network.h
- src/include/86box/plat_netsocket.h
- src/include/86box/serial.h
- src/network/CMakeLists.txt
- src/network/net_modem.c
- src/network/net_slirp.c
- src/network/network.c
- src/network/utils/getline.c
- src/qt/CMakeLists.txt
- src/win/win_netsocket.c
Summary
=======
This PR introduces modem emulation, ported over from DOSBox.
This PR also introduces SLIP support.
Checklist
=========
References
==========
None.
> Modem emulation (includinng SLIP connectivity)

- .gitignore
- src/device/serial.c
- src/include/86box/serial.h
- src/network/net_modem.c
- src/qt/CMakeLists.txt
- src/unix/CMakeLists.txt
- src/unix/unix_netsocket.c
- src/win/win_netsocket.c
Summary
=======
net_modem: TCP/IP support and Telnet emulation.
Also adds copyright text.
Checklist
=========
References
==========
None.
> net_modem: TCP/IP support and Telnet emulation

- src/device/novell_cardkey.c
Summary
=======
See above.
Checklist
=========
References
==========
None.
> Fix brace warning

- src/network/net_modem.c
- src/unix/unix_netsocket.c
- src/win/win_netsocket.c
Summary
=======
netsockets: Swap port number
Checklist
=========
References
==========
None.
> netsockets: Swap port number

- src/network/net_modem.c
- src/unix/unix_netsocket.c
Summary
=======
unix_netsocket.c: Fix comparison value
Checklist
=========
References
==========
None.
> unix_netsocket.c: Fix comparison value

- src/network/net_modem.c
Summary
=======
net_modem.c: Make sure the CONNECT response gets through
Checklist
=========
References
==========
None.
> net_modem.c: Make sure the CONNECT response gets through

- src/network/net_modem.c
Summary
=======
net_modem.c: Fix memory leak
Checklist
=========
References
==========
None.
> net_modem.c: Fix memory leak

- src/qt/qt_settingsotherremovable.cpp
Summary
=======
Fix broken translation for ZIP drives
Checklist
=========
References
==========
> Fix broken translation for ZIP drives

- src/machine/m_pcjr.c
- src/machine/machine.c
Summary
=======
So that the build compiles fine.
Checklist
=========
References
==========
> Fix incompatible pointers of the generic PIT and PCjr's

- src/video/vid_ati_mach8.c
Summary
=======
Reworked the way the mode changes work in said chips (and way less hacky than before).
Checklist
=========
References
==========
> ATI/IBM mode changes in the Mach8/32.

- src/video/vid_ati_mach8.c
Summary
=======
And 0x6e9 is an alias to 0x2e8 per the Mach32 manual (H_TOTAL).
Checklist
=========
References
==========
[Mach8/32 manual](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
> Further fixes to the code related to the Mach8/32 mode changes.

- src/scsi/scsi_ncr53c400.c
Summary
=======
And more logging cleanups.
This should make the T130B driver for NT 3.1 work normally, at least.
Checklist
=========
References
==========
> Workaround to prevent timeouts with the T130B driver on NT 3.1.

- src/video/vid_xga.c
Summary
=======
See above.
Checklist
=========
References
==========
> Just shut up the warning.

- src/qt/languages/vi-VN.po
Summary
=======
like the title, translation based on a copy of Spanish lang file.
Checklist
=========
References
==========
(nothing i guess)
> Adding Vietnamese language (vi-VN) translation file

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_llvm.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
Summary
=======
- Update deprecated actions
- Fix workflows not being triggered when the workflow file is updated
Checklist
=========
References
==========
N/A
> GHA maintenance

- src/qt/languages/vi-VN.po
Summary
=======
checked the lang file to fix hiccups regarding to translation completeness. 
Now it should be fine without my last PR which turned out to be from an unsynced version and got conflict.
Checklist
=========
References
==========
N/A
> minor fixes/corrections for vi-VN translation

- src/scsi/scsi_ncr53c400.c
Summary
=======
Checklist
=========
References
==========
> Warning fix

- src/video/vid_xga.c
Summary
=======
1. Text is no longer glitchy under win95 using XGA.
2. Now there's a better way to handle the cursor/sprite X/Y offsets, should fix remaining Win3.x cursor blackness and other stuff using said cursor.
Checklist
=========
References
==========
> XGA 1-2: Pattern and cursor/sprite fixes.

- src/video/vid_s3.c
Summary
=======
S3 928:
When the pitch is 1280, make sure the proper horizontal resolution is displayed right (in this case, 1280x1024).
S3 Vision864:
Exclude it from the horizontal blank bits due to more issues that are TBD (like the Trio32 and 64 and up), this works around the mode issues under Windows 9x and more as well as fix 32bpp horizontal rendering in said chip.
Checklist
=========
References
==========
> More S3 changes/fixes.

- src/qt/qt_main.cpp
Also need to add the appropriate translation strings to the language files
Summary
=======
Checklist
=========
References
==========
> Fixes for translation not working in the main window

- src/video/vid_s3.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fix compile warning.

- src/include/86box/video.h
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
- src/video/vid_s3_virge.c
Summary
=======
1. Added an on-board S3 ViRGE DX (375) video card to the Intel AP440FX socket 8-based machine alongside its on-board CS4236B audio.
2. Sanity check for on-board S3 ViRGE devices.
Checklist
=========
References
==========
> Video changes part 3 (minor though)

- src/scsi/scsi_ncr53c400.c
- src/video/vid_s3_virge.c
Summary
=======
See above (CD-ROM speeds too for said SCSI chips).
Checklist
=========
References
==========
> NCR 53c400 timing fixes.

- src/device/isamem.c
Summary
=======
* Add the lo-tech EMS Board also the modded version with 4MB support
* Also fix a few minor EMS bugs
Checklist
=========
References
==========
None
> Add the lo-tech EMS Board

- src/floppy/fdd.c
Summary
=======
* Add 2.88MB dual RPM drive
* A few cleanups in fdd.c
Checklist
=========
References
==========
None
> Add 2.88MB dual RPM drive

- src/chipset/CMakeLists.txt
- src/chipset/ali1409.c
- src/include/86box/chipset.h
- src/include/86box/machine.h
- src/include/86box/video.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
- src/video/vid_oak_oti.c
Summary
=======
Added Machine Acer 100T motherboard
Added Support for OAK Video compatiblity with Acer100T motherboard
Added initial support for ALI M1409 chipset 
Checklist
=========
* [ X] I have discussed this with core contributors already
* [ X] This pull request requires changes to the ROM set
* [ X] I have opened a roms pull request - https://github.com/86Box/roms/pull/263/
> Added Machine Motherboard Acer100T

- src/machine/machine_table.c
Summary
=======
Fixing incorrect bus type configuration.
Checklist
=========
* [ X] I have discussed this with core contributors already
> Fixing bus type

- src/device/isamem.c
Summary
=======
* Add BocaRAM/XT
* Corrections to AST Rampage
* A few fixes to to the BocaRAM/AT (Still not ready to be freed from it's devbranch chains however)
Checklist
=========
References
==========
None
> Add BocaRAM/XT plus more EMS improvements

- src/device/isamem.c
Summary
=======
Improvements to the RAMpage XT and EMS logging
Checklist
=========
References
==========
None
> Improvements to the RAMpage XT and EMS logging

- src/sound/ymfm/ymfm.h
- src/sound/ymfm/ymfm_fm.ipp
- src/sound/ymfm/ymfm_ssg.h
Summary
=======
To 86box.
Checklist
=========
References
==========
> Ported the "latest" YMFM changes.

- src/device/isamem.c
Summary
=======
The 4MB hack should *only* apply to lotech cards.
Checklist
=========
References
==========
None
> Improve lotech EMS

- src/include/86box/vid_cga_comp.h
Summary
=======
See above.
Checklist
=========
References
==========
> vid_cga_comp.h: another compile fix.

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_macos.yml
Summary
=======
* [Build support for Apple silicon](https://github.com/86Box/86Box/commit/3374246436219c62cd777790743720996689f907)
* [freetype & libpng are installed by default on mac](https://github.com/86Box/86Box/commit/f73dff6d768a7eb7f94336d596595516d72f5e81)
* [Switch sonarcloud scanner to git release](https://github.com/86Box/86Box/commit/7411fda449483bd5b86a2193ff371a52640d5302)
Checklist
=========
References
==========
None
> Github Actions Improvements

- src/floppy/fdd_pcjs.c
- src/qt/dummy_cdrom_ioctl.c
- src/unix/dummy_cdrom_ioctl.c
Summary
=======
Fix 10 more warnings in the code.
Checklist
=========
References
==========
None
> Fix 10 more warnings in the code

- src/cdrom/cdrom_image_backend.c
- src/ini.c
Summary
=======
Fix several uninitialized variables
Checklist
=========
References
==========
None
> Fix several uninitialized variables

- src/video/vid_paradise.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fix warning.

- src/include/86box/plat.h
- src/include/86box/prt_devs.h
- src/lpt.c
- src/printer/prt_ps.c
- src/qt/qt_platform.cpp
- src/unix/unix.c
Summary
=======
Checklist
=========
References
==========
> Add Generic PCL Printer

- src/video/vid_s3.c
Summary
=======
1. Ported the S3 ViRGE reset fix to the Pre-ViRGE cards.
2. Slight cleanup on the acceleration and logs.
3. Unused sequencer register data now return 0xff instead of 0. This fixes Scorched Earth 1.x on DOS using S3 Trio32/64/V+/V2/868/968 cards (on other S3 it works fine as is).
Checklist
=========
References
==========
> S3 fixes of the day.

- src/86box.c
- src/device/serial.c
- src/include/86box/86box.h
- src/include/86box/serial.h
Summary
=======
Support additional serial ports ala the MP5587-1/2 (This doesn't include UI changes)
Checklist
=========
References
==========
None
> Support additional serial ports ala the MP5587-1/2

- src/device/lpt.c
- src/printer/prt_ps.c
Summary
=======
[Fix compile error in lpt.c](https://github.com/86Box/86Box/commit/5eff07dc2de9d147189178c1625ed45a09aa8cb4)
[Update prt_ps.c to match current structs](https://github.com/86Box/86Box/commit/531f451c57cd409564d31481e344e67f8bac1746)
Checklist
=========
References
==========
None
> Updates to new LPT code

- src/machine/machine_table.c
Summary
=======
Submitting the parts of my current work which are ready, but also could conflict.
Checklist
=========
References
==========
None
> Updates to machine_table.c

- src/config.c
- src/disk/hdc.c
- src/floppy/fdc.c
- src/include/86box/config.h
- src/include/86box/fdc.h
- src/include/86box/fdc_ext.h
- src/machine/m_at_compaq.c
- src/machine/m_europc.c
- src/machine/m_ps1.c
- src/machine/m_ps2_isa.c
- src/machine/m_v86p.c
- src/machine/m_xt.c
- src/machine/m_xt_t1000.c
- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
* [Allow complete removal of FDC](https://github.com/86Box/86Box/commit/add1c3918894b218e79674edd145434d342ca76f)
* [Better support for internal floppy](https://github.com/86Box/86Box/commit/07e3aba22c0520c5646cb0d39dea67914a95d625)
* [Don't attempt to add dummy internal device to system](https://github.com/86Box/86Box/commit/f68f0487264f02455313613752525d37803fe4f5)
* [Commented out support for hiding internal fdc](https://github.com/86Box/86Box/commit/8aba1361e6ec192017b4cd0cb09d615ffcd24de4)
* [Add ability to select XT or AT FDC](https://github.com/86Box/86Box/commit/00068539e131a5f759f239472debd1b73e74e542)
* [Fix flags in fdc.h](https://github.com/86Box/86Box/commit/7ce119dcbae0c0b6393c2dd59c66c7d86fcc99e5)
* [Handle freeing mallocs in config.c …
> FDC improvements, some bug fixes & cleanups

- src/video/vid_paradise.c
Summary
=======
See above.
Checklist
=========
References
==========
> Compile fix on PVGA.

- src/sound/sound.c
Summary
=======
Title.
Checklist
=========
References
==========
N/A
> Sort the ESS sound cards in the card list

- src/include/86box/snd_opl_nuked.h
- src/sound/snd_opl_nuked.c
Summary
=======
Nuked-OPL3: Update to latest as of 15/07/2024
Checklist
=========
References
==========
None
> Nuked-OPL3: Update to latest as of 15/07/2024

- src/video/vid_paradise.c
Summary
=======
Actually fix it correctly as well as fixing 16 color mode that was made corrupt after the cleanup of the bank commit.
Checklist
=========
References
==========
> PVGA fixes of the day (July 16th, 2024)

- src/device.c
- src/device/isamem.c
- src/device/isartc.c
- src/disk/hdc.c
- src/floppy/fdc.c
- src/include/86box/device.h
- src/network/network.c
- src/scsi/scsi.c
- src/sound/midi.c
- src/sound/sound.c
- src/video/vid_table.c
Summary
=======
Reduce the amount of otherwise identical dummy devices significantly
Checklist
=========
References
==========
None
> Less dummy devices

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/qt/qt_main.cpp
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.hpp
- src/unix/unix.c
- src/video/vid_table.c
Summary
=======
Initial underlying code support for more than 2 video cards
Checklist
=========
References
==========
None
> Initial underlying code support for more than 2 video cards

- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Added Pravetz-16S machine definition
Checklist
=========
References
==========
[CPU12+.pdf](https://github.com/86Box/86Box/files/14834554/CPU12%2B.pdf)
[Pravetz-16S article in Sandacite.bg](https://sandacite.bg/български-компютър-правец-16s-2/)
> Adding Pravetz-16S definition

- src/machine/m_xt.c
Summary
=======
Fix pravetz16s compile
Checklist
=========
References
==========
None
> Fix pravetz16s compile

- src/machine/m_xt.c
Summary
=======
Add missing kbc to pravetz16s
Checklist
=========
References
==========
None
> Add missing kbc to pravetz16s

- src/cdrom/CMakeLists.txt
- src/cdrom/cdrom_image.c
- src/cdrom/cdrom_image_backend.c
- src/cdrom/cdrom_ioctl.c
- src/include/86box/cdrom.h
- src/include/86box/cdrom_image_backend.h
- src/qt/qt_settingsfloppycdrom.cpp
Summary
=======
Checklist
=========
References
==========
> Libsndfile

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
- CMakePresets.json
Summary
=======
experimental preset renamed to dev_debug
Github actions updated accordingly
Checklist
=========
References
==========
None
> experimental preset renamed to dev_debug

- src/video/vid_s3_virge.c
Summary
=======
See above.
Checklist
=========
References
==========
> Initial implementation of the timed FIFO on the ViRGE

- src/scsi/scsi_pcscsi.c
Summary
=======
This commit should fix the NT 3.1 AMD PCscsi drivers when they look for devices on LUN > 0 and causing havoc with them (BSOD). Basically clear the FIFO and set the SEQ_0 bit in the RSEQ read reg. AM53c974 side: a biosless card is biosless.
General: fixed all the log excesses.
Checklist
=========
References
==========
> More ESP SCSI fixes (LUN mainly)

- src/machine/machine_table.c
Summary
=======
Fix Tandy 1000 SX minimum RAM
Checklist
=========
References
==========
None
> Fix Tandy 1000 SX minimum RAM

- src/cdrom/cdrom_image_backend.c
- src/chipset/sis_85c50x.c
- src/cpu/386.c
- src/cpu/808x.c
- src/cpu/x86.c
- src/cpu/x87.c
- src/device/smbus_sis5595.c
- src/disk/hdc_ide_ali5213.c
- src/disk/hdc_ide_um8673f.c
- src/disk/hdc_ide_w83769f.c
- src/dma.c
- src/floppy/fdc_monster.c
- src/gdbstub.c
- src/network/net_rtl8139.c
- src/sound/snd_cs423x.c
- src/unix/dummy_cdrom_ioctl.c
- src/video/vid_ega.c
Summary
=======
Assorted compile fixes found while checking build with more logging options turned on
Checklist
=========
References
==========
None
> Assorted compile fixes

- CMakeLists.txt
- src/cdrom/CMakeLists.txt
Summary
=======
Correctly devbranch mitsumi CDROM
Checklist
=========
References
==========
None
> Correctly devbranch mitsumi CDROM

- src/CMakeLists.txt
- src/cpu/386_ops.h
- src/include/86box/machine.h
- src/machine/machine_table.c
Summary
=======
More DEV_BRANCH related cleaning (I managed to miss a fair bit)
Checklist
=========
References
==========
None
> More DEV_BRANCH related cleaning

- src/video/vid_s3_virge.c
Summary
=======
See above.
Checklist
=========
References
==========
> S3 ViRGE class: Rethreading for future investigation.

- src/video/vid_s3_virge.c
Summary
=======
See above.
Checklist
=========
References
==========
> Attempt at fixing the threading of the ViRGE.

- README.md
Summary
=======
Add a link to the build guide to README.md
Checklist
=========
References
==========
None
> Add a link to the build guide to README.md

- src/video/vid_s3_virge.c
Summary
=======
1. ROM updated to 1.03.
2. Re-apply more fixes that were missed during the restructuring to be on par with PCem's speed.
3. Implemented Command DMA bus mastering required by Diamond Stealth 3D specific drivers (especially the GX2-based 4000).
4. Some indentation fixes.
Checklist
=========
References
==========
> ViRGE changes of the day (August 20th, 2024)

- src/video/vid_ati_mach64.c
Summary
=======
Re-thread the video chip family again but with fixes to avoid desyncs and some cleanups.
Checklist
=========
References
==========
> Mach64 changes of the day (August 21st, 2024)

- src/cpu/cpu.c
Summary
=======
Split off AMD K5 from K6
Checklist
=========
References
==========
None
> Split off AMD K5 from K6

- debian/changelog
- src/unix/assets/86Box.spec
- src/unix/assets/net.86box.86Box.metainfo.xml
Summary
=======
Update dates for 4.2.1 release
Checklist
=========
References
==========
None
> Update dates for 4.2.1 release

- CMakeLists.txt
- src/CMakeLists.txt
- src/cdrom/CMakeLists.txt
- src/chipset/CMakeLists.txt
- src/codegen/CMakeLists.txt
- src/codegen_new/CMakeLists.txt
- src/cpu/CMakeLists.txt
- src/device/CMakeLists.txt
- src/disk/CMakeLists.txt
- src/floppy/CMakeLists.txt
- src/game/CMakeLists.txt
- src/mac/CMakeLists.txt
- src/machine/CMakeLists.txt
- src/mem/CMakeLists.txt
- src/network/CMakeLists.txt
- src/printer/CMakeLists.txt
- src/qt/CMakeLists.txt
- src/scsi/CMakeLists.txt
- src/sio/CMakeLists.txt
- src/sound/CMakeLists.txt
- src/unix/CMakeLists.txt
- src/video/CMakeLists.txt
Summary
=======
Puts each referenced C file on a separate line, to aid with future branch merge conflict issues. (Originally Lemondrops idea)
Checklist
=========
References
==========
None
> One line per file in CmakeLists.txt

- src/include/86box/video.h
- src/video/vid_ati28800.c
- src/video/vid_table.c
Summary
=======
The ATI VGA Wonder 1024D XL Plus.
Checklist
=========
References
==========
> Add a proper 1MB capable ATI 28800-6 BIOS

- src/disk/hdc_esdi_mca.c
Summary
=======
1. More logs.
2. Placed the required bits in the reset routine to make Xenix 2.3.4q work (at least getting past the reset detection).
3. Some more fixes for OS/2 1.x (proposed by WNT50).
Checklist
=========
References
==========
> ESDI MCA changes of the late night (September 18th, 2024)

- src/video/vid_paradise.c
Summary
=======
Correct the memory size (and its bits) of said chips and reorganize them.
Checklist
=========
References
==========
[WD90c30 manual]
(http://bitsavers.informatik.uni-stuttgart.de/components/westernDigital/_dataBooks/1993_SystemLogic_Imaging_Storage/16_WD90C30A.pdf)
[PVGA1A manual]
(https://bitsavers.trailing-edge.com/components/westernDigital/_dataBooks/1991_SystemLogic_Imaging_Storage/19_PVGA1A.pdf)
> PVGA changes of the day (September 22nd, 2024)

- src/video/vid_ati_mach8.c
Summary
=======
1. Going from screenshots of the Mach32 chips, they all have the ati18811-1 clock regardless of the bus type, whilst the Mach8 has an ati18812, which is actually a ati18811-0
2. Unbreak the NS3.1 Mach32 driver, ergo, don't block the LFB processing.
Checklist
=========
References
==========
> Mach32 and clock changes of the day (September 22nd, 2024)

- src/sound/snd_pas16.c
Summary
=======
And added a note about it.
Checklist
=========
References
==========
> Workaround the volume that is too low on the PAS Plus.

- src/video/vid_xga.c
Summary
=======
Fixed 1MB aperture vram access.
Checklist
=========
References
==========
> XGA aperture fixes of the day (September 24th, 2024)

- src/video/vid_s3.c
Summary
=======
1. Actually fix the remaining pinkish/reddish stuff in 32bpp modes properly (for real, especially OS/2 and possibly other stuff).
2. The Compare accel stuff is more sanitized.
3. When the BitBLT DY coordinates are negative, don't draw the pixels. This fixes some software cursor issues with OS/2's S3 3.03.xx drivers.
4. Reset the FIFO when the card is reset.
5. Indentation fixes (to be improved further however).
6. Implement bit 5 functionality of 0xBEE8 index 0xE (MULT_MISC) (and currently only in the Rectangle Fill command). This fixes missing text on I-O Data Vision968 specific drivers for Windows 3.10 Japanese (PC/AT compatible)
7. Moved the Streams engine out of the FIFO (like the ViRGE) as well as making all CRTC's of the Trio64V2 writable and SEQREGs from 0x10 …
> S3 Pre-ViRGE changes of the day (September 26th, 2024)

- src/video/vid_xga.c
1. SVGA decode mask shouldn't be used in XGA native mode, fixes wrong locks in LFB access.
2. INMOS XGA only: more accurate emulation per INMOS G201 MCA/ISA manual, including the MMIO access and port 0x96, allowing full BIOS and MMIO access at the same time on 0xc0000.
Summary
=======
Checklist
=========
References
==========
[INMOS G201 MCA/ISA manual](https://www.ardent-tool.com/datasheets/INMOS_IMSG201.pdf)
> XGA changes of the day (October 5th, 2024)

- .github/workflows/cmake_macos.yml
- .github/workflows/codeql_macos.yml
Summary
=======
* Switch to macos-13 for github actions
* Add libslirp to macos x86_64
Checklist
=========
References
==========
None
> Switch to macos-13 for github actions

- src/qt/languages/pt-BR.po
> Improvements to 86Box translations for PT-BR

- src/video/vid_xga.c
Summary
=======
1. Pattern/font fixes for Windows 3.1's third party XGA drivers as well as OS/2's win3.x' box (seamless and full).
2. The 4MB aperture is still used internally even if the 1MB one is in use, fixes OS/2's XGA driver on boot when less than 16MB of memory is used.
Checklist
=========
References
==========
> XGA changes of the early day (October 28th, 2024)

- src/video/vid_s3.c
Summary
=======
1. Simplified 4bpp rendering mode.
2. Implement CRTC31 bit 0 functionality which enables/disables the vendor banks. Fixes Diamond Stealth 64 964 VRAM (VLB/PCI) detection on NT 3.1 (and possibly other cards) while keeping NT 3.1 347.1's full screen Command Prompt text normal without garbage using the 911/924 chips.
Checklist
=========
References
==========
> S3 bank update (October 29th, 2024)

- src/video/vid_ati_mach8.c
Summary
=======
1. Added the missing call to mach32_updatemapping from port 0x3CF through its index 6.
2. If the accelerator DAC is active and the extended 256 color bit is on too then enable 8514/A mode when needed, otherwise it's VGA mode or decided by the passthrough/clock selection ports.
3. VGA DAC reads are redirected to the 8514/A DAC reads only when 8514/A mode is on.
Checklist
=========
References
==========
> Even better (hopefully) way to fix the mode switches (November 3rd, 2024)

- src/video/vid_ati_mach8.c
Summary
=======
Mark the ATI extended 8514/A mode accordingly (that is, if bit 5 of ATI reg 0xb0 and using ATI extended ports/8514 RAMDAC ports at the same time). Fixes wrong colors in some instances using standard IBM 8514/A drivers on Mach32.
Checklist
=========
References
==========
> 8514/A compatible changes on Mach32 of the day (November 3rd, 2024)

- src/scsi/scsi_spock.c
Summary
=======
1. The SCSI ID is now more correct about about the difference between physical unit number and actual SCSI ID. This should fix boot freezes on NT 1991 builds for x86 using said card, as well as keeping compatibility the same as before.
Checklist
=========
References
==========
> Spock changes of the day (November 13th, 2024)

- src/qt/languages/nl-NL.po
- src/qt/qt_platform.cpp
- src/qt/qt_translations.qrc.in
Summary
=======
Added Dutch translations.
Checklist
=========
References
==========
Used /src/qt/languages/86box.pot as base for translation.
> Added Dutch translations

- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
Summary
=======
Fix SChinese and TChinese translations
Checklist
=========
References
==========
> Fix SChinese and TChinese translations

- src/disk/hdc_ide.c
- src/disk/hdd.c
- src/include/86box/hdd.h
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_grid.c
- src/machine/machine_table.c
AT/286 based early (1988) laptop with indestructible magnesium case.
Also add emulation of 3 specific Conner HDDs as required by stock 1520 BIOS. It only works with these particular drives and requires them to be somewhat slow or reads will hang. The alternative is to use RomBuster to patch your BIOS.
The machine had 3 display options (640x480 plasma or 2 different LCDs). For now we need to use stock CGA with mono amber monitor to get some of the plasma feel. Next step is to add Yamaha V6366 video card support.
Summary
=======
new machine as described
Checklist
=========
* [ X] This pull request requires changes to the ROM set
* [ X] I have opened a roms pull request - https://github.com/86Box/roms/pull/270/
References
==========
_Provide links to datasheets or other documentation that …
> Add new machine GRiD GRiDcase 1520

- src/sound/ymfm/ymfm.h
- src/sound/ymfm/ymfm_fm.h
- src/sound/ymfm/ymfm_fm.ipp
- src/sound/ymfm/ymfm_opl.cpp
- src/sound/ymfm/ymfm_opm.cpp
- src/sound/ymfm/ymfm_opn.cpp
- src/sound/ymfm/ymfm_opq.cpp
- src/sound/ymfm/ymfm_opz.cpp
Summary
=======
Update YMFM to latest version as of 11/30/2024
Checklist
=========
References
==========
None
> Update YMFM to latest version as of 11/30/2024

- .ci/build.sh
- cmake/llvm-macos-aarch64.cmake
Summary
=======
Checklist
=========
References
==========
Fixing for CI on Mac on linux
> Fix build for mac and linux

- src/machine/m_at_grid.c
Summary
=======
Cleanups and warning fixes to grid 1520
Checklist
=========
References
==========
None
> Cleanups and warning fixes to grid 1520

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
Summary
=======
Update sonar scanner
Checklist
=========
References
==========
None
> Update sonar scanner

- .ci/build.sh
Checklist
=========
References
==========
<https://github.com/macports/macports-ports/commit/1832f91cbcbff49b449a21fa830605c1e1cea43d>
> build.sh: Update the MacPorts OpenAL hack

- src/qt/languages/pt-BR.po
Summary
=======
Better translation of string "None": Nada->Nenhum
> Minor change in pt-BR.po

- src/sound/ymfm/ymfm_fm.ipp
Summary
=======
See above.
Checklist
=========
References
==========
> Make YMFM work again on 86box using OPL2/3.

- src/video/vid_s3_virge.c
Summary
=======
1. Proper pixel clock implemented on GX2 and up chips. Fixes speed on various stuff (including games for Windows).
2. Cleanup.
Checklist
=========
References
==========
> ViRGE changes of the day (December 22nd, 2024)

- src/include/86box/sound.h
- src/sound/snd_sb.c
- src/sound/sound.c
Summary
=======
* [Add SB16 CT2940 no IDE variant](https://github.com/86Box/86Box/commit/0a0c1e349fec38ff9e3d51d18dedd87aa3862ad3)
* [Update SB Copyright](https://github.com/86Box/86Box/commit/14d5b7e259211a18d00db517085cc47202696820)
Checklist
=========
References
==========
> Add SB16 CT2940 no IDE variant

- src/sound/snd_cms.c
Summary
=======
Some additional comments in CMS
Checklist
=========
References
==========
None
> Some additional comments in CMS

- src/include/86box/sound.h
- src/sound/snd_sb.c
For future use
Summary
=======
Add Vibra 16XV (Onboard)
For future use
Checklist
=========
References
==========
None
> Add Vibra 16XV (Onboard)

- src/include/86box/sound.h
- src/sound/snd_sb.c
- src/sound/sound.c
Summary
=======
Add Vibra 16CL
Checklist
=========
References
==========
None
> Add Vibra 16CL

- src/include/86box/snd_sb.h
- src/include/86box/sound.h
- src/sound/snd_sb.c
- src/sound/sound.c
Summary
=======
Add Creative EMU8000 PnP (Goldfinch)
Checklist
=========
References
==========
None
> Add Creative EMU8000 PnP (Goldfinch)

- src/device.c
Summary
=======
Fix various omissions in device.c
Checklist
=========
References
==========
None
> Fix various omissions in device.c

- src/include/86box/snd_akm4531.h
- src/include/86box/sound.h
- src/sound/snd_audiopci.c
- src/sound/sound.c
Summary
=======
Add Ensoniq ES1370
Checklist
=========
References
==========
None
> Add Ensoniq ES1370

- src/sound/snd_audiopci.c
- src/sound/snd_sb.c
Summary
=======
More fixes to parens and normalization of es1370, and cleaning in snd_sb.c too
Checklist
=========
References
==========
None
>  More fixes to parens and normalization of es1370, and cleaning in snd_sb.c too

- src/sound/snd_audiopci.c
Summary
=======
Fixes to es137x code
Checklist
=========
References
==========
None
> Fixes to es137x code

- src/sound/snd_audiopci.c
Summary
=======
Add CT1297 to CT5880, seen on the CT4810
Checklist
=========
References
==========
> Add CT1297 to CT5880, seen on the CT4810

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
Atari PC3 & PC4
Checklist
=========
References
==========
None
> Atari PC3 & PC4

- src/sound/snd_sb.c
- src/sound/snd_sb_dsp.c
Summary
=======
Cleanups and improvements to SB1.x and 2.0
Checklist
=========
References
==========
None
> Cleanups and improvements to SB1.x and 2.0

- src/include/86box/snd_sb.h
- src/sound/snd_azt2316a.c
- src/sound/snd_cmi8x38.c
- src/sound/snd_optimc.c
- src/sound/snd_pas16.c
- src/sound/snd_sb.c
- src/sound/snd_sb_dsp.c
Summary
=======
A few bug fixes according to docs and fw for sb
Also skeleton support for DSP versions
Checklist
=========
References
==========
None
> A few bug fixes according to docs and fw for sb

- src/video/vid_cl54xx.c
Summary
=======
Improved the byte swap fix introduced time ago, this time by making it trigger on banked writes when needed.
Checklist
=========
References
==========
> And Cirrus per the previous commit.

- src/qt/qt_settingsports.cpp
- src/qt/qt_settingsports.hpp
Summary
=======
Fixes some logspam when runnnig under gdb
Checklist
=========
References
==========
None
> Cleanups in qt_settingsports

- src/machine/m_at.c
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
CONFIG_BIOS for IBM 5160, diagnostics and more
Checklist
=========
References
==========
None
> CONFIG_BIOS for IBM 5160, diagnostics and more

- src/device.c
- src/include/86box/device.h
- src/sound/midi.c
Summary
=======
Cleanups in device.c, and some consistency in sound/midi.c
Checklist
=========
References
==========
None
> Device cleanups

- src/machine/m_xt.c
Summary
=======
Add other BIOS versions to ibmpc
Checklist
=========
References
==========
None
> Add other BIOS versions to ibmpc

- src/machine/m_xt.c
Summary
=======
Add other BIOS versions to ibmxt (86)
Checklist
=========
References
==========
None
> Add other BIOS versions to ibmxt (86)

- src/cdrom/cdrom_image_backend.c
- src/cdrom/cdrom_mitsumi.c
- src/config.c
- src/game/joystick_standard.c
- src/game/joystick_sw_pad.c
- src/qt/dummy_cdrom_ioctl.c
- src/qt/qt_settingsinput.cpp
- src/qt/sdl_joystick.c
- src/qt/win_joystick_rawinput.c
- src/unix/dummy_cdrom_ioctl.c
Summary
=======
Random warning fixes and cleaning
Checklist
=========
References
==========
None
> Random warning fixes and cleaning

- src/include/86box/machine.h
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
Summary
=======
Checklist
=========
* [✓] I have discussed this with core contributors already
* [✓] This pull request requires changes to the ROM set
References
==========
> Add ABIT BX6

- src/machine/machine_table.c
Summary
=======
Checklist
=========
References
==========
> Fixed a BX6-related typo

- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_t128.c
Summary
=======
Based on my tests, the former 5380 commit will apply to the 53c400 only, for now...
Checklist
=========
References
==========
> Okay, maybe for the 53c400 only so.

- README.md
Summary
=======
Checklist
=========
References
==========
> Update README.md - added the Avalonia86 manager

- src/include/86box/scsi_ncr5380.h
- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c400.c
Summary
=======
Getting on my nerves, NCR 5380... and fixed the LCS6821 that broke in the previous 5380-based commit.
Checklist
=========
References
==========
> More NCR53c400 fixes (January 13th, 2025)

- src/device/isamem.c
Summary
=======
Quick fixes to the Everex EV-165A
Checklist
=========
References
==========
https://theretroweb.com/expansioncard/documentation/52637.pdf
> Quick fixes to the Everex EV-165A

- src/device/isamem.c
- src/device/isartc.c
- src/machine/m_at.c
- src/machine/m_xt.c
Summary
=======
* Corrections to the AST SixPakPlus
* Add Generic MM58167 RTC
* Add GlaTick ROM to Generic MM58167 RTC
* Cleanups in isartc code
* CONFIG_BIOS for ibmat (5170)
* GlaBIOS for 5150
* GlaBIOS for 5160 (Currently Disabled)
Checklist
=========
References
==========
None
> IBM and RTC Changes

- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
GlaBIOS for Juko ST
Checklist
=========
> GlaBIOS for Juko ST

- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
GlaBIOS for the Vendex HeadStart Turbo 888-XT.
Checklist
=========
> GlaBIOS for Vendex HeadStart Turbo 888-XT

- src/video/vid_8514a.c
- src/video/vid_s3.c
Summary
=======
1. Cosmetic changes.
2. Revert the position of the starting coordinates of the Short Stroke command, fixes some glitches in NT and elsewhere.
Checklist
=========
References
==========
> 8514/A and S3 minor change (January 26th, 2025)

- src/include/86box/machine.h
- src/machine/m_at_socket4.c
- src/machine/machine_table.c
Summary
=======
Add the AT&T Globalyst 330 (Pentium/Socket 4)
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/mitac-trigon-pb5500c
> Add the AT&T Globalyst 330 (Pentium/Socket 4)

- src/device/cartridge.c
- src/game/gameport.c
Summary
=======
* [Fixes to tmacm](https://github.com/86Box/86Box/commit/6725d93b37d42cc317eee10060d196cba95b681d)
* [Actually close cartridge on error](https://github.com/86Box/86Box/commit/26fb3bf69479c8bb8fdd04c51ab4633d31b2a711)
Checklist
=========
References
==========
None
> Some fixes to tmacm and carts

- src/86box.c
- src/config.c
- src/game/gameport.c
- src/game/joystick_ch_flightstick_pro.c
- src/game/joystick_standard.c
- src/game/joystick_sw_pad.c
- src/game/joystick_tm_fcs.c
- src/include/86box/86box.h
- src/include/86box/config.h
- src/include/86box/gameport.h
- src/qt/qt_joystickconfiguration.cpp
- src/qt/qt_settingsinput.cpp
- src/qt/sdl_joystick.c
- src/qt/win_joystick_rawinput.c
- src/unix/unix.c
Summary
=======
Initial work for Gameport instancing
Checklist
=========
References
==========
None
> Initial work for Gameport instancing

- src/device/isamem.c
- src/include/86box/net_ne2000.h
- src/include/86box/network.h
- src/network/net_ne2000.c
- src/network/network.c
- src/qt/win_cdrom_ioctl.c
Summary
=======
* [Rename define+device for lotech EMS board](https://github.com/86Box/86Box/commit/ed54c33c69ad4442568b6f6227c5dc7fd1c6a411)
* [Rename define+device for Realtek 8019AS PNP](https://github.com/86Box/86Box/commit/f6ecf0ab5bf3dd08bb846640e21406fb3c59ffee)
* [Trivial EMS cleanups and a few comments](https://github.com/86Box/86Box/commit/55fdd1498e5586d65fbc828850520445dbccc29c)
* [Fix for building on msys2 clang found by ANightly](https://github.com/86Box/86Box/commit/2f3e3fc92c3b5a5885ea0d3d369e79b1016b4b47)
Checklist
=========
References
==========
None
> Cleanups and a bugfix

- src/scsi/scsi_spock.c
Summary
=======
1. Made logs more consistent.
2. Actually add Write and Verify command, used by IBM OS/2 1.2 Extended, and fixes a hang by said OS after inserting disk 6.
Checklist
=========
References
==========
[IBM PS/2 SCSI](https://www.ardent-tool.com/docs/pdf/ibm_scsiwc_trm.pdf)
> Spock/Tribble (IBM PS/2 SCSI) changes of the late night (February 21st, 2025)

- src/cpu/x87_ops.h
Summary
=======
x87: Fix Final Reality discolored screen for interpreter
Checklist
=========
References
==========
None.
> x87: Fix Final Reality discolored screen for interpreter

- src/cpu/386_dynarec.c
Summary
=======
Fix compile on ARM64
Checklist
=========
References
==========
None.
> Fix compile on ARM64

- src/CMakeLists.txt
Summary
=======
Revert some changes for NDR that were not needed after all.
Checklist
=========
References
==========
None.
> Revert some unnecessary changes for NDR

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE FIFO/3D IRQs now happen in the main thread.
FIFO is also no longer immediately woken up upon writes to 2D/3D MMIO spaces.
Checklist
=========
References
==========
None.
> S3 ViRGE: Make IRQs happen in main thread

- src/qt/qt_settingsports.cpp
Checklist
=========
References
==========
N/A
> Fix the LPT device list duplicating on every machine change

- src/scsi/scsi_spock.c
Summary
=======
1. Make IRQ's more correct and per manual.
2. Only an adapter reset command should reset the SCSI devices connected to it.
3. Differentiate the two controllers by the connector bit (pos3 bit 12) in the CMD GET POS INFO SCB command.
4. Actually emulate bit 7 of pos4 in the pos writes so that selection between 16KB and 32KB rom loading is done properly.
5. Some cleanups.
Checklist
=========
References
==========
[IBM PS/2 Spock manual](https://www.ardent-tool.com/docs/pdf/ibm_scsiwc_trm.pdf)
> Spock/Tribble changes of the day (March 8th, 2025)

- src/sound/snd_pas16.c
Summary
=======
Signal DRQ once the transfers are complete for real.
Checklist
=========
References
==========
> PAS16 SCSI change of the day (March 8th, 2025)

- src/scsi/scsi_t128.c
Summary
=======
1. More accurate speed without stalls.
2. Added more IRQ's for AT compatibles.
Checklist
=========
References
==========
> T128 changes of the evening (March 9th, 2025)

- src/qt/languages/vi-VN.po
Summary
=======
this commit is to fix possible machine translation errors that were made in last commits.
Checklist
=========
References
==========
_none_
> some translation fixes for vi-VN lang

- src/network/net_slirp.c
Summary
=======
- Switch from long-deprecated `slirp_init()` to `slirp_new()`
- Use `slirp_pollfds_fill_socket()`/`[un]register_poll_socket` with libslirp 4.9.0 or later
- Set the DHCP hostname
Checklist
=========
References
==========
N/A
> Handle libslirp deprecations

- src/qt/qt_openglrenderer.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
Screenshots taken with the OpenGL 3.x renderer active are now properly processed.
Checklist
=========
References
==========
None.
> OpenGL 3.x screenshots are now processed

- src/qt/qt_openglshadermanagerdialog.cpp
Summary
=======
Fix more compile errors affecting macOS.
Checklist
=========
References
==========
None.
> Qt: Fix more compile errors

- src/qt/qt_platform.cpp
Summary
=======
Attempt fixing crash on NetBSD
Checklist
=========
References
==========
None.
> Attempt fixing crash on NetBSD

- src/CMakeLists.txt
- src/qt/qt_platform.cpp
- src/unix/unix.c
Summary
=======
Fix building on Haiku OS
Checklist
=========
References
==========
None.
> Fix building on Haiku OS

- src/qt/qt_glsl_parser.cpp
- src/qt/qt_openglshadermanagerdialog.cpp
Summary
=======
Attempt to detect BOMs in GLSL files before loading and parsing them on OpenGL renderer.
Checklist
=========
References
==========
None.
> OpenGL: Attempt detecting BOM before parsing parameters

- src/qt/languages/ja-JP.po
Summary
=======
- Fixes Japanese translation.
Checklist
=========
References
==========
> Fix Japanese translation

- src/network/net_tulip.c
Summary
=======
1. Change the block type of the extended format of the 21143 to 3 and do not issue an IRQ abuse.
Checklist
=========
References
==========
[DEC 21x4 serial rom](http://www.bitsavers.org/components/intel/ethernet/21X4_Serial_ROM_Format_199903.pdf)
> DEC 21x4 changes of the day (March 24th, 2025)

- src/codegen_new/codegen_backend_x86-64_ops.c
Summary
=======
host_x86_MOV8_REG_ABS: Avoid more fatals
Checklist
=========
References
==========
None.
> host_x86_MOV8_REG_ABS: Avoid more fatals

- src/sound/snd_sb.c
Summary
=======
Port Sound Blaster 1.x/2.x SAA1099 emulation to SAASound.
Checklist
=========
References
==========
None.
> Port Sound Blaster 1.x/2.x SAA1099 emulation to SAASound

- src/qt/qt_mainwindow.cpp
Summary
=======
Don't attempt altering window position if fullscreen
Checklist
=========
References
==========
None.
> Don't attempt altering window position if fullscreen

- src/qt/qt_mainwindow.cpp
Summary
=======
Fix compilation on Qt6
Checklist
=========
References
==========
None.
> Fix compilation on Qt6

- .github/workflows/cmake_windows_msys2.yml
Summary
=======
Add Windows 11 ARM64 builds to GitHub Actions
Checklist
=========
References
==========
> Add Windows 11 ARM64 builds to GitHub Actions

- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
Summary
=======
- French translation updates by @jvernet
- Companion translation updates for #5479
- Remove a few more unused strings
- Add a string for 5-button 2-wheel mouse
- Russian translation updates by @usergithub64 (partial merge of #5470)
Checklist
=========
References
==========
N/A
> UI fixes (part 2 - translations)

- src/qt/languages/sv-SE.po
- src/qt/qt_progsettings.cpp
- src/qt/qt_translations.qrc.in
Summary
=======
Contributed by toshineon on Discord.
Checklist
=========
References
==========
N/A
> qt: Add Swedish translation

- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
This adds the Acer P3 machine, which uses the SiS 496/497 chipset.
Checklist
=========
* [X ] This pull request requires changes to the ROM set
* [ X] I have opened a roms pull request - https://github.com/86Box/roms/pull/changeme/
References
==========
> Add Acer P3 (SiS 496) machine.

- src/disk/hdc_ide.c
Summary
=======
DMA-based IDE writes are now reported properly to the UI instead of not being reported properly.
Checklist
=========
References
==========
None.
> DMA-based IDE writes are now reported properly

- src/video/vid_ati_mach8.c
Summary
=======
This patch fixes the pitch that was originally 0 when specifying the 8514/A compatible side in the Mach8/32 cards, which should be 1024 for 8514/A compatible stuff.
Checklist
=========
References
==========
> Fix pitch regression of the ATI Mach8/32 side (April 28th, 2025)

- src/game/joystick_standard.c
Summary
=======
Fix second standard joystick which I'd messed up in a previous commit.
Checklist
=========
References
==========
None
> Fix second standard joystick

- src/video/vid_ati_mach8.c
Summary
=======
See above.
Checklist
=========
References
==========
> Stall fix for the mach8/32 (April 30th, 2025)

- src/video/vid_s3.c
Summary
=======
1. Actually mostly workarounds to make it render normally without a hitch (I hope) using the Diamond Stealth VRAM 911-based 15bpp driver.
2. Updated logs.
Checklist
=========
References
==========
> Fixes to the S3 911/924 of the night (May 4th, 2025)

- src/video/vid_ati_mach8.c
Summary
=======
See above, covering the foreground and background select bits as well.
Checklist
=========
References
==========
> Another stall fix for the mach8/32.

- src/machine/m_at_386dx_486.c
Summary
=======
Checklist
=========
References
==========
> Add the Micro Firmware/Phoenix 4.05 BIOS to the PB450.

- src/video/vid_s3.c
Summary
=======
See above.
Checklist
=========
References
==========
> Some cleanup to the recent fixes on the S3 code (May 6th, 2025)

- src/video/vid_s3.c
Summary
=======
1. Pixtrans on port 0xb2e8 is not available on 864/964 and up (including the trio64) due to color compare taking its place, fixes some graphical glitches in WinXP.
2. The DOS s3id utility identifies the 80x chips correctly, either it's 801 ISA or 805 VLB, but not 805 ISA even if they share the same id, but since it's an ISA card, identify the Elsa Winner 1000 805 ISA as a 801 card.
Checklist
=========
References
==========
> Late night S3 changes (May 9th, 2025)

- src/scsi/scsi_spock.c
Summary
=======
Don't duplicate drives into phantom drives.
Checklist
=========
References
==========
> Spock/Tribble changes of the evening (May 9th, 2025)

- src/qt/win_netsocket.c
Summary
=======
Make sockets from incoming connections nonblocking on Windows
Checklist
=========
References
==========
None.
> Make sockets from incoming connections nonblocking on Windows

- src/machine/m_at_compaq.c
Summary
=======
1. Properly return the flat panel display bit in port 0x1bc6, fixes adapt.com and the corresponding Portable identification in the disk cmos.
2. Preliminary MDA mapping on the Plasma display, per bit 3 toggling of port 0x23c6.
3. Implemented port 0x17c6.
4. Cleanups.
Checklist
=========
References
==========
[Compaq Portable III sources](https://www.seasip.info/VintagePC/compaq3.html)
> Some more Compaq AT changes of the night (May 15th, 2025)

- src/machine/m_at_compaq.c
Summary
=======
Fixes #5011.
Checklist
=========
References
==========
> Compaq Plasma fixes

- src/machine/machine_table.c
- src/video/vid_et4000w32.c
Summary
=======
_This pull request adds the option for VLB cards to the ZEOS Martin._
Checklist
=========
References
==========
> The ZEOS Martin actually has VLB Slots.

- src/network/net_rtl8139.c
Summary
=======
Backport RxConfig fixes from QEMU
Checklist
=========
References
==========
None.
> Backport RxConfig fixes from QEMU

- src/qt/qt_rendererstack.cpp
Summary
=======
Fix cursor clipping on Windows
Checklist
=========
References
==========
None.
> Fix cursor clipping on Windows

- src/acpi.c
- src/chipset/intel_piix.c
- src/device/kbc_at.c
- src/device/postcard.c
- src/dma.c
- src/floppy/fdc.c
- src/include/86box/fdc.h
- src/include/86box/keyboard.h
- src/include/86box/machine.h
- src/include/86box/sio.h
- src/lpt.c
- src/machine/m_at_slot1.c
- src/machine/m_at_slot2.c
- src/machine/m_at_socket7.c
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
- src/nvr_at.c
- src/sio/sio_fdc37c93x.c
- src/sio/sio_pc87307.c
- src/sio/sio_pc87309.c
Summary
=======
Checklist
=========
References
==========
> Add the DellOptiPlex Gn+

- src/device/kbc_at.c
Summary
=======
Checklist
=========
References
==========
> KBC AT: Remove some excess logging.

- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
Checklist
=========
References
==========
> Packard Bell PB410: Fix on-board video.

- src/qt/qt_openglrenderer.cpp
Summary
=======
Attempt to make OpenGL 3.0 filter settings consistent
Checklist
=========
References
==========
None.
> Attempt to make OpenGL 3.0 filter settings consistent

- src/include/86box/machine.h
- src/machine/m_at_socket8.c
- src/machine/machine_table.c
Summary
=======
This commit adds the Dell Dimension XPS Pro___n machine with 440FX chipset and Socket 8 to 86Box
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/dell-dimension-xps-pro___n#docs
> Add the Dell Dimension XPS Pro___n

- src/device/dell_jumper.c
Summary
=======
Checklist
=========
References
==========
> Forgot the dell_jumper.c.

- src/machine/m_xt_olivetti.c
Summary
=======
add Olivetti M240 BIOS 2.12
(freshly dumped from my motherboard) 
Checklist
=========
> add Olivetti M240 BIOS 2.12

- src/video/vid_chips_69000.c
Summary
=======
Some minor fixes for C&T B69000.
Checklist
=========
References
==========
None.
> Some minor fixes for C&T B69000

- src/include/86box/video.h
- src/machine/m_amstrad.c
- src/machine/m_pcjr.c
- src/video/vid_hercules.c
- src/video/vid_mda.c
- src/video/vid_table.c
- src/video/video.c
Summary
=======
Alternate font support for MDA and Hercules
Checklist
=========
References
==========
None
> Alternate font support for MDA and Hercules

- src/include/86box/vid_ega.h
- src/video/vid_ega.c
Summary
=======
* EGA Alternate address support (Behind a compile time gate as we don't yet have a BIOS which supports it)
* some EGA optimizations
Checklist
=========
References
==========
https://minuszerodegrees.net/oa/OA%20-%20IBM%20Enhanced%20Graphics%20Adapter.pdf, (document page 85, actual page 89)
> (compile disabled) EGA Alternate address support and some EGA optimizations

- src/video/vid_ega.c
Summary
=======
It really comes down to the EEPROM for the monitor settings and fixes for resolutions between hdisp > 640 && hdisp < 800 (like MDA)
Checklist
=========
References
==========
> ATI EGA Wonder 800 Plus changes (June 7th, 2025)

- src/86box.c
- src/config.c
- src/device/CMakeLists.txt
- src/device/isarom.c
- src/device/isartc.c
- src/include/86box/86box.h
- src/include/86box/config.h
- src/include/86box/isarom.h
- src/machine/machine.c
- src/qt/qt_deviceconfig.cpp
- src/qt/qt_settingsotherperipherals.cpp
- src/qt/qt_settingsotherperipherals.hpp
- src/qt/qt_settingsotherperipherals.ui
Summary
=======
* [ISA ROM Board Support](https://github.com/86Box/86Box/commit/16975c374f87269b29ea13eb55920bcce1b31feb)
* [Fix missing handller for CONFIG_INT in DeviceConfig::ConfigureDevice](https://github.com/86Box/86Box/commit/d95420a5e664c85721fc561b68e90daf8498d137)
* [Fix bug in generic MM58167](https://github.com/86Box/86Box/commit/b5708db5b02df7bf786a20b08ce4338f2c1a621a)
Checklist
=========
References
==========
None
> ISA ROM Board Support (Plus 2 bug fixes)

- src/qt/languages/pl-PL.po
Summary
=======
This commit was sparkled by the current Polish translation being bad. The most drastic example is how the word 'Unmute' was translated to 'Wycisz', which, translated back, is 'Mute'. Along with some other nonsensical changes, I have figured out that the previous translator just copy-pasted the strings one-by-one to DeepL, without any caring if it's consistent ('Enhanced Color' being translated in singular and plural right next to each other, for example) or makes any sense ('Folder', which is a word in Polish, translated to 'Teczka', which was maybe used in early Mac OS translations and nowhere else).
Checklist
=========
References
==========
> Fix and update pl-PL.po

- src/qt/qt_settingsnetwork.cpp
Summary
=======
Corrections to TAP UI
Checklist
=========
References
==========
None
> Corrections to TAP UI

- src/device/serial_passthrough.c
- src/include/86box/serial_passthrough.h
- src/qt/win_serial_passthrough.c
- src/unix/unix_serial_passthrough.c
Summary
=======
Named pipe client on windows
Checklist
=========
References
==========
None
> Named pipe client on windows

- src/video/vid_cga.c
Summary
=======
More magic number work in CGA
Checklist
=========
References
==========
None
> More magic number work in CGA

- src/include/86box/machine.h
- src/include/86box/video.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
- src/video/vid_cl54xx.c
Summary
=======
_See above._
Checklist
=========
References
==========
> Add ICL DRS M35/286.

- src/include/86box/machine.h
- src/machine/m_at_socket4.c
- src/machine/machine_table.c
Summary
=======
_See above._
Checklist
=========
References
==========
> Add the Acer V12P + two RAM corrections which I forgot.

- src/include/86box/renderdefs.h
- src/qt/qt.c
- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
Summary
=======
Deal with renderer magic numbers
Checklist
=========
References
==========
None
> Deal with renderer magic numbers

- .github/workflows/cmake_macos.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
- src/86box.c
- src/cdrom/cdrom_image_viso.c
- src/codegen_new/codegen_backend_x86-64_ops.c
- src/cpu/386_ops.h
- src/cpu/cpu.h
- src/cpu/softfloat3e/s_shiftRightJam256M.c
- src/device/isarom.c
- src/disk/hdc_xtide.c
- src/nvr.c
- src/qt/dummy_cdrom_ioctl.c
- src/qt/qt_downloader.hpp
- src/qt/qt_glsl_parser.cpp
- src/qt/qt_keybind.hpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_updatedetails.cpp
- src/qt/qt_vmmanager_main.cpp
- src/qt/win_serial_passthrough.c
- src/qt/wl_mouse.cpp
- src/unix/dummy_cdrom_ioctl.c
- src/unix/unix.c
- src/utils/log.c
- src/video/vid_jega.c
Summary
=======
[Many warning fixes](https://github.com/86Box/86Box/commit/3a26b9d46be193096f7d1aa599d988a92c1d8c86)
[Do less work on Github Actions](https://github.com/86Box/86Box/commit/cb5cb7e660093d0f3b8977160b4d9bc5a64d4d3e)
[Some codeql fixes](https://github.com/86Box/86Box/commit/026f76549565344c78e6d0aa5f6c777b6f93f358)
[Correct some macos GHA deps](https://github.com/86Box/86Box/commit/a560abe2aaf98269f6055539bc93899270a22344)
Checklist
=========
References
==========
None
> Warning & codeql fixes

- src/cpu/x87_ops_arith.h
Summary
=======
x86-specific FADD implementation
Checklist
=========
References
==========
None.
> x86-specific FADD implementation

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
Checklist
=========
References
==========
> Adjust the timings of the 8514/A and compatibles (June 30th, 2025)

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
Summary
=======
Updates to GHA scripts and GHA arm64 Linux build support
Checklist
=========
References
==========
None
> Updates to GHA scripts and GHA arm64 Linux build support

- src/include/86box/vid_cga.h
- src/include/86box/vid_quadcolor.h
- src/include/86box/video.h
- src/machine/m_xt_zenith.c
- src/video/CMakeLists.txt
- src/video/vid_cga.c
- src/video/vid_cga_olivetti.c
- src/video/vid_cga_quadcolor.c
- src/video/vid_table.c
Summary
=======
Quadram QuadColor 1+ 2
Checklist
=========
References
==========
https://github.com/sarah-walker-pcem/pcem/pull/281
> Quadram QuadColor 1+ 2

- src/86box.c
- src/config.c
- src/cpu/386_dynarec.c
- src/include/86box/86box.h
- src/qt/qt_main.cpp
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsmachine.hpp
- src/qt/qt_settingsmachine.ui
Summary
=======
Switch to 1ms CPU frame intervals by default, significantly improving smoothness.
Checklist
=========
References
==========
None.
> Switch to 1ms frame intervals

- src/include/86box/net_dp8390.h
- src/network/net_3c503.c
- src/network/net_dp8390.c
- src/network/net_ne2000.c
- src/network/net_wd8003.c
Fixes Netware related sessions with the ne2000 and possibly other dp8390-based cards (code is from DOSBox-x where it was working there too).
Summary
=======
Checklist
=========
References
==========
> Actually fix Loopback interrupt.

- src/machine/machine_table.c
Summary
=======
Correct internal name for Tandy 1000 SX
Checklist
=========
References
==========
None
> Correct internal name for Tandy 1000 SX

- src/unix/unix.c
Summary
=======
Fix small frames on SDL backend
Checklist
=========
References
==========
None.
> Fix small frames on SDL backend

- src/qt/qt_settingsmachine.ui
- src/qt/qt_vmmanager_mainwindow.cpp
- src/qt/qt_vmmanager_mainwindow.hpp
- src/qt/qt_vmmanager_mainwindow.ui
Summary
=======
Fix placement of CPU frame size option, also add Exit option
Checklist
=========
References
==========
None.
> Fix placement of CPU frame size option, also add Exit option

- src/qt/qt_vmmanager_addmachine.cpp
- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_main.hpp
- src/qt/qt_vmmanager_preferences.cpp
Summary
=======
Hide and disable update checker on custom builds
Checklist
=========
References
==========
None.
> Hide and disable update checker on custom builds

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_vmmanager_clientsocket.cpp
- src/qt/qt_vmmanager_clientsocket.hpp
- src/qt/qt_vmmanager_details.cpp
- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_protocol.cpp
- src/qt/qt_vmmanager_protocol.hpp
- src/qt/qt_vmmanager_serversocket.cpp
- src/qt/qt_vmmanager_serversocket.hpp
- src/qt/qt_vmmanager_system.cpp
- src/qt/qt_vmmanager_system.hpp
Summary
=======
Implement focus-shifting on Windows and waiting status.
Checklist
=========
References
==========
None.
> Implement focus-shifting on Windows and waiting status

- src/qt/languages/tr-TR.po
Summary
=======
This commit fixes various errors in the Turkish translation (provided by the tr-TR.po file in src/qt/languages), while also improving its consistency with the original English translation.
Checklist
=========
References
==========
N/A
> Turkish translation (tr-TR.po) fixes and improvements

- src/qt/qt_rendererstack.cpp
Summary
=======
Checklist
=========
References
==========
> Clip the cursor to the focused window

- src/device/mouse.c
- src/device/mouse_serial.c
- src/include/86box/mouse.h
Summary
=======
Microsoft Serial BallPoint mouse.
Checklist
=========
References
==========
None.
> Microsoft Serial BallPoint mouse

- src/scsi/scsi_pcscsi.c
Summary
=======
Checklist
=========
References
==========
> Ported the latest changes of the ESP code from QEMU to 86box (July 19th, 2025)

- src/cdrom/cdrom_mitsumi.c
- src/include/86box/cdrom_mitsumi.h
Summary
=======
Allow configuring IO, IRQ and DMA
Checklist
=========
References
==========
None.
> Improvements to mitsumi CDROM configuration

- src/cdrom/cdrom_mitsumi.c
Summary
=======
Some improvements towards mitsumi cdrom image handling
Checklist
=========
References
==========
None
> Some improvements towards mitsumi cdrom image handling

- src/chipset/scamp.c
- src/chipset/wd76c10.c
- src/cpu/808x.c
- src/qt/qt_openglrenderer.cpp
- src/sound/midi_opl4.c
- src/video/vid_bochs_vbe.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/video.c
Summary
=======
Fix several codeql warns
Checklist
=========
References
==========
None
> Fix several codeql warns

- src/cdrom/cdrom_mke.c
Summary
=======
Panasonic/MKE OS freeze fixes (redo)
Checklist
=========
References
==========
None.
> Panasonic/MKE OS freeze fixes (redo)

- src/qt/languages/pl-PL.po
Summary
=======
Fix some typos and accelerators at the same time.
Checklist
=========
References
==========
> Add Polish strings for #5859

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_vmmanager_clientsocket.cpp
- src/qt/qt_vmmanager_clientsocket.hpp
- src/qt/qt_vmmanager_details.cpp
- src/qt/qt_vmmanager_details.hpp
- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_main.hpp
- src/qt/qt_vmmanager_mainwindow.cpp
- src/qt/qt_vmmanager_model.cpp
- src/qt/qt_vmmanager_model.hpp
- src/qt/qt_vmmanager_protocol.cpp
- src/qt/qt_vmmanager_protocol.hpp
- src/qt/qt_vmmanager_serversocket.cpp
- src/qt/qt_vmmanager_serversocket.hpp
- src/qt/qt_vmmanager_system.cpp
- src/qt/qt_vmmanager_system.hpp
Summary
=======
Update the machine configuration displayed in the details pane if it has been changed.
Checklist
=========
References
==========
N/A
> Manager: Update machine configuration on change

- src/include/86box/sound.h
- src/sound/CMakeLists.txt
- src/sound/snd_adlib.c
- src/sound/snd_covox.c
- src/sound/sound.c
Summary
=======
ISA Covox's and clones
Checklist
=========
References
==========
https://archive.org/details/knobelkiste_kryoflux_202508
> ISA Covox's and clones

- src/scsi/scsi_aha154x.c
- src/scsi/scsi_pcscsi.c
And restore the hostid configuration of the Aha154xA/B.
Summary
=======
Checklist
=========
References
==========
> Add DC2974 AM53c974 bios images.

- src/config.c
Summary
=======
Fix incorrect internal name
Checklist
=========
References
==========
None.
> Fix incorrect internal name

- src/qt/qt_vmmanager_system.cpp
Checklist
=========
References
==========
N/A
> Fix build failure with Qt 6

- .github/workflows/cmake_linux.yml
Checklist
=========
References
==========
N/A
> Github Actions: Add Linux Qt 6 builds

- src/qt/qt_vmmanager_config.cpp
- src/qt/qt_vmmanager_system.cpp
Checklist
=========
References
==========
N/A
> Fix build failures with Qt 6

- src/qt/qt_vmmanager_main.cpp
Summary
=======
[Implement VM cloning option.](https://github.com/86Box/86Box/commit/985468a7a7914ce912b2f093ecac8a13dded3b75)
Checklist
=========
References
==========
None.
> Implement VM cloning option

- src/qt/qt_vmmanager_main.cpp
Summary
=======
Some fixes
Checklist
=========
References
==========
None.
> Some fixes

- src/video/vid_et4000w32.c
Summary
=======
Fixes for Dangerous Dave on ET4000/w32 cards.
Checklist
=========
References
==========
None.
> Fixes for Dangerous Dave on ET4000/w32 cards

- src/qt/languages/es-ES.po
Reviewing and changes.
there are some mistake.
may will result wrong.
Changes:
Change Vytvoř to Generar. Should be Crear?
Change Cabezas to Cabezal
src:
https://es.wikipedia.org/wiki/Cilindro-Cabezal-Sector
Summary
=======
Checklist
=========
References
==========
> Reviewing and changes es-ES.po

- src/include/86box/video.h
- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/video/vid_table.c
- src/video/video.c
Summary
=======
Add display for refresh rates in status bars.
Checklist
=========
References
==========
None.
> Add display for refresh rates in status bars

- src/sio/sio_fdc37c669.c
- src/sio/sio_gm82c803ab.c
- src/sio/sio_gm82c803c.c
- src/sio/sio_pc87307.c
- src/sio/sio_pc87309.c
- src/sio/sio_pc873xx.c
Summary
=======
Several Clang warning fixes.
Checklist
=========
References
==========
None.
> Several Clang warning fixes

- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
Summary
=======
This PR fixes a missing tag in one of the msgid from the previous PR #5931
Checklist
=========
References
==========
None.
> Update 2 to template and translations

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/include/86box/vid_svga.h
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
Satisfy refresh rates correctly on said chips and add the clock chip of the add-on 8514/A Ultra.
Checklist
=========
References
==========
> ATI Pre-Mach64 (Mach8, Mach32) changes

- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/qt/qt_updatecheckdialog.ui
- src/qt/qt_vmmanager_main.cpp
Summary
=======
- Update the Russian translation
- Remove two unused strings
- Fix two typos
Checklist
=========
References
==========
N/A
> Text and translation update

- src/qt/languages/zh-CN.po
Summary
=======
My summary is as the title suggests, to correct a mistake in my previous commit.
Checklist
=========
References
==========
> Correct a mistake in zh-CN.po

- src/qt/languages/cs-CZ.po
Summary
=======
Checklist
=========
References
==========
> Fix Czech translation of manager strings

- src/video/vid_ati28800.c
Summary
=======
Checklist
=========
References
==========
> Fix clocks of the ATI 28800 series of cards

- src/qt/languages/tr-TR.po
Summary
=======
Updates the Turkish (tr-TR) translation to cover any untranslated strings, as well a few minor changes with regards to loanwords.
Checklist
=========
References
==========
> Update Turkish (tr-TR) translation

- src/qt/languages/cs-CZ.po
Summary
=======
Checklist
=========
References
==========
> More Czech translation fixes

- src/include/86box/video.h
- src/video/vid_s3_virge.c
- src/video/vid_table.c
Summary
=======
Remove the PCI version since it was never announced or produced and add the 2 MB version of the card. 
More details about the card can be found here:
https://ftp.kkatarn.ru/drivers-backup/video/ancient/Diamond/html/eng/products/stealth/s3d4k_ts.htm
Checklist
=========
References
==========
> Diamond Stealth 3D 4000 changes

- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
Summary
=======
Minor fixes for Finnish and French languages.
Checklist
=========
References
==========
None.
> Minor updates for fi-FI and fr-FR

- src/qt/qt_mainwindow.cpp
Summary
=======
qt_mainwindow.cpp: Cleanups.
Checklist
=========
References
==========
None.
> qt_mainwindow.cpp: Cleanups

- src/qt/qt_mainwindow.cpp
Summary
=======
Fix shortcuts not working with numpad when on fullscreen.
Checklist
=========
References
==========
None.
> Fix shortcuts not working with numpad when on fullscreen

- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
Summary
=======
More accurate translation for Portuguese (Portugal, Brazilian) languages
Checklist
=========
References
==========
None.
> More accurate translation for Portuguese languages

- src/cpu/808x_biu.c
Summary
=======
Checklist
=========
* [x ] I have discussed this with core contributors already
References
==========
> Update 808x_biu.c to fix prefetcher timing

- src/scsi/scsi_pcscsi.c
Summary
=======
Checklist
=========
References
==========
> Minor cleanup on 53c9x code (September 7th, 2025)

- src/86box.c
- src/arch_detect.c
- src/chipset/compaq_386.c
- src/cpu/386_common.h
- src/cpu/cpu.h
- src/cpu/x87_ops.h
- src/floppy/lzf/lzf_d.c
- src/include/86box/bswap.h
- src/include/86box/machine.h
- src/include/86box/mem.h
- src/machine/machine_table.c
- src/mem/mem.c
- src/mem/row.c
- src/mem/smram.c
- src/printer/prt_ps.c
- src/qt/qt_platform.cpp
- src/utils/random.c
Removed 32-bit specific code from the memory manager, as well as a few remnants in the buildscripts
> Clean up some remaining 32bit stuff

- src/include/86box/plat.h
- src/mem/rom.c
- src/qt/qt_platform.cpp
- src/unix/unix.c
Summary
=======
Introduce `plat_file_check` and use it for ROM existence checking.
Checklist
=========
References
==========
None.
> Introduce `plat_file_check` and use it for ROM existence checking

- src/qt/qt_main.cpp
Summary
=======
Always use desktop OpenGL implementations.
Checklist
=========
References
==========
None.
> Always use desktop OpenGL implementations

- src/sound/midi.c
I was consistently seeing an issue where MIDI input would cause my guest VM to hang.  This pull request resolves the issue.
> BUGFIX: MIDI In causes VM hang when sysex message received.  

- src/qt/qt_vmmanager_system.cpp
Summary
=======
Checklist
=========
References
==========
N/A
> Manager: Indicate Voodoo SLI in the details pane

- src/qt/languages/86box.pot
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nb-NO.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsmachine.ui
Summary
=======
Add ability to search for machines in machine settings.
Checklist
=========
References
==========
None.
> Add ability to search for machines in machine settings

- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
Summary
=======
Update Language Module: Simp-Chinese and Trad-Chinese (05/10/2025)
Checklist
=========
> Update Language Module: Simp-Chinese and Trad-Chinese

- src/config.c
- src/game/joystick_ch_flightstick_pro.c
- src/game/joystick_standard.c
- src/game/joystick_sw_pad.c
- src/game/joystick_tm_fcs.c
Summary
=======
A little more progress towards dual gameport support
Checklist
=========
References
==========
None
> A little more progress towards dual gameport support

- src/video/vid_ati_mach64.c
Summary
=======
Gamma correction support for Mach64VT2.
Checklist
=========
References
==========
None.
> Gamma correction support for Mach64VT2

- src/include/86box/video.h
- src/video/vid_ati_mach64.c
- src/video/vid_table.c
Summary
=======
Add ATi Mach64 VT emulation.
Checklist
=========
References
==========
None.
> Add ATi Mach64 VT emulation
