86Box/86Box

- src/86box.c
- src/codegen_new/codegen_backend_arm64_ops.c
- src/cpu/386_dynarec.c
- src/cpu/808x/queue.c
- src/cpu/cpu.h
Summary
=======
Cleaning up some clang warnings. A few are specific to arm64 macOS and gated appropriately.
Checklist
=========
References
==========
N/A
> Clang warning cleanup

- src/include/86box/plat.h
- src/qt/qt_platform.cpp
- src/unix/unix.c
- src/win/win.c
Summary
=======
`plat_get_cpu_string` uses different methods to try and get the cpu string. These methods vary by OS. If it can't be determined it simply returns `Unknown`.
It is only really implemented in qt. There are stubs in unix and win that also return `Unknown`.
* Mac: `sysctl`
* Windows: registry key
* Linux: `/proc/cpuinfo`
Checklist
=========
References
==========
N/A
> Add new platform function to get cpu string

- src/qt/qt_platform.cpp
Summary
=======
Use `QRegularExpression` instead of `QRegExp` to ensure compatibility with qt6.
Checklist
=========
References
==========
N/A
> qt: Fix qt6 regex compatibility

- src/sound/snd_opl_ymfm.cpp
- src/sound/ymfm/ymfm.h
- src/sound/ymfm/ymfm_fm.ipp
- src/sound/ymfm/ymfm_opl.cpp
- src/sound/ymfm/ymfm_opm.cpp
- src/sound/ymfm/ymfm_opn.cpp
- src/sound/ymfm/ymfm_opq.cpp
- src/sound/ymfm/ymfm_opz.cpp
Summary
=======
Cleaning up a bunch of ymfm warnings:
* One such warning revolved around the YMF278B implementation. The index was based around a ternary which made gcc unhappy. Cleaned up by matching the official example (existing code did not match)
* Another issue was cleaned up by adding a conditional to make gcc happy (this one resulted in several warnings)
In addition, all `sprintf`s were cleaned up to `snprintf`s to make clang happy. Since ymfm uses pointer arithmetic to write to the buffer a special macro had to be created to be passed to `snprintf` and properly calculate the remaining size. You'll see the macro as `SNPRINTF_BUFFER_SIZE_CALC`.
Checklist
=========
References
==========
N/A
> ymfm: Clean up numerous warnings

- src/qt/qt_vulkanrenderer.cpp
- src/qt/qt_vulkanrenderer.hpp
- src/qt/sdl_joystick.cpp
- src/sound/munt/MidiStreamParser.cpp
- src/sound/munt/Part.cpp
Summary
=======
Some more warning cleanups. `sprintf` and unused vars.
I think `qt_vulkanrenderer.hpp` got converted from CRLF->LF when I modified it.
Checklist
=========
References
==========
N/A
> More sprintf and warning cleanup

- src/cdrom/cdrom_image_viso.c
- src/codegen_new/codegen_backend_arm64_ops.c
- src/cpu/codegen_timing_pentium.c
- src/disk/minivhd/manage.c
- src/unix/unix_serial_passthrough.c
- src/video/vid_xga.c
Summary
=======
These are primarily for gcc on linux.
* Fix up some buffer sizes to where gcc won't be upset about possible truncation
* Move some printf formatters to `PRIu64` which will work across all platforms
* Assign a return variable to some `fread`s and `write`s. These were triggering `-Wunused-result` because the functions have the attribute `warn_unused_result`.
* Note that the return value isn't checked or acted upon, just assigned to make gcc happy.
Tested the changes for warnings on mac (clang), linux (gcc) and windows (gcc). 
Checklist
=========
References
==========
N/A
> More warning cleanups

- src/device/postcard.c
Summary
=======
Clean up postcard string operations to make gcc happy on linux.
* `sprintf` -> `snprintf`
* Adjust buffer sizes so strings won't get truncated
Checklist
=========
References
==========
N/A
> postcard: Clean up some gcc warnings

- src/device/isapnp.c
Summary
=======
Reverts a macro change in 6bc73bfc9 which causes the macro to sometimes get optimized out.
Checklist
=========
References
==========
N/A
> isapnp: Revert macro changes

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
1. Hopefully fixed the passthrough stuff for good and fixed typo's in the IBM 8514/A poll function about the cursor.
2. Eliminated the ibm8514_on global variable in favor of a struct variable to be consistent with XGA.
Checklist
=========
References
==========
> New batch of ATI Mach8/32 changes:

- src/video/vid_ati68860_ramdac.c
Summary
=======
Now the ATI 68860 RAMDAC is using the proper 8514/A ON flag when needed.
Checklist
=========
References
==========
> Compile fix.

- src/disk/minivhd/manage.c
Summary
=======
Restore an `fread()` that was accidentally removed during a cleanup in https://github.com/86Box/86Box/commit/375f69ed611a404765034547353f3b639ef39805#diff-d72bfe3a78e6ceb45ad18538746a43d7a89dd5bdea6958276ed0c2760086cef7L449, causing VHD support to break.
Checklist
=========
> Fix broken VHD handling

- src/include/86box/machine.h
- src/machine/m_at_compaq.c
- src/machine/machine_table.c
Summary
=======
Changed to the May 1988 due to malformed status of the January 1988 one.
Checklist
=========
References
==========
> Compaq Deskpro 386 1988 BIOS ROM change:

- src/include/86box/path.h
- src/qt/qt_platform.cpp
- src/unix/unix.c
- src/win/win.c
Summary
=======
The qt version of `path_get_slash` was returning a pointer to a string defined locally in the function. This was causing garbage to be returned from whatever memory location after it went out of scope.
I simplified the function based on what it was performing. I also changed the return type from `char *` to `const char*` to make things more simple. Header, QT, win, unix files were updated with the new signature.
Checklist
=========
References
==========
N/A
> Fixing up path_get_slash return value

- src/include/86box/cdrom.h
- src/scsi/scsi_cdrom.c
Summary
=======
Change the NEC CD-ROM DRIVE:74 to 75 due to the former being buggy on NT.
Checklist
=========
References
==========
> Change NEC CD-ROM DRIVE:74 to 75.

- src/video/vid_8514a.c
Summary
=======
Replaced svga->bpp == 24 with dev->accel_bpp == 24 as well as proper ATI graphics engine offsets added to 24bpp mode in the 8514/A rectangle fill commands (cmd 2, 3, 4) as well as on a command val of 8514/A bitblt (mainly 0xc2b5, actual cmd 6). This should fix 24bpp mode under Windows/NT and other operating systems, like OS/2 2.x/Warp.
Checklist
=========
References
==========
> More 8514/A related fixes:

- src/qt/qt_settingsnetwork.ui
Checklist
=========
References
==========
N/A
> qt: Remove a trailing space in a label in qt_settingsnetwork.ui

- src/include/86box/plat_fallthrough.h
- src/include/86box/plat_unused.h
Summary
=======
Make plat_fallthrough and plat_unused headers less fragile
Checklist
=========
References
==========
None
> Make plat_fallthrough and plat_unused headers less fragile

- src/qt/qt_settingsmachine.ui
Summary
=======
Revert the (visual, UI) machine settings updates while maintaining the new PIT option. Only the ui file is changed.
The PIT option is (for now) placed on the same line as wait states.
Checklist
=========
References
==========
N/A
> Revert earlier machine settings updates

- src/qt/qt_harddrive_common.cpp
Summary
=======
Temporarily hide the Mitsumi CD-ROM bus in the bus dropdown on the floppy/CD-ROM settings page for the 4.0 release
Checklist
=========
References
==========
N/A
> qt: Temporarily hide the Mitsumi CD-ROM bus in dropdowns

- src/qt/qt_deviceconfig.cpp
- src/qt/qt_harddiskdialog.ui
- src/qt/qt_joystickconfiguration.cpp
- src/qt/qt_joystickconfiguration.ui
- src/qt/qt_newfloppydialog.ui
- src/qt/qt_progsettings.ui
- src/qt/qt_settingsdisplay.ui
- src/qt/qt_settingsfloppycdrom.ui
- src/qt/qt_settingsharddisks.ui
- src/qt/qt_settingsinput.ui
- src/qt/qt_settingsmachine.ui
- src/qt/qt_settingsnetwork.ui
- src/qt/qt_settingsotherperipherals.ui
- src/qt/qt_settingsotherremovable.ui
- src/qt/qt_settingsports.ui
- src/qt/qt_settingssound.ui
- src/qt/qt_settingsstoragecontrollers.ui
Summary
=======
Expand the number of items visible in expanded comboboxes to 30 from the default 10.
Checklist
=========
References
==========
N/A
> qt: Expand the number of items displayed in comboboxes to 30

- src/qt/qt_mainwindow.ui
Summary
=======
Reverts the toolbar changes, adds a separator before ACPI shutdown. Only the ui file is changed.
Checklist
=========
References
==========
N/A
> Revert toolbar changes, add separator

- src/gdbstub.c
Summary
=======
This PR fixes a build issue that occurred while building with GDB stub support (`-DGDBSTUB=ON`) enabled, as can be seen in:
```text
$ cmake -DGDBSTUB=ON ..
...
$ make
...
/home/david/86Box/src/gdbstub.c: In function ‘gdbstub_client_write_reg’:
/home/david/86Box/src/gdbstub.c:551:14: error: ‘GDB_REG_FS_BASE’ undeclared (first use in this function); did you mean ‘GDB_REG_FSTAT’?
551 |         case GDB_REG_FS_BASE ... GDB_REG_GS_BASE:
|              ^~~~~~~~~~~~~~~
|              GDB_REG_FSTAT
```
The issue was introduced in commit 565421a, which commented out the `GDB_REG_FS_BASE` and `GDB_REG_GS_BASE` registers, but did not remove the code snippets that referenced them in `gdbstub_client_write_reg()`. This PR comments out those code snippets as well.
Additionally, I've …
> Fix GDB stub builds due to undeclared symbol

- src/gdbstub.c
Summary
=======
This PR brings two small fixes that prevents from using GDB stub normally:
1. Fixes an out-of-bounds issue when the `ENABLE_GDBSTUB_LOG` flag is set.
2. Remove an additional space in the response of the 'qfThreadInfo' package that prevents GDB from recognizing the current thread.
With these fixes, GDB now works like a charm here.
(There is a more detailed explanation of each fix in the commit messages)
Checklist
=========
References
==========
https://sourceware.org/gdb/onlinedocs/gdb/General-Query-Packets.html
> GDB stub small fixes: out-of-bounds and wrong packet reply in 'qfThreadInfo'

- src/unix/assets/86Box.spec
Summary
=======
86Box 4.0 has additional dependencies which were missing from the RPM spec file
Checklist
=========
> Add new 4.0 dependencies to RPM spec file

- src/config.c
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsmachine.hpp
- src/win/win_settings.c
Summary
=======
Disable the SoftFloat FPU option if no FPU (including internal) is present
Checklist
=========
References
==========
N/A
> Disable the softfloat checkbox when no FPU is selected

- src/machine/machine_table.c
- src/qt/qt_mainwindow.cpp
- src/sound/snd_gus.c
Summary
=======
1. Disable the "Enable Discord integration" menu item if the Discord library fails to load
2. Mark the Quadtel 286 clone as requiring SoftFloat FPU to make the "80287 internal register error" go away
3. Dev branch only: Fix the GUS MAX's CS4231 codec using the incorrect DMA channel for playback; add support for the correct (GF1's record) channel
Checklist
=========
References
==========
For item 3: [UltraSound Lowlevel ToolKit, Revision 2.22](http://dk.toastednet.org/GUS/docs/UltraSound%20Lowlevel%20ToolKit%20v2.22%20(21%20December%201994).pdf), page 123 (129) - "Note that the DMA channels appear flipped between the GF1 and the codec. This is to allow us to DMA to dram to load patches while the codec is busy playing back .WAV data."
> Assorted fixes

- src/86box.c
Summary
=======
Fix crash when using PLIP networking - attempt to fix #3699.
I've swapped the order of initialization of the LPT and network modules to ensure the network module can access the LPT instance and fill in the card details.
I hope there are no side-effects to this change.
Checklist
=========
References
==========
None
> Init LPT before Network to fix PLIP mode.

- src/unix/unix_serial_passthrough.c
Summary
=======
The logic for clearing bits in termios.c_flag was reversed. That caused clearing of all the other flags than which were intended to be cleared, which in turn caused the host serial port to be stuck at random and unusable configuration (5 data bits on macOS).
Checklist
=========
> fix flags for serial passthrough on unix

- src/include/86box/scsi_x54x.h
- src/include/86box/vid_xga.h
- src/machine/m_ps2_mca.c
- src/scsi/scsi_aha154x.c
- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_x54x.c
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_cl54xx.c
- src/video/vid_im1024.c
- src/video/vid_paradise.c
- src/video/vid_svga.c
- src/video/vid_tgui9440.c
- src/video/vid_xga.c
Summary
=======
1. Cirrus Logic GD54xx, Paradise/WD VGA now reset the interlace once a text mode is issued if not done automatically.
2. Paradise/WD's 15/16bpp modes using the 800x600 resolution now have the correct ma_latch, should fix most operating systems drivers using this combo.
3. More fixes (hopefully) to the accelerated pitch and rowoffset of the Trident TGUI cards (9440AGi and 96x0XGi), should fix issues with delayed displays mode changes under various operating systems (e.g.: Win3.1x).
4. Preliminary implementation of the Area Fill command of XGA, which is issued while using various painting and/or calc utilities on Win3.1x (IBM XGA updated drivers, e.g.: 2.12).
5. Preliminary (and incomplete) 4bpp XGA mode.
6. The XGA memory test for the 0xa5 using writes (used by various …
> Video, Storage and MCA changes/fixes.

- .github/workflows/cmake.yml
Summary
=======
Make the windows QT packages static and avoid bundling needless libraries.
Disable the macos artifact creation for now as it's broken and I don't know the right solution. (Avoid needless build failure reports)
Checklist
=========
References
==========
None
> GHA changes

- src/qt/qt_main.cpp
- src/qt/qt_settingsmachine.cpp
- src/win/win_settings.c
Summary
=======
Reintroduce a warning message on startup when cpu_override is enabled that was present in the Win32 UI. Also allow dynarec to be disabled on dynarec-only CPUs (falling back to interpeter) in the UI when cpu_override is on.
Checklist
=========
References
==========
N/A
> qt: Add a warning when cpu_override is enabled

- .github/workflows/cmake.yml
Summary
=======
Fix a homebrew issue with `libsndfile` and enable the build again in GHA.
There's a library / packaging issue with the `libsndfile` bottle in homebrew which causes the bundling to fail. Until that issue is addressed we need to have GHA build `libsndfile` from source.
Checklist
=========
References
==========
N/A
> GHA: Enable mac builds, homebrew fixes

- src/video/vid_ati_mach64.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_tgui9440.c
Summary
=======
ATI Mach64 is temporarily unthreaded because of blitter desyncing.
ATI Mach32 now returns to ATI mode from IBM mode and vice versa more correctly.
Make the IBM 8514/A compatible poll not run if a 3D add-on card (Voodoo1/2) takes precedence (seen on a Mach32 PCI and Voodoo2 3D combo).
Finally ended the mess ups of the TGUI9440/96x0 pitch, it actually was the CRTC offset reg (SVGA CRTC 0x13) that defined it with some shifting based on the BPP.
Checklist
=========
References
==========
TGUI9440/96x0.
[Only thing regarding about said chipset](https://android.googlesource.com/kernel/tegra/+/android-tegra-flounder-3.10-lollipop-release/drivers/video/tridentfb.c)
> More video fixes:

- README.md
Summary
=======
Removes WinBox and 86Box Manager Lite from the README file. Both are no longer maintained.
Checklist
=========
References
==========
N/A
> README update: Remove unmaintained managers

- cmake/flags-gcc.cmake
Summary
=======
Remove the C/C++ standard flags from the toolchain files that never worked anyway due to `CMAKE_(C|CXX)_STANDARD` overriding them and were potentially compilation-breaking due to disabling compiler extensions.
Checklist
=========
References
==========
N/A
> Remove the C/C++ standard flags from the toolchain files

- src/video/vid_svga.c
Summary
=======
The XGA memory test takes account of Win3.x' XGA memory test again without conflicting XGAKIT's test, fixes DOS-based boxes using Win3.x XGA drivers in 386 mode.
Checklist
=========
References
==========
> VGA/XGA memory fix.

- src/network/net_pcap.c
`u_int` and `u_char` are not portable type aliases and are not available on all systems. this change alters net_pcap.c to instead use the standard `unsigned char` and `unsigned int` type names. this change allows 86Box to be built on Linux distributions that use musl-libc instead of glibc.
> net_pcap: use standard unsigned type names

- src/video/vid_ati_mach8.c
Summary
=======
Small mach32/svga mapping fix (actually fixes font rendering on win3.1x using the Mach32 2.6 drivers)
Checklist
=========
References
==========
> Small Mach32/SVGA font mapping fix.

- src/qt/qt_harddrive_common.cpp
Checklist
=========
References
==========
N/A
> Fix speeds other than RAM disk not being selectable for SCSI or ATAPI HDDs

- src/cpu/cpu_table.c
- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
Summary
=======
This adds support for the Hyundai Super-286C.
This is a fairly standard NEAT machine.
Checklist
=========
(discussed in discord a few months ago)
> add machine Hyundai Super 286C

- src/video/vid_s3.c
Summary
=======
Toggling the RSF bit is now applied to reads too. Fixes wrong colors on Solaris using true color mode and possibly other stuff too.
Checklist
=========
References
==========
[S3 Trio64V+ datasheet](http://www.bitsavers.org/components/s3/DB018-A_Trio64V+_Integrated_Graphics_Video_Accelerator_Jul95.pdf)
> More S3 blitting fixes:

- src/cpu/cpu.c
Summary
=======
Makes Pentium Pro and Pentium II (incl. Celerons) report accurate cache and TLB information in the output of CPUID with EAX=2.
Checklist
=========
References
==========
[Intel Processor Identification and the CPUID Instruction](http://datasheets.chipdb.org/Intel/x86/CPUID/24161821.pdf) - information on the cache descriptor values
<https://www.cpu-world.com/> (too many pages to list) - CPUID dumps of real CPUs
> Report correct cache info in CPUID on P6-family CPUs

- src/cpu/cpu.c
Summary
=======
- Fix the Pentium Pro reporting twice the cache it actually had
- Re-format and re-order comments so that they always list entries from the least significant byte first
Checklist
=========
References
==========
<http://users.atw.hu/instlatx64/GenuineIntel/GenuineIntel0000617_P6_CPUID.txt>
> [v4.1] Further adjustment to the CPUID cache stuff

- src/cpu/cpu.c
Summary
=======
Adds the Page Global enable feature (CR4 mask, CPUID flag, toggle bit in the Feature Control Register MSR) to the VIA Cyrix III. Also removes pointlessly setting the default value of said MSR's variable on CPUs that don't support it (i.e. any non IDT/Centaur/VIA CPU).
Checklist
=========
References
==========
[VIA Cyrix III Processor Datasheet](http://bitsavers.org/components/cyrix/VIA_Cyrix_III_Processor_Data_Sheet_200011.pdf)
> Add the Page Global Enable flag to the Cyrix III

- src/cpu/x86seg.c
Summary
=======
I've been hit by #1951 myself, and debugging the issue led me to guess cpl_override should be set for this read. With this patch, the warnings disappear, but OpenServer still doesn't go graphical unless a very small subset of video cards has been selected.
Checklist
=========
References
==========
Debugging the same CPU state in QEMU helped me verify the expected value for the `seg` assignment.
> add cpl_override in pmodeiret() when cpu_state.flags has NT_FLAG

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
1. Made the 8514/A mode switch to VGA and viceversa (including ATI mode) actually usable and eliminating the last bugs related to them. Fixes 8514/A mode in OS/2 1.x/2.x (both IBM and Microsoft).
2. More sanity checks to the 8514/A and XGA pointers. Should fix emulator crashes on hard resets.
Checklist
=========
References
==========
> More and more video changes and fixes (8514/A and compatibles):

- src/video/vid_ati68860_ramdac.c
Summary
=======
Forgot to apply the correction to the ATI 68860 ramdac, should clear the compile warnings.
Checklist
=========
References
==========
> Forgot to apply the correction to the ATI 68860 ramdac, should clear the compile warnings

- src/qt/qt_machinestatus.cpp
Checklist
=========
References
==========
N/A
> Fix ATAPI HDDs not being displayed in the status bar

- src/include/86box/vid_svga_render.h
- src/video/vid_ega.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
- src/video/video.c
Summary
=======
This replaces the generic (S)VGA 2bpp, 4bpp, and 8bpp renderers with a single renderer which supports more of what the VGA at least theoretically does.
I am aware that this almost certainly will break a lot of things. I've tried to *not* break things, but, well... a lot of stuff depends on the (S)VGA renderer.
Features:
* Loading (Sequencer) and address incrementing (CRTC) are now independent
* You can read the same value twice or four times and it does what you'd think it would
* Planes are chained in a ring
* No idea if it's actually a ring or if it needs to shift in some 0s or some 1s, so this will need testing on quite a few pieces of hardware.
* Byte/Word/Doubleword mode are now handled theoretically properly
* The CGA 2bpp flag no longer ignores the 2 upper bit …
> (S)VGA paletted renderer rewrite

- src/video/vid_svga_render.c
Summary
=======
Seems the Tseng cards are as incompatible as the S3 cards in terms of pure IBM VGA emulation, especially the chain4 stuff, so accomodate the fix to the renderer. Fixes 8bpp rendering on Tseng cards when invoked.
Checklist
=========
References
==========
> 8-bit renderer fix about the Tseng cards:

- src/qt/CMakeLists.txt
- src/qt/qt_mainwindow.cpp
- src/qt/x11_util.c
- src/qt/x11_util.h
Summary
=======
From a request in #86box-support on Discord.
This updates the WM_CLASS instance name from 86box' vm_name variable after the mainwindow has opened. I haven't done extensive testing so far, as I only have a machine running Xwayland readily available.
Checklist
=========
References
==========
https://www.x.org/docs/ICCCM/icccm.pdf
> update WM_CLASS instance name from vm_name

- src/video/vid_svga.c
- src/video/vid_svga_render.c
Summary
=======
This *should* sort out issue #3843 (I just knew there would be regressions), but it would need to be tested with the Windows 95 driver to prove it - I was using a more direct method to test things, and it works in the cases I tested.
Basically, in a high-resolution 8bpp mode, this now bypasses the shifter logic, which should make it consistent with how the HT-216 handles the mode as documented in the datasheet ("The whole 8 bits in the PEL is shifted out each PCLK").
I was also working on implementing the Shift 256 flag correctly, which should operate as expected now.
And there's an unused variable which has been cleaned up.
Checklist
=========
References
==========
* For Various VGA documents, most notably the 82
* "HT216-32 Local Bus VGA Controller" reference
> (S)VGA updates and fixes, 2023-11-22 edition

- src/network/net_eeprom_nmc93cxx.c
- src/network/net_tulip.c
Summary
=======
Corrected serial ROM defaults, fixes NT 3.x's driver of the NIC while keeping compatibility with the other guests.
Checklist
=========
References
==========
[DEC 21x4 Serial ROM Format manual](https://bitsavers.computerhistory.org/components/intel/ethernet/21X4_Serial_ROM_Format_199903.pdf)
> DEC/Tulip/Intel 21140/21143 fixes:

- src/video/vid_voodoo_banshee.c
Summary
=======
This should fix rendering bugs in programs which expect an 8bit RAMDAC when run on a 3dfx Voodoo Banshee in an SVGA 8bpp mode.
Checklist
=========
References
==========
https://3dfxarchive.com/reference.htm - "3dfx Voodoo Banshee Reference Rev 1.1"
> Handle SVGA 8bit RAMDAC for Voodoo Banshee cards

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_cl54xx.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
1. Update svga->fast to account for packed chain mode toggles, fixes issues on Descent II for DOS using the Cirrus cards.
2. Re-organized ATI Mach8/32 LFB access as well as 8514/A/ATI mode toggles, should end the video mode issues once and for all.
3. Fixed a small but major pattern issue with IBM OS/2 1.30.1's XGA driver (not .2, which is fine as is).
Checklist
=========
References
==========
> Cirrus, ATI Mach8/32 and XGA fixes.

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Fixed wrong setting of highres and lowres mode of 8bpp, makes Transport Tycoon run properly on these ATI cards again.
2. 32-bit (RGBA) True Color is actually supported on the Mach32, but barely used, and the original code was wrong. This fix makes 32-bit True Color render the right colors.
Checklist
=========
References
==========
> Mach8/32 fixes (again):

- src/video/vid_ati_mach8.c
Summary
=======
See title.
Checklist
=========
References
==========
> Fix the initialization of the color cursor regs (ATI Mach32)

- src/cdrom/cdrom.c
Summary
=======
Data track is not audio, fixes anything that wants to play data track as audio.
Checklist
=========
References
==========
> SCSI CD-ROM Toshiba fixes.

- src/include/86box/video.h
- src/video/CMakeLists.txt
- src/video/vid_table.c
- src/win/Makefile.mingw
Summary
=======
Correct undevbranching of the Matrox Millenium
Checklist
=========
References
==========
None
> Correct undevbranching of the Matrox Millenium

- src/include/86box/vid_svga.h
- src/video/vid_mga.c
- src/video/vid_svga_render.c
Summary
=======
This should fix the blinking in 8bpp modes on the Matrix Millennium.
What I've been using to test this:
In a non-CJK MS-DOS 6.2x, run `debug`, then:
```
a100
mov ax, 13
int 10
int 3
g=100
q
```
Now you're in mode 13h, run `qbasic` and then exit it. (esc, alt, f, x - all separate keys)
The background should be black. If it's reddish-brown, then you've ended up in the weird thing that is 8bpp blink mode, which is supported by some VGA clones but not all. The Matrox Millennium card sets the blink bit, so what this PR does is it tells the renderer to ignore the blink bit when bpp > 4 on a Matrox card.
Checklist
=========
References
==========
None
> Disable blink in 8bpp modes on MGA; Re-instate main 8bpp hires renderer

- src/video/vid_mga.c
Summary
=======
Oops, Planar and Extended can be mixed, but not with non-packed chain4 enabled, this should fix more mode bugs in the MGA Millennium card.
Checklist
=========
References
==========
> More MGA fixes.

- src/video/vid_mga.c
- src/video/vid_svga.c
Summary
=======
1. Reverted the packed chain4 and fb_only sides to 1 when extended mode is set, but with the call to svga_recalctimings removed from port 0x3df due to mode issues, this should fix all the MGA mode issues I know.
2. Cleaned up the rendering order in svga_recalctimings, especially 4bpp and 8bpp.
Checklist
=========
References
==========
> MGA fixes 2:

- src/video/vid_mga.c
Summary
=======
Fixes bus-mastering problems under Matrox Mystique.
* Make all bus-mastering-related variables atomic
* Do not, under any circumstances, attempt to read beyond PRIMEND and SECEND
This allows NT 4.0's Matrox Mystique drivers to work with busmastering options enabled. I'm yet to check Windows 9x drivers.
Checklist
=========
References
==========
None.
> Matrox Mystique: Bus-mastering fixes

- src/printer/prt_escp.c
Summary
=======
Allow ESC/P printer emulation to operate without the dot matrix font, which has unclear license status, by substituting it with Courier for draft-quality printing if dotmatrix.ttf is not found, and using Roman instead as a fallback for unsupported LQ typefaces.
Checklist
=========
> ESC/P: make the dot matrix font optional

- src/video/vid_mga.c
Summary
=======
Matrox Mystique: Make it work under Windows NT 4.0 for real
M3D games will freeze/crash the emulator, however. I haven't had any idea of how the DOS M3D libraries handle busmastering properly; the code was clearly designed with M3D DOS games in mind, not OS-level display drivers.
Checklist
=========
References
==========
None.
> Matrox Mystique: Make it work under Windows NT 4.0 for real

- src/video/vid_s3.c
Summary
=======
This reports the correct revision ID for the S3 Trio64V2/DX at least for a specific onboard chip. This is reported over PCI and extended S3 registers.
I attempted this because I was trying to convince Windows 95 to detect the card, but it turned out it could still detect it anyway and it just needed some encouragement. Still, might as well get another thing right.
Checklist
=========
References
==========
Trio64V+ reference manual + testing on real hardware.
> Report correct S3 Trio64V2/DX revision ID

- src/include/86box/vid_ega.h
- src/include/86box/video.h
- src/video/vid_ati18800.c
- src/video/vid_ega.c
- src/video/vid_table.c
Summary
=======
1. Reverted the migration from ATI 18800 as the EGA code had the proper palette.
2. Add support for the 800x600 resolution required by said card.
Checklist
=========
References
==========
> ATI EGA Wonder 800+ fixes.

- src/video/vid_mga.c
Summary
=======
MGA: More Mystique busmastering fixes
* ~~Use mutex locking when reporting SOFTRAPEN~~
* IEN register now correctly returns values it currently holds
* Restore VLINEPEN interrupt
~~NT 4.0's OpenGL screensavers now can render around 20-40 frames before freezing.~~
Edit: 3D busmastering now works, but it is slow.
Checklist
=========
References
==========
None.
> MGA: More Mystique busmastering fixes

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
Summary
=======
* Set the window icon for the entire application, instead of just the main window; fixes dialog windows having a generic icon when the main window isn't initialized (like the standalone Settings dialog)
* Set the .desktop file name on \*nix; may possibly fix the generic icon showing up instead of 86Box's icon on Wayland
Checklist
=========
References
==========
<https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon>
> Qt: Application icon fixes

- src/video/vid_mga.c
Summary
=======
Don't call svga_recalctimings() on MGA's port 0x3df, fixes Debian Woody's matroxfb screen test.
Checklist
=========
References
==========
> Fix Debian Woody's matroxfb's test again.

- src/video/vid_mga.c
Summary
=======
MGA: Don't reset screen size every recalctimings
Fixes intense resizing.
Checklist
=========
References
==========
None.
> MGA: Don't reset screen size every recalctimings

- src/video/vid_mga.c
Summary
=======
mystique_line_compare: Re-enable line compare behaviour
Reduces glitches on M3D, although it doesn't eliminate it completely
Checklist
=========
References
==========
None.
> mystique_line_compare: Re-enable line compare behaviour

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. For some reason, background colors were always black under those drivers in 8bpp mode, added a tweak to fix it (as well as Clock colors).
2. Likewise for the red scrolling in pbrush or write, added a tweak to its bitblt read mask.
3. Don't call svga_recalctimings in the hdisp/vdisp ports directly, fixes screen size on said drivers without affecting other stuff.
Checklist
=========
References
==========
> ATI Mach8/32 fixes regarding 1992 ATI Ultra drivers for Windows 3.1x:

- src/video/vid_mga.c
Summary
=======
Matrox Mystique: Fix display flickering issues for real
Direct3D tests under Windows 95 do not flicker anymore, and the MSICUBE sample program renders correctly.
Checklist
=========
References
==========
None.
> Matrox Mystique: Fix display flickering issues for real

- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/video/vid_mga.c
- src/video/vid_svga_render.c
Summary
=======
MGA: Implement gamma correction for 24+ bpp modes
Checklist
=========
References
==========
None.
> MGA: Implement gamma correction for 24+ bpp modes

- src/include/86box/vid_svga.h
- src/video/vid_mga.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
Summary
=======
MGA: Implement gamma-correction for <= 16 bpp modes
Checklist
=========
References
==========
None.
> MGA: Implement gamma-correction for <= 16 bpp modes

- src/video/vid_mga.c
Summary
=======
MGA: Make sure dxdiag on D3D 9.0b doesn't crash the emulator on Windows 98 SE
Checklist
=========
References
==========
None.
> MGA: Make sure dxdiag on D3D 9.0b doesn't crash the emulator

- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_ati18800.c
- src/video/vid_ati28800.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_svga_render.c
Summary
=======
1. Made the 4 color mode (67h) work properly now, including its 4 schemes on all ATI cards that support said mode.
2. Shadow set now has a true purpose for 8514/A compatibility on ATI Mach8/32.
3. Non-ATI 8514/A used to not work before because of the dev->local variable was not being set to 0 in the ibm8514_init() function, now it's fixed.
Checklist
=========
References
==========
> More ATI changes plus one IBM 8514/A fix:

- src/qt/qt_joystickconfiguration.cpp
- src/qt/qt_settingsinput.cpp
- src/win/win_jsconf.c
Summary
=======
Fixes issues preventing successful emulated joystick POV hat configuration, such as hat's Y axis being set to the same host axis as the X axis, axes being reset to the stick's Y axis or another seemingly random host axis, etc.
Checklist
=========
References
==========
N/A
> Joystick: Fix emulated POV hat configuration

- src/include/86box/video.h
- src/video/vid_mga.c
- src/video/vid_table.c
Summary
=======
This PR adds the Matrox Millennium II video adapter.
Latest Windows 98 SE drivers are tested and working OK. Transparency under Direct3D is broken but Vintage3D website also reports broken transparency.
Note: 1920x1080 with 24 bits-per-pixel mode is very broken, and all signs point to being a driver bug, not an emulation bug.
Checklist
=========
References
==========
None.
> MGA: Add Matrox Millennium II video adapter

- src/video/vid_mga.c
Summary
=======
Millennium II: Don't ignore OPTION_INTERLEAVE
Checklist
=========
References
==========
None.
> Millennium II: Don't ignore OPTION_INTERLEAVE

- src/video/vid_mga.c
Summary
=======
Revision ID now properly indicates a Matrox Mystique 220 card.
Implement BAR swap for Matrox Mystique 220 that was done for revision 3.
Checklist
=========
References
==========
None.
> MGA: Properly report Matrox Mystique 220 in PCI revision ID

- src/video/vid_mga.c
- src/video/vid_tvp3026_ramdac.c
Summary
=======
Millennium and Millennium 2: Enable gamma correction only for 24+ bpp
Checklist
=========
References
==========
None.
> Millennium and Millennium 2: Enable gamma correction only for 24+ bpp

- src/include/86box/vid_svga.h
- src/video/vid_mga.c
- src/video/vid_s3.c
- src/video/vid_tvp3026_ramdac.c
Summary
=======
TVP3026: Implement gamma correction for 15/16 bpp modes
Checklist
=========
References
==========
None.
> TVP3026: Implement gamma correction for 15/16 bpp modes

- src/sound/snd_sb.c
Checklist
=========
References
==========
N/A
> Actually enable gameport on init on non-PnP SB16/AWE32

- src/video/vid_voodoo_banshee.c
Summary
=======
vid_voodoo_banshee: Implement gamma correction for 16bpp
Checklist
=========
References
==========
None.
> vid_voodoo_banshee: Implement gamma correction for 16bpp

- src/video/vid_mga.c
Summary
=======
Disable 32-bit Z buffer on Mystique 220 and earlier
Checklist
=========
References
==========
None.
> Disable 32-bit Z buffer on Mystique 220 and earlier

- src/machine/m_at_socket4.c
This updates the filename to match the newer 1013AF2 BIOS.
Summary
=======
Currently, the Intel Premiere/PCI ED uses ```1009AF2``` as BIOS. But there is a newer BIOS ```1013AF2```. This commit updates the used filename and a PR for updating the ROM is filled at https://github.com/86Box/roms/pull/223.
I did run a Test with Windows 95 OSR 2.5 and I haven't noticed any issues for me. I do also own the Intel Premiere/PCI ED, if there is something you would like to test.
Checklist
=========
References
==========
BIOS History: https://theretroweb.com/motherboards/s/intel-premiere-pci-ed-batman-s-revenge#bios
> Intel Premiere/PCI ED: update bios to 1013AF2

- src/qt/qt_main.cpp
Summary
=======
Don't set the application icon in qt_main.c on Mac so it won't override the bundle's icon.
Checklist
=========
References
==========
N/A
> Don't set the application icon in qt_main.c on Mac

- src/qt/qt_main.cpp
Summary
=======
This fixes a typo on a mac icon fix submitted by lemondrops.
The original code uses 
`#ifndef Q_OS_APPLE `
instead of 
`#ifndef __APPLE__`
After changing this line, the correct icon appears on MacOS Dock, for both app window and settings window.
Checklist
=========
References
==========
OBattler
> fixes typo on mac icon fix

- src/video/vid_mga.c
Summary
=======
Fix detection of MGA G100 video RAM when 16MB
Checklist
=========
References
==========
None.
> Fix detection of MGA G100 video RAM when 16MB

- src/video/vid_mga.c
Summary
=======
MGA: Fix busmastering under Windows 2000
Checklist
=========
References
==========
None.
> MGA: Fix busmastering under Windows 2000

- CMakeLists.txt
- src/device/mouse_serial.c
- src/include_make/86box/version.h
Summary
=======
It's 2024.
Also replaces the hardcoded copyright year with the COPYRIGHT_YEAR macro in the emulated Logitech serial mouse's self-report string.
Checklist
=========
References
==========
<https://www.timeanddate.com/>
> Update the default copyright year

- src/qt/qt_winrawinputfilter.cpp
Summary
=======
Qt: Rawinput now follows keyboard focus properly
Checklist
=========
References
==========
None.
> Qt: Rawinput now follows keyboard focus properly

- src/qt/qt_rendererstack.cpp
Summary
=======
Mouse capturing now works on secondary monitors
Checklist
=========
References
==========
None.
> Mouse capturing now works on secondary monitors

- src/video/vid_s3.c
- src/video/vid_sc1502x_ramdac.c
Summary
=======
1. Made the 924 BIOS use the AT&T 491 ramdac since it supports such (tested).
2. Tweaks to the 928 Brooktree ID detection to make sure the cursor is shown correctly in 16bpp+ modes (it uses the BT485 ID detection so that it knows what BT is using to accommodate the cursor model).
3. Refactored the mode (CRTC50) and pitch timing stuff (moved to recalctimings for example) so that drivers/games/operating systems and what not can be used normally. (Warning, more stuff is to be tested due to a gazillion of combinations used by said stuff).
4. VRAM wraparound is now working as it should, fixes Commander Keen games.
5. Indentation fixes.
6. Attempt to fix 15/16bpp mode acceleration used by the 911/924 chips (not perfect and still has bugs).
7. Added the remaining missing stuff of …
> S3 refactoring:

- src/include/86box/scsi_pcscsi.h
- src/scsi/scsi.c
- src/scsi/scsi_pcscsi.c
Summary
=======
1. Changed the MCA ID of said adapter to one that is add-on based rather than integrated (still no bios though).
2. Fixed the DMA/IRQ stuff of the 86c01 DMA side of the card.
Checklist
=========
References
==========
> NCR 53c9x MCA small improvements.

- src/scsi/scsi_ncr5380.c
Summary
=======
1. The chip in question now supports the right command length for vendor unique commands, fixes crashes that use said commands.
2. Made the CD speed of said chip even closer to the real thing.
Checklist
=========
References
==========
> Small 5380 SCSI improvements.

- src/video/vid_s3.c
Summary
=======
1. Fixed the Elsa Winner 2000 Pro-X/8 (964 and 968) 15/16/32bpp modes at 1280x1024+.
Checklist
=========
References
==========
> S3 mode fixes (1):

- src/network/net_pcnet.c
1. Racal Etherblaster now has, on reset, the proper initialization values, fixes detection under various operating systems, especially NT.
2. More IRQ and DMA options.
Summary
=======
Checklist
=========
References
==========
> PCnet-based fixes:

- src/video/vid_s3.c
Summary
=======
1. Fixed 16bpp modes (including 15-bit) of the Trio32/64 that were doubling their horizontal resolution.
2. Made Bresenham Line easier to work with.
Checklist
=========
References
==========
> S3 mode fixes 2 and one small accel cleanup:

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Properly implemented polygon filling in the BitBLT side of the ATI 8514/A compatibles (Mach8/32), this allows games like Mj8514 and demos like HDIDEMO from IBM to run under ATI's hdiload 1.1 properly.
2. Finally figured out the polygon filling command in the IBM one about read and write masks (Command 5 and Command 2 with polygon filling bits on, currently only for the read mask one), this allows the above samples to render properly with IBM's original hdiload 1.0 from 1987.
Checklist
=========
References
==========
> Huge fixes to 8514/A compatibles:

- src/video/vid_ega.c
- src/video/vid_svga.c
Summary
=======
This fixes the CRTC-based fine vertical scroll behaviour on the EGA render and the (S)VGA renderer.
The code was effectively offsetting the row counter and hiding the top few rows in the overscan. This messes up a lot of things, resulting in blank rows at the bottom and split screen activating on the wrong row.
Also, after this fix, if you set an out-of-range fine scroll value and you see some garbage at the top of your screen... that's normal for at least one real chipset.
Checklist
=========
References
==========
vgadoc, that bug report, and my trusty onboard S3 Trio64V2/DX for comparison.
> EGA, (S)VGA: Fix vertical fine scroll behaviour

- src/device/unittester.c
- src/video/vid_ega.c
- src/video/vid_ega_render.c
Summary
=======
This fixes the fine scroll in the EGA text modes, including 8-dot and 9-dot modes, also providing a fallback for the "shift left by 1" effect in lieu of a correct implementation of the character skew counter.
This *also* does some changes to the unit tester - firstly, the debug log is a lot more useful, and secondly, it's now compatible with EGA double-scanned rendering (yep, that was a bug).
Checklist
=========
References
==========
IBM EGA reference; vgadoc; remembering something about various SVGA datasheets explaining the horizontal panning pretty much identically to each other; testing on my S3 Trio64V2/DX for feasible behaviour.
> Fix EGA fine scrolling in text modes

- src/device.c
- src/include/86box/device.h
- src/machine/m_ps1.c
- src/machine/machine_table.c
Summary
=======
IBM PS/1 Model 2011: Add language ROM options.
Checklist
=========
References
==========
None.
> IBM PS/1 Model 2011: Add language ROM options.

- src/video/vid_cl54xx.c
- src/video/vid_et4000.c
- src/video/vid_et4000w32.c
- src/video/vid_mga.c
- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_svga.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Apply blanking extensions to more SVGA cards.
* Fix duplicated logic in vid_svga.c
* Voodoo 3/Banshee emulation now has blanking extensions applied
* S3 ViRGE and Matrox video cards as well
* Tseng ET4000-series cards as well
* Fix off-by-one error in vid_cl54xx.c
Trident cards are yet to be investigated. XGA and 8514/A are yet to be made blanking extensions compliant. Mach64, Paradise/WDC and OAK OTI cards remain as-is for now.
Checklist
=========
References
==========
Datasheets/databooks of respective cards whenever possible.
> Apply blanking extensions to more SVGA cards.

- src/video/vid_mga.c
Summary
=======
MGA: Do not reset DWORD expected counter while SOFTRAP read is still pending
Fixes Matrox Simple Interface games without breaking Windows 2000 drivers.
Checklist
=========
References
==========
None.
> MGA: Do not reset DWORD expected counter while SOFTRAP read is still pending

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/include/86box/vid_svga.h
- src/include/86box/video.h
- src/video/vid_8514a.c
- src/video/vid_ati68860_ramdac.c
- src/video/vid_ati_mach8.c
- src/video/vid_table.c
Summary
=======
1. Cleanups and moving the mach8/32 struct to a dedicated header so that would allow for future 8514/A add-on clones (in paper).
2. Mach8/32's port 0x4ae8/9 and shadow set ports (0x5aee and 0x46ee) now account to the mode changes seriously, should fix most of the horizontal/vertical coordinates while entering GUI modes of various stuff.
3. Horizontal/Vertical window coordinates can only be modified if the display enable bit of port 0x22e8 is set as well as bit 0 of port 0x4aee, fixes most problems noted above.
4. Implemented horizontal blanking stuff a la VGA but actually for 8514/A and clones (like ATI).
5. Added some comments regarding the current situation.
6. The Mach8 was actually a 8514/A clone co-processor, not a single solution card of its own. The ATI Graphics …
> ATI Mach8/32 mode changes and cleanup:

- src/video/vid_ega.c
- src/video/vid_ega_render.c
Summary
=======
A few bugs are fixed here.
* One was my fault for forgetting to adjust the graphics renderer to handle the 8/9-dot workaround in the text renderer.
* Another was exposed by my changes: The wobbling that happens in one of the BIOSes, which was triggered by the cursor settings constantly being written repeatedly, which spammed calls to `ega_recalctimings()`.
* Lastly, there's a bit that only exists in VGA which was in the EGA renderer for some reason. This wasn't the cause of any of the bugs I was trying to fix, but it's still worth getting rid of it.
Checklist
=========
References
==========
Mostly boiled down to original research based on available documentation and logical deduction.
> Fix a few bugs pertaining to EGA fine horizontal scrolling

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
Hopefully fix various modes altogether in all three chips (640x480, 800x600, 1024x768 and 1280x1024).
Checklist
=========
References
==========
> Slight cleanup of the 8514/A compatible chips.

- CMakeLists.txt
- src/include/86box/machine.h
- src/machine/CMakeLists.txt
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
Turns out the breakage is caused by the amount of RAM.
Checklist
=========
References
==========
> Raise minimum RAM for MSI MS-4144 to 5 MBs

- .github/workflows/c-cpp.yml
- .github/workflows/cmake_windows_msys2.yml
Summary
=======
This will disable the GHA:
* `makefile` job (consists entirely of deprecated win32 builds)
* Deprecated win32 builds in the windows cmake job
The makefile job yaml file remains in place but is disabled with a conditional. Once merged the job can also be disabled in the repo settings.
Checklist
=========
References
==========
[GitHub docs link](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) for disabling a job using a conditional.
> Disable GHA win32 and makefile jobs

- src/qt/qt_mainwindow.ui
Fix broken translation of "ACPI shutdown" tooltip for all languages
Summary
=======
Checklist
=========
References
==========
> Fix broken translation of "ACPI shutdown" tooltip for all languages

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_compaq.c
- src/machine/m_at_socket370.c
- src/machine/m_at_socket4.c
- src/machine/m_at_socket7_3v.c
- src/machine/machine_table.c
Summary
=======
Thanks to theretroweb.com, we are able to identify which features and hardware are available on the boards we emulate. This PR aims to add devices on boards that were previously not there even if they should've, and removed hardware from machines that lack those. Notes have been left for future internal hardware implementation. As some machines have been identified, they have been renamed and rearranged; turns out the Award "486" didn't support 486es at all!
Checklist
=========
References
==========
[The Retro Web](https://theretroweb.com)
[ManualsLib](https://manualslib.com)
> Machine flag cleanups and other assorted machine changes

- src/machine/machine_table.c
Summary
=======
The machine appears to be the Arche AMA-2010 (Kenitec 286/16). Thanks @mfmcosta for bringing this up.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/arche-ama-2010
> Rename "Phoenix 286 clone" as the machine has been identified

- src/machine/machine_table.c
Summary
=======
The machine appears to be a Micoms XL-7 Turbo. Thanks @mfmcosta for finding this out.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/micoms-system-pt-xl-7-turbo
> Rename "AMI XT clone" as the machine has been identified

- src/machine/machine_table.c
Turns out this was an error on The Retro Web's part.
Summary
=======
Checklist
=========
* [xI have discussed this with core contributors already
References
==========
> Revert "Rename "AMI XT clone" as the machine has been identified"

- src/scsi/scsi_ncr5380.c
Summary
=======
This should fix more timing issues with said SCSI controllers in various CPU/HDD/CD-ROM speeds.
Checklist
=========
References
==========
[NCR 53c400 (Rancho RT1000A/B, Longshine LCS6821N and Trantor 130B](https://archive.org/details/bitsavers_ncrsymbios_1404289)
> Refactor 5380-based SCSI controllers

- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
This PR adds the A-Trend 4GPV5 machine, which is based on the Contaq 82C596A chipset and has an Award 4.99G BIOS.
Checklist
=========
References
==========
> Add A-Trend 4GPV5 machine

- src/qt/languages/ru-RU.po
- src/qt/languages/uk-UA.po
- src/qt/qt_settingsmachine.ui
Summary
=======
Fix broken translation of "PIT mode:" for all languages.
Added "86Box Unit Tester" for RU.
"v" dot removal for RU and UA.
Checklist
=========
References
==========
> Fix broken translation of "PIT mode:" for all languages

- src/cdrom/cdrom.c
- src/include/86box/cdrom.h
- src/scsi/scsi_cdrom.c
Summary
=======
1. Re-implemented in the best way possible the muted part of the Toshiba/NEC Play Audio commands and related, per spec.
2. Forgot to add a check to a Sony Vendor Data Out command  when the len is 0 it should become a Status command, fixes emulator crashes when len is 0 using some CD software.
Checklist
=========
References
==========
> SCSI CD-ROM fixes of the day.

- src/video/vid_cl54xx.c
- src/video/vid_paradise.c
Summary
=======
Vendor banking should be 0 when plain IBM VGA modes are set, fixes corrupt text modes (Cirrus and Paradise at the moment).
Checklist
=========
References
==========
[WD90c30 manual for the IBM VGA wraparound](https://bitsavers.org/components/westernDigital/_dataBooks/1993_SystemLogic_Imaging_Storage/16_WD90C30A.pdf)
> SVGA video card fixes of the day.

- src/video/vid_ht216.c
Summary
=======
Don't touch the POS I/O ports at all, fixes hang ups with the card in question using the IBM PS/1 machines, which rely on those ports.
Checklist
=========
References
==========
> Radius Video7 ISA card update about the I/O handler.

- src/video/vid_cl54xx.c
- src/video/vid_s3.c
Summary
=======
When I say banking should be 0 when IBM VGA modes are set, they must be, Cirrus...
Also, updated the vram mask using the gd54xx struct rather than svga's for consistency.
Checklist
=========
References
==========
> Update on Cirrus banking.

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_svga_render.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_cl54xx.c
- src/video/vid_svga.c
Summary
=======
1. Second attempt to fix the banking in the Cirrus (sigh, why doesn't banking get nulled automatically...)
2. Introduce a new timer to the 8514/A side so it won't slow the VGA clock down it was shared before.
Checklist
=========
References
==========
> Couple of changes in the video side.

- src/include/86box/vid_svga_render.h
- src/video/vid_ati68860_ramdac.c
- src/video/vid_svga_render.c
Summary
=======
Temporarily replace the ATI68860 8bpp renderer with a clone one while the current renderer (8bpp) is being fixed for proper colors on the Mach64.
Checklist
=========
References
==========
> Mach64 temporary updates:

- src/video/vid_cl54xx.c
- src/video/vid_svga.c
Summary
=======
A bit controversial regarding extra_banks but this should be enough to fix everything in the banks of the CL-GD54xx (up to 5480).
Checklist
=========
References
==========
> Fixed the Cirrus banking issue for good (really)

- src/machine/machine_table.c
Summary
=======
It would cause a hang in the BIOS if it's lower than 8MB (screenshot below)
Tested on 1MB ram
Checklist
=========
References
==========
N/A
> Bumped the minimum ram to 8MB on ASUS P5A

- src/include/86box/video.h
- src/video/vid_mga.c
- src/video/vid_table.c
Summary
=======
1. When the 128K banking is activated, use a mask of 0xffff instead of 0x1ffff.
2. Debian uses standard VGA mapping when in chain4 mode and its lfb is adapted accordingly.
3. Fixed the decode VRAM mask on the Millennium II so that the vram is detected correctly and no more glitches.
4. Undev the Millennium II as well.
Checklist
=========
References
==========
> Matrox MGA fixes:

- src/video/vid_s3.c
Summary
=======
32-bit toggleable regs are now written properly, fixes OS/2 32-bit color using S3 Pre-ViRGE drivers while keeping existing compatibility fine.
Checklist
=========
References
==========
> S3 Pre-ViRGE 32bpp fixes:

- src/video/vid_chips_69000.c
- src/video/vid_mga.c
- src/video/vid_svga.c
Summary
=======
vid_svga.c: Hardware cursors with negative Y values work properly now
* Fixes cursor disappearing completely in Matrox cards in some cases, and also accounts for accuracy.
* Allows emulated video adapters allowing negative Y values for hardware cursor to render those properly.
Checklist
=========
References
==========
None.
> vid_svga.c: Hardware cursors with negative Y values work properly now

- src/video/vid_tvp3026_ramdac.c
Summary
=======
vid_tvp3026_ramdac: Implement warp-around for hardware cursor buffer32 drawing
Fixes crashes on Windows 2000
Checklist
=========
References
==========
None.
> vid_tvp3026_ramdac: Implement warp-around for hardware cursor buffer32 drawing

- src/video/vid_chips_69000.c
Summary
=======
C&T 69000: Fix VBIOS size
Checklist
=========
References
==========
None.
> C&T 69000: Fix VBIOS size

- src/include/86box/video.h
- src/video/vid_mga.c
- src/video/vid_table.c
Summary
=======
1. The Debian issue mystery lies around chain2_read/write being required when the LFB mapping is enabled too when MGA modes are set without blitting, however, when it is blitting, immediately tell chain2 to not interfere with the mapping. Fixes Debian once and for all as well as VRAM detection correctly while keeping existing compatibility fine.
2. Undev branch the G100 per above. (Revert if more bugs are revealed).
3. An AND with 0 is not tolerable as it nulls the LFB, fixes hang ups with Win2000 using the Millennium II and possibly the G100.
4. the Extended CRTCs now have a call for timing recalculation, fixes mode changes when blitting is going on.
Checklist
=========
References
==========
_Provide links to datasheets or other documentation that helped you implement …
> MGA updates for the vram detection and stuff.

- src/video/vid_chips_69000.c
Summary
=======
C&T: Clear bit 7 of CRTC register 0x40 on vertical blank start, fixes DirectDraw hangs.
Checklist
=========
References
==========
None.
> C&T: Clear bit 7 of CRTC register 0x40 on vertical blank start, fixes DirectDraw hangs

- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
Some more 486-era machine flag changes that I missed during my initial run. 
Checklist
=========
References
==========
[The Retro Web](https://theretroweb.com/)
> More 486 machine changes that I missed

- src/video/vid_chips_69000.c
Summary
=======
C&T 69000: Monochrome patterns are no longer horizontally reversed
Fixes mouse dragging glitches under Windows 2000 on 16+ bpp.
Checklist
=========
References
==========
None.
> C&T 69000: Monochrome patterns are no longer horizontally reversed

- src/video/vid_chips_69000.c
Summary
=======
C&T 69000: Fix ROP 0xFF `WHITENESS` on 16+ bpp modes
Fixes blue background on Write in Windows 3.11 drivers.
Checklist
=========
References
==========
None.
> C&T 69000: Fix ROP 0xFF `WHITENESS` on 16+ bpp modes

- src/machine/m_at_386dx_486.c
Summary
=======
The onboard slots should come before the external slots it seems like.
Checklist
=========
References
==========
> Fix ActionPC onboard PCI slots

- .github/workflows/c-cpp.yml
- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
Summary
=======
Remove libvncserver from dependencies from Github Actions workflows; since they're built with VNC renderer disabled, it's effectively useless.
Fixes Windows workflows breakage.
Checklist
=========
> workflows: Remove libvncserver from deps

- src/video/vid_chips_69000.c
Summary
=======
C&T 69000: avoid stale linear mappings
Checklist
=========
References
==========
None.
> C&T 69000: avoid stale linear mappings

- src/video/vid_s3.c
- src/video/vid_svga.c
- src/video/vid_tvp3026_ramdac.c
Summary
=======
S3 side:
Temporary changes to match the release (due to tomorrow) of 86box. Said changes are about the horizontal display of the tvp3026-based S3 chips.
IBM/ATI 8514-based:
Temporarily commented out the hblank side of it due to htotal bugs.
TVP3026 side:
When the upper clock selection bits are 0 and when extended VGA modes are set, double the hdisp.
Checklist
=========
References
==========
> Some temporary video changes regarding the horizontal display.

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE: Respect blend control compose modes on pre-GX2 ViRGE
Fixes video overlay staying on-screen on Linux.
Checklist
=========
References
==========
None.
> S3 ViRGE: Respect blend control compose modes on pre-GX2 ViRGE

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE/GX2: Fix screen overlay staying on Windows XP.
Checklist
=========
References
==========
None.
> S3 ViRGE/GX2: Fix screen overlay staying on Windows XP

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE: Buffer flips no longer trigger recalctimings
Checklist
=========
References
==========
None.
> S3 ViRGE: Buffer flips no longer trigger recalctimings

- src/unix/assets/net.86box.86Box.metainfo.xml
From the [Flathub](https://flathub.org) AppStream validator:
```
{
"errors": [
"appstream-failed-validation",
"appstream-missing-developer-name"
],
"warnings": [
"appstream-summary-too-long",
"appstream-screenshot-missing-caption"
],
"appstream": [
"E: net._86box._86Box:~: category-invalid Emulation",
"E: net._86box._86Box:~: all-categories-ignored"
],
"message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```
This PR:
- Fixes the "Emulation" category that should be "Emulator" (same as the desktop file one).
- Adds developer name that is required by multiple AppStream validators nowadays.
> Fix AppStream metainfo file

- src/unix/unix_serial_passthrough.c
Summary
=======
plat_serpt_write_vcon(): write() returns how much data it has written to the file descriptor, and in case an error, it returns -1. So the EWOULDBLOCK never really triggers, as in the following condition we're not checking the errno, but the return value of the write() function.
Checklist
=========
> unix_serial_passthrough.c: check errno for EWOULDBLOCK

- src/video/vid_s3_virge.c
Summary
=======
So that 24bpp color is not discolored anymore as well as hblank bugs being nulled.
Checklist
=========
References
==========
> Temporary solution to a 24bpp issue and hblank.

- src/include/86box/bswap.h
Summary
=======
1. __builtin_bswap{32,64} were added in GCC 4.3, and __builtin_bswap16 was added in GCC 4.8, however, currently, the GCC requirements in bswap.h file has >= 10. This requirement of GCC version is false for bswap* but true for __has_builtin() (as it first was added in GCC 10.1). As bswap* builtins were added before GCC 10, the preprocessor check will always going to be true for bswap but will be false if GCC version is < 10 as __has_builtin() won't be present. Since the byteswap function, on x86-64, can boil down to a single bswap instruction, this optimization may left behind (unless GCC do some pattern matching). To avoid this, just use the compiler macros (for GCC: \__GNUC\__, clang: \__GNUC\__ or \__clang\__) and if the compiler is neither GCC or Clang, fall-back to …
> bswap.h: fix GCC requirements for bswap* builtins

- src/qt/qt_platform.cpp
- src/unix/unix.c
- src/win/win_ui.c
Summary
=======
Fix ACPI poweroffs saving the exit confirmation dialog disable option to the config file.
Checklist
=========
References
==========
N/A
> Fix ACPI poweroffs disabling exit confirmations

- src/include/86box/snd_emu8k.h
- src/sound/snd_emu8k.c
- src/sound/snd_sb.c
Summary
=======
Add a correct PnP ROM for the CT4380 "regular" Sound Blaster AWE64, instead of the AWE64 Value ROM used as a substitute. Also add IDE to it, since the dump indicates the presence of IDE.
Additionally move the PnP and EMU8000 ROM paths to macros to avoid duplication.
Checklist
=========
References
==========
N/A
> Add a correct PnP ROM for the CT4380 Sound Blaster AWE64

- src/disk/hdc.c
- src/disk/hdc_ide.c
- src/include/86box/hdc.h
Summary
=======
Added McIDE (MCA IDE) controller for MCA machines that don't have it (PS/2 models 50+).
Checklist
=========
References
==========
> IDE changes (now for MCA).

- src/disk/hdc_ide.c
Summary
=======
The ADF is a bit misleading, for pos3 and pos4, the right bits are bits 5-4, not 6-5. Fixes IRQ and added the secondary addresses without conflicting with the FDC, now ATAPI drives work fine.
Checklist
=========
References
==========
> IDE/ATAPI port/irq changes for MCA:

- src/86box.c
- src/config.c
- src/disk/CMakeLists.txt
- src/disk/lba_enhancer.c
- src/include/86box/86box.h
- src/include/86box/hdc.h
- src/qt/qt_settingsstoragecontrollers.cpp
- src/qt/qt_settingsstoragecontrollers.hpp
- src/qt/qt_settingsstoragecontrollers.ui
Summary
=======
This PR adds Vision Systems LBA Enhancer.
It adds 28-bit LBA addressing to machines with BIOSes that do not support it.
Checklist
=========
References
==========
None.
> Add Vision Systems LBA Enhancer

- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
Disable checkboxes for devices that require ROMs when ROMs for them are not present. Affects the standalone IBM XGA and the Vision Systems LBA Enhancer.
Checklist
=========
References
==========
N/A
> Qt: Disable device checkboxes when ROMs for them aren't present

- src/unix/unix_netsocket.c
Summary
=======
unix_netsocket.c: Unused variables warnings cleanup
Checklist
=========
References
==========
None.
> unix_netsocket.c: Unused variables warnings cleanup

- src/network/net_modem.c
Summary
=======
net_modem: process '&' escaped commands properly
Checklist
=========
References
==========
None.
> net_modem: process '&' escaped commands properly

- src/qt/qt_platform.cpp
Summary
=======
Correct the Ghostscript DLL filename that's used in an error message on 64-bit Windows from "gsdll32.dll" to "gsdll64.dll".
Checklist
=========
References
==========
N/A
> Fix Ghostscript DLL filename in an error message on 64-bit Windows

- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_progsettings.cpp
Summary
=======
* Fix up the architecture check #ifdef from [the previous PR](https://github.com/86Box/86Box/pull/4275) to match what is used to determine the DLL filename to try loading;
* Add a missing period at the end of certain error messages, fixes translations of them not appearing under certain circumstances;
* Sort the language list alphabetically instead of by LCID.
Checklist
=========
References
==========
N/A
> Miscellaneous fixes and improvements for v4.1.1

- src/network/net_pcap.c
Summary
=======
On windows, add the directory where Npcap always installs its libraries to the DLL search path when looking for libpcap. This makes PCap networking usable if Npcap is not installed in WinPcap-compatible mode.
Checklist
=========
References
==========
<https://npcap.com/guide/npcap-devguide.html#npcap-feature-native>
> [v4.2] Check for pcap DLL in Npcap's installation directory on Windows

- src/network/net_pcap.c
Summary
=======
This PR modifies the PCAP filter accordingly:
* Multicast packets are now passed through
* The `broadcast` keyword is used instead of `ff:ff:ff:ff:ff:ff`
The biggest effect is fixing NetBEUI / NetBIOS which was not working before: NetBEUI uses a multicast address (`03:00:00:00:00:01`) instead of a standard ethernet broadcast which was not passing the PCAP filter.
Anything that uses NetBEUI / NetBIOS should now work with PCAP, including LAN Manager. Any other L3 that uses multicast should also now work.
Screenshot of win98 with no TCP/IP installed, using only NetBEUI to communicate with another win98 host configured the same:
Checklist
=========
References
==========
N/A
> Modify the PCAP filter to allow multicast packets

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_compaq.c
- src/machine/machine_table.c
Summary
=======
And a proper Compaq Portable III 386 BIOS.
Note: The SCAT 286 003 machine is a SCAT-based AMI 286 machine.
Checklist
=========
References
==========
> Add the Tandy 4000 AT compatible and SCAT-286-003 machines

- src/disk/zip.c
Summary
=======
Revert the changes in e7f15d87. Fixes a crash when 86box loads a zip image.
Checklist
=========
References
==========
e7f15d87 was the original commit for this
> Fix zip disk image load crash

- .github/workflows/cmake_windows_msys2.yml
Summary
=======
UCRT64 isn't used in any official capacity or for release builds. Disabling in GHA to try and trim down the workflow times.
Checklist
=========
References
==========
N/A
> Disable UCRT64 in msys2 workflow

- src/disk/zip.c
Summary
=======
Thanks to `-Wstringop-truncation` gcc is very particular about the use of `strncpy`.
It seems to be particularly concerned that 
* The destination string could, prior to the copy, potentially have no null terminator present
* The length copied from the source string could potentially have no null terminator (because the length being copied is less than the source size)
* If both of the above are true, the final dest string, after copy, could therefore have no null terminator
The fix for this is to explicitly set the null terminator which makes gcc happy.
Checklist
=========
References
==========
A previous attempt to fix this accidentally broke zip loading and had to be undone in #4298
> Fix gcc warning with use of strncpy

- src/network/net_modem.c
Summary
=======
* Increase phone book size to 200 entries from 20, while decreasing the entry size from 1023 to 127 (anything longer wouldn't work anyway)
* Make certain string operations, including phonebook parsing, safer
* Fix escape sequence guard timer counter never resetting, effectively making the guard timer non-functional
* Stop command line processing after dialing; dialed number no longer gets interpreted as a command, affected primarily hostnames
Checklist
=========
References
==========
N/A
> Modem fixes

- src/network/net_modem.c
Summary
=======
* Implement `ATD;` command (return to command mode after dialing). To simulate the in-progress dialing, the number before the semicolon is appended to a temporary buffer, when an `ATD` command without a semicolon is issued, the buffer contents are prepended and the complete number is dialed at once. Fixes Windows 98 dialer being stuck if "wait for dial tone" option was enabled
* Implement `AT&C` command (Carrier Detect signal control). `&C0` makes the modem always assert DCD, `&C1` (default) - only when on-line
* Implement `ATDL` command (re-dial last number)
* Implement `A/` command (repeat previous command). Doesn't require the `AT` prefix or carriage return after it
* Add extra logging
* Add 86Box version in `ATi4` output (like DOSBox)
Checklist
=========
References …
> Modem additions

- .editorconfig
- src/device/serial_passthrough.c
- src/include/86box/plat_netsocket.h
- src/network/net_modem.c
- src/qt/win_netsocket.c
- src/qt/win_serial_passthrough.c
- src/unix/unix_netsocket.c
- src/unix/unix_serial_passthrough.c
Summary
=======
* Disable most modem logging
* Run `clang-format` on modem, netsocket and serial passthrough code
* Clean up .editorconfig: remove specific entries made redundant after the new indent style was introduced, add definition for Qt .ui files 
Checklist
=========
References
==========
N/A
> Modem (and related) cleanups

- src/video/vid_voodoo.c
Summary
=======
Apparently some software reprograms the vertical display wrong sometimes (in this case, vdisp + 2). This should fix software titles that use such techniques...
Checklist
=========
References
==========
> Voodoo: vertical display programming fix.

- src/include/86box/vid_svga.h
- src/video/vid_et3000.c
- src/video/vid_et4000.c
Summary
=======
ET3000AX: the chip in question should not support 1MB of video memory.
ET4000AX: the early TC6058AF revision can support 1MB of video memory (e.g.: Diamond Speedstar BIOS D3.10, undumped anyway), and actually don't update the rowoffset to 256 when using such chip in 320x200x256 mode. Fixes the copper demo in said chip revision.
Checklist
=========
References
==========
> Tseng Labs fixes and bug-compatible fixes too.

- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.ui
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsmachine.hpp
- src/qt/qt_settingsmachine.ui
Summary
=======
This adds a few UI updates.
First, a warning was added about the performance impact of softfloat if enabled. Screenshot:
Second, some voodoo updates.
If a voodoo is selected as the *primary* display card, the UI disables the option to add a voodoo 1 or 2. Note that this can be overridden in the config file and will be respected.
To make things a little more clear, `Voodoo Graphics` was replaced with `Voodoo 1 or 2 Graphics`.
Screenshot:
Checklist
=========
References
==========
N/A
> UI updates: softfloat and voodoo

- src/86box.c
- src/config.c
- src/device.c
- src/include/86box/86box.h
- src/qt/qt_deviceconfig.cpp
- src/qt/qt_main.cpp
- src/qt/qt_util.cpp
- src/qt/qt_util.hpp
Summary
=======
* MAC Address configuration
* UUID generation based on vm path
* Detection when a vm is moved or copied
* Regeneration of configured MAC addresses when a vm is copied
* Centered device name in configuration dialog
MAC addresses can now be configured in device settings. A `Generate` button is provided to generate a random MAC. Previously this could only be done by manually editing the config file.
Note: The input dialog is filtered and limited to only hex characters.
Screenshot:
Note that the device name is now centered. It was previously left justified.
A UUID is now generated during vm start. The UUID is based on the filesystem path of the current vm and is stored in the `General` section. This is used to detect when a vm has moved from its original location.
The primary …
> MAC address configuration, machine move detection

- src/config.c
- src/qt/qt_platform.cpp
Summary
=======
The `plat_get_cpu_string` function was added a while back (#3533) in order to try and detect the host cpu string. This takes the function and adds the output to the `General` section in the config as `host_cpu`.
Additionally, this will also add `EMU_BUILD_NUM` into `General` as `emu_build_num` if it is set to anything other than the default `0`.
Checklist
=========
References
==========
#3533
> Add host_cpu and emu_build_num to config

- src/sound/snd_pas16.c
Summary
=======
Okay, turns out bit 5 (for the board revision) is for all PAS2-based cards, which includes both Plus and 16.
This should fix the PCM IRQ on PoP1 and board detection on Plus DOS drivers.
Checklist
=========
References
==========
> PASPlus fix for PoP1

- src/machine/m_at_386dx_486.c
Summary
=======
this should fix the issues.
Checklist
=========
References
==========
Provide links to datasheets or other documentation that helped you implement this pull request.
according to theretro web has 1x ide interface 
https://theretroweb.com/motherboards/s/siemens-nixdorf-system-board-d824
uses FDC37C651 SUPER 1/0 FLOPPY DISK CONTROLLERS 
http://www.bitsavers.org/components/standardMicrosystems/_dataSheets/SMC_37C651.pdf
mainboard pictures : https://www.ebay.it/itm/256012385136
Technical Manual See Page 6
https://theretroweb.com/motherboard/manual/fts-systemboardd824technicalmanualen-10-1083427.pdf-5f6661e2be9b0918876552.pdf
> Fix Error initializing Hard Disk Controller in Siemens Nixdorf D824

- src/qt/qt_settingsdisplay.cpp
Summary
=======
In #4327 I was accidentally disregarding an earlier check for whether the voodoo option is enabled based on PCI capability. This moves the check to the correct place.
Checklist
=========
References
==========
#4327
> Voodoo UI option fix

- src/machine/m_at_386dx_486.c
- src/machine/m_at_socket5.c
- src/machine/m_xt.c
- src/video/vid_et4000w32.c
This pull request makes changes for the following 4 machines:
-pravetz16: capitalization of `BIOS_IMKO4_FE00.BIN` corrected to `BIOS_IMKO4_FE00.bin`
-s76p: capitalization of `s76p.rom` corrected to `S76P.ROM`
-dellplato: capitalization of `1016AX1J.bio` and `1016AX1J.bi1` file extensions corrected to `.BIO` and `.BI1` respectively
-pb450: capitalization of `OPTI802.BIN` corrected to `OPTI802.bin`
This pull request makes changes for the following 2 video cards:
Tseng Labs ET4000/w32p Rev. B PCI (VideoMagic)
Tseng Labs ET4000/w32p Rev. B VLB (VideoMagic) (these both share a ROM, and its extension needed to be lower-cased)
Summary
=======
Due to case-sensitive filesystems on *nix systems, these machines and video cards were not showing up. I was told it's preferred to edit the source code …
> Fix missing devices and machines on Linux (and probably MacOS/*nix in general)

- src/network/net_tulip.c
Summary
=======
This fixes detection under various operating systems, including NT-based ones.
Checklist
=========
References
==========
> the DEC 21143-based NIC expects a SROM Format version of 3

- src/qt/qt_harddiskdialog.cpp
- src/qt/qt_harddrive_common.cpp
- src/qt/qt_harddrive_common.hpp
- src/qt/qt_settings.cpp
- src/qt/qt_settings_bus_tracking.cpp
- src/qt/qt_settings_bus_tracking.hpp
- src/qt/qt_settingsfloppycdrom.cpp
- src/qt/qt_settingsfloppycdrom.hpp
- src/qt/qt_settingsharddisks.cpp
- src/qt/qt_settingsharddisks.hpp
Summary
=======
This PR adds a new internal bus tracking feature for IDE, ATAPI and SCSI buses. Essentially, channels that are in use by other devices are disabled in the UI and therefore unable to be selected. It also fixes an issue where the channel suggestion doesn't properly select the lowest one after a drive removal.
Checklist
=========
References
==========
N/A
> qt: Disable bus channels that are currently in use

- src/video/vid_xga.c
Summary
=======
As well as the cursor/sprite being finally fixed when the xoff goes from 0x20 onwards. This makes Win3.x' XGA cursor look normal and everything else as well. (as in, intact).
Checklist
=========
References
==========
[XGA 1-2 manual (for the mapping)](http://bitsavers.trailing-edge.com/pdf/ibm/pc/cards/IBM_VGA_XGA_Technical_Reference_Manual_May92.pdf)
> Cleanup of the XGA mapping to be less messed up.

- src/sound/snd_sb.c
Summary
=======
Variable declarations, unlike statements, aren't allowed after labels (including case labels) according to the C standard, so insert a semicolon to make an empty statement that satisfies the requirement.
Oddly, MSYS2/MinGW-w64 GCC, unlike other compilers, including GCC on other systems, seemed to accept them without errors...
Checklist
=========
References
==========
N/A
> snd_sb.c: Fix compilation error

- src/qt/qt_deviceconfig.cpp
Summary
=======
This addresses a warning in `qt_deviceconfig.cpp`. There was a recent refactor where a raw / cast pointer to a `QString` was being used rather than the `QString` itself. This PR flips it around and let the `QString` (`selected` var) be used instead. In the one case that it needs a comparison with the C string value the necessary Qt function is used instead.
Checklist
=========
References
==========
N/A
> Clean up warning in DeviceConfig

- src/machine/m_xt_olivetti.c
Dumped BIOS 2.11
Updating the BIOS from 2.04 to 2.11 fixes several bugs:
- "Format Failure" message during hard disk formatting under MS DOS
- WANGTEK 40 MB streaming tape unit management
- I/O errors in floppy disk after an ON/OFF sequence
- Clock problems after using "GOSLOW"
- Possibility of testing system from a remote work station
- Possibility of programming in RTCC
- Solves FUJITSU 8284 problem
Summary
=======
Add Olivetti M240 BIOS version 2.11
Checklist
=========
> Update Olivetti M240 BIOS to 2.11

- src/scsi/scsi_ncr53c400.c
Summary
=======
See above, so that the CD-ROM speed is accurate enough on both ends (T13B and the MMIO variants) and, at the same time, not timing out abnormally.
Checklist
=========
References
==========
> DMA speed fixes in place on the 53c400.

- src/include/86box/vid_8514a.h
- src/video/vid_ati_mach64.c
- src/video/vid_ati_mach8.c
Summary
=======
1. On both Mach'es: direct linear video memory access is now the default for LFB mapping: fixes Mach64 drivers on NeXTSTEP/OPENSTEP and keeps everything else intact.
2. Mach8/32: minor cleanup to mode change code.
Checklist
=========
References
==========
> ATI Mach32/64 changes for the better:

- .github/workflows/cmake_windows_msys2.yml
Summary
=======
This PR disables the 32-bit windows builds in GitHub Actions.
Checklist
=========
References
==========
N/A
> GHA: Disable 32-bit windows builds

- src/CMakeLists.txt
- src/cJSON.c
- src/floppy/CMakeLists.txt
- src/floppy/fdd.c
- src/floppy/fdd_pcjs.c
- src/include/86box/fdd_pcjs.h
- src/include/cJSON.h
Summary
=======
This PR adds support for pcjs json floppies. This PR also adds cJSON to 86Box in order to properly support the required json parsing. cJSON is a lightweight json parser for C and comes in the form of a single source / single header file combo.
Specifically, this implements v2 of the pcjs image spec. All disk images are treated as read-only. 
More information here: https://www.pcjs.org/tools/diskimage/
pcjs v2 spec info: https://github.com/jeffpar/pcjs/blob/master/machines/pcx86/modules/v2/disk.js
This supplants the existing pcjs json floppy support (`fdd_json.c` and `fdd_json.h`) which was written to the pcjs v1 spec. Those files can be removed once this is merged.
Checklist
=========
References
==========
https://www.pcjs.org/tools/diskimage/ …
> Add support for pcjs json floppy images

- src/video/vid_ati_mach64.c
Summary
=======
These few cases where it gets corrupt fonts like in some builds of NT 4.0 and mode changes in Win95's driver. Hopefully this keeps everything else intact.
Checklist
=========
References
==========
> Fix Mach64 LFB in some cases.

- src/sound/snd_sb_dsp.c
Summary
=======
Add sanity checks to prevent segfaults on non-ESS SB clones using the setirq and setdma8 functions.
Checklist
=========
References
==========
> Non-ESS SB clones fix:

- CMakeLists.txt
- src/CMakeLists.txt
- src/cpu/386_common.h
- src/cpu/386_dynarec.c
- src/cpu/386_dynarec_ops.c
- src/cpu/cpu.c
- src/cpu/x86.c
- src/cpu/x86_ops_flag.h
- src/cpu/x86_ops_mov_ctrl.h
- src/cpu/x86_ops_ret.h
- src/io.c
- src/mem/mem.c
Summary
=======
Extends (or rather, brings back previously removed code for) full debug register emulation to 486 and later CPUs, including I/O breakpoints for most P5 and P6-class ones. Due to a major performance decrease even during regular usage, especially on lower-end host PCs (the reason it is normally limited to 386 CPUs) with it present, it must now be enabled during compile time with the `DEBUGREGS486` option.
Checklist
=========
References
==========
N/A
> Restore debug register emulation for 486+ CPUs behind a compile-time option

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_ics2494.c
- src/video/vid_svga.c
Summary
=======
1. Corrected the ATI 1881x clocks for use with the ATI Mach8/32 and VGA Wonder chips. The CPU slowdowns should now be gone.
2. Merged I/O ports common to both the ATI and IBM 8514/A compatible chips where they have identical code (extended behavior is still separate). Code duplication is now less than before.
3. Fixed a general polygon pattern issue in the Mach8/32 affecting calc.exe in Win3.x and other stuff.
4. Mode changes are, once again, changed (ATI and IBM), as close as possible to the real thing without destroying existing resolutions.
5. The 8514/A Vertical Counter has been extended to 0xfff so that it can take 1280x1024 resolutions well offered by the Mach32 as well as a better way to change the IBM/ATI modes through a callback swap where approprietate.
6. In …
> Video changes part 1 for 4.2

- src/video/vid_s3_virge.c
Summary
=======
So that ViRGE cards can work again without black screening.
Checklist
=========
References
==========
> Fix onboard flag for actual onboard ViRGE BIOSes.

- src/device/isamem.c
Summary
=======
* Lotech EMS doesn't have the ability to disable the page frame
* fix ability to use all available EMS on the board (Previously 16k was unavailable)
Checklist
=========
References
==========
None
> Two fixes to lo-tech EMS board

- src/device/isamem.c
- src/machine/machine_table.c
Summary
=======
* Fix IBM 5170's memory size choices
* Add the IBM 32k Memory Expansion Option
* Add the IBM 64K Memory Expansion Option
* Correct existing IBM Memory to match the 64/256K Memory Expansion option
* Add the IBM PC/AT 128KB Memory Expansion Option
Checklist
=========
References
==========
None
> Correct IBM 5170 memory size, more IBM ISA memory cards

- src/qt/qt_deviceconfig.cpp
Summary
=======
Fix 2 segfaults in deviceconfig found due to isamem/isartc.
Checklist
=========
References
==========
None
> Fix 2 segfaults in DeviceConfig

- src/machine/machine_table.c
Summary
=======
Correct max mem on IBM 286 clones and the XT/286
Checklist
=========
References
==========
None
> Correct max mem on IBM 286 clones and the XT/286

- src/device/isamem.c
Summary
=======
Fix granularity of Generic AT RAM expansion card
Checklist
=========
References
==========
None
> Fix granularity of Generic AT RAM expansion card

- src/mem/mem.c
Summary
=======
Fixes building with debug registers for 486+ enabled
Checklist
=========
References
==========
N/A
> mem.c: Remove (conditionally) duplicate definitions

- src/machine/m_at_socket7.c
- src/machine/machine_table.c
Summary
=======
Add optional onboard C&T 69000 video to the ADLink NuPRO-592, allowing it to be turned into the NuPRO-591 model, since the BIOS supports all three (590 with onboard video and not-yet-emulated NIC, 591 and 592). The machine name has been altered accordingly.
Checklist
=========
References
==========
<https://theretroweb.com/motherboards/s/adlink-nupro-590-series>
> Add onboard C&T 69000 video to the ADLink NuPRO-592

- src/video/vid_et4000.c
Summary
=======
This should fix the black screens when returning to text mode after the GUI.
Checklist
=========
References
==========
> ET4000 RAMDAC break fix.

- src/video/vid_paradise.c
Summary
=======
Banking no longer goes beyond 0xfffff thanks to masking, fixes possible and in-coming glitches on said cards.
Checklist
=========
References
==========
> More fixes to the Paradise/WD VGA cards

- src/qt/qt_main.cpp
Summary
=======
Qt6 on Windows defines the UNICODE macro by default unlike Qt5. This PR fixes compilation with Qt6 on Windows by forcing it and changing the WinBox manager checks to use Unicode strings.
Checklist
=========
References
==========
None.
> Compile fixes for Qt6 on Windows

- src/disk/hdc_ide_w83769f.c
- src/include/86box/hdc.h
- src/include/86box/machine.h
- src/machine/m_at_socket4.c
- src/machine/machine_table.c
Summary
=======
The Micronics M5Pi is a Socket 4 430LX machine that uses a version of the "PhoenixBIOS Ax86" BIOS. Possibly one of the last machines to use a relatively-stock version of the old Phoenix BIOS.
Checklist
=========
References
==========
https://theretroweb.com/motherboard/manual/m5pi-5f691a3f73f3a600802954.pdf
> Add Micronics M5Pi

- src/qt/qt_util.cpp
- src/qt/qt_util.hpp
Summary
=======
A few updates to the UUID system:
* Ensure relative paths are properly resolved to the canonical dir
* Do not display a mismatch prompt unless the system has configured NICs. If there are no configured NICs, just update the UUID on mismatch because there is no action to be taken.
Checklist
=========
References
==========
N/A
> UUID updates

- src/qt/qt_mediamenu.cpp
Summary
=======
Fixes a crash in the host drive enumeration where pointers were being passed from a `QString` that went out of scope.
Checklist
=========
References
==========
N/A
> Fix strings in enumeration of host drives

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
IBM 8514/A set:
Fixed a one off video bug that was causing the VGA video to not be restored after quitting a 8514/A GUI session (namely on Win2.x' 8514/A's driver). ATI Mach32:
Fixed another vertical display issue when activated (in 1280x1024 mode, when 1024 was 1022). All involved:
Apply RG's changedvram fix to 8514/A, Mach8/32 and XGA's changedvram pointers.
Checklist
=========
References
==========
> Video changes of the day (July 8th, 2024)

- src/qt/qt_settings.cpp
- src/qt/qt_settings.ui
- src/qt/qt_settingsfloppycdrom.ui
- src/qt/qt_settingsotherremovable.ui
Summary
=======
This PR updates the main settings window to make it consistent across platforms:
* Reverts `152c0cbf1` to restore back to a list view
* Gets the current font size (which may vary by OS and theme / font size) and sets the cell height as a double of that to allow enough space for wrapping text
* Enables word wrap on the list view entries
* Sets the width on the list view (200, just a bump up from the original 192 to arrive at ~1/4 of the overall width give or take some pixels for padding)
* Correctly sets the size policy on the list view
* Removes some old hacks that were in place around sizing the list view. They are no longer necessary with the appropriate sizing and size policies
In addition, I took the opportunity to update the CD-ROM and MO/ZIP pages as well. There were …
> Settings window fixes on mac and linux

- src/include/86box/net_ne2000.h
- src/include/86box/network.h
- src/network/net_ne2000.c
- src/network/network.c
Summary
=======
Currently, the emulator allows only NE1000-like ethernet boards for the XT-class machines. However, a relatively popular modern 8-bit NE2000-compliant board exists[^OBP] https://github.com/skiselev/isa8_eth. 
[^OBP]: And, possibly, if not 8-bit, then 16-bit but 8-bit ISA-compatible NE2000-like boards existed -- I used at last one such board, which worked with more or less general packet driver named ne2000\.com. 
So I attempted to add ability to add 8-bit NE2000-compatible boards to the XT machines. It is a rather straightforward clone with minimal modifications of the NE2K_NE2000_COMPAT. I am using the board on the real hardware, in fact this code appeared due to recreating the Amstrad 1640 PC with this board in emulation. 
Tested basically in the SLiRP and PCap modes, …
> Initial support for the 8-bit NE2000 compatible boards.

- src/video/vid_paradise.c
Summary
=======
Sometimes 256 color+ would still glitch because the generic way of enabling 8bpp mode is triggered instead. This fixes some stuff that relies on it.
Checklist
=========
References
==========
> PVGA 256 col+ fixes (July 14th, 2024)

- src/include/86box/machine.h
- src/machine/m_at.c
- src/machine/machine_table.c
Summary
=======
Wells American A*Star 286 IBM PC AT clone 6-14mhz w/ BIOS
Checklist
=========
References
==========
my physical machine and a bunch of magazines on google books.
https://theretroweb.com/motherboards/s/wells-american-corporation-a-star-14mhz
> add Wells American A*Star AT clone

- src/disk/mo.c
- src/disk/zip.c
- src/qt/qt_machinestatus.cpp
- src/scsi/scsi_cdrom.c
- src/scsi/scsi_disk.c
Summary
=======
All: the icon refresh for the respective storage now works properly across all adapters that use it (especially the aha154x compatibles and spock/tribble).
SCSI CD-ROM: The Sony/Texel/DEC SCSI command 0xC0 (Set Address Format) isn't a command that checks for ready status, however, it is for other vendors like NEC, Matsushita, etc. and I am not wishing to create a duplicate command_flags array duplicate just for vendor unique commands. This fixes the MSF bit of Sony/Texel/DEC CD-ROM drives which don't use the Mode Page equivalent.
Toshiba only: attempt to mark the 3201B as a SCSI-1 only CD-ROM drive properly.
Checklist
=========
References
==========
[Texel SCSI CD-ROM drive manual (same commands as Sony + 0xC0)](http://www.bitsavers.org/pdf/texel/Texel_DMxx28_CDROM_SCSI_V1_ …
> SCSI and disk fixes (July 14th, 2024)

- src/sound/resid-fp/FilterModelConfig6581.cpp
- src/sound/resid-fp/FilterModelConfig8580.cpp
- src/sound/resid-fp/WaveformCalculator.cpp
- src/sound/resid-fp/config.h
Summary
=======
Fix resid warnings, and also explicitly set the C++ version
Checklist
=========
References
==========
None
> Fix resid warnings, and also explicitly set the C++ version

- src/sound/resid-fp/WaveformGenerator.cpp
Summary
=======
Title.
Checklist
=========
References
==========
N/A
> residfp: Fix unused variable warnings with Clang

- src/video/vid_chips_69000.c
Summary
=======
Cleaned up the code and fixed the reset and LFB accesses. NT 4.0 now works with its v2.47 drivers without a soft reset (it used to only with a soft reset originally and, without it, hang with a blank screen upon reaching the GUI).
Checklist
=========
References
==========
> Chips PCI card fixes (July 20th, 2024)

- src/qt/qt_settingsports.cpp
- src/qt/qt_settingsports.hpp
Summary
=======
Cleans up the QT serial headers and adds underlying UI support for COM5-7
Checklist
=========
References
==========
None
> Serial cleanups and forward support improvements

- src/chipset/opti499.c
Summary
=======
Title. Fixes an use after free() warning.
Checklist
=========
References
==========
N/A
> opti499.c: Remove an unneeded call to free()

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
This driver was originally started as SMT3 by Cacodemon345, but later changed to Touchpen 4 as that variant dropped most legacy output formats so less had to be implemented. This PR implements SMT3 legacy Format Hexadecimal, which is needed to play Funworld Photo Play 2000 software.
The original Format Tablet code does some interesting bit checking with b and dev->b, which makes the calibration routine give replies so fast after CX, that it confuses the Photo Play software. For format hex I have added simpler mouse button check, and let the calibration routine run after a mouse button release. Maybe Cacodemon345 can tell if the original behavior was intended, or we can simplify Format Tablet the same way?
Checklist
=========
References
==========
Reference: …
> Adding SMT3 Format Hexadecimal to Microtouch driver

- src/config.c
- src/include/86box/plat.h
- src/qt/qt.c
- src/unix/unix_sdl.c
* plat_vidapi() accepts char pointer, which never gets modifed later on. Mark it as const.
* In src/config.c, va_name is initialized as NULL, however, plat_vidapi_name() never returns a NULL pointer, nor it was initialized under a condition branch. Removing NULL, might save one instruction, which requires zeroing the register before setting its initial value.
=========
> Mark plat_vidapi() argument as const and remove the NULL

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
As it now emulates more protocols than the TouchPen, I figured it'd be better defined as just 3M Microtouch (as it now does part of SMT3(V) and TouchPen 4
Checklist
=========
References
==========
> Updated description of Microtouch Emulation

- src/cdrom/CMakeLists.txt
- src/cdrom/cdrom_image.c
- src/cdrom/cdrom_image_backend.c
- src/cdrom/cdrom_ioctl.c
- src/include/86box/cdrom.h
- src/include/86box/cdrom_image_backend.h
- src/qt/qt_settingsfloppycdrom.cpp
Summary
=======
Add support for wave files in cue sheets using libsnd.
Checklist
=========
References
==========
> Add support for wave files in cue sheets using libsnd

- src/include/86box/scsi_ncr5380.h
Summary
=======
Remove dead code in scsi_ncr5380.h
Checklist
=========
References
==========
None
> Remove dead code in scsi_ncr5380.h

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
Simplify mouse button checks and remove alternate calibration routines to build a proper foundation to add the next commands.
Verified with Photoplay 2000, Megatouch XL, DOS and windows 95 Microtouch drivers.
Checklist
=========
> Microtouch: Simplify mouse button and calibration checks

- src/device/mouse_microtouch_touchscreen.c
- src/include/86box/mouse.h
- src/qt/qt_rendererstack.cpp
Summary
=======
In 86Box 4.1, the mouse cursor was disabled in relative input mode, then used by wacom_tablet device only. Cacodemon345 changed this to a crosshair cursor for the Microtouch driver. This PR restores the old default behavior, but adds an option for the Microtouch device to enable or disable the crosshair.
Checklist
=========
> Microtouch: add option to turn off visible mouse crosshair

- src/qt/languages/fr-FR.po
- src/qt/languages/ru-RU.po
- src/qt/languages/uk-UA.po
- src/qt/qt_deviceconfig.cpp
- src/qt/qt_joystickconfiguration.cpp
- src/qt/qt_progsettings.cpp
- src/qt/qt_settingsmachine.cpp
Summary
=======
- Fix the "None" option not being translated in several places (FPU selection, host joystick selection, host serial port selection for serial passthrough)
- Make "POV # (X/Y axis)" translatable
- Add translations for "MiB" in the HDD table header for languages that require it
Checklist
=========
References
==========
N/A
> Miscellaneous UI fixes

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
Microtouch:
- Add menu option to select between the four available Microtouch controller identities.
- Add format Decimal.
- Have identities boot up in the right default modes.
- Fix SOH flag not being reset after packets.
- Optimize format Hexadecimal.
- Update TODO and rename variables for format to build a foundation to implement modes later.
Checklist
=========
References
==========
www.touchwindow.com/mm5/drivers/mtsctlrm.pdf
> Microtouch: add controller type selection and start adding legacy modes for them

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
- Set CTS/DSR/DCD high like a real Microtouch so linux drivers don't hang anymore.
- Implement Mode Status for Format Hex/Dec, making the default modes like the real thing.
- Change fifo sizes and behavior to not feed a serial port that just opened with 500 bytes of click data.
- Add a few more empty command responses. Set unknown commands to reply back with 0 instead of 1. Sort alphabetically.
- Currently, the mouse poll interrupt creates serial packets. The old code did so at 100Hz. The real Microtouch sends data as fast as it can do over the serial port, making the rate different per mode. The future solution is to decouple the data generation from the mouse polling, but for now I've set the poll rate to the approximate speed the different modes need as a workaround. …
> Microtouch: serial fixes, poll rate increases, mode status, cleanups

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
My current progress as a quick PR to fix compiler warnings:
- Always return <SOH>0<CR> (success) for commands to greatly increase compatibility in case we don't know what to do.
- Remove command wrapper function plus empty commands and fix compiler warnings around it.
- Fix unit type string for SMT2/3.
- Update touch liftoff to send previous location to make win95 paint go less crazy. Touchdown still not great though.
Checklist
=========
> Microtouch: fix compilation warnings, optimize command handling and liftoffs

- src/fifo8.c
- src/include/86box/fifo8.h
- src/include/86box/scsi_pcscsi.h
- src/scsi/scsi.c
- src/scsi/scsi_cdrom.c
- src/scsi/scsi_pcscsi.c
Summary
=======
Ported the latest changes/fixes to the above controller from QEMU and added a bios-less AMD Am53c974 device (non-DC390). The latest changes fix the AMD-branded DOS ASPI drivers on both cards (even without bios).
Checklist
=========
References
==========
> AMD/DC390 SCSI fixes of the day (August 4th, 2024)

- scripts/86Box-install-roms.sh
I would like to submit a simple shell script that can be conveniently used by a user download the ROM files for 86Box.
This script was tested in FreeBSD, but there should be no reason it should not work in Linux also.
> add helper script to download ROMS to user's home directory

- src/scsi/scsi_cdrom.c
- src/scsi/scsi_pcscsi.c
Summary
=======
SCSI CD-ROM: request sense command should preserve its sense data unless a different command is issued, fixes DOS hanging with a blinking cursor using CDSCSI-2.sys for the 53c9x MCA card when there's no CD inside, making its no length Data In hack no longer needed.
Checklist
=========
References
==========
[SCSI-2 specification, page 112 of the PDF](http://www.bitsavers.org/components/ncr_symbios/scsi/SCSI-2_Standard_1994.pdf)
> SCSI fixes of the day (August 8th, 2024)

- src/video/vid_tgui9440.c
Summary
=======
Adjust the resolution accordingly for 1280x1022x256 (weird resolution using NT 3.1 drivers) as well as the X axis mouse movement in interlaced mode.
Checklist
=========
References
==========
> TGUI9440 (VLB/PCI) change of the day (August 9th, 2024)

- src/include/86box/vid_svga.h
- src/video/vid_s3.c
- src/video/vid_svga.c
- src/video/vid_tgui9440.c
Summary
=======
1. SVGA: Added an indicator of the internal line to make matters easier for some vertical resolution problems.
2. TGUI 9400CXi: Fixed the basic acceleration as much as I could.
3. TGUI 9440AGi+: As with the line indicator, make matters easier for some resolution problems plus some refactoring of the bpp. Added write protection to some regs based on some documentation on the vt8601.
4. TGUI cursor: fixed the left edge of the cursor X offset.
5. S3: Apply the vblankstart = dispend statement only on enhanced modes, fixes vertical display on The Incredible Machine for DOS.
6. Commented out some excess logs.
Checklist
=========
References
==========
> Video changes of the day (August 12th, 2024, S3/TGUI/SVGA)

- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_tvp3026_ramdac.c
Summary
=======
1. TVP3026: disable lut mapping on 24bpp modes (mainly the S3 Vision968 drivers which use the TVP3026 ramdac).
2. S3 Vision968 (MiroVideo 40SV Ergo): Corrected 1280x1024 24bpp resolution.
3. ViRGE class: limit the FIFO entries in the bitblt regs to less than 16 entries and make the Image Transfers FIFO writes not wraparound to 1 and reads to 0 (to allow at least a read to a write in the thread without hanging the entire emulator elsewhere). Fixes Win3.1 PBRUSH colors while keeping performance on par with PCem.
Checklist
=========
References
==========
> S3 changes (and TVP3026) of the day (August 15th, 2024)

- src/video/vid_s3_virge.c
Summary
=======
Make sure the ViRGE GX2 and up (including the Trio3D/2X) use the secondary stream only per what was found in the past.
Checklist
=========
References
==========
> Some fixes to the Streams engine of the ViRGE/Trio3D

- CMakeLists.txt
- src/CMakeLists.txt
- src/qt/CMakeLists.txt
- src/thread.cpp
Summary
=======
Fix the SDL UI failing to build with duplicate symbol errors when C++11 threads are disabled in favor of pthreads - the `CPPTHREADS` CMake options is functional again. Also revert previous failed fix attempts.
Checklist
=========
References
==========
N/A
> Fix SDL UI failing to build when C++11 threads are disabled

- src/video/vid_s3_virge.c
Summary
=======
Apparently the extended sequencer registers (>= 0x20) are required to have sane values on the STREAMS engine on GX2 and probably other chips in the ViRGE range.
Checklist
=========
References
==========
> More ViRGE fixes (August 29th, 2024)

- src/qt/qt_mediamenu.cpp
- src/qt/qt_mediamenu.hpp
Summary
=======
Fixes 86Box crashing on start after adding a ZIP drive.
Checklist
=========
References
==========
N/A
> Qt: Remove leftovers of the "Reload previous image" option

- src/disk/hdd_image.c
- src/qt/qt_harddiskdialog.cpp
Summary
=======
Instead of writing out disk blocks slowly across the entire volume, just use the ftruncate function to create a file instantly at the desired size.
Depending on file system, this can either result in identical results to the old code just faster (eg: ZFS and btrfs with compression enabled), sparse files (most native Unix file systems without compression, eg ext4 and UFS), or a full non-sparse file like before (creating an image on FAT and exFAT).
Checklist
=========
> Use ftruncate on Unix to create hard disk images quickly

- src/include/86box/vid_xga.h
- src/video/vid_xga.c
Summary
=======
Don't overwrite the VGA DAC mask in XGA mode, instead, using dedicated variables for it.
Checklist
=========
References
==========
> XGA changes of the day (September 5th, 2024)

- src/qt/qt_mediahistorymanager.cpp
Summary
=======
This fixes a crash (introduced in 208b213aac) when inserting/ejecting a disk image.
Checklist
=========
> Media history: fix buffer overflow

- src/video/vid_ati_mach64.c
Summary
=======
The so called "NT 3.5 font fix" on the Mach64 applies only to the Source Control reg with bits 2-3 set, but Solaris only sets bit 2 (without bit 3), so, don't align the source with bit 3 cleared. This fixes the garbled fonts under Solaris using said card.
Checklist
=========
References
==========
> Mach64 font fix about Solaris. (September 13th, 2024)

- src/sound/snd_sb_dsp.c
Summary
=======
This fixes the audio issue on Zool 2.
Checklist
=========
References
==========
> Remove a useless AND to 0x7f in the SB DSP reset routine in its port 0x0e (Read)

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
Noticed there were a bunch of sprintf truncation warnings in the buildbot. This should squash most if not all of them.
Checklist
=========
> Microtouch: Fix compiler warning

- src/video/vid_ati_mach64.c
Summary
=======
Make it sure the alternative 8bpp renderer to avoid any palette flickering.
Checklist
=========
References
==========
> Mach64VT class 8bpp render fix.

- CMakeLists.txt
- src/qt/qt_platform.cpp
Summary
=======
* link with wxneeded is required for DYNAREC, in addition to being installed onto a filesystem with the wxallowed flag (like /usr/local on a default installation)
* pthread_setname_np is pthread_set_name_np on OpenBSD
Checklist
=========
References
==========
https://man.openbsd.org/ld#wxneeded
https://man.openbsd.org/man8/mount.8#wxallowed
https://man.openbsd.org/pthread_set_name_np
> Compile and linker fixes for OpenBSD

- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_vga.h
- src/include/86box/vid_xga.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_cl54xx.c
- src/video/vid_et4000.c
- src/video/vid_ht216.c
- src/video/vid_svga.c
- src/video/vid_vga.c
- src/video/vid_xga.c
Summary
=======
8514/A changes:
1. Correct interlaced display resolution.
2. Added a limit to cursor coordinates.
3. Test/WIP features of the add-on Mach8 side (ATI 8514/A Ultra) such as configurable BIOS.
4. Made the CMD 5 of the acceleration (Polygon Boundary) more accurate per manual (as much as I could regarding the clipping).
Cirrus related:
1. Added SUBSYS PCI vendor/device ID of the 5480 (per manual).
IBM VGA:
1. Built-in/option rom-less VGA don't need the "available" flag.
ATI Mach8/32:
1. As with 8514/A, corrected interlaced display.
XGA-1/-2:
1. Moved the XGA R/W memory size tests out of the SVGA R/W routines to reflect the per card basis, although anything that uses its own SVGA mapping would call the tests there (such as Cirrus, Headland and ATI) when not accessing the LFB. …
> Major video changes of the day (October 3rd, 2024)

- src/device/mouse_microtouch_touchscreen.c
Summary
=======
Added working touchscreen calibration with nvr saving for games that have their calibration points in "wrong" locations.
Also fixed a bunch of naming inconsistencies and made most functions static.
Checklist
=========
> Microtouch: implement calibration extended

- src/qt/qt_mainwindow.cpp
Summary
=======
Makes the About dialog closeable with the Esc key or the window manager's close button.
Checklist
=========
References
==========
N/A
> qt: Make the About dialog closeable with Esc key

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/include/86box/vid_svga.h
- src/include/86box/vid_xga.h
- src/video/CMakeLists.txt
- src/video/vid_8514a.c
- src/video/vid_ati68860_ramdac.c
- src/video/vid_ati_mach8.c
- src/video/vid_bt481_ramdac.c
- src/video/vid_paradise.c
- src/video/vid_s3.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
8514/A/Mach8/32:
Reworked the acceleration a bit as well as the mode switches from VGA to ATI/8514/A mode and viceversa based on the documentation. Fixes the Linux GUI fonts using the Mach32 driver (possibly Mach8 too) and other anomalies (still needs more work on the acceleration though).
PVGA:
Minor fixes to the banking.
S3-based (Pre-ViRGE):
1. Made the chip class use its own banking so that the Enhanced Mode mapping (equivalent to 64K-based A0000) is taken into account (per bit 3 of CRTC31, which forces the mapping to be 64K A0000, regardless of the GDCREG6 bits). Fixes NT 3.1 347.1's S3 driver.
2. Initial rework on 15bpp/16bpp accelerated mode of the 911/924 chips (currently not 100% bug free, I need help with this chips).
XGA-1/2:
Get rid of the linear endian reverse …
> Big video changes of the day (October 26th, 2024)

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_xga.c
Summary
=======
8514/A compatibles:
1. The mode switch (from VGA to 8514/A/ATI and vice-versa) has been fixed again (for the Nth time).
2. Removed a pattern hack used on DPCONFIG = 0x5211 on bitblt, now patterns work properly using the ATI Mach8 3.0 win3.1x drivers.
3. Clipping regs are more accurate for acceleration.
XGA 1-2:
A picky OS is a picky OS, fixes to the Win95 fonts (which uses the pattern sources) applied.
Checklist
=========
References
==========
> Small but important video changes of the day (October 27th, 2024)

- src/include/86box/vid_8514a_device.h
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsdisplay.hpp
- src/qt/qt_settingsdisplay.ui
- src/video/vid_8514a.c
- src/video/vid_xga.c
Summary
=======
IBM 8514/A (MCA/ISA).
Added a configure button to the QT frontend for the amount of memory used by said add-on chips.
XGA:
Forgot a change about the 4mb aperture.
Checklist
=========
References
==========
> Video and emulator GUI changes of the day (October 28th, 2024)

- src/cpu/x86.c
- src/include/86box/vid_8514a.h
- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
1. vga_on global variable removed, as it didn't play well with 2 subsystems at once (8514/A and XGA both enabled).
2. Emulate the Foreground/Background Color aliases of PIX_TRANS properly when not executing a command.
3. Voodoo 3D override now works properly (again) with Mach32 PCI cards and others by turning the 8514/A timer off and on accordingly.
Checklist
=========
References
==========
> Changes to 8514/A compatible stuff (November 2nd, 2024)

- src/qt/languages/vi-VN.po
Summary
=======
Added more strings to cover untranslated parts, also a misinterpreting fix for the "right ctrl is left alt" (which took me two commits)
Checklist
=========
References
==========
Took the strings from [`pt-BR.po`](https://github.com/86Box/86Box/blob/master/src/qt/languages/pt-BR.po)
> vi_VN addition and misinterpreting fix

- src/video/vid_ati_mach8.c
Summary
=======
1. ATI Extended 8514/A mode may not use bit 5 of ATI reg 0xb0 sometimes but at the same time it won't use the standard VGA way of setting up 256+ colors, therefore, in the VGA DAC writes, use standard VGA way to revert to VGA mode in the writes instead of relying on bit 5 of ATI reg 0xb0 being enabled/disabled there. Fixes mode switches in VLB/PCI configurations using Windows 9x and possibly other stuff, ISA is unaffected and still works fine.
2. Added more logs and and remove/set I/O handlers correctly for the PCI side.
Checklist
=========
References
==========
> Fixing regressions of the mach32 (November 5th, 2024)

- src/qt/qt_deviceconfig.cpp
- src/qt/qt_settingsinput.cpp
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingssound.cpp
Summary
=======
- Improve string handling to reduce chance of corruption
- Device name as shown at the top of the device config dialog (as well as the title bar) is now translated too
- Don't attempt to translate system MIDI I/O port names
Checklist
=========
References
==========
<https://doc.qt.io/qt-5/qobject.html>
<https://doc.qt.io/qt-5/qstring.html>
> Further improvements to the translation system

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_eeprom.h
- src/include/86box/vid_svga.h
- src/video/vid_8514a.c
- src/video/vid_ati_eeprom.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
1. Finally add the ATI 8514/A Ultra add-on BIOS in both ISA and MCA variants (despite the ROM page failure on POST).
2. Fixed a mode switch bug in the Mach8 (both add-on and vga combo) when exiting the Win3.x GUI using the native drivers.
3. Corrected (best possible) the eeprom load of the Mach8 products.
4. Partial implementation of the FIFO on the 8514/A compatible products including Mach8/32 and plain IBM 8514/A.
Checklist
=========
References
==========
> Video changes of the day (November 13th, 2024)

- .gitignore
- src/qt/qt_rendererstack.cpp
- src/qt/xinput2_mouse.cpp
Summary
=======
1. Added a line to .gitignore to ignore IDE configuration files generated by the Jetbrains CLion IDE.
2. Moved the check for `mouse_capture` to a position before XInput events are handled. In commit `c695cb8d`, the behavior of `xinput2_proc` was changed to call the function `mouse_scale_x`/`mouse_scale_y` from the previous behavior of modifying xinput-related variables. These calls were made before the `mouse_capture` check, modifying global mouse variables when the mouse input was not captured.
3. Added a check for `mouse_capture` before handling a QWheelEvent. This prevents an issue where mouse scrolls made while the mouse isn't captured cause the behavior of the mouse wheel being 'stuck'  on certain configurations.
Checklist
=========
References
==========
_Provide …
> Linux mouse fixes

- .ci/build.sh
- .github/workflows/cmake_linux.yml
- .github/workflows/codeql_linux.yml
- src/qt/CMakeLists.txt
- src/qt/qt_progsettings.cpp
- src/qt/qt_translations.qrc.in
Fixes standard messagebox buttons not being translated
Summary
=======
Checklist
=========
References
==========
> Embed Qt base translations in the executable

- src/qt/CMakeLists.txt
- src/qt/languages/86box.pot
- src/qt/languages/ru-RU.po
- src/qt/qt_settingsharddisks.cpp
Summary
=======
- Fix HDD preset names (specifically "RAM Disk (max.speed)") not being translated in the HDD table
- Make the Qt base translation embedding introduced in #4973 optional, but enabled by default
- Fix a few mistakes in the Russian translation, as well as translate names of generic ISA memory expansion cards
- Add a template file for new translations
Checklist
=========
References
==========
N/A
> Localization fixes

- .github/workflows/cmake_linux.yml
- .github/workflows/cmake_macos.yml
- .github/workflows/cmake_windows_msys2.yml
- .github/workflows/codeql_linux.yml
- .github/workflows/codeql_macos.yml
- .github/workflows/codeql_windows_msys2.yml
Summary
=======
- Drop the remnants of 32-bit Windows builds, in anticipation of MSYS2's CLANG32 environment being phased out, and the qt5-static package dropping MINGW32
- Add libvdeplug as a dependency on \*nix
Checklist
=========
References
==========
N/A
> GitHub Actions maintenance

- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/m_at_socket7_3v.c
- src/machine/machine_table.c
Summary
=======
@OBattler I was wondering if I could split the Gateway 2000 Tigereye into two different versions..
Mailman (Single-Voltage)
Hitman (Dual-Voltage)
Checklist
=========
References
==========
> Gateway Tigereye Changes

- src/include/86box/snd_resid.h
- src/include/86box/sound.h
- src/sound/snd_resid.cpp
- src/sound/snd_ssi2001.c
- src/sound/sound.c
Summary
=======
Add "The Entertainer" for Microprose Gunship 429.04
Checklist
=========
References
==========
https://forum.vcfed.org/index.php?threads/the-entertainer-sound-card-exposed.41255/
> Add "The Entertainer" for Microprose Gunship 429.04

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
Summary
=======
- Add checkboxes to make sure users have reproduced the issue with latest Jenkins builds and searched the issue tracker beforehand
- Remove the host CPU field, since the host CPU is now reported in the .cfg files
- Remove the download source dropdown, since builds from third-party sources are unsupported anyway
- Fix the link to the machine request thread
- Miscellaneous tweaks
Checklist
=========
References
==========
N/A
> Issue template updates

- src/include/86box/snd_opl.h
- src/sound/snd_opl.c
- src/sound/snd_opl_ymfm.cpp
Summary
=======
Add initial support for YM2151 & YM2164
(Specifically the underlying hooks for the SAAYM and IBM Music Feature Card in YMFM)
Checklist
=========
References
==========
None
> Add initial support for YM2151 & YM2164

- src/include/86box/snd_opl.h
- src/sound/snd_opl.c
- src/sound/snd_opl_ymfm.cpp
- src/sound/ymfm/CMakeLists.txt
- src/sound/ymfm/ymfm_opn.h
- src/sound/ymfm/ymfm_opx.h
Summary
=======
Adds all the variants of various FM Chips that YMFM supports to our code
(This will still need soundcards which actually take advantage of it to use however)
Fixed a couple of bugs in YMFM
Checklist
=========
References
==========
None
> More YMFM backend integration work

- src/video/vid_cl54xx.c
- src/video/vid_s3.c
Summary
=======
Cirrus 5436/46 and 5480.
Finally fixed the Solaris 2.6 font issue, was a dword swap one with color expansion.
S3.
1. Make 868/968 ignore horizontal skew, ergo horizontal override until a proper solution is found regarding hardware tests.
2. Fixed a minor mix issue with S3 911/924 Win3.1 drivers in 8bpp mode.
Checklist
=========
References
==========
> S3 and Cirrus updates of the first day of winter (December 21, 2024)

- src/cpu/cpu.c
- src/cpu/cpu.h
- src/mem/mem.c
Summary
=======
Port [PSE-36](https://en.wikipedia.org/wiki/PSE-36) (36-bit page size extension) support for Pentium II-class (post-Klamath) CPUs [from PCBox](https://github.com/PCBox/PCBox/compare/5a00b0a567...2f2effba2e).
Checklist
=========
> Add PSE-36 (36-bit page size extension) support

- src/video/vid_8514a.c
Summary
=======
Fix nibble pixtrans on bitblt command (CMD 6), this makes icons and stuff on MS OS/2 1.10 Nokia's 8514 driver no longer glitchy (IBM's was already fine as is and it still is).
Checklist
=========
References
==========
> 8514/A change of the day (December 22nd, 2024)

- src/cpu/808x.c
- src/cpu/cpu.c
- src/cpu/cpu.h
- src/cpu/cpu_table.c
- src/include/86box/machine.h
- src/machine/m_xt.c
- src/machine/machine_table.c
Summary
=======
This pull request adds initial emulation of the Mazovia 1016, which was a homegrown IBM PC/XT clone designed in Poland using components available in the Eastern Bloc. Notably, as 8088 clone CPUs were not available at this time, the Mazovia adapts the XT design to use an 8086 CPU, albeit with I/O bus accesses lengthened by an additional cycle (as documented by the references).
Note that this attempts to emulate the original "M86" design. Some manufacturers of the Mazovia later switched to using the same cases to fit (cheaper) Taiwanese 8088 XT boards under their own brand - for example, there exists a BIOS dump from 1989 which is the Phoenix XT 2.27 BIOS with stripped out and replaced copyright notices (no, really, [that's the only major …
> Add initial Mazovia 1016 emulation

- src/video/vid_s3.c
Summary
=======
1. Initialize Multifunction indexes 0x0D and 0x0E properly, should fix inverted colors on S3 OS/2 Warp drivers.
2. Make the remaining Vision868/968 only ports handle the 32-bit toggling properly.
3. Cleanups.
Checklist
=========
References
==========
[S3 Trio32+](http://www.bitsavers.org/components/s3/DB014-B_Trio32_Trio64_Graphics_Accelerators_Mar1995.pdf)
> S3 changes of the day (December 25th 2024, Christmas 2024 gift)

- src/include/86box/sound.h
- src/sound/snd_sb.c
- src/sound/sound.c
Summary
=======
* [Add AWE64 CT4380 no IDE variant](https://github.com/86Box/86Box/commit/e11743c5216226ffa5319612d67fbc95db99684c)
* [Standardization for PNP ROM loading](https://github.com/86Box/86Box/commit/21a98774e46fe9280b6e55d7da59b41336306ce1)
Checklist
=========
References
==========
None
> Add AWE64 CT4380 no IDE variant

- src/network/network.c
Summary
=======
Bring net_cards in line with other device arrays
Checklist
=========
References
==========
None
> Bring net_cards in line with other device arrays

- src/game/gameport.c
- src/include/86box/gameport.h
- src/sound/snd_sb.c
Summary
=======
Add PNP 1IO and make Vibra16XV use it
Checklist
=========
References
==========
None
> Add PNP 1IO and make Vibra16XV use it

- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Summary
=======
Add the Intel 440BX chipset variant of the Compaq ProSignia S316/318 PC, based on the ECS P6BXT-A+ motherboard.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/ecs-p6bxt-a-rev-2-2x
> Add the Compaq ProSignia S316/318 (Intel chipset)

- src/dma.c
Summary
=======
Actually add DMA PS/2 (MCA) XFER commands 0x9 (Set DMA Mask), 0xa (Reset DMA mask) and 0xb to addr 0x1a in both r/w parts.
Checklist
=========
References
==========
> DMA change of the day (December 31st, 2024)

- src/include/86box/scsi_device.h
- src/scsi/scsi_cdrom.c
Summary
=======
Added undocumented 0xC5 NEC SCSI-2 CD-ROM command (most likely a no op command like 0x0D).
Checklist
=========
References
==========
> SCSI CD-ROM change of the day (December 31st, 2024)

- src/scsi/scsi_pcscsi.c
Summary
=======
1. Too many soft resets should not reset the SCSI layer, fixes CD Audio on the 53c90a MCA controller used by guests.
2. Implemented preliminary MDL S/G mode for the PCSCSI side.
3. The underflow DMA function is no longer needed as it now SCSI transfers on the 53c90a MCA controller works properly.
4. Minor corrections to the PCI side (mainly the revision).
5. The DMA 86c01 side of the MCA 53c90a controller is more polished now, should fix some more bugs.
Checklist
=========
References
==========
> Some changes on the PCSCSI code of the new year (January 1st, 2025)

- src/include/86box/machine.h
- src/machine/m_at_socket4.c
- src/machine/m_at_socket5.c
- src/machine/machine_table.c
Summary
=======
1. Added the Award 430NX-based (Socket 5) ASUS P54NP4 with the right configuration.
2. Based on the pictures of the board, the IDE controller is not built-in in the ASUS P5MP3, but on a riser card, iirc, therefore, make IDE optional.
Checklist
=========
References
==========
> Some machine changes of the day (January 1st, 2025)

- src/scsi/scsi_t128.c
Summary
=======
Actually recognize the Trantor 228 MCA SCSI controller as such (bit 3 of status is for the PS/2 MCA bus type of the 128 controller)
Checklist
=========
References
==========
> Late day changes (January 2nd, 2025)

- src/include/86box/machine.h
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
Adding 486 based machine: Compaq Presario 7100/7200 Series
Based on the MiTAC/Trigon PL4600C(-II) Mainboard, Configuration based on Presario 7106 (AMD DX4).
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/mitac-trigon-pl4600c
> Add Compaq Presario 7100/7200 Series 486 Machine (UMC 8881)

- src/sio/sio_pc87307.c
Summary
=======
Don't clobber the GPIO I/O Base value.
According to the PC87307 datasheet, port 0x60 bits [2:7] are read-only for the Parallel Port (4) device and cannot be altered by software. For others devices, the 0x60 port may be written with any value.
The SGI firmware emits the following PC87307 initialization sequence after each reset:
```
/* Select the GPIO device (7) */
SIO IDX: 2E <-- 07
SIO DAT: 2F <-- 07
/* I/O Base MSB = 0x0F */
SIO IDX: 2E <-- 60
SIO DAT: 2F <-- 0F
/* I/O Base LSB = 0xC0 */
SIO IDX: 2E <-- 61
SIO DAT: 2F <-- C0
/* Enable address decoding (I/O Base = 0xFC0) */
SIO IDX: 2E <-- 30
SIO DAT: 2F <-- 01
```
The GPIO I/O Base is erroneously assigned to 0x7C0. Fix by removing the 0x07 mask.
Checklist
=========
References
==========
[PC87307 …
> pc87307: Fix GPIO base address configuration

- src/sound/snd_audiopci.c
Summary
=======
Fixes low pitch problems when MIDI is played back through the software synth.
Checklist
=========
References
==========
None
> Fix wrong sample rate of ES1370 software synth playback

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_s3.c
Summary
=======
S3:
1. Cleaned up the Short Stroke command processing.
2. Proceed calculating the error term only when it's equal or greater than the line length (Draw Line, Command 1 and also applies to Short Strokes, Command 0).
8514/A compatibles:
1. Reworked the polygon draw type A processing.
2. As with the S3, reworked the way error term is handled in the processing, and on Command 5 (Draw Polygon Boundary Line).
Checklist
=========
References
==========
> 8514/A and S3 changes of the late day (January 9th, 2025)

- src/scsi/scsi_pcscsi.c
Summary
=======
Restore the old way of identifying the chip id in the DC390. Fixes NT 4.0 booting from CD-ROM using said SCSI controller when its BIOS is enabled.
Checklist
=========
References
==========
> And DC390 for today.

- src/machine/m_xt.c
Summary
=======
Add other BIOS versions to ibmxt (82)
Extras currently disabled due to some issues.
Checklist
=========
References
==========
None
> Add other BIOS versions to ibmxt (82)

- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
This PR simply allows the selection of either the current default PCI 1.0A BIOS or the PNP 1.1A BIOS in 86Box. Note that nvr (both nvr/pb450.bin and nvr/pb450.nvr) need to be cleared after switching for the change to actually happen.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/packard-bell-pb450#bios
Own experience with PNP 1.1A PB450 board.
> Allow selection between PCI and PNP BIOSes on the PB450.

- src/floppy/CMakeLists.txt
- src/floppy/fdc.c
- src/floppy/fdc_compaticard.c
- src/include/86box/fdc_ext.h
Summary
=======
CCI and CCII mostly implemented, still missing CR_2 bits 5 (Pin 2 control) and 3-0 (Data Transfer Rate Select)
Patch also contains the CCIV, but it's disabled for now due to issues.
Checklist
=========
References
==========
https://retrocmp.de/compati/cc1-3rd.pdf
> Initial Micro Solutions CompatiCard support

- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c400.c
- src/scsi/scsi_t128.c
Summary
=======
1. Sanity check for the SCSI temp_buffer if it's allocated or not.
2. Data reads and writes in non-DMA mode should be accessible only when DMA mode is Idle (as in, no DMA at all, whereas DMA mode will go to the SCSI controllers' callbacks).
3. More fixes to the 53c400 timings.
Checklist
=========
References
==========
> NCR 5380-based changes of the day (January 12, 2025)

- src/86box.c
- src/include/86box/86box.h
- src/include/86box/log.h
- src/include/86box/nv/vid_nv_rivatimer.h
- src/log.c
- src/timer.c
- src/video/CMakeLists.txt
- src/video/nv/nv_rivatimer.c
Summary
=======
This merges core code changes that were made for Nvidia Riva 128 and Riva 128 ZX (NV3/NV3T) emulation.
This pull request is made of two parts:
1. A high-frequency timer ("RivaTimer") that runs asynchronously to the emulated CPU core using the system timer API. Existing timers in 86Box are dependent on the TSC (timestamp register) in the emulated / guest CPU. The Nvidia NV3 clock generators run completely separately and asynchronously to the main clock speed on the CPU, and although the CPU obviously affects the performance (especially as initial geometry transformation and lighting are not actually done by the GPU in this case), the actual clock speed of the Riva 128 is not affected by it. In order to allow current and future efforts to emulate devices that generate their …
> RIVA 128 preparation: Implement high-frequency timer asynchronous to guest CPU and a new logging function to detect repeated patterns of lines

- src/cpu/386_dynarec.c
Changed exec386_dynarec_dyn from inline to noinline to resolve NEW_DYNAREC build issue on Linux x86_64.
Summary
=======
Checklist
=========
References
==========
[Discord thread](https://discord.com/channels/262614059009048590/1231192238672056320/)
Similar issue from PCem: https://github.com/sarah-walker-pcem/pcem/issues/157
https://github.com/sarah-walker-pcem/pcem/pull/159
[Dax's identification of PCem issue and implementation of fix to 386_dynarec.c](https://discord.com/channels/262614059009048590/1231192238672056320/1329041757802991709)
> Change exec386_dynarec_dyn to noinline in 386_dynarec.c

- src/video/vid_ati_mach8.c
Summary
=======
ATI Mach8-based (add-on only):
Do not override the clone VGA banked mapping with the standard VGA when needed. Fixes issues with banked mapping with ATI 8514/A enabled on cards with clone mappings such as Cirrus, Video7, Paradise/WD, etc.
Checklist
=========
References
==========
> 1st set of changes (video-related) of the day (January 16th, 2025)

- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
The Mylex MVI486 system currently lists and uses the Opti 895/82C895 chipset in 86Box.  The real board uses the Opti 498/82C498 chipset, which is a variant of the Opti 495.  This PR updates `machine_table.c` to reflect and select the 495 chipset, and updates `m_at_386dx_486.c` to add the `opti495` device to the machine instead of the `opti895` device.  I have tested basic functionality with the current ROM set.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/mylex-mvi486
https://theretroweb.com/chipsets/379
http://66.113.161.23/~mR_Slug/chipset/cs-search.pl?searchOne=*82C498%20
> Fix incorrect Opti chipset for MVI486

- src/include/86box/vid_svga.h
- src/video/vid_cl54xx.c
- src/video/vid_ht216.c
- src/video/vid_paradise.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
Generic SVGA layer:
Added function pointers of the banked mapping for use with add-on cards with their own mapping when the VGA card banked mapping is not active or viceversa (e.g.: XGA).
XGA-1/2:
1. Reimplemented Area Fill and Boundary Mode as best as possible.
2. Fixed conflicts with banked mapping with VGA clones.
3. Fixed inverted colors (again) on accelerated 16bpp mode under OS/2.
Video7 with ATI 8514/A add-on.
Added a workaround (BIOS issue? I don't know) that disables 8514/A mode and reenables VGA mode when needed. Fixes screen freezes and polling issues with various drivers for Windows and others.
Checklist
=========
References
==========
> The delayed video changes of the night (January 20th, 2025)

- src/include/86box/scsi_device.h
- src/include/86box/scsi_ncr5380.h
- src/scsi/scsi_device.c
- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c400.c
- src/scsi/scsi_t128.c
- src/sound/snd_pas16.c
Summary
=======
1. Separate the SCSI bus functions from NCR 5380 into true general purpose SCSI bus functions, allowing use of future legacy scsi controllers.
2. Corrected NCR 5380 chip period for the SCSI controllers based on that chip so that CD-ROM speed is correct enough per speed tests and no more breakage (I hope, report if they are still there, please!) on desyncs.
3. A NCR 5380 software reset involves asserting an IRQ.
Checklist
=========
References
==========
> Big SCSI bus update of the day, NCR 5380 too (January 20th, 2025)

- src/include/86box/vid_svga.h
- src/include/86box/vid_xga.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
XGA:
1. Added a proper poll so to have its timings independent of the SVGA core and changes its renderer accordingly, mainly a blank render one.
2. Workaround the Ctrl-Alt-Del reset of Windows 2.x so that it switches back to VGA text mode correctly when using the 0xA000 64K aperture (in vid_svga.c).
SVGA core:
Re-organized the way the different timers are organized so that the XGA and 8514/A pollers can coexist with the SVGA timer without conflicts.
ATI Mach32:
Reworked the true color renderer and made it a Mach32 exclusive due to its differences from the standard one. Fixes wrong rendered colors in NT using the 32bpp renderer in RGB mode.
Checklist
=========
References
==========
_Provide links to datasheets or other documentation that helped you implement this pull …
> Video changes of the day (January 26th, 2025)

- src/include/86box/scsi_ncr5380.h
- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c400.c
Summary
=======
Apparently the Trantor T130B SCSI controllers has a different way of calculating the timings and removed the scsi_bus_read() calls from the Current SCSI bus status port (Read Port+4). Fixes NT using said controller as well as CD swapping while maintaining the correct accurate CD speed.
Checklist
=========
References
==========
> More changes to the 5380 chips (January 26th, 2025)

- src/device/keyboard.c
- src/include/86box/plat.h
- src/qt/qt_platform.cpp
Summary
=======
It seems that Ctrl+End was used on non-Win32 platforms because WxWidgets couldn’t use non-modifier keys as a keyboard sequence.  Qt can, and F8+F12 interferes with the operation of software a lot less than Ctrl+End does (try doing some text editing!).
86Box hasn’t used WxWidgets for quite some time and this platform limitation hack has long outlived its necessity.
Checklist
=========
> Use F8+F12 to release mouse on all platforms

- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/machine_table.c
Summary
=======
Add the PC Partner VIA809DS (Socket 7 Dual Voltage/VIA VP3)
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/pcpartner-via809ds-35-8809-xx
> Add the PC Partner VIA809DS (Socket 7 D.V./VIA VP3)

- src/video/vid_mga.c
Summary
=======
Matrox MGA:
A break from work can save the day all so to say. Fixes bitblt'ing on WinNT4.0/Win2000 using 32bpp modes and possibly other stuff using said Matrox chip.
Checklist
=========
References
==========
> Video changes of the night (January 29th, 2025)

- src/machine/machine_table.c
Summary
=======
This is the Part 1 of a planned series of pull requests I will make to fix the machine table entries for 586-based (Pentium, K6, WinChip etc.) machines.
All changes with the commit for this PR are listed below:
Changes
=======
- **ALL BOARDS (except Gateway Mailman, TC430HX, Infinia 7200, CU430HX, Equium 5200D, PCV-90):** Decreased min RAM to 4MB
- **ALL BOARDS:** Decreased min RAM increasement amounts to 4MB
- **ALL INTEL BOARDS (excluding OEM):** Board codename added to the entry names
- **Acer V35N:** Increased max RAM to 512MB; renamed to "Acer AcerPower Ultima"
- **AOpen AP53:** Increased max RAM to 512MB; decreased max multiplier to x2.5; added revision to board name
- **Acer M3A:** Increased max RAM to 512MB
- **ASUS P/I-P55T2P4:** Increased max RAM to 512MB and max …
> Fix various errors with the machine table for 586-based machines (Part 1)

- src/device/keyboard.c
- src/include/86box/keyboard.h
- src/qt/qt_mainwindow.cpp
Summary
=======
All held-down keys are now released when Alt-Tab'ing out of 86Box (or when it is not the active window anymore).
Only applies when Raw Input is in use on Windows.
Checklist
=========
References
==========
None.
> All held-down keys are now released when Alt-Tab'ing out

- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
Summary
=======
Mouse cursor now properly appears after uncapture.
Checklist
=========
References
==========
None.
> Mouse cursor now properly appears after uncapture

- src/video/vid_mga.c
Summary
=======
This PR fixes drawing the background of OS/2 Warp 3 icons on the desktop with a patterned foreground when not selected.
Checklist
=========
References
==========
Original bug:
https://pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15787
> OS/2 3.0 icon backgrounds are now drawn properly

- src/codegen/codegen_ops_x86-64.h
- src/codegen/codegen_ops_x86.h
- src/codegen_new/codegen_ops_helpers.h
- src/cpu/386_dynarec.c
- src/cpu/cpu.h
- src/cpu/x87_ops.h
Summary
=======
This PR reverts all FPU changes made for Final Reality.
Need For Speed III renders to screen discolored with the recent FPU changes made. Fixing Final Reality without breaking everything else will need more thorough changes.
Checklist
=========
References
==========
None.
> Revert all FPU changes for Final Reality

- src/codegen_new/codegen_backend_x86-64_ops.c
Summary
=======
This PR fixes some x64 NDR fatals that were encountered due to some edge cases not getting handled.
Brief testing with NFS III shows no problems.
Checklist
=========
References
==========
None.
> x64 NDR: Properly address the entire cpu_state struct

- src/codegen_new/codegen_backend_x86-64.c
- src/codegen_new/codegen_backend_x86-64_defs.h
- src/codegen_new/codegen_backend_x86-64_ops.c
Summary
=======
This PR fixes crashes/undefined behaviour with 2+ GB of allocated RAM on NDR backend, by properly taking the signed-ness of x64 offsets into account.
There's also a logic fix for 8-bit signed offsets.
Checklist
=========
References
==========
None.
> x64 NDR: Fix crashes/undefined behaviour with 2+ GB of allocated RAM

- CMakeLists.txt
- src/CMakeLists.txt
- src/codegen_new/codegen_backend_x86-64.c
- src/codegen_new/codegen_backend_x86-64_ops.c
Summary
=======
1. NDR is now enforced on ARMv7/ARM64 instead of bombing out with an error.
2. Make GCC/Clang not use anything in the red zone on x64 for now.
3. Compile with `-fno-omit-frame-pointer` on x64 as well.
4. More comments for non-commented machine code.
5. Don't attempt saving/restoring RSI and RDI outside Windows since both are volatile in the System V ABI.
Checklist
=========
References
==========
None.
> Misc. changes for new dynamic recompiler

- src/machine/m_at_286_386sx.c
Summary
=======
This machine wasn't showing up due to searching for a ".bin" when the file was named ".BIN".
Checklist
=========
References
==========
> Fix Acer 100T machine not showing up on Linux due to case-sensitivity.

- src/video/vid_s3_virge.c
Summary
=======
Use a significantly faster version of the ROP code from ET4000/w32 (or pre-ViRGE S3) in place of the current slow one.
DirectDraw tests now run significantly faster, and Direct3D tests also now run smoothly.
Checklist
=========
References
==========
None.
> S3 ViRGE: Use a significantly faster version of the ROP code

- src/video/vid_tgui9440.c
Summary
=======
Use a significantly faster version of the ROP code in the Trident TGUI video cards, instead of the slower one.
At least 30%-40% performance improvement is seen under Windows 98 SE when moving windows around with "Show window contents when dragging" option enabled.
Checklist
=========
References
==========
None.
> Trident TGUI: Use a significantly faster version of the ROP code

- src/video/vid_ps55da2.c
Summary
=======
Changes:
* Add a line drawing function used in Windows 3.x.
* Support some raster operations used in Windows 3.x.
* Change an address mask for video memory accessing.
* Bit mask with word aligned addresses.
* Fix a screen glitch in OS/2 DOS monochrome graphics mode (MODE 1).
* Fix the screen resolution.
This change will also solve an issue mentioned in https://github.com/86Box/86Box/issues/5239#issuecomment-2676323198.
Checklist
=========
References
==========
> IBM PS/55 DA2: Fix various drawing issues in graphics mode

- src/sound/snd_audiopci.c
Summary
=======
Fix ES1370 detection courtesy of TC1995
Checklist
=========
References
==========
None
> Fix ES1370 detection

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati68860_ramdac.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Follow the Mach32 manual more closely regarding vblank support.
2. The subsystem status now takes account of the other bits more accurately.
3. The Mach32 PCI, when used with the ATI 68860 ramdac, has its own bpp's when in accelerator mode, separate from the VGA compatible side, so fix this accordingly.
4. Reset the vram when a mapping change occurs, should clear the messups in the ATI Mach8/32 accel video mode tests.
Checklist
=========
References
==========
[Mach32 manual for the subsystem stuff](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
> 8514/A compatible changes of the day (March 6th, 2025)

- src/qt/qt_machinestatus.cpp
Summary
=======
Fixes a crash when right- or double-clicking the sound status bar icon.
Checklist
=========
References
==========
N/A
> Initialize the sound icon menu pointer

- src/qt/qt_mainwindow.cpp
- src/qt/qt_util.cpp
- src/qt/qt_util.hpp
Summary
=======
Disables Windows 11's rounded window corners on secondary monitor windows, as well as the main emulator window when the status bar is disabled.
Checklist
=========
References
==========
<https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute>
<https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_window_corner_preference>
> Disable Windows 11 rounded window corners when they cover the emulated screen

- src/scsi/scsi_t128.c
Summary
=======
1. Made as best as possible implementation of the status bits 1-2 of the Trantor 128 so to make a more accurate speed for SCSI devices (CD-ROM and HDD) without stalls.
2. Slightly reorganized the timer of the T128.
Checklist
=========
References
==========
> Trantor T128/MediaVision SCSI changes of the day (March 8th, 2025)

- src/video/vid_ati_mach8.c
Summary
=======
Do not subtract from the linear base when it's not in the range, should fix NT 3.x graphics bugs using the LFB.
Checklist
=========
References
==========
> Mach32 LFB changes of the day (March 8th, 2025)

- src/qt/qt_mainwindow.cpp
Summary
=======
Fix Preferences dialog crash due to an oversight.
Checklist
=========
References
==========
None.
> Fix Preferences dialog crash

- src/sound/snd_sb.c
- src/sound/snd_sb_dsp.c
Summary
=======
1. Correct ChipChat mixer port length as well as making mixer reg 0x3a read back its value.
2. Swap the sb port addresses back so that they match the Piper adf. This fixes SoundPiper 16/32 detection.
3. Log cleanups and additions for better debugging.
Checklist
=========
References
==========
> ESS/SB changes of the day (March 8th, 2025)

- src/video/vid_svga.c
- src/video/vid_xga.c
Summary
=======
Workaround xga/vga toggle bug in the inmos card so that it switches from xga to vga and viceversa on ami bioses.
Checklist
=========
References
==========
> XGA/VGA changes of the evening (March 8th, 2025)

- src/video/vid_ati_mach8.c
Summary
=======
The Byte Write access of the LFB of the Mach32 was not correctly taking account of the subtraction of the address, this fixes possible graphics bugs using the LFB (Linear Aperture).
Checklist
=========
References
==========
> Mach32 LFB changes (March 8th, 2025)

- src/device.c
- src/include/86box/device.h
- src/qt/qt_deviceconfig.cpp
Summary
=======
* [Fix a few potential segfaults found in device.c](https://github.com/86Box/86Box/commit/29b6cd484cfdd5e2477b33cfc0fe40f3e710aef1)
* [Extra CONFIG_BIOS Helpers](https://github.com/86Box/86Box/commit/a7d8f4a4e1e0808fae91ecc28149d443fc6b54d4)
* [Improve empty bios file entry support](https://github.com/86Box/86Box/commit/6740b62d23e8443d7a44ebaf2e88bbdf9e3c2f1b)
* [Make config_bios_t dev's into an array](https://github.com/86Box/86Box/commit/4504348fffc8fb3885347c124228fa25d19f6c86)
* [Two missing CONFIG_END's in qt_deviceconfig.cpp](https://github.com/86Box/86Box/commit/097ea4abf2d6220b2951be2996e72e9c528d2d34)
Checklist
=========
References
==========
None
> CONFIG_BIOS related changes and some hardening

- src/qt/qt_openglrenderer.cpp
Summary
=======
Call `glViewport` with correct function pointer
Checklist
=========
References
==========
None.
> Call `glViewport` with correct function pointer

- src/qt/qt_openglrenderer.cpp
Summary
=======
Restore GLSL version code from the earlier OpenGL renderer.
Checklist
=========
References
==========
None.
> Restore older GLSL version code

- src/qt/qdarkstyle/dark/darkstyle.qss
Summary
=======
Make tooltip display on the status bar icons consistent with the ones on the toolbar.
Checklist
=========
References
==========
None.
> Qt: Make tooltip displays consistent

- src/qt/qt_openglrenderer.cpp
Summary
=======
Fix shader manager dialog crash when using multi-monitors with the OpenGL 3.x renderer.
Checklist
=========
References
==========
None.
> OpenGL 3.x: Fix shader manager dialog crash when using multi-monitors

- src/qt/qt_openglrenderer.cpp
Summary
=======
Alter GLSL `#version` statements for macOS in the default OpenGL 3.x shaders.
Checklist
=========
References
==========
None.
> Alter `#version` statements for macOS

- src/qt/qt_rendererstack.cpp
Summary
=======
Properly restore system cursor if "Show Crosshair" is enabled with Microtouch touchscreen input active.
Checklist
=========
References
==========
None.
> Microtouch: Properly restore system cursor if "Show Crosshair" is enabled

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/qt/languages/86box.pot
- src/qt/qt_main.cpp
- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.ui
Summary
=======
Add an option to inhibit multimedia keys from host on Windows.
It will be completely hidden on non-Windows platforms.
Checklist
=========
References
==========
None.
> Add option to inhibit multimedia keys from host on Windows

- src/qt/qt_openglrenderer.cpp
Summary
=======
Attempt to fix OpenGL 3.x screenshot when using default shader.
Checklist
=========
References
==========
None.
> Attempt fixing OpenGL 3.x screenshot

- src/qt/qt_openglrenderer.cpp
Summary
=======
Always use an alpha value of 1.0 for drawing scene to texture
Fixes invisible screenshots and blank screens on certain systems
Checklist
=========
References
==========
None.
> OpenGL: Always use an alpha value of 1.0 for drawing scene to texture

- src/qt/qt_glsl_parser.cpp
- src/qt/qt_openglrenderer.cpp
Summary
=======
1. Shader parameters lines are now parsed with an alternate method used for modem emulation.
2. Filter setting changes now take effect properly.
Checklist
=========
References
==========
None.
> Misc. OpenGL renderer fixes

- src/qt/qt_mainwindow.cpp
- src/sound/snd_audiopci.c
Summary
=======
1. Fixes broken translation of "About 86Box"
2. Fixes broken translation of "Receive MIDI Input" for Ensoniq AudioPCI (ES1370)
Checklist
=========
References
==========
> Fixes for broken translation

- src/video/vid_chips_69000.c
Summary
=======
All ROPs now implemented for C&T B69000 and also fixed transparency bitblts.
Several optimizations are now also implemented.
Checklist
=========
References
==========
None.
> C&T 69000: All ROPs now implemented, also fixed transparency bitblts

- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
Don't use starblit/endblit for renderer switches.
Also switch renderers properly for secondary monitors if shader settings were altered.
Checklist
=========
References
==========
None.
> Don't use startblit/endblit for renderer switches

- src/cpu/x87_ops.h
- src/cpu/x87_ops_misc.h
Summary
=======
Use `fpclassify` for FXAM instead of manual comparison.
Implement NaN detection for interpreter floating point compare on ARM64, also porting the CHKCOP hack from x86.
Checklist
=========
References
==========
None.
> Use `fpclassify` for FXAM instead of manual comparison

- src/video/vid_chips_69000.c
Summary
=======
Fix wrong refresh rate on C&T B69000.
Cycle hack remnants has also been removed.
Checklist
=========
References
==========
None.
> C&T 69000: Fix bad refresh rate

- src/video/vid_chips_69000.c
Summary
=======
Revert some optimizations for C&T B69000 that made GUI acceleration slow.
Checklist
=========
References
==========
None.
> C&T B69000: Revert optimizations that made GUI acceleration slow

- src/include/86box/machine.h
- src/machine/m_at_socket370.c
- src/machine/machine_table.c
Summary
=======
Add the Soyo SY-7SBB motherboard with the SiS (5)600 chipset and PPGA Socket 370.
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/soyo-sy-7sbb
https://theretroweb.com/motherboard/manual/m7sbb10-62fa38f2695a3949534707.pdf
> Add the Soyo SY-7SBB (SiS 600, Socket 370)

- src/86box.c
- src/cpu/cpu.c
- src/cpu/x87_ops.h
- src/cpu/x87_ops_misc.h
Summary
=======
Pre-calculate `pow` table for FXTRACT instruction as an optimization.
Checklist
=========
References
==========
None.
> Pre-calculate `pow` table for FXTRACT instruction

- src/CMakeLists.txt
- src/include/86box/86box.h
- src/include/86box/bswap.h
- src/include/86box/log.h
- src/qt/qt_platform.cpp
- src/unix/unix_serial_passthrough.c
Summary
=======
- Fixed stdarg.h-related issues
- Fixed bswap.h, moved macro position.
- Fixed pthread_setname_np, `arg` needs to be `void*`.
- Fixed baud rate stuffs. NetBSD does not have these baud rates.
Checklist
=========
References
==========
https://man.netbsd.org/paxctl.8
https://man.netbsd.org/pthread_setname_np.3
> Fix for NetBSD

- src/network/net_modem.c
Summary
=======
Sends `DONT` instead of `WONT` in response to `WILL`/`WONT` for unrecognized options. This fixes connections to GNU telnetd, which expects a proper reply to `WILL ENCRYPT`
Checklist
=========
References
==========
> net_modem: fix response to unrecognized will/wont telnet commands

- CMakeLists.txt
- src/include/86box/86box.h
- src/sound/CMakeLists.txt
- src/sound/audio4.c
Summary
=======
- audio(4) support for NetBSD/OpenBSD
- Make audio(4) default for NetBSD/OpenBSD
- Fix 86box/86box.h to include stdarg.h on OpenBSD so it compiles (Should be separated PR, but found it was needed anyways.)
Checklist
=========
References
==========
https://man.netbsd.org/audio.4
https://github.com/mackron/miniaudio/blob/master/miniaudio.h
https://man.openbsd.org/audio.4
> audio(4) support

- src/include/86box/machine.h
- src/include/86box/video.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
- src/video/vid_ega.c
- src/video/vid_jega.c
Summary
=======
Add a 386 Japanese AX laptop computer. It uses the original JEGA BIOS ROM mentioned in #5367, but the 16x16 font is not yet.
This machine has some special key shortcuts:
* LCtrl + LAlt + ESC : Enter into the CMOS Setup
* LCtrl + LAlt + [ : Switch the display out to external monitor
* LCtrl + LAlt + ] : Switch the display out to monochrome LCD
* LCtrl + LAlt + F1 : Switch the keyboard layout to US mode
* LCtrl + LAlt + F2 : Switch the keyboard layout to JA mode
* LCtrl + LAlt + [0] : Turn off the screen (ignored in emulation)
You need use the SETUP program in the MS-DOS 3.21 System Disk to change machine-specific settings.
Checklist
=========
References
==========
Advert in 1990
> Add OKI if386AX30L machine

- src/machine/machine_table.c
The real machine supports 512 KB RAM configurations and ISA video cards, however in my testing I could not use a ISA VGA card reliably, possible due to BIOS bug or a 86Box bug that makes the onboard video still active even when ISA VGA is added
Summary
=======
Change the minimum RAM to 512 KB in the IBM PS/2 Model 30-286 machine, to reflect the real machine.
Checklist
=========
References
==========
https://en.wikipedia.org/wiki/IBM_PS/2_Model_30#Model_30_286
https://www.youtube.com/watch?v=T3XIFXxIxlM (a video of this machine booting with a Cirrus Logic ISA SVGA card)
> IBM PS/2 Model 30-286 fixes

- CMakeLists.txt
- src/sound/CMakeLists.txt
- src/sound/audio4.c
- src/sound/sndio.c
Summary
=======
- Adds sndio support for OpenBSD
- Makes sndio default for OpenBSD
Checklist
=========
References
==========
https://man.openbsd.org/sndio.7
https://man.openbsd.org/sio_open.3
> Add sndio interface

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_rendererstack.hpp
Summary
=======
Always make sure emulator is not off-screen when resizing
Checklist
=========
References
==========
None.
> Always make sure emulator is not off-screen when resizing

- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.ui
Summary
=======
Add confirmation dialog checkboxes in Preferences to alter confirmation dialog behaviour when saving machine settings or closing the emulator.
Checklist
=========
References
==========
None.
> Add confirmation dialog checkboxes in Preferences

- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.ui
Summary
=======
Add the other two confirmation dialog checkboxes in Preferences
Checklist
=========
References
==========
None.
> Add the other two confirmation dialog checkboxes in Preferences

- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsnetwork.ui
Summary
=======
Move the network backend-specific settings under a separate header and only show the ones intended for the currently selected backend. Originally written by @cold-brewed for a feature branch.
Checklist
=========
References
==========
N/A
> Network settings page redesign

- src/game/gameport.c
- src/game/joystick_ch_flightstick_pro.c
- src/game/joystick_tm_fcs.c
- src/include/86box/gameport.h
Summary
=======
Add variants of the CH Flightstick Pro and Thrustmaster Flight Control System with rudder pedals (CH Pedals in rudder mode and Thrustmaster Rudder Control System respectively) connected between the joystick and the machine.
Checklist
=========
References
==========
N/A
> Add variants of the CH Flightstick Pro and Thrustmaster FCS with rudder pedals attached

- src/machine/machine_table.c
this will be solved the ps2 mouse  not appear on the setting
Summary
=======
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/mitac-trigon-pwa-pl4600c
https://theretroweb.com/motherboards/s/dell-dimension-xps-p60
> Replace MACHINE_PCI with MACHINE_PS2_PCI for pl4600c and  Dell Dimension XPS P60 machine_table.c

- src/video/vid_ps55da2.c
Summary
=======
Changes:
* Fix an issue that the screen is resized repeatedly when booting OS/2. #5239
* Fix screen size calculation in recalctimings func.
* Set the line position of underscore attribute by CRTC's register in PS/55 text mode.
* Remove unused variables, change functions' declaration scope, formatting
Checklist
=========
References
==========
The video BIOS switches the screen resolution to 1040 x 754 in video mode 3. Each line has 29 pixels in height. so you'll see 26 lines, and the last line is always blank. Actually, this occurs on real hardware too.
> Fix bugs related to PS/55 emulation

- src/qt/qt_main.cpp
- src/utils/ini.c
Summary
=======
Set LC_NUMERIC to "C" in program startup to fix GLSL parameter parsing issues.
Checklist
=========
References
==========
None.
> Set LC_NUMERIC to "C" in program startup to fix GLSL parameter parsing

- src/qt/qt_styleoverride.cpp
- src/qt/qt_styleoverride.hpp
Summary
=======
Overrides Qt's default implementation of disabled icon grayscaling with one that replicates our existing icons aesthetic
Checklist
=========
References
==========
> qt: implement authentic icon grayscaling

- src/scsi/scsi_ncr5380.c
- src/scsi/scsi_ncr53c400.c
- src/scsi/scsi_t128.c
Summary
=======
1. Avoid audio stops when they don't need to be.
2. And improved the MMIO-based NCR 53c400 timings to be similar to the port I/O-based one (T130B).
3. Minor timing fixes to the T128/PAS as well (especially for the hdd, when entering Windows 1.x using a SCSI HDD).
Checklist
=========
References
==========
> More fixes for 5380-based SCSI chips of the day (March 29th, 2025)

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Implemented the FIFO test data to pass some tests of the Mach8 POST ROM and tests (not complete yet).
2. Overhauled the mode switches again, but this time with way less hacks and more on manual instructions.
3. Use a function pointer to determine if the Mach8 type used is a VGA combo or add-on.
4. Mach32 mode tests are no longer incorrectly green (was caused by improper pixtrans parts).
5. Implemented overscan color to the Mach32 as well as the CRT offset.
6. And fixed a PCI LFB GPF issue with the Mach32 2.3 drivers on Win3.1x.
7. Implemented memory boundary for both the Mach32 SVGA and its accelerator.
8. Added undocumented ports used by the FIFO (such as ports 0x8AEE and 0xEAEE).
9. Plus resetting the device right a la s3.
10. Temporarily switched the bus type of the …
> Vast overhaul for the Mach8/32/8514/A (March 29th, 2025)

- src/video/vid_s3.c
- src/video/vid_svga.c
Summary
=======
SVGA related:
If CRTC1/HDISP is odd (if bit 0 is set), then make it even accordingly, else leave it as is. Should fix some display skews.
S3 related:
Remove old code references (can still be accessed through history if one needs it).
8514/A compatible related:
Proper use of the htotal and hdisp timings.
Checklist
=========
References
==========
> More display changes.

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
1. Use proper identification to what chips use what.
2. Apply some mode switch fixes to the ATI 8514/A Ultra and make 1024x768 87Hz interlaced the default mode if htotal is 0 and on ati8514_init.
3. Add the undocumented ports to the ATI 8514/A Ultra add-on as well.
Checklist
=========
References
==========
> More fixes to the 8514/A compatible side.

- src/qt/qt_hardwarerenderer.cpp
- src/qt/qt_openglrenderer.cpp
- src/qt/qt_renderercommon.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_vulkanrenderer.cpp
- src/qt/qt_vulkanwindowrenderer.cpp
Summary
=======
Qt: Fix HiDPI scaling on non-software renderers.
Checklist
=========
References
==========
None.
> Qt: Fix HiDPI scaling on non-software renderers

- src/include/86box/vid_8514a.h
- src/include/86box/vid_ati_mach8.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. The DX/DY coordinates for BitBLT are now signed again, fixes 8514/A cursor issues.
2. Made the busy/data available processor statuses more like the ATI one for more stability and no stalls, fixes Windows 3.x and IBM OS/2 1.x (possibly later ones too) that use the built-in 8514/A driver.
3. Made the mode switching clearer (through a note) regarding the shadow sets, this should make every program happy, I hope.
4. In the Mach32 series only, a first load of the CRT sets also initializes the GE offsets if the corresponding bit is set, fixes Mach8/32 mode tests in their eeprom and demoai with hdiload from ATI/IBM.
Checklist
=========
References
==========
> Major changes on the 8514/A side again (March 30th, 2025)

- src/video/vid_ati_mach64.c
Summary
=======
The LFB can now be enabled properly on the ISA/VLB variants of the Mach64GX.
Checklist
=========
References
==========
> Mach64 ISA/VLB LFB update of the day (March 30th, 2025)

- src/qt/qt_hardwarerenderer.cpp
Summary
=======
Hardware Renderer: Make sure to account for devicePixelRatio when setting up the matrix
Checklist
=========
References
==========
None.
> Hardware Renderer: Make sure to account for devicePixelRatio when setting up the matrix

- src/floppy/fdc.c
- src/qt/qt_machinestatus.cpp
Summary
=======
Make sure that floppy icons and options do not appear if there's no floppy controller available at all (either as part of the machine or as an external card).
Checklist
=========
References
==========
None.
> Make sure that floppy icons and options do not appear if there's no floppy controller available

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Aliases are aliases, period.
2. Actually make the ports using bit 15 of their range use the command FIFO.
3. Improved the special ATI command 0xc2b5 in the IBM bitblt side, fixes cursor issues in 24bpp mode using OS/2.
4. When the FIFO is empty, clear the busy and available flags.
5. Also reapply a workaround for 24bpp foreground color patterns in ATI command Scan To X command, fixes patterns in OS/2 and possibly elsewhere.
6. Accelerated HiColor mode, in the IBM passthrough mode, should always be enabled, for now, as well as the Extended ATI Mach32 8bpp mode when prompted, fixes OS/2 booting into the GUI in HiColor mode.
7. Dummy data path configuration values on direct linedraw should not trigger a pixtrans read when it's not needed, fixes possible hang ups in IBM/ATI …
> 8514/A compatible changes of the day (April 2nd, 2025)

- src/include/86box/scsi_device.h
- src/include/86box/scsi_t128.h
- src/scsi/scsi_t128.c
- src/sound/snd_pas16.c
Summary
=======
1. The PAS SCSI controller driver mamv1.sys dislikes having bits 0-6 set when a transfer has completed, take account from this, fixes mamv1.sys incomplete CD transfers (bits 0-6 get re-enabled when the transfer is ongoing).
2. I now understand why the T128 doesn't have a block count register, it does the block count manually from the SCSI layer directly, this fixes Pseudo-DMA transfers when using, e.g.: CD transfers using a sector size of 2340 bytes.
Checklist
=========
References
==========
> Trantor SCSI changes of the day (April 2nd, 2025)

- src/device/bugger.c
Summary
=======
A couple of tweaks to the ISABugger display:
- Use a monospace font so that the character positions don't shift around when the display changes.
- Light up the LED bits in the appropriate colour when they are on.
This is what it looks like:
Checklist
=========
References
==========
> ISABugger display improvement

- src/video/vid_ps55da2.c
Summary
=======
* Add a character drawing function to support for the DSPXDA2 driver of IBM DOS/V Extension.
* Implement CRTC regs: start address, end address, line compare to support text scrolling with DSPXDA2 driver.
* Enable updating CRTC registers when the video output is disabled.
Checklist
=========
References
==========
The IBM DOS/V Exntension was a commercial add-on software for DOS J5.0/V and later. The CD-ROM version of PC DOS J7.0/V bundled it.
https://en.wikipedia.org/wiki/DOS/V
>IBM DOS/V Extension extends DOS/V drivers to set up a variety of text modes for certain video adapters. The High-quality Text Mode is the default 80 columns by 25 rows with 12×24 pixels large characters. The High-density Text Mode (Variable Text; V-Text) offers large text modes with various font …
> PS/55: Add support for V-Text driver of IBM DOS/V Extension

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
Summary
=======
Make Qt shortcuts actually work in fullscreen
Also removes hacks related to fullscreen.
Checklist
=========
References
==========
None.
> Make Qt shortcuts actually work in fullscreen

- src/video/vid_bochs_vbe.c
Summary
=======
Bochs SVGA: Buffer window switching now works properly.
Fixes Duke Nukem 3D display being glitchy.
Checklist
=========
References
==========
None.
> Bochs SVGA: Buffer window switching now works properly

- src/qt/qt_renderercommon.cpp
- src/qt/qt_renderercommon.hpp
- src/qt/qt_rendererstack.cpp
Summary
=======
When using the Microtouch, if the scaling modes are active, the touch points will now properly scale to those instead of always assuming the default strecth-to-entire-screen mode is active.
Checklist
=========
References
==========
None.
> Microtouch touch points now work properly in fullscreen/maximized with scaling modes

- src/sound/snd_pas16.c
Summary
=======
Actually make the DMA transfer speed normal in when in 16-bit stereo mode with System Configuration 1 bit 1 (Master Clock) cleared. Fixes audio being too quick with said configuration.
Checklist
=========
References
==========
> PAS16/Plus change of the day (April 15th, 2025)

- src/include/86box/machine.h
- src/machine/m_at.c
- src/machine/machine_table.c
Summary
=======
A chipset-less 286 AT machine, almost identical to the IBM AT, but supports 1 MB onboard RAM instead of just 512 KB
BIOS can be configured using the utilities from PB_2330a_diag.IMA found in MS-DOS 3.30 Packard Bell OEM from WinWorldPC
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/packard-bell-pb286-is-vt286-version-2
> Add Packard Bell PB286

- src/include/86box/video.h
- src/video/vid_table.c
- src/video/vid_voodoo_banshee.c
Summary
=======
A Voodoo Banshee variant, the Quantum3D Raven (PCI only, AGP seemed unstable and froze with Direct3D games/programs). It's of moderate interest because one Win9x game is vendor-locked to it, San Francisco Rush The Rock: Alcatraz Edition, and also seemingly supported 3D shutter glasses (which is not emulated here).
Requires the corresponding pull request: https://github.com/86Box/roms/pull/301.
Checklist
=========
References
==========
> Add basic support for the Quantum3D Raven.

- src/qt/qt_openglrenderer.cpp
Summary
=======
Disable OpenGL 3.x logs from the renderer.
Checklist
=========
References
==========
None.
> Disable OpenGL 3.x logs

- src/qt/win_dynld.c
Summary
=======
We usually specify `UNICODE`, but since `dynld_module` requires a `const char *`, let's use the ANSI `LoadLibraryA` function specifically. This way we avoid a type mismatch error.
Checklist
=========
References
==========
> win_dynld: use LoadLibraryA specifically

- src/device/kbc_at.c
Summary
=======
Title says at all.
Checklist
=========
References
==========
Referenced by this [commit](https://github.com/86Box/86Box/commit/fd2214f54471c02bea2c99deda54ac138f5d4f43), but because the "internal_name" is a duplicate of Acer PS/2 PCI KBC, I corrected them for Phoenix PS/2 PCI KBC
> Fix "internal_name" for Phoenix PS/2 PCI KBC

- .github/workflows/cmake_macos.yml
Summary
=======
Not only is this workaround no longer needed for packaging, it breaks the workflow completely due to CMake 4.0.
Checklist
=========
References
==========
N/A
> workflows: Don't rebuild libsndfile on macOS

- src/cpu/cpu_table.c
To distinguish from Cyrix-heritage Joshua CPUs. 
Summary
=======
added "(Samuel)" to the name Cyrix III.
Checklist
=========
References
==========
- #5451
> VIA Cyrix III (Samuel) - add codename

- src/qt/qt_keybind.cpp
- src/qt/qt_keybind.hpp
- src/qt/qt_settingsinput.cpp
Summary
=======
Keybind UI fixes
1. Don't clear the description text cell if selected; clear the actual keybind text instead.
2. Header texts are now correct.
3. Make the keybind dialog model and usable with dark mode.
4. Copyright text fixes.
Checklist
=========
References
==========
None.
> Keybind UI fixes

- src/qt/qt_platform.cpp
Summary
=======
Fixes the OOB write caused by `b[s] = 0;` in `CharPointer::operator=`. Since arrays in C are zero-indexed, the last index in an array of size 1 would be 0, i.e. size - 1.
Checklist
=========
References
==========
> Fixed stack overflow in CharPointer::operator=

- src/qt/qt_machinestatus.cpp
Summary
=======
HDD tooltips now list paths of disk images, CHS and their sizes.
Checklist
=========
References
==========
None.
> HDD tooltips now list paths of disk images, CHS and their sizes

- src/qt/qt_machinestatus.cpp
Summary
=======
Make `MB` in HDD tooltips translated
Checklist
=========
References
==========
None.
> Make `MB` in HDD tooltips translated

- src/config.c
- src/qt/qt_settingsinput.cpp
- src/qt/qt_settingsinput.hpp
Summary
=======
Fixes cleared keybindings being reset to default on startup by saving them as "none" instead of empty strings.
Also fixes `QMetaObject::connectSlotsByName: No matching signal for...` warnings on run time.
Checklist
=========
References
==========
N/A
> Fix cleared keybindings not being reloaded

- cmake/intel-linux-x86_64.cmake
- cmake/llvm-linux-x86_64.cmake
Summary
=======
Added cmake files for x86_64 linux llvm clang/clang++ and intel icx/icpx compilers.
Build successfully with clang 14.0 and Intel oneAPI 2025.0 on Linux Mint LMDE 6.
Checklist
=========
> Add cmake files for linux clang and intel compilers

- src/qt/qt_deviceconfig.hpp
- src/qt/qt_settingsdisplay.cpp
- src/qt/qt_settingsinput.cpp
- src/qt/qt_settingsmachine.cpp
- src/qt/qt_settingsnetwork.cpp
- src/qt/qt_settingsotherperipherals.cpp
- src/qt/qt_settingsports.cpp
- src/qt/qt_settingssound.cpp
- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
Fixes (somehow) controls being non-interactable when no parent dialog is passed and 86Box is running in settings-only mode (affected configurations of the LBA enhancer, unit tester and the NetWare key card).
Checklist
=========
References
==========
N/A
> qt: For device config dialogs, default to the settings dialog as the parent

- src/video/vid_s3.c
Summary
=======
1. See above, as best as possible, but manuals would be helpful.
2. Reverted the ramdac of the 924 to the sierra one because of a bug that triggers 24bpp mode when it shouldn't.
Checklist
=========
References
==========
> Vast overhaul to the 15bpp/16bpp accelerated mode of the 911/924.

- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
Summary
=======
1. Do not stall the guest when the passthrough mode is on, fixes hang ups in Windows 3.1 using the 2.3 drivers.
2. In the pitch register, make sure the passthrough goes on when needed only on the ATI Mach32, not 8, fixes mode on/off in text mode when needed.
3. Cosmetic changes and logs.
Checklist
=========
References
==========
> Some more changes to the Mach8/32/8514/A side (April 29th, 2025)

- src/video/vid_ega.c
- src/video/vid_svga.c
Summary
=======
This fixes a bug in the EGA and (S)VGA code where SR04.2 odd/even mode was computing the mask incorrectly.
Chain4 mode may also be broken but I'm holding off fixing that as it likely varies across the many different SVGA chipsets we emulate.
Checklist
=========
References
==========
Miscellaneous hardware, namely my AMD Stoney laptop and my S3 Trio64V2.
I did cross-reference with the Intel GPU 2023 docs which tends to be more accurate than the IBM docs, but it turns out that it implies that the write mask is ignored in odd/even mode (the SR04 bit 2 part) where it is clearly not ignored on a lot of hardware (plus how would 640x350x2bpp mono mode work without that being the case, anyway?).
Test program for comparison which I originally wrote here: …
> Fix EGA/VGA/SVGA odd-even handling of write mask

- src/video/vid_bochs_vbe.c
Summary
=======
Bochs VBE: Update for 0.9c ROM
(ROM update itself fixes Duke Nukem 3D's palette fadeouts.)
Checklist
=========
References
==========
None.
> Bochs VBE: Update for 0.9c ROM

- src/video/vid_ati_mach8.c
Summary
=======
1. The Mach8 doesn't have separate graphics pitches a la Mach32 (68800-6 and up), fixes the rendering in some drivers for Windows.
2. Special case for the add-on Mach8 for the mode switching (resolution only).
Checklist
=========
References
==========
> Late night fixes for the Mach8 (May 5th, 2025)

- src/machine/machine_table.c
Summary
=======
I find the newly-added Delhi III has an onboard video chip: ATI 3D Rage IIc, and the emulated machine cannot boot with an AGP card (several beeps, indicating video issue). And I find a photo which indicates NEC Mate NX MA23D has an OAK OTI-610 audio chip. Perhaps it is the same on MA30D.
Checklist
=========
References
==========
[MA23D on eBay](https://www.ebay.com/itm/116193982911)
https://theretroweb.com/motherboards/s/trigem-delhi-iii
https://nicmania.sakura.ne.jp/etc/img/06_82558b.jpg
> No AGP slot on Delhi III and internal device note for 2 machines 

- src/include/86box/video.h
- src/video/vid_s3.c
- src/video/vid_table.c
Summary
=======
There is no ISA-specific S3 86c805 video card on 86Box until now. This adds ISA16/86c805-based ELSA Winner 1000 to the video card list.
Note: ATT491 RAMDAC is being used for this video card as ATT409 RAMDAC is not added yet.
Checklist
=========
References
==========
https://theretroweb.com/expansioncards/s/elsa-winner-1000isa
> Add ISA 86c805 (ELSA Winner 1000)

- src/sound/saasound/SAAImpl.cpp
- src/sound/saasound/SAAImpl.h
Summary
=======
SAASound filter variables is now properly per-class, eliminating some glitches.
Checklist
=========
References
==========
None.
> SAASound filter fixes

- src/include/86box/plat.h
- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/qt/qt_keybind.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_platform.cpp
- src/qt/qt_settingsinput.cpp
Summary
=======
Keybinds are now both saved and read in portable form and only converted to native one for display purposes, fixing them not being read correctly when certain languages are set.
Also get rid of `qPrintable()` due to it using the system 8-bit codepage instead of UTF-8, and some unnecessary QString ↔ C string conversions.
Patch originally written by @Cacodemon345.
Checklist
=========
References
==========
N/A
> Fix keybinds being saved in native/localized form

- src/qt/qt_mainwindow.cpp
Summary
=======
Add missing tooltips for keyboard lock icons.
Checklist
=========
References
==========
None.
> Add missing tooltips for keyboard lock icons

- src/machine/m_at_socket5.c
Summary
=======
1. The 430NX does support PCI IRQ steering, fix it accordingly.
2. Reorder the number of the slots.
3. Add the SIO ZB device to said machine as it must have one.
4. Remove the onboard 810 SCSI controller.
Checklist
=========
References
==========
> P54NP4 fixes of the evening (May 7th, 2025)

- src/video/vid_ati_mach64.c
Summary
=======
See above.
Checklist
=========
References
==========
> Fix mono pattern position in the Mach64 cards using 24bpp mode (May 7th, 2025)

- src/sound/snd_pas16.c
Summary
=======
See above, fixes the non-audio mamv1.sys SCSI controller driver using CD/HDD reads/writes.
Checklist
=========
References
==========
> Actually fix the timing of the PAS16/Plus SCSI side (May 8th, 2025)

- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_rendererstack.hpp
Summary
=======
Honour `--nohook` on X11 as well.
Checklist
=========
References
==========
None.
> Honour `--nohook` on X11 as well

- src/codegen_new/codegen_backend_x86-64_ops.c
Summary
=======
x64 NDR: Avoid pushes/pops for `host_x86_MOV32_REG_ABS`
Checklist
=========
References
==========
None.
> x64 NDR: Avoid pushes/pops for `host_x86_MOV32_REG_ABS`

- src/scsi/scsi_t128.c
Summary
=======
1. If the timer result is less than 10.0 microseconds, then adjust it to 10.0. Fixes some timing read issues with the T128 (and possibly PAS SCSI).
2. Remove unused variables.
Checklist
=========
References
==========
> Quick timer fix on the T128/PAS SCSI (May 10th, 2025)

- src/qt/qt_mainwindow.cpp
Summary
=======
Revert X11-related keyboard grabbing changes (except for `--nohook` ones).
Fixes moving with titlebar on GNOME and Cinnamon.
Checklist
=========
References
==========
None.
> Revert X11-related keyboard grabbing changes (except for `--nohook` ones)

- src/include/86box/machine.h
- src/machine/m_at_286_386sx.c
- src/machine/machine_table.c
Summary
=======
Add the Phoenix BIOS variant for the Micronics 09-00021, in addition to the existing Tandon BIOS variant, since the Phoenix BIOS is much less limited.
Checklist
=========
References
==========
[_Provide links to datasheets or other documentation that helped you implement this pull request._
](https://theretroweb.com/motherboards/s/micronics-386-i-cache-09-00010-xx-09-00021-#bios)
> Add the Phoenix BIOS variant of the Micronics 09-00021 386DX machine

- src/machine/machine_table.c
Summary
=======
This pull request moves "&tgui9440_onboard_pci_device" from .device to .vid_device, fixes a crash.
Checklist
=========
References
==========
Nothing.
> SBC-490 .vid_device assorted fixes

- src/video/vid_tgui9440.c
Summary
=======
1. DirectDraw memory address fixes of the day (removing the bit 6 of crtc 2a side of the if in recalctimings).
2. In spite of no documentration or NDA manuals, get data from the pattern registers as best as possible in 32bpp mode, this fixes patterns in 32bpp mode using various stuff.
Checklist
=========
References
==========
> Trident pattern and memory access changes (May 19th, 2025)

- src/video/vid_ati_mach8.c
Summary
=======
1. Report the ATI 28800 of the Graphics Ultra as 28800-6.
2. Access the upper word properly on vdisp.
3. Make sure there's enough vsyncstart/vtotal space for a full vertical display.
Checklist
=========
References
==========
> Small ATI Mach8 changes (May 19th, 2025)

- src/video/vid_ati_mach8.c
Summary
=======
Make the previously Mach8 add-on only mode changes also available to the Graphics Ultra, should fix incorrect resolutions after switching from fullscreen DOS prompt to windowed and viceversa under Win98 (and SE).
Checklist
=========
References
==========
> Mach8 mode changes of the day (May 20th, 2025)

- src/device/kbc_at.c
Summary
=======
Fix a small typo with the jumper fix PR I created that causes some checks to fail
Checklist
=========
> Fix a small typo with the password disable jumper fix that causes some checks to fail

- src/video/vid_s3.c
Summary
=======
This fixes wrong colors in certain instances of Windows 95 builds' 911/924 drivers.
Checklist
=========
References
==========
> S3 911/924 high color: check if rd_mask is not 0 (May 21st, 2025)

- src/machine/m_xt_olivetti.c
I initially only updated the BIOS revision numbers, but should have changed the full correct filenames, oops
Summary
=======
fixes the wrong filename used for the updated Olivetti M240 2.12 ROM set
> Fix wrong filenames used for Olivetti M240 BIOS

- src/network/net_pcnet.c
Summary
=======
Rename "AMD PCnet-VL" to "AMD PCnet-32", as per the datasheet.
Checklist
=========
References
==========
https://theretroweb.com/chip/documentation/am79c965-66c24a7e6969d347126123.pdf
> Rename "AMD PCnet-VL" to "AMD PCnet-32"

- src/scsi/scsi_ncr53c400.c
Summary
=======
Upon an initial POST, the initital status/control 53c400 port should be 0, fixes various versions of the T130B driver on Windows 95 builds.
Checklist
=========
References
==========
> Small important change for the 53c400 (May 30th, 2025)

- src/video/vid_chips_69000.c
Summary
=======
Divide by 3 the destination address on color patterns to make sure the pattern position is perfectly aligned. Fixes color patterns in Win3.1x and Win9x (and possibly NT-based and other stuff).
Checklist
=========
References
==========
> C&T 69000 changes of the day (June 1st, 2025)

- src/sound/snd_ad1848.c
Summary
=======
This fixes the the looping wave plays in Win95 using GUS MAX and possibly on WSS derived products.
Checklist
=========
References
==========
[AD1848K manual](https://theretroweb.com/chip/documentation/ad1848k-656257163ec73854266197.pdf)
[CS4231A manual](https://www.cebix.net/downloads/bebox/cs4231a.pdf)
> Small IRQ correction on ad1848/cs4231 (June 5th, 2025)

- src/machine/machine_table.c
Summary
=======
Because the Olivetti M24 was very widely known under the AT&T PC 6300 name, while the M240 was known as AT&T PC 6300 WGS, I changed the machine table to reflect these alternative names due to the big popularity of the AT&T counterparts
Checklist
=========
References
==========
> Rename the Olivetti M24 and M240 to add the names of their AT&T counterparts

- src/qt/qt_settingsdisplay.cpp
Summary
=======
This brings it in line with the other Voodoo 3/Banshee cards that don't permit Voodoo 1 or two at the same time without the ini tweak (as per #4327). 
Checklist
=========
References
==========
> Add the Quantum3D Raven to the list of cards recognized as Voodoos/Banshees.

- src/machine/m_at.c
- src/machine/m_xt.c
Summary
=======
* [Make XT82 diag's and debug roms work](https://github.com/86Box/86Box/commit/c135786d0c198d9e4e72867053eab88be675a13e)
* [Make XT86 diag's and debug roms work](https://github.com/86Box/86Box/commit/f542b5a8af2e79d61cbf4bb73889723838d44df0)
* [Update Ruuds diagnostic rom to 5.4](https://github.com/86Box/86Box/commit/9f37d0b1d163e08a6cf97380e43d44e82d70c6ef)
* [Add Supersoft Diagnostics to IBM 5170](https://github.com/86Box/86Box/commit/301cd7be7a0a3face438b15b1138479ab9c9918f)
Checklist
=========
References
==========
None
> Diagnostics ROMs for 5150-5170

- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/machine_table.c
Summary
=======
Make the internal video for 3302, ActionPC and ActionTower configurable.
**NOTE**: My commit name is wrong (it supposed to be Jun 10 but I mistyped as Jun 30). I apologize for that.
Checklist
=========
References
==========
> Assorted device fixes (Jun 10)

- src/video/vid_cga_toshiba_t3100e.c
Summary
=======
Fix a regression due to incorrect porting job to the new CGA code in Toshiba T3100E
Checklist
=========
References
==========
> Fix Toshiba T3100E CGA 320*200 mode

- src/include/86box/m_pcjr.h
- src/include/86box/m_tandy.h
- src/include/86box/vid_ega.h
- src/include/86box/vid_hercules.h
- src/include/86box/vid_mda.h
- src/machine/m_amstrad.c
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_cga.c
- src/video/vid_cga_toshiba_t3100e.c
- src/video/vid_ega.c
- src/video/vid_ega_render.c
- src/video/vid_hercules.c
- src/video/vid_hercules_incolor.c
- src/video/vid_hercules_plus.c
- src/video/vid_mda.c
- src/video/vid_pcjr.c
- src/video/vid_tandy.c
- src/video/vid_wy700.c
Summary
=======
General:
Rename stat -> status
Rename mdacols -> mda_attr_to_color_table
Rename cgacols -> cga_attr_to_color_table
MDA:
Preparation for adding colour MDA support:
Add mda_crtc_registers enum for MDA CRT Control registers in MDA code
Add mda_registers enum for MDA registers and use it in MDA code
Add mda_mode_flags enum for MDA mode bits and use it in MDA CODE
Improve mda_in & mda_out decode logic. If the address is not 0x3BA (MDA_REGISTER_CRT_STATUS) we can use addr & 1 to see if we need to return the current crtc register number. This may be slightly slower but MDA is not hard to emulate
Rename "ctrl" to "mode" because, although it's officially called control, it behaves like the CGA mode register and this is a more accurate name for what it actually does.
CGA: …
> Video Refactor Part 4: MDA, more renames

- src/include/86box/vid_ati_mach8.h
- src/video/vid_ati_mach8.c
Summary
=======
If the height is 1, then make sure Cur_X is used for the destination X start, otherwise, Dest_X_Start is the destination X start for the blit. This fixes some blit errors on Win2000's mach8/32 drivers.
Checklist
=========
References
==========
[Mach32 manual, blit section](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
> Fix mach8/32 win2000 blit regression (June 15th, 2025)

- src/video/vid_ati68860_ramdac.c
- src/video/vid_ati_mach64.c
Summary
=======
1. Make sure the horizontal sync part is actually loaded.
2. The Mach64 *T parts have an integrated RAMDAC as opposed to the non-*T parts which have a separate RAMDAC (like the ATI68860), so modify accordingly, this also fixes intermittent black cursors in Win95 OSR2.5 using updated Mach64 drivers in the VT2.
3. Make sure the type of the Mach64 is properly assigned as such (in info->local).
Checklist
=========
References
==========
[Mach64 Pre-VT manual](http://www.bitsavers.org/components/ati/PRG888GX0-01_ATI_Mach64_Accelerator_Programmers_Guide_Technical_Reference_Manual_1994.pdf)
[Mach64 VT manual](http://bitsavers.informatik.uni-stuttgart.de/components/ati/RRG-G02700_mach64_Register_Reference_Guide_ATI-264VT_and_3D_RAGE_1996.pdf)
> Some cleanup and work on the Mach64 side (June 16th, 2025)

- src/video/vid_voodoo.c
Summary
=======
When 3D is enabled on the behalf of the Voodoo, make sure the override is reflected in recalctimings as well so that it can use the old calculation way of the overscan. Fixes more blackness in some areas of some games (and possibly more).
Checklist
=========
References
==========
> Voodoo 3D change of the day (June 16th, 2025)

- src/include/86box/vid_mda.h
- src/include/86box/video.h
- src/video/vid_mda.c
Summary
=======
This enhances MDA to add MDA colour support:
1: Add "CGAPAL_CGA_BASE" define to video.h so cga palette using code can determine where the real cga palette starts
2: Add RGBI monitor type to MDA configuration
3: Add mda->monitor_type to store the selected monitor type (cgapalette is shifted left by 1)
4: When RGBI monitor type is selected, implement the unused rev0 MDA colour text support including forced underline for certain colours
5: Various comments and variable renames during mda, move from int to int32_t
Checklist
=========
> Video Refactor Part 5(gum): MDA Colour support 

- src/video/vid_s3_virge.c
Summary
=======
Fix an issue where the S3 ViRGE chip type and PCI registers are not correctly assigned when using an on-board S3 ViRGE (325), fixes the Intel AP440FX onboard ViRGE (325) showing up as a ViRGE/DX (375). Also fix some other usages of info->local that did not take the onboard flag into account.
Checklist
=========
References
==========
> Ensure the S3 ViRGE type is correctly assigned including when using an onboard ViRGE

- src/include/86box/vid_ati_mach8.h
- src/include/86box/vid_svga.h
- src/video/ramdac/vid_ramdac_ati68860.c
- src/video/ramdac/vid_ramdac_ati68875.c
- src/video/vid_ati_mach64.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
1. Convert the ramdac types into an enumerator.
2. Make sure the 8514/A compatible ramdacs are, if in VGA mode, using VGA compatible ports and/or, in 8514/A mode, the 8514/A ports when needed, fixes color issues in 1280x1024 resolutions on NT 3.1 and various stuff using the Mach32.
3. Add pitch initialization on reset, fixes 8514/A display drivers on various stuff on Mach8/Mach32 cards.
Checklist
=========
References
==========
> Video: more changes and fixes of the day (June 26th, 2025)

- src/include/86box/vid_8514a.h
- src/video/vid_8514a.c
- src/video/vid_ati_mach8.c
- src/video/vid_svga.c
Summary
=======
The mode switching phase now takes account of the display enable/reset bits of port 0x22e8 (bits 5-6). Fixes Solaris mode switching and keeps everything else happy (I hope).
Checklist
=========
References
==========
[Mach32 manual, page 39 of the PDF](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
> More fixes to the mode switching of the ATI/IBM 8514/A compatibles (June 28th, 2025)

- src/qt/qt_settingsstoragecontrollers.cpp
Summary
=======
Should fix unavailable configuration boxes in the 86box settings GUI.
Checklist
=========
References
==========
> Actually use the configuration of the FDC cards when needed.

- src/video/vid_ati_mach8.c
Summary
=======
Now it correctly detects what's selected as the ramdac.
Checklist
=========
References
==========
[Mach32 manual, page 301 of the PDF](https://fenarinarsa.com/misc/atari-forum/reg-688000-15_programmers_guide_to_the_mach32_registers.pdf)
> Fix swapped value of the ramdacs used by the Mach32 PCI.

- src/machine/machine_table.c
Summary
=======
Correct RAM memory step from `8192` to `4096`
Checklist
=========
References
==========
According to D943's [technical manual](https://theretroweb.com/motherboard/manual/fts-systemboardd943technicalmanualen-10-1083435.pdf-5f6735e51714c464590416.pdf), it supports 4mb memory modules.
> Siemens-Nixdorf D943: Correct memory step

- src/game/gameport.c
- src/game/joystick_standard.c
- src/include/86box/gameport.h
- src/qt/win_joystick_rawinput.c
Summary
=======
Fix a memory leak in windows rawinput joystick, add several generic joystick types
Checklist
=========
References
==========
None
> Fix a memory leak in windows rawinput joystick, add several generic joystick types

- src/qt/qt_settingsnetwork.cpp
Summary
=======
Fix warning in qt_settingsnetwork.cpp
Checklist
=========
References
==========
None
> Fix warning in qt_settingsnetwork.cpp

- src/video/vid_ati_mach8.c
Summary
=======
Which fixes Win3.1's Mach32 2.3 4bpp driver stalling.
Checklist
=========
References
==========
> Fix one edge case of gpstatus stall.

- src/video/vid_xga.c
Summary
=======
Which fix OS/2's 4bpp rendering in a similar way to Win3.1.
Checklist
=========
References
==========
> Some more XGA fixes

- src/video/vid_svga_render.c
Summary
=======
SVGA: Don't draw blank screens out of bounds.
Checklist
=========
* [X} Closes #5758
References
==========
None.
> SVGA: Don't draw blank screens out of bounds

- src/sound/snd_gus.c
- src/sound/snd_ssi2001.c
Summary
=======
[read/writegus -> gus_read/write](https://github.com/86Box/86Box/commit/c5d083bd28b4f6d9cf219072210cd0a6d51c5424)
[Some corrections in snd_ssi2001.c](https://github.com/86Box/86Box/commit/d79dd904eabd1614076af5f433e3e8e156c31f12)
* Gameport disabled by default on ssi2001 and entertainer
Checklist
=========
References
==========
None
> A few corrections and cleanups to the code

- src/qt/CMakeLists.txt
- src/qt/qt_main.cpp
- src/unix/gamemode/gamemode_client.h
Summary
=======
Add support for Feral Interactive's gamemode on Linux, using the `libgamemodeauto` library.
Checklist
=========
References
==========
None.
> Add support for Feral Interactive's gamemode on Linux

- src/86box.c
Summary
=========
Add fractional part to percentage message when no mouse is emulated
Checklist
=========
References
==========
None.
> Add fractional part to percentage message when no mouse is emulated

- src/include/86box/vid_xga.h
- src/video/vid_xga.c
Summary
=======
1. XGADemo now displays the correct colors through implementation of the palette sequence order in bit 2 of reg66 (Palette Sequence) of the XGA  ports and no longer hangs DOS when displaying the demo per interrupt r/w ports implementation.
2. And some more checks for more patterns needed by some software.
Checklist
=========
References
==========
[XGA manual](https://dn790007.ca.archive.org/0/items/bitsavers_ibmpccardseferenceManualMay92_1756350/IBM_VGA_XGA_Technical_Reference_Manual_May92.pdf)
> XGA changes of the day (July 12th, 2025)

- src/device/novell_cardkey.c
Summary
=======
The registers previously were mixed up which made the device not work, this PR fixes that.
Checklist
=========
References
==========
https://www.os2museum.com/wp/unlocking-netware-2-0a/
> Fix Netware key card registers

- src/sound/snd_sb_dsp.c
Summary
=======
Fix High Speed autoinit DMA on SB16
Checklist
=========
References
==========
None
> Fix High Speed autoinit DMA on SB16

- src/video/vid_voodoo_reg.c
Summary
=======
Voodoo: Recalculate texture parameters on `textureMode` writes
Fixes corrupted textures on Screamer Rally.
Checklist
=========
References
==========
None.
> Voodoo: Recalculate texture parameters on `textureMode` writes

- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_socket4.c
- src/machine/m_at_socket5.c
- src/machine/m_at_socket7_3v.c
Summary
=======
This commit fixes the broken BIOS version switchers on the Acer V12P, Siemens-Nixdorf D842 and D943 machines. It also improves almost all of the other switchers for consistency, while defaulting to the latest official BIOS version on all machines.
Checklist
=========
References
==========
N/A
> BIOS version switcher fixes and improvements on available machines

- src/include/86box/machine.h
- src/machine/m_at_socket7.c
- src/machine/machine_table.c
Summary
=======
This PR adds support for the Biostar M5ATA motherboard, a Socket 7 board.
Checklist
=========
References
==========
I've dumped the ROM from my own board.
The manual can be found at [The Retro Web's page for Biostar M5ATA](https://theretroweb.com/motherboards/s/biostar-m5ata#docs).
The PCI IRQ steering table was obtained using PCIREG and refined based on feedback obtained on the Discord server.
> Add Biostar M5ATA motherboard

- src/cdrom/cdrom_image.c
Summary
=======
This is a fix for #5829 by replacing dev->ops->get_last_block (which was segfaulting for an unknown reason) with image_get_last_block, existing code that should afaik do the same thing.
It is confirmed to fix the crash. I have not done further testing re: any effects on DVD vs CD detection.
Checklist
=========
References
==========
No datasheets or documentation necessary. All discussion regarding the segfault, faulting line, and reasoning for my fix is on the discord.
> Attempt to fix cdrom image loading crash #5829 by replacing segfaulting dev->ops->get_last_block with image_get_last_block

- src/cdrom/cdrom_mke.c
Summary
=======
Configurable model and firmware version for mke (Availability of 0.80 for CR-562 is assumed)
Checklist
=========
References
==========
None
> Configurable model and firmware version for mke

- src/config.c
Summary
=======
Fix MKE channel not being saved due to being overwritten by parameters
Checklist
=========
References
==========
N/A
> MKE: Fix channel not being saved

- src/config.c
- src/qt/qt_settingsfloppycdrom.cpp
Summary
=======
- Fix channels 2 and 3 not being usable;
- Disable the CD-ROM speed dropdown when the bus is set to "Disabled";
- Explicitly set CD-ROM speed on a bus change, preventing speed on Panasonic/MKE bus drives being wrongly considered variable.
Checklist
=========
References
==========
N/A
> MKE: More UI fixes

- src/qt/qt_main.cpp
Summary
=======
Don't use time-critical priority for VM thread
Fixes some unresponsiveness on Windows
Checklist
=========
References
==========
None.
> Don't use time-critical priority for VM thread

- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/qt/qt_settingsinput.cpp
Summary
=======
Title.
Checklist
=========
References
==========
N/A
> Qt: Fix translations for the "keybind already in use" error

- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_main.ui
Summary
=======
Makes the manager's machine list resizable and increases its default width.
Checklist
=========
References
==========
N/A
> Manager: Make the machine list resizable

- src/machine/m_at.c
- src/machine/m_at_286_386sx.c
- src/machine/m_at_386dx_486.c
- src/machine/m_at_slot1.c
- src/machine/machine_table.c
Summary
=======
1. Fix chipsets of incorrectly assigned machines (Super-286C, A*Star, Tandy 4000, Vectra VEi8)
2. Add F82C710 Super I/O for the Samsung SCAT machines because they have them
3. Add more notes about unemulated or unadded onboard devices
4. Added friendly names for Intel and TriGem boards that didn't have them
Checklist
=========
References
==========
Mostly https://theretroweb.com/
> Minor machine changes

- src/qt/qt_vmmanager_details.cpp
- src/qt/qt_vmmanager_details.hpp
- src/qt/qt_vmmanager_system.cpp
- src/qt/qt_vmmanager_system.hpp
Summary
=======
The following hardware types are now displayed in the details view:
* FPU (non-integrated);
* Secondary video card, graphics accelerator cards other than Voodoo, and Voodoo 1/2 type;
* Removable disk and MO drives;
* External storage controllers (floppy, HDD, CD-ROM), in addition to SCSI;
* Sound cards beyond the first one and standalone MPU-401;
* Keyboard type;
* Devices connected to parallel ports;
* ISA RTC, ROM and memory expansion cards.
Compatibility with 4.2.x configs for ZIP drives and hard drive controllers (including tertiary/quaternary IDE) is present.
Additionally:
* Non-integer CPU clocks are now displayed correctly;
* 5¼" 360 KB floppy drives are now displayed correctly;
* Network types are now correctly capitalized;
* Translated device names will now be …
> Manager: Expand types of hardware displayed in the details view

- src/scsi/scsi_pcscsi.c
Summary
=======
1. When the Message Accepted ESP command is issued, don't clear the Internal State/Read Sequence ESP reg to 0, this fixes the AMD bios devices detection.
Checklist
=========
References
==========
> AMD 53c974 fixes of the day (August 3rd, 2025)

- src/machine/machine_table.c
Summary
=======
According to their official manuals (except for AP-4100AA, which does not have a manual on The Retro Web), this fixes the memory configuration on four machines:
1. DataExpert EXP4349: Increase maximum memory from 48mb to 64mb
2. Lanner Electronics AP-4100AA: Increase maximum memory from 32mb to 128mb (assumed)
3. A-Trend ATC-1762: Increase maximum memory from 40mb to 128mb
4. Acrosser AR-B1476: Increase minimum memory from 1mb to 8mb (the motherboard has 8mb memory onboard), and increase maximum memory from 32mb to 72mb
Checklist
=========
References
==========
[Manual for DataExpert EXP4349](https://theretroweb.com/motherboard/manual/dataexpert-expertboard-exp4349-users-manual-62028f11175ef640491931.pdf)
[Manual for A-Trend …
> Machine table: Memory fixes (August 5)

- src/device/isartc.c
Updates GLaTICK 0.8.8/86B version to use same year register as 86Box time synchronization.
Summary
=======
Default GLaTICK MM58167 uses register `0AH` to store year (compatible with AST `ASTCLOCK.COM`), whereas 86Box time sync uses register `0EH` to store year. This version uses `0EH` so year is also correctly read.
Checklist
=========
References
==========
n/a
> Update GLaTICK ROM links

- src/include/86box/86box.h
Summary
=======
Various build issues on Haiku, mostly involving system headers having fields clobbered by cpu-related defines, can be fixed simply by including stdlib.h at the top of 86box.h.
Checklist
=========
References
==========
N/A
> Fix building on Haiku

- src/qt/qt_vmmanager_config.cpp
- src/qt/qt_vmmanager_system.cpp
Summary
=======
Manager: Explicitly set UTF-8 encoding when reading/writing INI files, to avoid non-ASCII text being saved as escape sequences.
Checklist
=========
References
==========
N/A
> Manager: Use UTF-8 when reading/writing INI files

- src/video/vid_jega.c
has isa 16 slot.
src: https://x.com/konekodensetsu/status/1804920614794440854
Summary
=======
Checklist
=========
References
==========
src: https://x.com/konekodensetsu/status/1804920614794440854
> Change flags to DEVICE_ISA16 for Oki vga/h-2 and spaced. vid_jega.c

- src/machine/machine_table.c
Summary
=======
According a manual about MA30D & MA23C, the actual machines have PCI slots only, without any ISA slot. The YMF724 onboard sound chip is also mentioned in this manual.
Checklist
=========
References
==========
(https://support.nec-lavie.jp/e-manual/m/nx/ma/pg980518/hw/dnt4/v1/mst/mapcomn1.pdf)
PCI slots on Page 71, and YMF724 on Page 142.
> NEC Mate NX MA23C & MA30D have no ISA slot, and update MA30D's note

- src/utils/log.c
Summary
=======
Fix warnings on Clang.
Checklist
=========
References
==========
None.
> Fix warnings on Clang

- src/qt/qt_updatedetails.cpp
- src/qt/qt_vmmanager_addmachine.cpp
- src/qt/qt_vmmanager_preferences.cpp
Summary
=======
This PR fixes some strings that aren't translatable in the VM Manager and Update checker.
Checklist
=========
References
==========
None.
> Fix untranslated strings

- src/include/86box/scsi_pcscsi.h
- src/scsi/scsi.c
- src/scsi/scsi_pcscsi.c
Summary
=======
1. Add the original AMD 53c974 (AMD bios only and revision 0x00 compared to the A revision which is 0x10 in the PCI regs) as well as correcting the SCSI bus reset when prompted (ESP CMD 0x03), the latter fixes DawiControl 53c974 drivers on win9x.
2. Check if DMA length is not 0 for DMA transfers.
3. More logs for possible problem diagnostics.
Checklist
=========
References
==========
[AMD 53c974A revision manual](https://theretroweb.com/chip/documentation/am53c974a-665896ecb6501350650532.pdf)
[AMD 53c974 original manual](https://bitsavers.computerhistory.org/components/amd/_dataSheets/1993_53c974_PCscsi.pdf)
> 53c9x changes of the night (August 11th, 2025)

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_mainwindow.ui
Summary
=======
Add open printer tray to tools dropdown
We already had it in the manager, makes sense to have it in the app too.
Checklist
=========
References
==========
None
> Add open printer tray to tools dropdown

- src/86box.c
- src/include/86box/86box.h
- src/qt/qt_main.cpp
- src/unix/unix.c
Summary
=======
Split off ROM set checking from pc_init_modules() into a separate function and make the original pc_init_modules() only get called when not starting the manager, skipping unneeded initialization of stuff not needed for the manager, including starting a blit thread.
Checklist
=========
References
==========
N/A
> Split off ROM set checking from pc_init_modules()

- src/qt/CMakeLists.txt
- src/qt/qt_progsettings.cpp
- src/qt/qt_progsettings.hpp
Summary
=======
Overhaul loading Qt base translation files:
- Now comprehensively handles all possible locations (system-wide location, translations folder next to executable, embedded into executable if available) and filenames (`qtbase_` and `qt_`, with or without country specified)
- Embedded translation files don't have to be renamed anymore during building
- Fixed Qt 6 deprecation warnings
Checklist
=========
References
==========
N/A
> Overhaul loading Qt base translations

- src/qt/qt_downloader.cpp
- src/qt/qt_machinestatus.hpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_rendererstack.cpp
- src/qt/qt_settings.cpp
- src/qt/qt_vmmanager_system.cpp
Summary
=======
Fix the remaining Qt 6 deprecation warnings (at least for Linux).
Checklist
=========
References
==========
N/A
> Fix Qt 6 deprecation warnings

- src/machine/machine_table.c
The dump is from Sharp AX286D
there are other portable model.
ax286n
src:
Summary
=======
Checklist
=========
References
==========
ax286n
https://www.facebook.com/groups/280993058608704/posts/8592062164168377/
> Change Machine name AX 286 to AX286D machine_table.c

- src/machine/m_at_286.c
Summary
=======
Actually fix the PB286, as it's an interleaved ROM
Checklist
=========
References
==========
> Fix the PB286 for real

- src/video/vid_s3.c
Summary
=======
Fix refresh rate for 15/16-bpp modes on Trio64V+.
Checklist
=========
References
==========
None.
> Fix refresh rate for 15/16-bpp modes on Trio64V+

- src/qt/languages/86box.pot
- src/qt/languages/ca-ES.po
- src/qt/languages/cs-CZ.po
- src/qt/languages/de-DE.po
- src/qt/languages/es-ES.po
- src/qt/languages/fi-FI.po
- src/qt/languages/fr-FR.po
- src/qt/languages/hr-HR.po
- src/qt/languages/hu-HU.po
- src/qt/languages/it-IT.po
- src/qt/languages/ja-JP.po
- src/qt/languages/ko-KR.po
- src/qt/languages/nl-NL.po
- src/qt/languages/pl-PL.po
- src/qt/languages/pt-BR.po
- src/qt/languages/pt-PT.po
- src/qt/languages/ru-RU.po
- src/qt/languages/sk-SK.po
- src/qt/languages/sl-SI.po
- src/qt/languages/sv-SE.po
- src/qt/languages/tr-TR.po
- src/qt/languages/uk-UA.po
- src/qt/languages/vi-VN.po
- src/qt/languages/zh-CN.po
- src/qt/languages/zh-TW.po
- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_system.cpp
Summary
=======
Show a message box if a VM process unexpectedly terminates. Update the existing message box for when the settings dialog's process crashes during creation of a new machine too.
Drive-by: fix the empty VM directory not being cleaned up when the process crashes during machine creation, aborting it; update some translations.
Checklist
=========
References
==========
N/A
> Manager: show a message box if a VM crashes

- src/qt/qt_vmmanager_main.cpp
Summary
=======
* Re-order and group context menu entries
* Add a rudimentary context menu when clicking on empty space in the machine list with the "new machine" item
Checklist
=========
References
==========
N/A
> Manager: Machine list context menu tweaks

- src/video/vid_s3.c
- src/video/vid_s3_virge.c
- src/video/vid_voodoo_banshee_blitter.c
Summary
=======
Add color/chroma-keying to S3 Trio64V+ and Trio64V2/DX.
Clean up some TODOs in Voodoo 3/Banshee code.
Checklist
=========
References
==========
None.
> Add color/chroma-keying to S3 Trio64V+ and Trio64V2/DX

- src/qt/languages/fi-FI.po
- src/qt/qt_progsettings.cpp
- src/qt/qt_translations.qrc.in
From what I have tested, the translation is now more sensible than the previous machine and human translation mix.
Some translations were intentionally left empty, either because they made no sense to translate, or if I didn't know what a reasonable translation would be.
Includes previous translations from ts-korhonen and ziplantil, as well as probably still some machine translations that were valid.
Any discovered issues should be reported as an issue or in Discord message.
Checklist
=========
> Restore Finnish translations

- src/cdrom/CMakeLists.txt
Summary
=======
Lemondrops reports that the build breaks on Win32 with CMake not expanding the one variable, lets wrap the setup in if(NOT WIN32) as suggested.
> fix the fix so Win32 doesn't break

- src/86box.c
- src/config.c
- src/include/86box/86box.h
- src/qt/qt_platform.cpp
- src/unix/unix.c
Summary
=======
This PR implements a portable mode, which can be enabled by having a `86box_global.cfg` file in the same directory as the 86Box executable.
In this mode, 86Box does not retrieve global configuration (including any virtual machines configured in the built-in manager) from `%LOCALAPPDATA%`, `$XDG_CONFIG_HOME`, or equivalent but strictly from the EXE directory.
Checklist
=========
References
==========
> Implement portable mode

- src/qt/languages/pt-PT.po
Summary
=======
Fix conflicting mnemonic for pt-PT language in VM manager
Checklist
=========
References
==========
None.
> Fix conflicting mnemonic

- src/video/vid_svga.c
- src/video/vid_voodoo_banshee.c
Summary
=======
Recalculate `svga->fast` on Voodoo 3/Banshee packed Chain4 mode toggles.
Fixes Star Wars TIE Fighter 256-color screens after switching back from high-res modes.
Checklist
=========
References
==========
None.
> Recalculate `svga->fast` on Voodoo 3/Banshee packed Chain4 mode toggles 

- src/qt/languages/ja-JP.po
- src/qt/qt_mainwindow.ui
Summary
=======
Fixes a minor typo that causes a string to not be translated added by commit 18cdab5
Fixes a missing change from commit 72ecf1d
Checklist
=========
References
==========
None.
> Fix minor typos

- src/qt/qt_main.cpp
- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_progsettings.cpp
- src/qt/qt_vmmanager_clientsocket.cpp
- src/qt/qt_vmmanager_clientsocket.hpp
- src/qt/qt_vmmanager_main.cpp
- src/qt/qt_vmmanager_main.hpp
- src/qt/qt_vmmanager_mainwindow.cpp
- src/qt/qt_vmmanager_mainwindow.hpp
- src/qt/qt_vmmanager_model.cpp
- src/qt/qt_vmmanager_model.hpp
- src/qt/qt_vmmanager_preferences.cpp
- src/qt/qt_vmmanager_preferences.ui
- src/qt/qt_vmmanager_protocol.cpp
- src/qt/qt_vmmanager_protocol.hpp
- src/qt/qt_vmmanager_serversocket.cpp
- src/qt/qt_vmmanager_serversocket.hpp
- src/qt/qt_vmmanager_system.cpp
- src/qt/qt_vmmanager_system.hpp
- src/qt/qt_vmmanager_windarkmodefilter.cpp
- src/qt/qt_vmmanager_windarkmodefilter.hpp
Summary
=======
Reflect language and color scheme changes in global config in manager and all its VMs.
Checklist
=========
References
==========
None.
> Reflect language and color scheme changes in global config in manager and all its VMs

- src/gdbstub.c
Summary
=======
I'm trying to debug a real bios with gdb stub, I restart often and sometime 86Box doesn't wait for debugger.
Looks like the problem is missing SO_REUSEADDR on the socket.
Could you please check on other platform (it's only tested on Linux)
> use SO_REUSEADDR on gdb stub socket

- src/sound/snd_covox.c
Summary
=======
Fix default on sound master plus, and comments
Checklist
=========
References
==========
None
> Fix default on sound master plus, and comments

- src/include/86box/scsi_disk.h
- src/scsi/scsi_disk.c
Summary
=======
I am one of the maintainers of the Adélie Linux distribution.  One of our users was trying to run Adélie beta6 in 86Box and was finding that 86Box was crashing during disk formatting when using a SCSI controller.
This is because Linux has a dynamic window buffer for some SCSI controllers, and 86Box thinks the length should always be the same once a buffer has been allocated.
Affects 4.2.1, 5.0, and main, at least.  Happy to discuss more at length if needed/desired.
Checklist
=========
References
==========
Linux kernel source.
<details><summary>ASAN report</summary>
<p>
```
=================================================================
==117171==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x515000e94d00 at pc 0x562d1f267e2d bp 0x7f002e8d8460 sp …
```
> Fix dynamic SCSI buffer window sizing causing SEGV

- src/include/86box/scsi_device.h
Summary
=======
Adjust `scsi_common_t` structure definition to match the rest
Checklist
=========
References
==========
None.
> Adjust `scsi_common_t` structure definition to match the rest

- src/video/vid_mga.c
Summary
=======
MGA: Implement unscaled YUV blits for ILOAD.
Drive-by: Fix wrong colors for 32-bit scaled YUV blits for ILOAD
Checklist
=========
References
==========
None.
> MGA: Implement unscaled YUV blits for ILOAD

- src/video/vid_s3_virge.c
Summary
=======
Add support for Trio3D/2X's 8-bit palette DAC.
Checklist
=========
References
==========
None.
> Add support for Trio3D/2X's 8-bit palette DAC

- src/network/net_modem.c
Summary
=======
This adds two forgotten baud rates (28.8k and 33.6k), according to Windows 98's modem setup.
Checklist
=========
References
==========
> Add Two Baud Rates

- src/qt/qt_vmmanager_main.cpp
Summary
=======
Fix for a untranslated string in the context menu of the machine list in the VM manager.
Checklist
=========
References
==========
None.
> Fix untranslated string

- src/qt/qt_openglrenderer.cpp
Summary
=======
Force all processed screenshots to be opaque.
Checklist
=========
References
==========
None.
> Force all processed screenshots to be opaque

- src/sound/ymfm/ymfm_opl.cpp
- src/sound/ymfm/ymfm_pcm.cpp
Summary
=======
Restore earlier OPL4 identification method.
Checklist
=========
References
==========
None.
> Restore earlier OPL4 identification method

- src/sound/ymfm/ymfm_opl.cpp
Summary
=======
Actually fix OPL4 ID readbacks.
Checklist
=========
References
==========
None.
> Actually fix OPL4 ID readbacks

- src/qt/qt_openglrenderer.cpp
- src/qt/qt_softwarerenderer.cpp
- src/qt/qt_softwarerenderer.hpp
Summary
=======
Software renderer no longer uses QRasterWindow, instead using QWindow and QBackingStore.
Checklist
=========
References
==========
None.
> Software renderer no longer uses QRasterWindow

- src/video/vid_svga_render.c
Summary
=======
SVGA: Fix overflow crashes in certain cases.
Checklist
=========
References
==========
None.
> SVGA: Fix overflow crashes in certain cases

- src/gdbstub.c
- src/video/vid_ati_mach64.c
Summary
=======
Implement YUV aperture on Mach64 VT2 for July 1996 drivers. Also fix oversized register apertures on VT2.
Make GDBSTUB memory reads/writes less error-prone.
Checklist
=========
References
==========
None.
> Implement YUV aperture on Mach64 VT2

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE: Fix sign position of DDA accumulator registers
Checklist
=========
References
==========
None.
> S3 ViRGE: Fix sign position of DDA accumulator registers

- src/video/vid_s3_virge.c
Summary
=======
S3 ViRGE: Move sign bit 1 bit further to the right for K2 scaler registers
Checklist
=========
References
==========
None.
> S3 ViRGE: Move sign bit 1 bit further to the right for K2 scaler registers

- src/chipset/vl82c59x.c
- src/machine/m_at_socket4_5.c
Summary
=======
Fix two warnings in the newly-introduced VLSI SuperCore/Wildcat code
Checklist
=========
References
==========
> Fix warnings in vl82c59x.c and m_at_socket4_5.c

- src/disk/hdc_esdi_mca.c
Summary
=======
Add missing BIOS loading address for IBM PS/2 ESDI adapter, fix issue with stock adf on the reference disk.
Checklist
=========
References
==========
https://www.ardent-tool.com/docs/pdf/ibm_esdi_trm.pdf#page=17
> Fix BIOS loading address of IBM PS/2 ESDI adapter

- src/qt/qt_mainwindow.cpp
- src/qt/qt_mainwindow.hpp
- src/qt/qt_renderercommon.cpp
Summary
=======
Implement Force 4:3 option for resizable windows with fullscreen stretching behaviour.
Checklist
=========
References
==========
None.
> Implement Force 4:3 option for resizable windows with fullscreen behaviour

- src/machine/machine_table.c
Summary
=======
Use the correct onboard variant of the S3 ViRGE/DX on the TC430HX machines. This allows the onboard video to use the correct PCI slot and also resolves the Toshiba Infinia 7xx1 starting up in 16-color VGA mode on first boot (due to it needing to redetect the ViRGE) after using the recovery CD.
Checklist
=========
References
==========
> Use the correct onboard ViRGE device for the TC430HX

- src/qt/qt_main.cpp
Summary
=======
Qt: revert native window behaviour for Windows.
Checklist
=========
References
==========
None.
> Qt: revert native window behaviour for Windows

- src/machine/machine_table.c
Summary
=======
The machine name "Sony Vaio PCV-90" will be renamed to "Sony Vaio PCV-70/90/100/120".
Checklist
=========
References
==========
https://theretroweb.com/motherboards/s/intel-ag430hx-agate
> Rename "Sony Vaio PCV-90" to "Sony Vaio PCV-70/90/100/120"

- src/machine/m_at_slot1.c
- src/machine/m_at_socket7.c
Summary
=======
1. Organize the Intel AN430TX BIOSes
2. Make the M7SHI and R534F use its official latest BIOSes (latter's Unicore BIOS is unofficial)
3. Slightly correct the beta BIOS name for AB-LX7
Checklist
=========
References
==========
> Few BIOS changes (October 7)

- src/include/86box/cdrom.h
Summary
=======
Adding extra MKE, CD-ROM and DVD-ROM drives.
Also renamed the Goldstar R560B's internal name so it can be used as per request.
Checklist
=========
References
==========
Info taken from real drives
Testing
==========
MKE drive tested on Windows 3.1 and Windows 95 (AB-AH4), DVD-ROM tested in Windows 98 (MS6119) and CD-ROM tested in Windows 98 SE (MS6168)
> Add some CD drives

- src/video/vid_ati_mach64.c
Summary
=======
Correct the internal name of on-board ATI Mach64CT device.
Checklist
=========
References
==========
None.
> Correct the internal name of on-board ATI Mach64CT device
